### ISSUE TITLE
Token-Transformer: type=others

### ISSUE THREAD

**Issue by AndySobol** [tokens-studio/figma-plugin#1002]
Hi all!
I'm having a problem assigning the correct type to design tokens.

I have the following source code with tokens:

```
{
    "color": {
        "red":"hsla(360, 86%, 56%, 1)",
        "danger":"{color.red}",
        "error":"{color.danger}"
    }
}
```

I expect to see the following transformation:

```
{
  "red": {
    "value": "#ef2e2e",
    "type": "color"
  },
  "danger": {
    "value": "{color.red}",
    "type": "color"
  },
  "error": {
    "value": "{color.danger}",
    "type": "color"
  }
}
```

How it works in the figma token plugin itself

<img width="479" alt="Снимок экрана 2022-07-09 в 14 03 20" src="https://user-images.githubusercontent.com/104469026/178102960-91835569-22f6-4b2b-b47e-5a95c1c8199e.png">

but unfortunately I get the following code:

```
{
  "red": {
    "value": "#ef2e2e",
    "type": "other"
  },
  "danger": {
    "value": "{color.red}",
    "type": "other",
    "failedToResolve": true
  },
  "error": {
    "value": "{color.danger}",
    "type": "other",
    "failedToResolve": true
  }
}
```

I don't quite understand what I'm doing wrong, please help

**Comment by six7** [comment]
I think you copied the json directly from the plugin, right?

Token-transformer expects the parent keys to be the first level. If you click Export you are able to export that json how you require it. Make sure to export a single file and check include parent keys.

**Comment by AndySobol** [comment]
Hello!
No I am writing json tokens in code editor

1. I initially write my token json file in the VSCode editor
<img width="998" alt="Снимок экрана 2022-07-10 в 15 33 37" src="https://user-images.githubusercontent.com/104469026/178145084-a23bfee4-9d89-4bcf-962e-42515918dd7e.png">

2. Next, I convert it to readable for figma token and for style -dictionary look.
<img width="1102" alt="Снимок экрана 2022-07-10 в 15 34 04" src="https://user-images.githubusercontent.com/104469026/178145094-728dc6f5-50ce-442c-88ac-d58e5bd21fb0.png">

Settings are used by default:
<img width="1415" alt="Снимок экрана 2022-07-10 в 15 35 14" src="https://user-images.githubusercontent.com/104469026/178145134-79c1c4c0-bf9b-4c0f-8a05-68f72bdc404a.png">

`"new": "token-transformer tokens/color.json figma/output.json --resolveReferences: true"`

Everything works as I need, except that tonen -transformer doesn't correctly assign type.
I just expected this script to work the same as in the figma-token plugin. And it works, does mathematical calculations, takes into account variables, but does not apply the type I need

**Comment by AndySobol** [comment]
I will clarify.

I want to write design tokens in vscode, transform the file with token-transformer and style-dictionary into a working, clean json file.

This file will be synced on the github branch and uploaded to the figma -token

**Comment by AndySobol** [comment]
Filmed an additional video:
https://youtu.be/Cr06kB5TclI

**Comment by six7** [comment]
Can you try adding `"type": "color"` to the group of tokens that are colors? That will then transform correctly.

**Comment by six7** [comment]
Closing this, I don't think this is relevant any longer.
