### ISSUE TITLE
Add support for URL token storage in multi file sync approach

### ISSUE THREAD

**Issue by dnaploszek** [tokens-studio/figma-plugin#1012]
**Is your feature request related to a problem? Please describe.**
In our company we're going to share the tokens with external contractors - we only want them to be able to consume the tokens with the simplest configuration possible. 
So the easiest configuration right now is the URL sync that currently allows only to sync with the single file, this is a blocker for us before we could fully adapt the Multi file sync approach

**Describe the solution you'd like**
Allowing to pass a link to a zip file in the URL Token storage option that will only read the tokens

**Describe alternatives you've considered**
For now we've resigned from using multi file sync.

**Comment by six7** [comment]
Closing this. Effectively we have support for this with the generic versioned storage provider: https://docs.tokens.studio/sync/generic-storage
