### ISSUE TITLE
Improve JSON viewer (linter)

### ISSUE THREAD

**Issue by rbosker** [tokens-studio/figma-plugin#1022]
**Is your feature request related to a problem? Please describe.**
Currently you don't see if you make changes in your JSON if anything breaks in the JSON structure.

In addition to this ticket, another JSON enhancement:

Colored curly brackets based on nested level in the JSON editor (like VS Code).
> The user sometimes sees these colors flashing on-screen briefly as they save the JSON, so it might be that it's being overwritten in the plugin to be the same color. The colors are helpful to the user.

**Describe the solution you'd like**
Show when references do not resolve directly in JSON

**Additional context**
Slack: https://figmatokens.slack.com/archives/C02JAL48UDN/p1665161447890619

**Comment by LukeFinch** [comment]
This request has been moved to our new feedback tool. Go check out https://tokensstudio.featurebase.app/ to create a free account. You can upvote and comment on existing posts, make a new request, and subscribe to be notified when requests move into our roadmap.

**Comment by UdayHyma** [comment]
Added to Featurebase Roadmap : [🧑‍💻 JSON view/edit enhancements](https://tokensstudio.featurebase.app/p/json-viewedit-enhancements)
