### ISSUE TITLE
Indication for other editors in the plugin

### ISSUE THREAD

**Issue by rbosker** [tokens-studio/figma-plugin#1028]
We should indicate when another user is currently using Figma Tokens in the same file (plugin = open)

**Comment by LukeFinch** [comment]
This request has been moved to our new feedback tool. Go check out https://tokensstudio.featurebase.app/ to create a free account. You can upvote and comment on existing posts, make a new request, and subscribe to be notified when requests move into our roadmap.

**Comment by UdayHyma** [comment]
Added to Featurebase Roadmap : [↕️ Git sync enhancements - push, pull, merge, branching](https://tokensstudio.featurebase.app/p/git-sync-enhancements)
