### ISSUE TITLE
Removing applied tokens on removing token (setting based)

### ISSUE THREAD

**Issue by rbosker** [tokens-studio/figma-plugin#1029]
Let's introduce a setting where users can define if `fill` (or any other property) should be removed when a token is removed or if just the token should be removed

**Comment by LukeFinch** [comment]
This request has been moved to our new feedback tool. Go check out https://tokensstudio.featurebase.app/ to create a free account. You can upvote and comment on existing posts, make a new request, and subscribe to be notified when requests move into our roadmap.

**Comment by UdayHyma** [comment]
Added to Featurebase Roadmap : [💡Removing a token removes the design property in figma
](https://tokensstudio.featurebase.app/p/removing-a-token-removes-the-design-property-in-figma)
