### ISSUE TITLE
Annotation feature is hard to discover

### ISSUE THREAD

**Issue by rbosker** [tokens-studio/figma-plugin#1030]
It is hard to discover the annotation feature for new/existing users and its functionality isn’t obvious from the UI. We should redesign this feature and add some help text.

**Comment by LukeFinch** [comment]
This request has been moved to our new feedback tool. Go check out https://tokensstudio.featurebase.app/ to create a free account. You can upvote and comment on existing posts, make a new request, and subscribe to be notified when requests move into our roadmap.

**Comment by UdayHyma** [comment]
Added to Featurebase Roadmap : [🤓 Document and annotate design token enhancements
](https://tokensstudio.featurebase.app/p/documentation-and-annotate)
