### ISSUE TITLE
Improve the Github/Gitlab add new credentials modal

### ISSUE THREAD

**Issue by rbosker** [tokens-studio/figma-plugin#1037]
Context: Right now the user must manually add the repository path from the url. This, coupled with the fact that the label is misleading (username/repo - it should be namespace/repo ) has led to some issues for users.

The user should be able to paste the whole GitHub/GitLab URL and we should extract the relevant parts for them.
<img width="763" alt="image" src="https://user-images.githubusercontent.com/109062656/178680798-f8350719-9f7e-4a61-b9be-7457adcc4d65.png">

**Comment by six7** [comment]
I somehow feel a solution that would take the whole URL would not help much for these users. What if instead we offered oAuth as a solution without having to provide any of these credentials? Instead users could login in a browser and just "select" a repository, which we then take?

**Comment by superbia** [comment]
An OAuth flow would be great, however I'm not comfortable with storing the access token in local storage/indexeddb. Perhaps #320 would enable a custom integration. Thanks for a great plugin and sorry for the slightly off-topic comment :)

**Comment by SamIam4Hyma** [comment]
@rbosker do you think this is still an active issue or can we close and revisit if it comes up again?

**Comment by LukeFinch** [comment]
This request has been moved to our new feedback tool. Go check out https://tokensstudio.featurebase.app/ to create a free account. You can upvote and comment on existing posts, make a new request, and subscribe to be notified when requests move into our roadmap.
