### ISSUE TITLE
Ability to add Line Height token in rem units

### ISSUE THREAD

**Issue by anveshdunna** [tokens-studio/figma-plugin#1045]
**Is your feature request related to a problem? Please describe.**
Currently we can add font size in rem units but we can't add line height in rem units.

**Describe the solution you'd like**
Ability to add line height values in rem units as well.

**Describe alternatives you've considered**
Currently using px values to define line height tokens.

**Comment by richardhuf84** [comment]
Would it be possible to have lineHeight as a unitless value?

You can add it as a percentage in Figma, but in code, unitless values are often required. 

For example, line-height: 1.5
