### ISSUE TITLE
Export tokens as an array of JSON vs just a single JSON object.

### ISSUE THREAD

**Issue by Andrewangeta** [tokens-studio/figma-plugin#1055]
**Is your feature request related to a problem? Please describe.**
Exporting many tokens are a great feature but custom currently there is no way to export a JSON structure that's an array 

**Describe the solution you'd like**
To be able to export a token set as an array of JSON objects as opposed to a single JSON object.
I'd imagine it's be as simple as making the first and last character `[]` as opposed to `{}`

So this kind of export would go from this 
```json
{
  "primary": {
    "value": "#000000",
    "type": "color",
    "description": "A primary color is the color displayed most frequently across your app's screens and components."
  },
  "on-primary": {
    "value": "#ffffff",
    "type": "color",
    "description": "Foreground color"
  },
}
```

to this 
```json
[
  "primary": {
    "value": "#000000",
    "type": "color",
    "description": "A primary color is the color displayed most frequently across your app's screens and components."
  },
  "on-primary": {
    "value": "#ffffff",
    "type": "color",
    "description": "Foreground color"
  },
]
```

**Describe alternatives you've considered**
N/A

**Additional context**
This would make custom parsers easier to implement if the JSON objects were homogeneous and inside of an array/collection.

so code written in swift for example would go from this 
```swift
let data = try Data(contentsOf: url)
            
guard let JSON = try JSONSerialization.jsonObject(with: data, options: .json5Allowed) as? [String: [String: String]] else {
    fatalError("The file \(appearance.rawValue)-colors.json was not valid JSON")
}
            
let colors = JSON.compactMap { key, value -> FigmaColor? in
   guard let color = value["value"] else { return nil }
   return FigmaColor(name: key.lowercased(), value: color, type: "color")
}
```

to this 

```swift
let data = try Data(contentsOf: url)
let colors = try JSONDecoder().decode([FigmaColor].self, from: data)
```

**Comment by six7** [comment]
I do like that. We currently internally already store tokens in an array, we convert it to an object when outputting the JSON.

The format looks like this:

```
[
  {
    "name": "primary",
    "value": "#000000",
    "type": "color",
    "description": "A primary color is the color displayed most frequently across your app's screens and components."
  },
  {
    "name": "on-primary",
    "value": "#ffffff",
    "type": "color",
    "description": "Foreground color"
  },
]
```


As a potential workaround for now: You could get all tokens stored on a document in array format by typing `figma.root.getSharedPluginData("tokens", "values")` which will give you an object with all token sets and each of these token sets contains the tokens in an array.
