### ISSUE TITLE
Adding descriptions to groups of tokens 

### ISSUE THREAD

**Issue by dabowman** [tokens-studio/figma-plugin#1078]
**Describe the bug**
When I add "description" keys to objects that contain tokens the plugin transforms the keys into their own tokens. Would love to be able to document sets of tokens with "description" keys. 

**To Reproduce**
Here is what I put into the plugin, notice the `"description"` under the parent `"lineHeights"`

```
     "lineHeights": {
      "description": "In production units remain %",
      "1": {
        "value": "110%",
        "type": "lineHeights",
        "description": "Use only for display."
      },
      "2": {
        "value": "120%",
        "type": "lineHeights",
        "description": "Use for larger headings."
      },
      "3": {
        "value": "130%",
        "type": "lineHeights",
        "description": "Use for small and medium sized headings."
      },
      "4": {
        "value": "140%",
        "type": "lineHeights",
        "description": "Use for body-sized text"
      },
      "5": {
        "value": "150%",
        "type": "lineHeights",
        "description": "Use for body-sized text in long-form reading applications."
      }
    }
```

This is what is output after applying the json in the plugin and updating. Notice that the description key has been transformed into it's own lineHeight token. 

```
    "lineHeights": {
      "1": {
        "value": "110%",
        "type": "lineHeights",
        "description": "Use only for display."
      },
      "2": {
        "value": "120%",
        "type": "lineHeights",
        "description": "Use for larger headings."
      },
      "3": {
        "value": "130%",
        "type": "lineHeights",
        "description": "Use for small and medium sized headings."
      },
      "4": {
        "value": "140%",
        "type": "lineHeights",
        "description": "Use for body-sized text"
      },
      "5": {
        "value": "150%",
        "type": "lineHeights",
        "description": "Use for body-sized text in long-form reading applications."
      },
      "description": {
        "value": "In production units remain %",
        "type": "lineHeights"
      }
    }
```

**Expected behavior**
I want to be able to put description keys within parent objects similarly to how I add descriptions to individual tokens.

**Comment by alecgeatches** [comment]
This would be great for documentation! Per the W3C Design Tokens Format Module [first draft](https://first-editors-draft.tr.designtokens.org/format/#description-0) and [second draft](https://second-editors-draft.tr.designtokens.org/format/#description-0), group-level description tokens are supported by the specification.

**Comment by six7** [comment]
Thanks for creating this! It's on our roadmap and we plan to work on it during an upcoming W3C compliance epic.

We have an issue for this already though: https://github.com/six7/figma-tokens/issues/272

**Comment by LehtinenRiku** [comment]
What about using aliases with descriptions? Thought of making that possible? Not super common, but at least I would find it useful.

**Comment by six7** [comment]
Closing this in favor of #272 - we'll track work over there (already preparing this)
