### ISSUE TITLE
Combination token with padding overwrites itemspacing token

### ISSUE THREAD

**Issue by bewarai** [tokens-studio/figma-plugin#1085]
I have 2 tokens. One has only paddings assigned to it. The other spacing. Either one overwrites the other. It should be possible to have an auto-layout with 2 combo tokens.

**Comment by tylerhellner** [comment]
+1. 

It seems like there can only be one active token per token slot at once, but it sure would be great if we could have multiple composition tokens active at once.

**Comment by bewarai** [comment]
Makes me also wonder, if both combo tokens have both padding assigned which one will overwrite the other? Maybe an !important could be helpfull. That case I could have a card token with spacing and RLTB padding and another combo token with bottom and top set to another value which could overwrite the values if the first! Just like css

**Comment by rbosker** [comment]
note: this will be part of Composition Token improvements

**Comment by six7** [comment]
Closing this in favor of https://github.com/tokens-studio/figma-plugin/issues/1218
