### ISSUE TITLE
Possibility to create styles for multiple themes at once

### ISSUE THREAD

**Issue by rbosker** [tokens-studio/figma-plugin#1097]
**Is your feature request related to a problem?**
When themes are used, currently you need to create styles for each theme individually. 

**Describe the solution you'd like**
Ideally, you’d be able to select one, multiple or all themes.

**Additional context**
<img width="346" alt="image" src="https://user-images.githubusercontent.com/109062656/181712571-e8cb92b2-b676-4d31-aee3-4256ef1fc81e.png">

**Note**
The way creating styles is different for v113 and upcoming v114, where you can choose which styles to create.

**Comment by SamIam4Hyma** [comment]
@rbosker please confirm but I assume this can be closed as we can currently perform this action in the plugin today.
