### ISSUE TITLE
Revise internal data structure

### ISSUE THREAD

**Issue by six7** [tokens-studio/figma-plugin#1120]
To prepare for an upcoming W3C compliance we should revise how we store / transform internal data to make this an easier process to adapt.

In short: Our internal tokens structure should be optimized to support more complex token structures.

**Comment by LiamMartens** [comment]
@six7 FYI I am working on a proposal for this to support the current w3c spec, improve dev experience and improve typing

**Comment by six7** [comment]
> @six7 FYI I am working on a proposal for this to support the current w3c spec, improve dev experience and improve typing

Sounds great! 🔥
