### ISSUE TITLE
Make it possible to handle a reset of an instance of a component, within the app.

### ISSUE THREAD

**Issue by rbosker** [tokens-studio/figma-plugin#1121]
**Is your feature request related to a problem? Please describe.**
Currently if you reset an instance of a component, this is not sent to Figma Tokens. Therefore FT does nothing with an instance that is reset.

**Describe the solution you'd like**
Make it possible that the reset of instance is handled in FT.

**Additional context**
This is probably due to caching on Figma end. FT doesn't get a response from Figma, when a reset of instance is performed.
https://user-images.githubusercontent.com/109062656/183024011-d8493052-9712-4f0d-8d98-c6bd991e392b.mov

**Comment by rbosker** [comment]
@LiamMartens tagging you here. What are your thoughts on this issue?

**Comment by six7** [comment]
Will be possible in Release 129
