### ISSUE TITLE
Figma token - BlurEffect

### ISSUE THREAD

**Issue by AndySobol** [tokens-studio/figma-plugin#1129]
Hello! 

Did not find the function backgroundBlur in the plugin Figma Token. And in ussues too. 

I thought that this Figma can not give out api, but on the [official site](https://www.figma.com/widget-docs/api/type-Effect/) there is a mention of the method. 

So the question is, is there a backgroundBlur token in the plugin, or is there some way to add it and work with it?

**Comment by six7** [comment]
So far the plugin doesn't offer that functionality yet, it would need to be built.

**Comment by AndySobol** [comment]
@six7 
Thank you for your answer!
Thank you for what you’re doing!

**Comment by six7** [comment]
Background blur will be part of the next major release.
