### ISSUE TITLE
ADO Credentials successfully fetch tokens but still shows error.

### ISSUE THREAD

**Issue by jagalletta** [tokens-studio/figma-plugin#1134]
**Describe the bug**
When connecting to ADO using a Personal Access Token, I can see successful token fetching in the network traffic, but the interface shows an error occurred during the process and does not allow me to move forward.

Network Traffic (successful token fetch):
![image](https://user-images.githubusercontent.com/11045799/183747170-2d71d381-2ebb-4255-92ea-9764d5093c49.png)

Interface Error:
![image](https://user-images.githubusercontent.com/11045799/183747223-8359dfe3-a5a0-48e9-8864-78c59284fe14.png)

Console Error
`Error TypeError: Cannot read properties of null (reading 'type')
    at Co (<anonymous>:2:1230331)
    at Ja (<anonymous>:2:1282155)
    at <anonymous>:2:1282528
    at Array.forEach (<anonymous>)
    at Ja (<anonymous>:2:1282474)
    at <anonymous>:2:1282528
    at Array.forEach (<anonymous>)
    at Ja (<anonymous>:2:1282474)
    at <anonymous>:2:1282528
    at Array.forEach (<anonymous>)
    at Ja (<anonymous>:2:1282474)
    at <anonymous>:2:1282528
    at Array.forEach (<anonymous>)
    at Ja (<anonymous>:2:1282474)
    at <anonymous>:2:1282528
    at Array.forEach (<anonymous>)
    at Ja (<anonymous>:2:1282474)
    at Ka (<anonymous>:2:1283016)
    at <anonymous>:2:1283557
    at Array.reduce (<anonymous>)
    at Ya (<anonymous>:2:1283451)
    at <anonymous>:2:1288294
    at Array.forEach (<anonymous>)
    at y.<anonymous> (<anonymous>:2:1288163)
    at l (<anonymous>:2:716304)
    at Generator._invoke (<anonymous>:2:716092)
    at Generator.next (<anonymous>:2:716729)
    at rs (<anonymous>:2:1285127)
    at a (<anonymous>:2:1285331)`

**To Reproduce**
1. Go to ADO token interface
2. Fill out appropriate credentials
3. Click Save

**Expected behavior**
Expected to be able to import tokens.json file from connected repository

**Screenshots or Screencasts**
See above

JSON Too Long to include so included here as truncated version:

`{
    "pmi": {
        "dsm": {
            "border": {
                "radius": {
                    "circle": {
                        "value": "50%",
                        "type": "borderRadius"
                    },
                    "2xl": {
                        "value": "1.625rem",
                        "type": "borderRadius"
                    },
                    "xl": {
                        "value": "1rem",
                        "type": "borderRadius"
                    },
                    "lg": {
                        "value": "0.5rem",
                        "type": "borderRadius"
                    },
                    "md": {
                        "value": "0.25rem",
                        "type": "borderRadius",
                        "description": "usage: medium border radius is used in interface containers, form inputs, textareas, and similar. If youâre unsure which radius to use, pick medium."
                    },
                    "sm": {
                        "value": "0.125rem",
                        "type": "borderRadius"
                    },
                    "bottom": {
                        "value": "0px 0px 0.5rem 0.5rem",
                        "description": "radius on bottom only",
                        "type": "borderRadius"
                    },
                    "top": {
                        "value": "0.5rem 0.5rem 0px 0px",
                        "description": "radius on top only",
                        "type": "borderRadius"
                    },
                    "left": {
                        "value": "0.5rem 0px 0px 0.5rem",
                        "description": "radius on left only ",
                        "type": "borderRadius"
                    },
                    "right": {
                        "value": "0px 0.5rem 0.5rem 0px",
                        "description": "radius on right only",
                        "type": "borderRadius"
                    }
                },
                "width": {
                    "none": {
                        "value": "0px",
                        "description": "no border ",
                        "type": "borderWidth"
                    },
                    "xs": {
                        "value": "1px",
                        "type": "borderWidth",
                        "description": "usage: Default border width. "
                    },
                    "sm": {
                        "value": "2px",
                        "type": "borderWidth"
                    },
                    "md": {
                        "value": "4px",
                        "type": "borderWidth"
                    },
                    "lg": {
                        "value": "8px",
                        "type": "borderWidth"
                    }
                }
            },
        },
        "spx": {
            "store": {
                "homepage": {
                    "background": {
                        "value": "{pmi.dsm.color.white}",
                        "type": "color"
                    }
                }
            }
        }
    }
}`

**Comment by SamIam4Hyma** [comment]
@six7 assuming this can be closed/archived as it appears to describe a bug/error but its several years old.

**Comment by six7** [comment]
Closing this as stale. Please reopen if you feel this was done in error, and provide further reproduction steps.
