### ISSUE TITLE
Recognize ems 🤞

### ISSUE THREAD

**Issue by ian-schechter** [tokens-studio/figma-plugin#1136]
**Is your feature request related to a problem? Please describe.**
To reduce the amount of tokens needed, we use formulas to achieve the line heights and letter spacing we are looking for.

Examples:
lineHeight: "1.333em",
letterSpacing: "clamp(-1px, ((1rem - 1em) * 0.08), 1000px)",
lineHeight: "1em + 6px",
letterSpacing: "((1rem - 1em) * 0.052)",

But because ems aren't supported, I have to manually input the line heights and letter spacing for each various type size.
Because we use these formulas in code, it also creates a disparity between Figma Tokens and our actual tokens :(

**Describe the solution you'd like**
Supporting rems and ems would be so cool!

**Describe alternatives you've considered**
I've used percentages which work great for line heights! But I've also had line height formulas a bit more complicated for headers for example (1em + 6px).
I've been using rems by applying a {1 rem} token to be used as an alias and then multiply it by whatever the em value would. I've been doing this for all values I can too (such as spacing, border radius, etc) to create parity with how we are building our system.
<img width="317" alt="image" src="https://user-images.githubusercontent.com/91859852/183789474-91bead4b-ce21-4796-bbea-91e46bb64219.png">

**Additional context**
If ems were supported, I could reduce the amount of tokens needed for letterspacing in the below screenshot from 20 to 3
<img width="310" alt="image" src="https://user-images.githubusercontent.com/91859852/183788418-3ac23153-3423-4bae-a4df-7d6a6df1ce44.png">

If ems were supported, I could reduce the amount of tokens needed for lineheights in the below screenshot from 16 to 3
<img width="493" alt="image" src="https://user-images.githubusercontent.com/91859852/183788622-aa479cad-fc7e-4b67-9ea9-8bf8ae54a94f.png">

**Comment by UdayHyma** [comment]
[Migrated to Featurebase](https://tokensstudio.featurebase.app/p/typography-styles-with-variables)
