### ISSUE TITLE
Implement textAlign as a token

### ISSUE THREAD

**Issue by rbosker** [tokens-studio/figma-plugin#1138]
**Is your feature request related to a problem? Please describe.**
Make it possible to use textAlign as a token, so a user can manage his text aligment via tokens.

**Describe the solution you'd like**
Currently this is not implemented, since it's not part of Figma's styles. We should support this on long-term, since this could be one of the benefits of using tokens on top of styles. We can connect typography decisions to e.g. colors, but also extend it by text alignment and other decisions.

This should cover left, center, right aligned. To be discussed how we'd implement it in JSON. Also unclear if/how vertical text alignment is to be implemented.

**Additional context**
Earlier discussed in: https://github.com/six7/figma-tokens/issues/95 
We did not include textAlign in the initial release as textAlign is not part of Figma's styles.
textCase & textDecoration are already implemented

**Comment by mck** [comment]
Since we have composition tokens, could we just have the textAlign token and make a composition with a typography token to solve that problem?

**Comment by LukeFinch** [comment]
This request has been moved to our new feedback tool. Go check out https://tokensstudio.featurebase.app/ to create a free account. You can upvote and comment on existing posts, make a new request, and subscribe to be notified when requests move into our roadmap.

**Comment by UdayHyma** [comment]
Added to Featurebase Roadmap : [🪙 Expand token types
](https://tokensstudio.featurebase.app/p/expand-token-types)
