### ISSUE TITLE
As a User I want the ability to see all tokens of all sets in a single view, to easily manage my tokens

### ISSUE THREAD

**Issue by rbosker** [tokens-studio/figma-plugin#1139]
**Is your feature request related to a problem? Please describe.**
Would love the ability to see all tokens across all sets in the sidebar, in a single scrollable/searchable view instead of having to go across and select each set individually. 

**Describe the solution you'd like**
An “All Sets” view where all tokens are represented.

**Describe alternatives you've considered**
Something like most Mail apps have an All Accounts view of your inbox.

**Comment by danvpeterson** [comment]
Thanks for creating this @rbosker! This would help make using the plugin a much better experience overall. Being able to keep the left sidebar collapsed 99% of the time to make the plugin smaller, and making search so much nicer to find whatever you need while still using sets and themes the way we need to.

To add on to this, it would be great if Sets marked as "source" in a theme could be excluded from this view. I have to have our Base level tokens included in all themes, but I don't want other designers actually using them in designs. So it'd be awesome if they could live in this view that shows them all the tokens they need all together per theme, without showing those Base ones they shouldn't be using anyway.

**Comment by LukeFinch** [comment]
This request has been moved to our new feedback tool. Go check out https://tokensstudio.featurebase.app/ to create a free account. You can upvote and comment on existing posts, make a new request, and subscribe to be notified when requests move into our roadmap.

**Comment by UdayHyma** [comment]
Added to Featurebase Roadmap : [🪙 Token organization enhancements
](https://tokensstudio.featurebase.app/p/token-organization-enhancements)
