### ISSUE TITLE
Show the original value format in reference tokens

### ISSUE THREAD

**Issue by rbosker** [tokens-studio/figma-plugin#1177]
**Is your feature request related to a problem? Please describe.**
In a reference token, show the value in the format that the core token was set in
For example with color tokens:
- base tokens formatted as HSLA
- referencing that base token shows the equivalent hex value

**Describe the solution you'd like**
Show the original value format in reference tokens, which is used in the base token.

**Additional context**
https://www.loom.com/share/c567f56ac6e34f8cb4eeb0c59722a7bf

**Comment by UdayHyma** [comment]
Added to FeatureBase Roadmap : [🎨 Expand functionality of color modifiers](https://tokensstudio.featurebase.app/p/expand-functionality-of-color-modifiers)

**Comment by SamIam4Hyma** [comment]
Added to Featurebase Request-	[ Expand accepted reference token types](https://tokensstudio.featurebase.app/p/expand-accepted-reference-token-types)
