### ISSUE TITLE
Introduce `gradient` token type

### ISSUE THREAD

**Issue by six7** [tokens-studio/figma-plugin#1199]
We've introduced basic gradient support previously by using just a string: `linear-gradient(...)` and we've received feature requests to extend that to other gradient types such as radial or conic.

```[tasklist]
### Tasks
- [ ] https://github.com/six7/figma-tokens/issues/858
- [ ] https://github.com/six7/figma-tokens/issues/441
```

Instead of just adding more of these hacky solutions, we should introduce a new token type for gradients.

The W3C DTCG has outlined in their draft how these gradient tokens should look like:  https://tr.designtokens.org/format/#gradient

These would look like this:
```
{
  "blue-to-red": {
    "$type": "gradient",
    "$value": [
      {
        "color": "#0000ff",
        "position": 0
      },
      {
        "color": "#ff0000",
        "position": 1
      }
    ]
  }
}
```

> **Note**
> As this draft is still evolving and currently doesn't show any support of these additional gradient types, I consider this issue currently being **blocked** as we don't want to move forward until a decision has been made.

**Comment by mgunnin** [comment]
Is this still in process?

**Comment by Davst** [comment]
Wondering the same. I see that it is marked as blocked... Is there any way to see why it is blocked?

**Comment by six7** [comment]
> Wondering the same. I see that it is marked as blocked... Is there any way to see why it is blocked? 

It says in the note at the bottom

**Comment by Davst** [comment]
https://github.com/design-tokens/community-group/issues/101 Seems to be in consensus on the need of a gradient types. 

These discussions seem to be a year ago though, and considering almost no progress is being made on that standard in the area I'd argue that the value of adding support for the css style gradient types for radial etc. outweigh the value of getting it according to standard the first time. 

I love the idea of following a standard.. but sometimes you have to balance that against that Radial gradients are common and this is a severely limiting factor. Implementing a "for the time being" solution by adding the other types to the existing solution in the meanwhile seems resonable to me.

**Comment by LukeFinch** [comment]
This request has been moved to our new feedback tool. Go check out https://tokensstudio.featurebase.app/ to create a free account. You can upvote and comment on existing posts, make a new request, and subscribe to be notified when requests move into our roadmap.

**Comment by UdayHyma** [comment]
Added to Featurebase Roadmap : [🪙 Expand token types](https://tokensstudio.featurebase.app/p/expand-token-types)
