### ISSUE TITLE
Introduce dimension type

### ISSUE THREAD

**Issue by six7** [tokens-studio/figma-plugin#1201]
In order to support the upcoming W3C format we'll need to introduce a dimension type: https://second-editors-draft.tr.designtokens.org/format/#dimension

The dimension type is a token that specifies a dimension, and is always bound to a specific unit (either rem or px).

As a dimension can be used in a wide range of applications, we need to rethink how we currently apply tokens. A user must choose on right-click what they want to apply this token for, like today but offering more choice.

![Image](https://user-images.githubusercontent.com/4548309/185694803-77ccb60e-e643-451d-a5de-c1c1e0abaae7.png)

## Things to do
- [x] Introduce a new `dimension` type
- [x] Validate that values of this token are specified as either `24px` or `24rem` (or `{alias}` / `$alias`), if not, give an error message in the value: `Value must include either px or rem`
- [x] When right-clicking this token, let the user choose between properties for `Spacing (all properties that we have in Spacing tokens)`, `Sizing (all properties of Sizing tokens)`, `borderWidth (all properties of borderWidth tokens)`
- [x] When left-clicking this token, let's be smart: A) User has auto layout selected: Apply the Gap property, B) User has any other frame selected: Apply sizing, C) user has a mix selected: Apply Gap.

This is an issue that will complete #289

**Comment by AndySobol** [comment]
Cool idea! It would also be nice to add the auto option. Now (release 116) it doesn’t work.
![Uploading Снимок экрана 2022-08-23 в 12.55.36.png…]()

**Comment by six7** [comment]
Shipped in 129
