### ISSUE TITLE
TokenPicker: Tab to jump to next .

### ISSUE THREAD

**Issue by six7** [tokens-studio/figma-plugin#1206]
It would be a neat addition for the `TokenPicker` when using it to autocomplete if pressing Tab would jump to the next .

So if I type 
`{colors.b`

And the plugin gives me suggestions like
```
colors.black.100
colors.black.200
...
```

and I press `Tab`
My new value is 
`{colors.black.`

That way if I know I need a token that is in that `colors.black` space I can quickly jump to those without having to type.

**Comment by UdayHyma** [comment]
Added to Featurebase Roadmap : [🪙 Token organization enhancements
](https://tokensstudio.featurebase.app/p/token-organization-enhancements)
