### ISSUE TITLE
Mapping a chronologic system token-set to another token-set

### ISSUE THREAD

**Issue by bewarai** [tokens-studio/figma-plugin#1207]
I have a system-tokenset setup of font-sizes based on a typescale.

The root size and multiple typescales. I output that way about 20 type-sizes using a formula of root-(number) x typescale.
I map these now manually to my theme tokens.

**Ex. I have:**
...
System.desktop.DT-font-size-12
System.desktop.DT-font-size-13
System.desktop.DT-font-size-14
...
System.desktop.DT-font-size-20

**and map these to**

Theme.desktop.titles.heading-2xl ({System.desktop.DT-font-size-12})
Theme.desktop.titles.heading-xl ({System.desktop.DT-font-size-11})
Theme.desktop.titles.heading-l ({System.desktop.DT-font-size-10})
...
Theme.desktop.titles.heading-2xs ({System.desktop.DT-font-size-6})

Mapping those sizes takes a lot of time because I have to remap them in each new project which could be solved by having them mapped chronologically:

if I would be able to just set my heading 2xl from ({System.desktop.DT-font-size-12}) to ({System.desktop.DT-font-size-11}) the rest would automatically follow based on the chronology of my system-tokens. Now I have to do that manually for each project.

Could be done for colors as well

**Comment by SamIam4Hyma** [comment]
@six7 Suggest to close b/c it's stale and we can reimagine when we focus on typography in a future epic.
