### ISSUE TITLE
Nesting in Composition tokens

### ISSUE THREAD

**Issue by esthercheran** [tokens-studio/figma-plugin#1219]
Currently composition tokens can be applied to a single layer. It would be great if a composition token could define tokens for nested layers and apply tokens to child/sibling layers as well.
For example: A composition token `button` with the following nesting:
Button container
- border radius
- fill
- padding
Button label
- typography
- fill
Button icon
- size
- fill

**Comment by six7** [comment]
What's the primary use case to solve here? I feel this might be overly complex to achieve.

One thing I could see working is to have something like for CSS, where defining a `color` attribute will define any `text-color` property down the line? But do be able to define specific layers sound complex?

**Comment by six7** [comment]
@esthercheran can you shape this more? i'm not sure this is ready yet.

**Comment by SamIam4Hyma** [comment]
Added to Featurebase Request-	[🪙 ➕ Support multiple tokens per layer of the same type](https://tokensstudio.featurebase.app/p/multiple-token-per-layer)

**Comment by SamIam4Hyma** [comment]
Added to Featurebase Request- [🪙 ➕ Support multiple tokens per layer of the same type](https://tokensstudio.featurebase.app/p/multiple-token-per-layer)
