### ISSUE TITLE
I want to be able to collapse/expand all sets in the folder structure in the left panel

### ISSUE THREAD

**Issue by rbosker** [tokens-studio/figma-plugin#1240]
**Is your feature request related to a problem? Please describe.**
I want to be able to collapse/expand all sets in the folder structure in the left panel

**Describe the solution you'd like**
Allow option click to expand/collapse all, like the token categories.

**Additional context**
<img width="248" alt="image" src="https://user-images.githubusercontent.com/109062656/187672354-bbb43c4a-78ab-4061-b243-993a66d4e8cf.png">

Slack chat: https://figmatokens.slack.com/archives/C02JAL48UDN/p1661870915270529

**Comment by LukeFinch** [comment]
This request has been moved to our new feedback tool. Go check out https://tokensstudio.featurebase.app/ to create a free account. You can upvote and comment on existing posts, make a new request, and subscribe to be notified when requests move into our roadmap.

**Comment by UdayHyma** [comment]
Added to Featurebase Roadmap : [🪙 Token organization enhancements
](https://tokensstudio.featurebase.app/p/token-organization-enhancements)
