### ISSUE TITLE
When duplicating/renaming a token/group, auto select the name input.

### ISSUE THREAD

**Issue by rbosker** [tokens-studio/figma-plugin#1241]
**Is your feature request related to a problem? Please describe.**
When you:
- Duplicate a token group
- Rename a token group
- Duplicate a token
now you have to manually select the Name input, before you can rename.

**Describe the solution you'd like**
Make the rename pop-up have the input selected.

**Additional context**
<img width="1338" alt="image" src="https://user-images.githubusercontent.com/109062656/187882804-93c421eb-8607-4184-89f6-4ab674e268c3.png">
Slack:https://figmatokens.slack.com/archives/C02JAL48UDN/p1661964642355909

**Comment by six7** [comment]
Released in 129
