### ISSUE TITLE
Remove tailwind

### ISSUE THREAD

**Issue by six7** [tokens-studio/figma-plugin#1246]
As we switched over to Radix and Stitches a while ago we should clean up the codebase and get rid of Tailwind, which we're still using in a few leftover areas.

We can break up this task like this:
- [x] Change EditTokenForm to use Stitches
- [x] Change PushDialog to use Stitches
- [x] Change TokenListing to use Stitches
- [x] Change Modal to use Stitches
- [ ] Change CreateBranchModal to use Stitches
- [ ] Change ADOForm to use Stitches
- [ ] Change BitBucketForm to use Stitches
- [ ] Change GitForm to use Stitches
- [ ] Change JSONBinForm to use Stitches
- [x] Change AnnotationBuilder to use Stitches
- [ ] Introduce ErrorMessage component as lots of old tailwind classes are used for that one

There's some larger areas that need refactoring as these heavily depend on Tailwind and could be refactored:
- [x] TokenButton
- [x] ColorPicker
- [x] `.content` and `.content-dark` scroll areas

**Comment by bewarai** [comment]
What was the main reason for making the switch? Just out of curiosity?

**Comment by six7** [comment]
Mainly the huge benefits of composability that Stitches brings. Compare creating variants with tailwind (adding classes) to that of using Stitches: https://stitches.dev/docs/variants

we made the switch a while ago but there's been some lingering remnants of tailwind code that I put off changing until now.
