### ISSUE TITLE
Feature: add tags to git commit (pipelines)

### ISSUE THREAD

**Issue by PeterSchuhmannNetflow** [tokens-studio/figma-plugin#1257]
Right now its not possible to add tags to a git commit. In case you want to use an automatic build pipeline (CI) you will be building it every time once a commit is done or manually. To deploy only specific versions of the work draft it would be perfect to add tags to the commit which could trigger the pipeline. 

Just an idea. Interessted so see what you guys think.

And thanks for a great plugin/tool!

**Comment by SamIam4Hyma** [comment]
@jorenbroekema can you confirm if this is still an issue?  Based on the recent work with style dictionary I suspect its not.

**Comment by jorenbroekema** [comment]
I think this issue is still a solid feature request, as it will allow users to tag commits and set up their CI/CD in a way to only trigger when a commit is tagged.

**Comment by UdayHyma** [comment]
[Migrated to Featurebase](https://tokensstudio.featurebase.app/p/git-sync-enhancements)
