### ISSUE TITLE
Make it possible to show details in the standard annotation box, instead of just the token name

### ISSUE THREAD

**Issue by rbosker** [tokens-studio/figma-plugin#1258]
**Is your feature request related to a problem? Please describe.**
Currently you can only annotate the token names. You're now not able to annotate more details in the annotation box.

**Describe the solution you'd like**
Make it possible to add more details to the annotation box.

**Additional context**
<img width="539" alt="image" src="https://user-images.githubusercontent.com/109062656/188814710-d90f7d32-5525-44af-a051-9de88f1432fd.png">

**Comment by six7** [comment]
Adding a user request:
They'd like to also surface Styles that were applied - and if that Styles is connected to a Token, show that Token name instead.

I think this is tricky, an easier way for now might be to just surface the Style name (if no token is applied for that property)

**Comment by SamIam4Hyma** [comment]
@rbosker suggesting we archive this issue and revisit ideas and solutions in an upcoming epic focusing on documentation, users currently have other ways to accomplish this goal using other tools (automator, specs etc) and its 2yrs old.
