### ISSUE TITLE
Introduce in-product explainers

### ISSUE THREAD

**Issue by rbosker** [tokens-studio/figma-plugin#1262]
### Description
To make it easier to get started with the plugin, we should introduce in-product explainers that the user can `Dismiss`. We should add new flags on the user's device to indicate if the user has dismissed these. If yes, don't show them anymore.

### MVP Product explainers
| Section | ClientStorage Flag | Text | Link |
| --- | --- | --- | --- |
| Sets | `onboarding_explainer_sets` | Sets allow you to split your tokens up into multiple files. \n\nYou can activate different sets to control theming. | https://docs.figmatokens.com/themes/token-sets?ref=onboarding_explainer_sets |
| Inspect | `onboarding_explainer_inspect` | This is where applied tokens of your selection show up, you can use Deep Inspect to scan the selected layers and all of its children. | https://docs.figmatokens.com/multi-inspect?ref=onboarding_explainer_inspect |
| Sync providers | `onboarding_explainer_syncproviders` | Connect your tokens to an external source of truth that you can push and pull to. This allows you to use tokens across files. | https://docs.figmatokens.com/sync/sync?ref=onboarding_explainer_syncproviders |

### Design
![Image](https://user-images.githubusercontent.com/4548309/188398327-c066a3bb-eca6-4db7-95cb-d167c979d010.png)
![Image](https://user-images.githubusercontent.com/4548309/188398358-b457ca91-9503-4e91-94be-06f185728742.png)
![Image](https://user-images.githubusercontent.com/4548309/188398368-ef110a2a-aa0e-4eba-ac7e-faa4cc2815e3.png)

**Comment by six7** [comment]
Released in 129
