### ISSUE TITLE
Add a way to reset Onboarding

### ISSUE THREAD

**Issue by rbosker** [tokens-studio/figma-plugin#1263]
### Description
As we're introducing a few Onboarding items we should provide the user with a way to reset that, so they can get back to the Onboarding state.

This would be a new button in Settings, where the user can click and it would Reset Onboarding. This can be very subtle.
![Image](https://user-images.githubusercontent.com/109062656/188829748-0d3fe61b-fc08-4b32-bd4d-cc97b3380ae0.png)

### Requirements
Resetting Onboarding means:
- Resetting the Onboarding flow
- Resetting any Flags we have from in-product education Dismissals

### Design
![Image](https://user-images.githubusercontent.com/4548309/189477436-22cedf55-63ff-44b8-a16b-f62e4aa47ac4.png)

**Comment by six7** [comment]
Shipped in 129
