### ISSUE TITLE
Refactor how we show Sync/Settings

### ISSUE THREAD

**Issue by rbosker** [tokens-studio/figma-plugin#1264]
### Description
The current Sync experience is poor as it grew drastically over the last couple of months with new providers that were added.

### Requirements
We should refactor this:
- Don't group sync settings by provider
- Instead, show all stored providers in a vertical list
- Add a `Add new` button that lets the user choose from Providers
- After choosing one, do the same thing as we did today.
- Change each Sync Item so we have a ... menu that shows more options
- Show Connection errors inside the active sync item if there is one

![Image](https://user-images.githubusercontent.com/4548309/188398933-56de05bd-9c5d-4c9e-8256-2ebeb4b0e99b.png)
![Image](https://user-images.githubusercontent.com/4548309/188398942-64a502d1-4ce4-483b-93fc-b06e272f390f.png)

![image](https://user-images.githubusercontent.com/4548309/190497321-91406b45-8d1a-4c5e-aa5a-4cf62f6d2396.png)

**Comment by rbosker** [comment]
include validation > @rbosker check the issue for the error handling.

**Comment by esthercheran** [comment]
All the sync providers are showing the same icon.


![Image](https://user-images.githubusercontent.com/66366384/203782231-61060d7a-6a36-4acd-a921-4efccb2940c6.png)


In light mode, the dropdown menu on 'Add new' is still in dark mode.



![Image](https://user-images.githubusercontent.com/66366384/203782668-ec09816c-8a9a-4d80-976a-8c531d2cf47e.png)

**Comment by six7** [comment]
Shipped in 129
