### ISSUE TITLE
Add border token type

### ISSUE THREAD

**Issue by rbosker** [tokens-studio/figma-plugin#1266]
### Description
Add border token type, based on the documentation of designtokens.org

Properties+example: https://tr.designtokens.org/format/#border

```
Type: 'border'
Name: 'Border'
Value: {
         color: ColorToken: color token input or reference to a color token | Placeholder: 'Border color',
         width: dimension token input or a reference to a borderWidth or dimension token | Placeholder: 'Border width'
         style: StrokeStyle | Placeholder: 'solid | dashed'
       }
```

![Image](https://user-images.githubusercontent.com/4548309/189477157-5e459476-5c3c-4af3-889a-1b4280aa7c83.png)

**StrokeStyle**:
This is an upcoming token type, for now let's just allow `solid | dashed` as that is what's allowed in Figma. 

#### Dev note:
One thing to consider here when applying these tokens: As we currently use the `border` property to apply colors as a border to layers, we now need to change this logic slightly:
If we find a `border` token applied and it was using a color token, we change this to a `borderColor` property that is instead applied.
If it was using a newer `<StrokeStyle>object` token, then we apply it as this new composite.

- `border: simple string` = Try to apply it as `borderColor`
- `border: <StrokeStyle>object` = Try to apply it as the new type impacting borderColor, `borderWidth` and `strokeStyle`

**Comment by six7** [comment]
Changed description to indicate a new approach that would let us keep using the `border` property for both the old way of applying border-color and also the new of applying as a strokeStyle

**Comment by six7** [comment]
Shipped in 129
