### ISSUE TITLE
Duplicate token into other sets

### ISSUE THREAD

**Issue by kibs** [tokens-studio/figma-plugin#1277]
**Is your feature request related to a problem? Please describe.**
I would like to easy duplicate a token into another set. If i have a "base" set where all tokens is listed, and want to create a set with "overrides" it would be great if we could easily duplicate a token into that "overrides" set

**Describe the solution you'd like**
The easiest would probably to be able to select a "set" in the duplicate token form

**Describe alternatives you've considered**
Dragging and dropping maybe?

**Additional context**
nothing for now

---

When duplicating a token, let's introduce a dedicated Modal for that case.

We'll use a header of `Duplicate token`,
we'll add a new option in the bottom `Sets`, where user can choose which sets to duplicate into.
By default, this is the set of the current token.
Users can choose any sets here, after saving we'll duplicate the token into these sets.
When a token with that same name exists in a set already, show an error validation next to the `Sets` input letting users know that a token exists already (and forbid saving - we might revisit that, but would be the quickest to implement).

![Image](https://user-images.githubusercontent.com/4548309/206902591-c26605db-f552-4cbc-a931-85c854532d3d.png)

**Comment by six7** [comment]
I like the idea of selecting a `set` in the duplicate form, feels like something that would solve this! It could default to the current set as well.
