### ISSUE TITLE
Specify necessary Personal Access Token scopes

### ISSUE THREAD

**Issue by Leland** [tokens-studio/figma-plugin#1285]
**Is your feature request related to a problem? Please describe.**
Figma Tokens Sync feature uses GitHub's Personal Access Tokens (PATs) to push changes to a repo. PATs are incredibly powerful. [With full access](https://docs.github.com/en/developers/apps/building-oauth-apps/scopes-for-oauth-apps), they can access a user's personal data, write across an entire organization, and more.

Today, Figma Tokens' Sync feature provides no clues on the authorization screen as to which of those scopes are needed: 
![image](https://user-images.githubusercontent.com/714017/190264029-23b0d43b-12bb-4f8f-b281-099be746e0f6.png)

That information _is_ provided [in the docs](https://docs.tokens.studio/sync/github#3-generate-your-personal-access-token): it's the `repo` scope.

~(Side note, that scope, while correct, is broad due to OAuth limitations. It will grant access to read/write **on every repo** the user also has access to. It would not be remiss to mention [machine users](https://docs.github.com/en/developers/overview/managing-deploy-keys#machine-users) in that documentation for organizations that decide to use Figma Tokens)~ No longer the case! https://github.blog/changelog/2022-10-18-introducing-fine-grained-personal-access-tokens/

**Describe the solution you'd like**
* Link out to some documentation within the setup form
* Specify PAT scope requirements near the field

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by six7** [comment]
Agree, ideally we'd link to the Docs on each of those providers so it's also easier for users who don't know much about those. I think that solution might already be enough and should be easy to implement.

**Comment by six7** [comment]
@Leland have you tried using GitHub's new [fine-grained Personal Access Tokens](https://github.blog/changelog/2022-10-18-introducing-fine-grained-personal-access-tokens/)? this would solve some of the concerns you had. (Nevertheless we should still document it)

**Comment by Leland** [comment]
Yes! Meant to comment about it :) This issue is definitely now more along the lines of "document what capabilities are needed for good UX" and less "this seems potentially really scary"

**Comment by rpominov** [comment]
I can confirm that fine-grained Tokens work well with the plugin. Would be good if this documentation https://docs.tokens.studio/sync/github would ask to create a fine-grained token rather than a regular one.

**Comment by daveallie** [comment]
@rpominov would you mind sharing which scopes you gave to the fine-grained token to allow it to work for github syncing, I tried a few different combinations but wasn't successful

**Comment by rpominov** [comment]
Sure. I've set "Repository permissions" / "Contents" to "Read and write", and left other permissions as is

![image](https://user-images.githubusercontent.com/825702/218021122-d9317c51-2aa8-4ede-98fd-aadcaccec45e.png)

**Comment by six7** [comment]
Closing this issue as it's now part of [the docs](https://docs.tokens.studio/sync/github#3-generate-your-personal-access-token)
