### ISSUE TITLE
Make it possible to sync hidden Figma styles with the plugin

### ISSUE THREAD

**Issue by rbosker** [tokens-studio/figma-plugin#1287]
**Is your feature request related to a problem? Please describe.**
Currently it's not possible to sync hidden Figma styles with the plugin. The plugin will not create the style nor connect to it.

**Describe the solution you'd like**
In some use cases it can be helpful to sync hidden styles with the plugin.

**Additional context**
From Zendesk request:
Our Figma libraries use styles that hidden from theme users, we would like to manage those styles with the Figma Tokens plugin but adding an underscore prevents the styles from syncing with Figma. Is it possible to sync hidden Figma styles with tokens from the plugin?

**Comment by six7** [comment]
IMO we should add something to `Settings` that allows to toggle that behavior, currently it just ignores tokens starting with _ or .

**Comment by denis-strong** [comment]
This could probably save me time by not using non-local libraries to keep everything synced

**Comment by SamIam4Hyma** [comment]
@rbosker Suggesting we archive as this is quite old/stale and we have other ways to manage the same problem
