### ISSUE TITLE
Blur background token

### ISSUE THREAD

**Issue by ian-schechter** [tokens-studio/figma-plugin#1291]
**Is your feature request related to a problem? Please describe.**
I have blur backgrounds on some components that are overlayed on top of images. A blur background or layer option would be amazing!

**Describe the solution you'd like**
The ability to add a blur background token

**Describe alternatives you've considered**

**Additional context**

**Comment by six7** [comment]
We'll likely support this in the form of [Dimension tokens](https://github.com/six7/figma-tokens/issues/1201) where you'd be able to choose `background blur` as one option.

**Comment by six7** [comment]
This was shipped with 129 in the form of dimension tokens!
