### ISSUE TITLE
Impossible to use some access tokens for GitLab

### ISSUE THREAD

**Issue by jahglow** [tokens-studio/figma-plugin#1298]
**Describe the bug**

**To Reproduce**
I managed to set up token sync for a file for myself on a repo gitlab.com/my_group/my_repo so it pulls and pushes allright. My role is maintainer, access token has 'api' enabled. So we created a token for my colleague who is also a maintainer in the repo and enabled the 'api' on the token. He can not push the changes - readonly mode. When saving profile with his token it says "Check credentials". Wen he switches to my token - he can pull and push alright. What's wrong and how to troubleshoot it? I'm not the only one facing thins issue.

**Expected behavior**
Should connect via gitlab access token

**Screenshots or Screencasts**
Another user experiencing the same:
```mdx
[Nino Strixner @ninostrixner1](https://www.figma.com/@ninostrixner1) · 6 days ago
Hey everyone,
I am facing the issue of not having access to create or edit tokens within the plugin. I does not seem as a but, more related to access rights. I connected the repo from GitLab to it, which works fine. Rights on gitlab are set to developer, but I am not able to push to GitLab. Could you provide any help on that side? Thanks in advance.
```

**Comment by six7** [comment]
In general `write_repository` should be enough, you shouldn't need the full `api` scope. It sounds like a permissions issue, did you make sure those are setup the same for both? As in `maintainer` role + access tokens having the same permissions?

**Comment by jahglow** [comment]
Well, the api should provide the full scope, the user can commit to the repo via gitlab interface thus his permissions are enough for the repo. So there is a group and a repo in the group. The user is developer in the group and maintainer in the repo. I cannot see why the access token on the account doesn't take into account the permissions for the repo

**Comment by six7** [comment]
I'm not aware of any limitation there, permissions should work.

@rbosker can you dig into this? I don't have the gitlab setup to reproduce this.

**Comment by rbosker** [comment]
Update: got this reproduced with @swordEdge > he's working on a fix

**Comment by swordEdge** [comment]
Discussed with @rbosker and users should have maintainer or owner role to push changes even though their access token has api scope. With Developer or Report role, users can't push changes.
This issue is not a bug. This is releated with the logic of GitLab.
