### ISSUE TITLE
Duplicate token group across sets.

### ISSUE THREAD

**Issue by stephen-salyer** [tokens-studio/figma-plugin#1299]
When i add to a theme i want to be able to duplicate those styles across theme from within the plugin.

the specific example im working through is states. I would love to duplicate the naming convention and change the values in other themes.

---

Let's change how we `Duplicate groups`.

Currently, we Duplicate right away, without confirming.

Let's introduce a modal `Duplicate group`, that asks the user for the new name of the group, and lets them choose a token set.
Let's also make sure the group name shows the full path, not just the name of the group.

After duplication and users have defined multiple sets to duplicate into, create that group and all its tokens (of that type) in the chosen sets.

![Image](https://user-images.githubusercontent.com/4548309/206902906-6a392b1e-3b10-4d06-aa99-d225b764ce4c.png)

**Comment by six7** [comment]
Bit confused by the term usage here, do you want to duplicate a `Token set` (the thing on the left of the plugin) to somewhere else? Or are you referring to individual tokens here?

**Comment by stephen-salyer** [comment]
Ah so sorry! 

If I have a group of tokens like a primary color ramp I would like to right click on primary within one theme and move it to another.

I'm currently doing this with the Jason editor and copy and pasting (since we are in testing phase for this tool and our theme structure is evolving over time)

I imagine something like 

Right click on group name, options (rename, copy, move, duplicate, ect)

I imagine duplicate asking if I want to duplicate this across themes. (Instead of the current workflow that is copy and paste across themes)

**Comment by ggrigorov** [comment]
"I imagine duplicate asking if I want to duplicate this across themes. (Instead of the current workflow that is copy and paste across themes)"

That would be gold. Please add it asap! 
Great need for a Pro users

**Comment by six7** [comment]
We'll work on this for the January release.
