### ISSUE TITLE
Allow creating a token for multiple themes

### ISSUE THREAD

**Issue by stephen-salyer** [tokens-studio/figma-plugin#1301]
If i have to add a variant to my secondary colors for multiple themes i would like to add it all in one spot.

Name of Token: color.secondary.variant
Theme 1: {Value}
Theme 2: {Value}
Theme 3: {Value}

Action: add to all themes

**Comment by six7** [comment]
In what token set would you like those variations be created? Or is that something that needs to be customizable?

**Comment by stephen-salyer** [comment]
Any token set I would think.

If secondary exist in all of my themes it would be nice to add a token and it's value to all secondary token sets in all themes instead of going to each theme and adding it over and over again.

**Comment by SamIam4Hyma** [comment]
@LukeFinch I think you have something similar to this for an upcoming sprint. Checking its not a duplicate

**Comment by UdayHyma** [comment]
Added to Featurebase Roadmap : [🌜Theme management (pro) enhancements](https://tokensstudio.featurebase.app/p/theme-management-enhancements)

**Comment by SamIam4Hyma** [comment]
Closing as added to featurebase
