### ISSUE TITLE
Deprecate and Replace With

### ISSUE THREAD

**Issue by stephen-salyer** [tokens-studio/figma-plugin#1302]
I would like to deprecate a token and replace it with another token that exist.

**Comment by six7** [comment]
Have you tried using `Inspect` and then the Remap / Bulk remap functionality (little arrow next to an applied token)? That way you can replace all old tokens with a new one.

A dedicated way to mark tokens as deprecated is interesting though, as often we don't want to remove tokens in a breaking manner but just indicate it's deprecated. Offering a quick way to change all applied/used would be neat.

**Comment by stephen-salyer** [comment]
I'll give that a try!

Yeah anyway to change all applied or remap would be cool.

**Comment by Leland** [comment]
They discussed this one on Style Dictionary a while back: https://github.com/amzn/style-dictionary/issues/252

Though it's not a standard (really, just one example of how to do this), they came up with [this example](https://github.com/amzn/style-dictionary/blob/main/examples/advanced/tokens-deprecation/), which adds `deprecated` as a boolean, and `deprecated_comment` to detail what to do about it.

Neither property is supported out of the box in Style Dictionary, so I wouldn't necessarily advocate for them in Figma Tokens' JSON – but may be something to keep in mind here? 🤔

**Comment by SamIam4Hyma** [comment]
@six7 suggest to archive / close this issue as we can currently bulk remap within the plugin and this issue is quite old.

**Comment by charles0122** [comment]
Perhaps this can be reopened: https://www.designtokens.org/tr/2025.10/format/#deprecated
