### ISSUE TITLE
When editing an input with an alias, HOME and END suddenly don't work.

### ISSUE THREAD

**Issue by rbosker** [tokens-studio/figma-plugin#1304]
**Describe the bug**
When editing an input with an alias, HOME and END suddenly don't work, after refocusing it is fixed, but then locks again.

**Expected behavior**
Expect that HOME and END work, also without having to refocusing it.

**Slack**
https://figmatokens.slack.com/archives/C04284ZALGL/p1663658629704259

**Comment by six7** [comment]
Released in 129

**Comment by denis-strong** [comment]
I am still experiencing this same issue after Fix
