### ISSUE TITLE
Make it possible to detach styles in a theme

### ISSUE THREAD

**Issue by rbosker** [tokens-studio/figma-plugin#1305]
**Is your feature request related to a problem? Please describe.**
Currently it's not possible in the UI to detach styles in a theme, but is only possible when editing $themes.json. 

**Describe the solution you'd like**
Add a detach button on the theme management page, so it's possible to detach a style from the UI.
<img width="784" alt="image" src="https://user-images.githubusercontent.com/109062656/191745694-c7e43a90-1315-4b0b-89f7-217b94136bc8.png">
![image](https://user-images.githubusercontent.com/109062656/191747507-5d4d4ea5-6ccf-4b95-a48b-f532f1793630.png)

**Slack**
https://figmatokens.slack.com/archives/C02DEJMS9AP/p1663844986674649

**Comment by mikekamminga** [comment]
Thinking of it, it would probably make sense to have a `detach style` button for each individual token as well to provide more granular control.

**Comment by six7** [comment]
> Thinking of it, it would probably make sense to have a `detach style` button for each individual token as well to provide more granular control.

That's what this issue is about, right? In the Themes modal, we currently only allow detaching individual styles when the style can't be found. Instead it would be better if you could do that anytime.

**Comment by six7** [comment]
Released in 129
