### ISSUE TITLE
Optimize themes.json file

### ISSUE THREAD

**Issue by rbosker** [tokens-studio/figma-plugin#1308]
**Is your feature request related to a problem? Please describe.**
Currently the status of a tokenset is defined per theme, with status 'source', 'enabled' & 'disabled'. When you have a large number of thems/sets, the JSON file can get big and would like to reduce this.

**Describe the solution you'd like**
Leave out the status 'disabled' and consider all sets as 'disabled' unless defined otherwise.

**Additional context**
```
{
    "name": "theme-1",
    "selectedTokenSets": {
      "set-A": "source",
      "set-B": "source",
      "set-C": "source",
      "set-D": "source",
      "set-E": "disabled",
      "set-F": "disabled",
      "set-G": "disabled",
      "set-H": "disabled",
      "set-I": "disabled",
      "set-J": "disabled",
      "set-K": "disabled",
      "set-L": "disabled",
      "set-M": "disabled",
      "set-N": "enabled",
      "set-O": "enabled",
      "set-P": "enabled"
    }
}
```

Could be represented like:
```
{
    "name": "theme-1",
    "selectedTokenSets": {
      "set-A": "source",
      "set-B": "source",
      "set-C": "source",
      "set-D": "source",
      "set-N": "enabled",
      "set-O": "enabled",
      "set-P": "enabled"
    }
}
```

Slack thread: https://figmatokens.slack.com/archives/C0336AEQ06Q/p1664181667215189

**Comment by six7** [comment]
Released in 129
