### ISSUE TITLE
Finding and Caching Tokens

### ISSUE THREAD

**Issue by stephen-salyer** [tokens-studio/figma-plugin#1312]
any move or remap of token/s will throw this counter up. Sometimes it works almost instantly. Most times it will crash the plugin. I typically get anywhere from 10-20 crashes a day. I am grateful for the local save of work that hasnt been pushed to github <3

<img width="339" alt="image" src="https://user-images.githubusercontent.com/39383255/192856725-6f688629-5960-40a8-8175-a7c0a467a538.png">

followed by this

<img width="569" alt="image" src="https://user-images.githubusercontent.com/39383255/192857985-4ee4dbd8-98c7-4b05-b713-b21a96ec18cd.png">

**Comment by six7** [comment]
I'll close this in favor of https://github.com/tokens-studio/figma-plugin/issues/1751 which we'll use to track related info, sorry for no action on this yet, it's quite hard to debug.
