### ISSUE TITLE
Add the possibility to make the ui of the plugin larger

### ISSUE THREAD

**Issue by rbosker** [tokens-studio/figma-plugin#1314]
**Is your feature request related to a problem? Please describe.**
Currently there is no possibility to make the UI of the plugin larger. This makes it harder for users with accessibility needs and also makes it hard to share on calls for example.

**Describe the solution you'd like**
Add the possibility to make the ui plugin larger in the settings tab.

**Additional context**
Needs design and need to be shaped:
- which sizes are we going to support?

**Comment by SamIam4Hyma** [comment]
@rbosker suggest to archive / close this issue as we can currently resize the plugin with the UI (bottom right) and its quite stale.
