### ISSUE TITLE
Enhancement: Improve the dropdowns throughout the plugin.

### ISSUE THREAD

**Issue by rbosker** [tokens-studio/figma-plugin#1315]
**Is your feature request related to a problem? Please describe.**
Currently the dropdown for searching tokens will always show max 6 results. If you have a large number of tokens, this can make it hard to find the token you're looking for.

**Describe the solution you'd like**
Make the dropdown larger, so more tokens are shown in one view.

**Additional context**
<img width="354" alt="image" src="https://user-images.githubusercontent.com/109062656/193249403-eb88bc89-3bbb-4ccc-99ce-dce28f1791e1.png">

**Comment by six7** [comment]
Blocked by #1265

**Comment by six7** [comment]
Closing this as #1203 should solve this already.
