### ISSUE TITLE
Filtering of git branches in the selector

### ISSUE THREAD

**Issue by unpunnyfuns** [tokens-studio/figma-plugin#1326]
**Is your feature request related to a problem? Please describe.**
When switching branches, there is no way to filter branches. On large git repos this can create a prohibitively large list to select from.

**Describe the solution you'd like**
A way to filter branch names in the git branch selector, similar to the token value selector.

**Comment by SamIam4Hyma** [comment]
@six7 if this is actively being worked on please remove the request label 
- if you want it migrated over to the featurebase, please remove the enhancement label (requests will be migrated)

**Comment by SamIam4Hyma** [comment]
@LukeFinch please check to see if this can be closed/archived or if the work is still in progress

**Comment by UdayHyma** [comment]
[Migrated to Featurebase](https://tokensstudio.featurebase.app/p/git-sync-enhancements)
