### ISSUE TITLE
GitLab with AOP LDAP protocol connection fail

### ISSUE THREAD

**Issue by simosiolek** [tokens-studio/figma-plugin#1332]
**Describe the bug**
GitLab with AOP LDAP protocol connection fail

**To Reproduce**
1. Go to Settings
2. Click on "Add new credentials" and configure the connection to GitLab using AOP LDPA protocol
3. See error "Error syncing with GitLab, check credentials"

**Expected behavior**
Setting up connection to GitLab using AOP LDPA protocol

**Comment by SamIam4Hyma** [comment]
@six7 assuming this can be closed as it mentions a bug/issue but is a couple years old now.

**Comment by six7** [comment]
Closing this as stale. Please reopen if you feel this was done in error, and provide further reproduction steps.
