### ISSUE TITLE
Bulk remapping: allow remapping a whole document

### ISSUE THREAD

**Issue by rbosker** [tokens-studio/figma-plugin#1333]
**Is your feature request related to a problem? Please describe.**
Currently you have to select layers, before you can bulk remap your tokens. If you now want to replace all tokens in a document with for example different pages, there is no easy way to bulk remap all these tokens.

**Describe the solution you'd like**
Make it possible to bulk remap tokens in a whole document, without having to select the layers.

**Additional context**
Needs further shaping/design.

**Comment by six7** [comment]
Would say we could add a checkbox to the Bulk remap
`Remap across document (slow)` which just performs the bulk remap on the Document.

**Comment by keithbarney** [comment]
Yes please!
