### ISSUE TITLE
Add shortcut for editing a token

### ISSUE THREAD

**Issue by rbosker** [tokens-studio/figma-plugin#1340]
**Is your feature request related to a problem? Please describe.**
Currently you have to right click on a token to select edit. 

## Acceptance criteria
- Let's add way where users can a `Cmd + Click` on a token to open the `Edit token dialog`.
- Let's make sure this doesn't interfere with the `Ctrl + Click` when triggering the context menu
- Let's make sure this works on both Mac and Windows keyboards.

**Additional context**
https://figmatokens.slack.com/archives/C02JAL48UDN/p1665576926578579

**Comment by six7** [comment]
I'd propose cmd+click as double click sounds very tricky to time right
