### ISSUE TITLE
Show a Blue Dot when there are remote changes that can be pulled

### ISSUE THREAD

**Issue by rbosker** [tokens-studio/figma-plugin#1343]
**Is your feature request related to a problem? Please describe.**
Currently you only see a blue dot in the bottom of the plugin, when you have changes to push to your syncing provider.

**Describe the solution you'd like**
Show a blue dot when there are remote changes available from the syncing provider.

We should check the remote to see if there's new changes that can be pulled, and if yes, show the blue dot. We can do that by
- polling the repository (performing a pull every `10` (?) seconds - we should see if that affects performance and tweak that number)
- if there's changes that lead to a different token listing, we should show the blue dot

Let's see if we can find a lightweight solution that doesn't affect performance (is there maybe a simple check for `last commit` that doesn't require us to check the whole token tree? - like we know the commit hash of the current pull, can we compare that to the last commit hash on the remote?

**Additional context**
![image](https://user-images.githubusercontent.com/109062656/195599278-c2f63cb3-aee9-4233-8c83-3b136fd5a7c1.png)

**Comment by six7** [comment]
I'd also say we should perform this check quite frequently, maybe every 10 seconds?

Not sure if there's a way where we can do it without polling 🤔 but if there is, that would be ideal.
