### ISSUE TITLE
Shortcut cmd/ctrl + enter/return triggers loading modal

### ISSUE THREAD

**Issue by rbosker** [tokens-studio/figma-plugin#1344]
**Describe the bug**
The shortcut cmd/ctrl + enter/return should push tokens, when you're in the push modal:
![image](https://user-images.githubusercontent.com/109062656/195621118-20c753a4-4884-43f2-a72a-ca0374dbc762.png)

Now the shortcut on other places in the app, opens the loading modal below. This loader will keep on loading and nothing happens. You have to exit this modal manually.
![image](https://user-images.githubusercontent.com/109062656/195621887-a536132a-3e44-4378-9b54-cd8f61e056ec.png)

**To Reproduce**
Open de plugin and hit the shortcut cmd+enter on any place.

**Expected behavior**
When using the shortcut cmd+enter in the plugin, nothing should happen. Only in the push modal, this should trigger a push to your syncing provider.

**Comment by cchaos** [comment]
I'd like to add to the `Expected Behavior` if possible:
When in the `description` or other multi-line text area, `cmd+enter` should submit/save.

**Comment by six7** [comment]
@rbosker lets try to get this in as one of the items in the current iteration for next week's bugbash

**Comment by six7** [comment]
Released in 129
