### ISSUE TITLE
@six7/figma-tokens-helpers fails to install in pipelines

### ISSUE THREAD

**Issue by reccanti** [tokens-studio/figma-plugin#1354]
**Describe the bug**
When trying to install this package in a pipeline running in a linux environment, I get the following error during installation:

```
error esbuild-darwin-64@0.14.54: The platform "linux" is incompatible with this module.
--
  | error Found incompatible module.
```

I can't find the original package on Github, but if I had to guess, it's because you're using the `esbuild-darwin-64` package directly rather than just `esbuild` and letting that determine which version to download

**To Reproduce**
1. Create a sample project with this as a dependency
2. Create a pipeline to run the install command in a non-Macos environment

You might also be able to simulate this by attempting to install the package locally on a windows or linux computer, now that I think about it

**Expected behavior**
The install step should finish without errors

**Comment by six7** [comment]
Thanks! I'll dig into that this week and publish as its own repo as well 👍

**Comment by six7** [comment]
sorry for the delay on this. we'll have some repository name changes coming and I wanted to wait for that (early december)

**Comment by reccanti** [comment]
No worries, thanks for keeping up with this!

**Comment by SamIam4Hyma** [comment]
@six7 is this bug still active or can it be closed/archived?

**Comment by SamIam4Hyma** [comment]
Closing this comment as it's stale.
