### ISSUE TITLE
When using JSONbin you always get the message to recover local changes

### ISSUE THREAD

**Issue by rbosker** [tokens-studio/figma-plugin#1360]
**Describe the bug**
When using JSONbin you always get the message to recover local changes, while there are no local changes. No matter if you update the remote tokens, this modal always appear.

**To Reproduce**
1. Connect tokens to JSONbin
2. Update remote tokens
3. Re-open te plugin
4. The modal below will be shown.

**Expected behavior**
if there are no local changes, this modal must not show.

**Screenshots or Screencasts**
<img width="449" alt="image" src="https://user-images.githubusercontent.com/109062656/196684206-80af8e0f-8f7b-4fe4-a080-317d1272a7f7.png">

https://figmatokens.slack.com/archives/C02DLQXNY6Q/p1666172249498539

**Comment by six7** [comment]
Released in 129
