### ISSUE TITLE
Token groups can't be named 'transparent' for references to work

### ISSUE THREAD

**Issue by rbosker** [tokens-studio/figma-plugin#1361]
**Describe the bug**
When you name a token group 'transparent', references to the tokens in this group won't work.
This does apply to all tokens, not only color tokens.

**Notes**
If possible, we also need to check if this can happen with other names for tokengroups to prevent future issues with referencing.

**Screenshots or Screencasts**
<img width="616" alt="image" src="https://user-images.githubusercontent.com/109062656/196728493-0196af2b-d677-4b8d-ac26-5735a1737c93.png">

**Comment by swordEdge** [comment]
Can't reproduce the bug.

**Comment by six7** [comment]
@rbosker can you create a video where you reproduced it?

**Comment by six7** [comment]
I'm guessing this was due to another token that came later that was messing up a reference. We do not have any restrictions on token names as far as I know.
