### ISSUE TITLE
Export selected tokens

### ISSUE THREAD

**Issue by bewarai** [tokens-studio/figma-plugin#1371]
If possible, could we find some way on how to export a set of tokens attached to a certain selection. For example: I have an auto-layout with some tokens and when exporting those, I could maybe auto-translate them to html/css?

**Comment by six7** [comment]
By export do you mean export to a file? And only the tokens used in the selection? Like `fill: bg.default, border: border.muted` ?

**Comment by bewarai** [comment]
I think that is right.
<img width="550" alt="Screenshot 2022-10-25 at 09 29 19" src="https://user-images.githubusercontent.com/33145617/197710964-bfc143bc-ed64-40b3-b947-6f234585ae73.png">

The tokens in the image are the ones I used in my selection. I like to have some way to export them, maybe even sync them with Github.

If you could do - for example output something like this (the card being an auto-lay out):

"Card" : {
"Desktop.gap.gp-md"
"Theme.base.primary-background"
"br-xs"
"shadow"
"Desktop.padding.card"
  }

**Comment by SamIam4Hyma** [comment]
@six7 proposing to merge/archive as it is covered in #1969
