### ISSUE TITLE
Export/overview tokens used in Figma page

### ISSUE THREAD

**Issue by bewarai** [tokens-studio/figma-plugin#1380]
I would like to see what tokens are used on my entire Figma page. Now I have to select certain artboards or all artboards to have a complete overview. 

Imagine I make a dashboard where I have an overview of what tokens are used where and at what time the tokens were edited? For example: My button is used on 2 artboards (3 times on artboard 1 / 2 times on artboard 2). This is great for design system managers as they have a better segmented overview of where tokens are settled and see what impact this can have.

Maybe at first a better sorting system? And of course someway to export/sync it with Github so that I can attach it to a dashboard?

**Comment by LukeFinch** [comment]
This request has been moved to our new feedback tool. Go check out https://tokensstudio.featurebase.app/ to create a free account. You can upvote and comment on existing posts, make a new request, and subscribe to be notified when requests move into our roadmap.

**Comment by UdayHyma** [comment]
Added to Featurebase Roadmap : [🪙 Add support for Token usage metadata](https://tokensstudio.featurebase.app/p/token-usage-metadata)
