### ISSUE TITLE
Conflicting token group

### ISSUE THREAD

**Issue by rbosker** [tokens-studio/figma-plugin#1386]
**Describe the bug**
When renaming a token group from for example `color.primary.base` to `color.primary`, you get a warning stating that the name already exists. 
This is correct behaviour when there are multiple tokens within the group. When there is only one token within the group, we should make it possible to rename the token

**Expected behavior**
If a token group contains 1 token, you should be able to make this renaming, without getting a warning.

**Screenshots or Screencasts**
Screenshot showing the case which we should allow.
https://user-images.githubusercontent.com/109062656/198219916-83e1917c-631b-4760-86d5-a5bfd2408248.mov

Slack:
https://figmatokens.slack.com/archives/C02DLQXNY6Q/p1666816644389029

**Comment by six7** [comment]
Released in 129
