### ISSUE TITLE
Paragraph indent not working with the value '0'

### ISSUE THREAD

**Issue by rbosker** [tokens-studio/figma-plugin#1388]
**Describe the bug**
When a text layer has a typography token with `paragraph indent` , it doesn't work if with the value `0`

**Expected behavior**
See attached screen capture. It does work for all other values than `0`. Also `0px` works for example.

**Screenshots or Screencasts**
https://user-images.githubusercontent.com/109062656/198247607-3f046b4c-1025-49e6-b790-98305af8f250.mov

**Related issue**
https://github.com/six7/figma-tokens/issues/735

**Slack**
https://figmatokens.slack.com/archives/C02DLQXNY6Q/p1666729817334339

**Comment by six7** [comment]
Released in 129
