### ISSUE TITLE
Support for CSS in JS output?

### ISSUE THREAD

**Issue by rajuashok** [tokens-studio/figma-plugin#1399]
Hi there, I'm curious if you plan to update `token-transformer` to support .js/.ts outputs. This is specifically to support CSS in JS libraries like Styled Components, System UI or Chakra UI.

Or is there a way to use the existing json output for CSS in JS ?

**Comment by six7** [comment]
You can use to transform the output to CSS in JS:
https://amzn.github.io/style-dictionary/
https://github.com/six7/figma-tokens-examples
