### ISSUE TITLE
When changing a group name, let users change the full path

### ISSUE THREAD

**Issue by keeganedwin** [tokens-studio/figma-plugin#1411]
I'm not sure if I've missed out conversations/issues in the slack channel regarding this but, in order to change the _semantic_ designation of a token, I have to **edit** individual tokens renaming them to change their semantic designation as follows:

https://user-images.githubusercontent.com/93133012/199918294-e9d9b546-b8b1-46c7-9a77-d565de33591d.mov

It would would be handy if I could _bulk_ edit the designation of tokens further than their component specific semantics:

https://user-images.githubusercontent.com/93133012/199919018-d9b5ad31-da88-43ca-a87d-6684f2281834.mov

**Comment by six7** [comment]
I think what we'd want to do is instead of just letting users edit the current group, let them edit the full path.

Then they could do what you suggested here.

**Comment by keeganedwin** [comment]
Yes, that sounds great!

**Comment by six7** [comment]
Released in 129
