### ISSUE TITLE
Composition values not getting merged

### ISSUE THREAD

**Issue by Blyawon** [tokens-studio/figma-plugin#1424]
**Describe the bug**
Base theme defines a composition with multiple values. A second theme overwrites only one value of the composition in the base theme. The remaining values of the base theme are then not getting applied any more.

**To Reproduce**
1. Create a base theme with a composition with multiple values e.g. border-radius and fill that is linked to a generic color token
2. Create a 2nd theme that overwrites the border-radius and has a different generic color token but this token is not applied in the composition
3. when applying the 2nd theme the fill in this example doesn't change since it's not in the composition token

**Expected behavior**
I would expect that compositions are getting merged even when individual values/tokens are not copied over to an extending theme

**Comment by six7** [comment]
We'll tackle this in our M2 of composition tokens.

I think we'll either work on this to make this a default for all `composite` type tokens (typography, shadow, border, etc) - where if multiple tokens use the same name, we try to inherit and just change values (after all, users could override or even deactivate those sets if they do not wish to have that behavior).

An alternative would be to specify `inheritance`, which would be more obvious, but requires an additional step.

**Comment by esthercheran** [comment]
https://user-images.githubusercontent.com/66366384/222440439-5fdb88f8-0156-478a-8370-5c46d6d8c3f2.mov
