### ISSUE TITLE
Gradients can't be used directly in compositions

### ISSUE THREAD

**Issue by Blyawon** [tokens-studio/figma-plugin#1425]
**Describe the bug**
When using a gradient directly in a fill of a composition without a referenced token, the fill is not being applied in Figma even though the gradient get's interpreted correctly. Gradients in compositions only work when the gradient is being linked to a generic token of the gradient

**To Reproduce**
1. Create a composition
2. Put a gradient from color a to b inside of the fill
3. Try to apply this composition to a frame
4. Fill is not being applied

**Expected behavior**
Gradients work without linked tokens in the compositions

**Comment by six7** [comment]
Released in 129
