### ISSUE TITLE
Plugin applying Box Shadow in wrong order

### ISSUE THREAD

**Issue by dermyhughes** [tokens-studio/figma-plugin#1427]
**Describe the bug**
The plugin supports adding multiple box shadows as a token. The issue is the order of the shadows is getting flipped when it gets converted to Figma Effects. This means the styles from the token are not displayed as intended on Figma.

**To Reproduce**
1. Create a Box Shadow token
2. Create a Drop Shadow token with the values `0 0 0 1px red`.
3. Create a second Drop Shadow token with the values `0 0 0 2px blue`
4. Create a third Drop Shadow token with the values `0 0 0 3px green`
5. Save the token
6. Apply the token to an element on Figma.
7. Note the order of the styles in the Effects panel. It is the reverse order of what it should be.

**Expected behavior**
The order created in the plugin should be maintained when applied to a Figma element.

An example of the implemented tokens showing why the order matters.
https://codepen.io/dermyhughes/pen/MWXoXwr

![image](https://user-images.githubusercontent.com/17506746/201889051-c87b29ae-0fb5-4f9b-8708-0e449add61a2.png)

**Screenshots or Screencasts**
Token on Plugin
![image](https://user-images.githubusercontent.com/17506746/201693853-c3dacd04-315a-42bd-9723-fca54386c141.png)

Order of styles as created on Figma (Note the flipped order)
![image](https://user-images.githubusercontent.com/17506746/201694077-edece63a-2722-4a6d-b25a-fab412904abe.png)

**Comment by six7** [comment]
Released in 129
