### ISSUE TITLE
Background Blur Tokens

### ISSUE THREAD

**Issue by realtenacious** [tokens-studio/figma-plugin#1431]
**Is your feature request related to a problem? Please describe.**
I guess the problem would just be that there is no current way to support background blur tokens.

**Describe the solution you'd like**
An area to document background blur. It would be great if it could also be set up to support a color applied as the background blur. I'll typically have a light version (eg. {opacity.white.24%}) and a dark version (eg. {opacity.black.24%}).  

**Describe alternatives you've considered**
I'm currently just documenting the token values in "other." But wouldn't use that to apply it as it also doesn't capture the color I would need with it. Although there might be way of doing that and I'm just uneducated on how. 

**Additional context**
This is how I typically document it. (grey labels are placeholder information)
<img width="1073" alt="Screenshot 2022-11-17 at 8 07 19 AM" src="https://user-images.githubusercontent.com/86127745/202454580-6d9b2099-2588-4dbd-8885-f478eda3f789.png">

**Comment by six7** [comment]
This will be supported in the next release with `dimension` tokens (it's already merged in the dev branch). We plan to ship this early december (we'll take a bit more time to properly test).

It does only control the blur value, though. You'd need a dedicated `fill` color token to apply the fill for it.

**Comment by six7** [comment]
Released in 129
