### ISSUE TITLE
Renaming a token that is used in a Composition does not remap them

### ISSUE THREAD

**Issue by bewarai** [tokens-studio/figma-plugin#1433]
I have a variant set for different kind of buttons. When I rename my token from for example - "button-l" to "size.button-l" it does not remap all my variants. This apparently only happens when renaming tokens in composition tokens.

**Comment by six7** [comment]
So to be clear:

You have a token named `button-A`
and you are using the token in a composition token
and then you rename that token to `button-B`
the changes are not done on tokens of type `composition` (eg the one where you were using it in)?

**Comment by swordEdge** [comment]
Can't reproduce the bug

**Comment by six7** [comment]
My guess is this is related to https://github.com/tokens-studio/figma-plugin/issues/1528 - closing it as we'll ship a fix for that one next release.
