### ISSUE TITLE
Display names for tokens and groups

### ISSUE THREAD

**Issue by beauroberts** [tokens-studio/figma-plugin#1434]
**Is your feature request related to a problem? Please describe.**
First, thanks so much for this amazing tool.

What I describe here is a very low priority issue, but one that would improve the pleasantness of working with the plugin for both our designers and developers. At the moment we are a bit split internally about whether to name our tokens using camelCase or something more human readable. Obviously, our preference is to display the more human readable names to our designers in the Figma Tokens plugin UI, but maintain a more machine-friendly camelCased name when saved to JSON. If we go one way or the other, we impact either the designer or developer ergonomics of working with tokens (albeit only _very_ slightly).

**Describe the solution you'd like**
The ability to just render the token or group name in sentence case would handle 80+% of cases, and make the token tree a bit friendlier for our designers to navigate.

In a smaller set of cases, it would be useful to be able to add some metadata for a display name that would be shown instead of the raw token name. Having the raw name available as a tooltip would be great. When displaying or providing a path to a token, I would expect that the raw names would be used in all cases. 

**Describe alternatives you've considered**
-

**Additional context**
-

**Comment by beauroberts** [comment]
Also, please let me know if there's some way I can help out.

**Comment by six7** [comment]
Would it help you if you were able to choose how group names are displayed? I'd rather avoid a field in the tokens data for this and would prefer making this a user-choice.

**Comment by beauroberts** [comment]
@six7 Thanks for the response. I think that would be helpful for sure.

**Comment by LukeFinch** [comment]
This request has been moved to our new feedback tool. Go check out https://tokensstudio.featurebase.app/ to create a free account. You can upvote and comment on existing posts, make a new request, and subscribe to be notified when requests move into our roadmap.

**Comment by UdayHyma** [comment]
Added to Featurebase Roadmap : [🪙 Token organization enhancements](https://tokensstudio.featurebase.app/p/token-organization-enhancements)
