### ISSUE TITLE
Accept "null" value to un-assign previously added value

### ISSUE THREAD

**Issue by rbosker** [tokens-studio/figma-plugin#1436]
**Is your feature request related to a problem? Please describe.**
Currently there is no way to un-assign previously added values via a token.

**Describe the solution you'd like**
Add a value like "none", "unset" or another logical naming, so a user is able to nullify previously added values.

**Describe alternatives you've considered**
Similar to the “none” value in CSS.

**Additional context**
https://figmatokens.slack.com/archives/C02DEJMS9AP/p1665523001818949?thread_ts=1665513576.411419&cid=C02DEJMS9AP

Some token types such as `asset` currently cannot be reset to `no asset` without removing the token. However, sometimes when using Theming you may want a layer to have an image fill, and sometimes you don't.

We should support this with a reserved keyword of `none` that would remove the `image fill` from the layer.

Other applications where this applies is 
- Assets (setting to no image fill)
- Colors (setting to no color fill)
- Shadows (setting to no shadow effect)

### Add option to Inspect

We should also make this option discoverable in the UI. When selecting tokens in Inspect, add a `Set to none` option which sets this option on the selected properties.

![Image](https://user-images.githubusercontent.com/4548309/206903369-21981aff-3c44-4105-9339-d604d252460c.png)

![Image](https://user-images.githubusercontent.com/4548309/206909068-f1755799-798c-4ad9-bced-66ec08433570.png)

**Comment by six7** [comment]
I'd suggest to go with `none`

**Comment by six7** [comment]
Released in 129
