### ISSUE TITLE
Add an option to token-transformer to treat filename as parent key

### ISSUE THREAD

**Issue by six7** [tokens-studio/figma-plugin#1438]
As described in https://github.com/six7/figma-tokens/issues/1375 users sync their tokens using multi-file sync to GitHub and then want to be able to transform individual files using token-transformer. They'd need a way to indicate that they file name is to be treated as the parent key, not the first level in the JSON.

**Comment by SamIam4Hyma** [comment]
@jorenbroekema is this still a known issue with the transformer or can it be closed?

**Comment by jorenbroekema** [comment]
token-transformer deprecated in favor of using sd-transforms, dont think it's a problem there since we first let SD merge inputs into a dictionary prior to transforming or expanding tokens
