### ISSUE TITLE
Ability to set unique token name from Figma style name

### ISSUE THREAD

**Issue by ryanbelisle** [tokens-studio/figma-plugin#1439]
## Problem
When declaring tokens that also have associated Figma styles (color, text, effects) the hierarchy of the token name determines the naming structure of the Figma style. This is very problematic. The way we structure Figma styles will probably be different than the underlying token taxonomy. This also limits the flexibility to re-structure Figma styles since they will impact the token names introducing 'breaking changes' per-se.

Name: `pds.tkn.color.purple.400`
Figma style: `pds / tkn / color / purple / 400`

## Solution Idea
- Make the token name independent from the Figma style name and allow them both to be unique.
- Still allow the token -> Figma styles to stay in sync in ways that support the unique token name from Figma style name (probably the really hard part!)
- Add the ability to read, update, and set the Figma style name from the Edit Token modal on applicable token types.

The above would allow independent control of the token name and Figma style names. Thus giving power and control to create names for each platform that make sense vs sticking to a rigid structure that can't be changed.

### Example 1
Lets say I want to have a `core` Tier of colors, and a `semantic` tier of colors, but don't want to include certain parts of the token name in the Figma style name and vice-versa. I also want my Figma color styles to have different names which make more sense for designers and how Figma works to keep the hierarchy simpler.

**Core Color Token**
Name: `pds.tkn.color.purple.400`
Figma style: `PDS Palette / Purple / 400`

**Semantic Color Token**
Name: `pds.tkn.color.primary.key`
Figma style: `PDS Primary / Key`
References: `pds.tkn.color.purple.400`

### Example 2
Lets say I have some component-specific token groups for colors, but I don't want to put `component` in the token name. However, it would make sense to keep it in the Figma style name to separate these from other color styles.

Name: `pds.tkn.button.surface.color.default`
Figma style: `PDS Components / PDS Button / Surface Default`

Thanks for considering! I feel this would be a nice enhancement to the plugin...

**Comment by AlexisDoroszkiewicz** [comment]
Was about to post for the exact same issue
Glad to see it's not just on our side :) 

Did you find a solution for this ?

**Comment by SamIam4Hyma** [comment]
@six7 proposing we close this one as its stale and can we reintroduced in Featurebase if the request is till relevant
