### ISSUE TITLE
Tracking tokens

### ISSUE THREAD

**Issue by bewarai** [tokens-studio/figma-plugin#1441]
I would like to have an easy way to track where certain tokens are used. I have a button.lg and I would love to know how many times this is used. On which pages, how many pages, other documents? so that if I make a change I know what impact this has across the entire organisation.

**Comment by six7** [comment]
Very interesting, thank you for creating this.

Out of interest, would you want to differentiate between tokens directly used and tokens used in an instance (eg in a component)? For example a token placed in a button might only be used 8 times, but indirectly it is used thousands of times across your feature pages.

Also, what's the main information you'd like to get out of that data? Usage? Or would you like to track that over time to understand adoption?

**Comment by bewarai** [comment]
I would like to see and know everything. If it's a button, I would like to track tokens that are just used within that instance. But at the same time I would like to track it maybe not within that instance. The button could have a color that inherits from my accent color. So In both cases I would love to see what the impact is on the button and the accent color used throughout the project.

We can get see indeed usage of that specific component, track impact when there is a change, based on that we might need to add new tokens to counter impact on other places. We can see if the it has a big impact or small. We could also see how tokens are changed over the course of a project and specific component. I could visualised in graphs or in spiderwebs etc. Could be very ambitious.

**Comment by LukeFinch** [comment]
This request has been moved to our new feedback tool. Go check out https://tokensstudio.featurebase.app/ to create a free account. You can upvote and comment on existing posts, make a new request, and subscribe to be notified when requests move into our roadmap.

**Comment by UdayHyma** [comment]
Added to Featurebase Roadmap : [🪙 Add support for Token usage metadata](https://tokensstudio.featurebase.app/p/token-usage-metadata)
