### ISSUE TITLE
[Style creation] Add the ability to append values to the descriptions when creating styles from tokens

### ISSUE THREAD

**Issue by cchaos** [tokens-studio/figma-plugin#1449]
**Is your feature request related to a problem? Please describe.**

_Copy/paste from Slack community:_

Without knowing strictly what the token -> style process looks like under the hood, I wonder if there might be an extra step where we can select what we'd like output in the description of the style? For example, I know a lot of my designers remember colors by their hex and not necessarily by the token name, so I'm copy/pasting the hex value into the description so that's it's searchable in Figma's style panel. It's sooo manual right now.

**Describe the solution you'd like**
I'd love to check a box that says "Output value in the description" when creating styles 

**Describe alternatives you've considered**
I tried to create a script using Automator, but it doesn't seem to have access to style descriptions or the ability to edit styles, only create and use them. But my guess if I created new styles we'd lose the link to the token.

**Additional context**
An example of my use case is when trying to migrate designers to the new naming convention, I add the old names & values to the description to make both searchable. The value is helpful when designers are trying to match the color they see in dev tools which purely shows up as a hex value not the variable name (we don't use CSS vars).

<img width="240" alt="Screen Shot 2022-11-21 at 22 35 40 PM" src="https://user-images.githubusercontent.com/549577/203402673-254a6700-4243-4b8e-9143-3ee74cfd327c.png">

**Comment by SamIam4Hyma** [comment]
@six7 proposing we archive as its stale.
