### ISSUE TITLE
Figma Tokens does not currently support the Gogs Git self-built server

### ISSUE THREAD

**Issue by zhudongyong** [tokens-studio/figma-plugin#1455]
**Is your feature request related to a problem? Please describe.**
> We have created tokens through Figma Tokens, but when we need to associate Git to share with engineers, we cannot associate Git server built by our company (the server is built by Gogs Git).

**Describe the solution you'd like**
> Hope to bind Git server built by Gogs in the Figma Tokens Setting interface, and then share it to designers automatically

**Describe alternatives you've considered**
> Verify that the connection form of the URL supports any available Git servers

**Additional context**
<img width="415" alt="截屏2022-11-28 10 09 44" src="https://user-images.githubusercontent.com/3364339/204177735-69a5c13f-06f1-4518-87d5-5f8febcf886a.png">

**Comment by SamIam4Hyma** [comment]
@six7 proposing we archive unless there are more details I'm not aware of that would allow me to tag the request
