### ISSUE TITLE
Color names don't show up after creating styles in Figma

### ISSUE THREAD

**Issue by ahhauhhu** [tokens-studio/figma-plugin#1457]
**Describe the bug**
I added color tokens each with a unique name that is different from each other and from existing styles in the Figma file. However, styles created from those tokens don't have any names.

**To Reproduce**
create a color token in the plugin with a name of "c1"
make sure c1 is a unique name in the plugin's JSON and is not a duplicate of any existing Figma styles in the document
create a style from the token c1

**Expected behavior**
I expect Figma styles created from the plugin's tokens to carry over the same names.

**Screenshots or Screencasts**
![image](https://user-images.githubusercontent.com/30395676/204472048-d07b150e-1536-4455-82df-84fb2be8091c.png)
![image](https://user-images.githubusercontent.com/30395676/204472075-c490ee37-dc89-42ba-b5e2-393a420f2d6f.png)

**Figma file (optional)**
Send us the link to a Figma file containing a reproducible example

**JSON (optional)**
If possible, attach the JSON that leads to this bug.

**Comment by larserbach** [comment]
Hi, I just stumbled over your post. Is it possible you have checked in your settings the option`Ignore first part of token name for styles`? This would explain why your styles have no names. Unchecking it, might resolve your issue.

<img width="746" alt="Screenshot 2022-12-02 at 12 48 28" src="https://user-images.githubusercontent.com/1247117/205286970-6b4d2bc1-e578-4ffb-b2c4-6976808e0ea2.png">

**Comment by six7** [comment]
Closing this in favor of the issue we'll use to track work https://github.com/tokens-studio/figma-plugin/issues/1612
