### ISSUE TITLE
When using Figma Branches, changes in the main file won't be updated automatically in branches

### ISSUE THREAD

**Issue by rbosker** [tokens-studio/figma-plugin#1458]
**Describe the bug**
When you are using Figma Branches and make changes to the main file, these changes won't be updated automatically in your branches.

**To Reproduce**
Note: Branches can only be used on Figma Enterprise. In the shared links the steps can be found to setup Figma Branches.

**Expected behavior**
As Figma states in the linked video below, 'Branches receive any updates made to the main file'.

**Links**
https://help.figma.com/hc/en-us/articles/360063144053-Guide-to-branching

**Comment by six7** [comment]
This is currently blocked by Figma, as `root` does not get merged plugin data when branches get merged.

**Comment by LukeFinch** [comment]
This request has been moved to our new feedback tool. Go check out https://tokensstudio.featurebase.app/ to create a free account. You can upvote and comment on existing posts, make a new request, and subscribe to be notified when requests move into our roadmap.

**Comment by UdayHyma** [comment]
Added to Featurebase Roadmap : [ᛘ Support branches in Figma
](https://tokensstudio.featurebase.app/p/support-branches-in-figma)
