### ISSUE TITLE
Improve error messages when connecting to a remote repository

### ISSUE THREAD

**Issue by larserbach** [tokens-studio/figma-plugin#1463]
Hi, I hope the following makes sense:

Preconditions:
I'm not a owner of a Pro-Account

The Problem:
I was curious what would happen if I added a string to the themes-array.
So I created a new branch and changed this line ` "$themes": [],` to ` "$themes": ["light", "dark"],` and pushed it.
In Figma Tokens I wanted to switch to my newly created branch to see what happened but got prompted with `Error syncing with GitHub, check credentials`
First I thought it would be an issue with my access-token or a spelling mistake, but everything was fine. 
Only when I reverted the change back to  ` "$themes": [],`, I was able to connect to the new branch.
My assumption is, if a non-pro-user tries to connect to a repo, where themes are defined in the JSON - you get the error message mentioned above.

The request:
I believe, for a better understanding of the issue, the error message should change to something along those lines: 
`Connect to repo was denied, because your current plan does not support themes. You can either upgrade or remove all themes from the requested JSON-file.`

**Comment by six7** [comment]
Closing this, we'll be improving error messages but this one isn't an error due to pro licensing
