### ISSUE TITLE
[Beta-129]: JSONBin consistently asks for Recover local changes

### ISSUE THREAD

**Issue by six7** [tokens-studio/figma-plugin#1491]
When using JSONBin sync we seem to have introduced a regression (possibly with the generic versioned storage), where using jsonbin asks me for Credentials every time I relaunch the plugin.

Using `beta-129` branch.

For the fix, base the work on the `release-129` branch (and a PR merging into that one)

![Image](https://user-images.githubusercontent.com/4548309/208987708-a2018aad-a5ca-42af-aa24-aab708b5722e.png)

To reproduce:
- Set up a jsonbin sync
- Create a new token, wait for jsonbin to have saved
- Relaunch the plugin

Note that it does ask you for Recover local changes, although we just successfully pushed. it seems `checkForChanges` is not reset properly anymore.

**Comment by SorsOps** [comment]
I pulled tag 0.128 and ran it locally, it appears that this issue might be prevalent prior to the 129 release ?

![image](https://user-images.githubusercontent.com/80043879/209148278-ed65abfd-4032-4ce8-b146-0606ef59cc5d.png)
![image](https://user-images.githubusercontent.com/80043879/209148763-169b4486-3bfa-4cdf-9154-106469cff931.png)
