### ISSUE TITLE
Failed storage providers are registered

### ISSUE THREAD

**Issue by SorsOps** [tokens-studio/figma-plugin#1492]
**Describe the bug**

When creating a new storage provider, when an error occurs 

**To Reproduce**
1. Create a new JSONBin storage provider
2. Set an ID for a missing bin
3. When the error is show "There was an error connecting. Check your credentials.", remove the optional ID so one is autogenerated
4. Click Save Credentials
5. See last screen shot for what is registered

**Expected behavior**
A single storage provider for the successfully registered provider is created instead of multiple 

**Screenshots or Screencasts**
![image](https://user-images.githubusercontent.com/80043879/209132109-adc8fbcb-d120-4601-a9ab-2a64a628f90b.png)

![image](https://user-images.githubusercontent.com/80043879/209131605-7ff2c4d4-0618-4543-9b27-18249fa5bdc6.png)

**Figma file (optional)**
Figma file does not affect this

**JSON (optional)**
JSON does not affect this

**Comment by SamIam4Hyma** [comment]
closing this issue for now as its stale and not planned for work.
