### ISSUE TITLE
token-transformer is stripping the parent key from the output.json

### ISSUE THREAD

**Issue by matt0rtega** [tokens-studio/figma-plugin#1496]
Working with a json file that has the following format:

`{
  "alias": {
   "control": { 
...
}
  }`
  
  results in the following output:
  
  `{
   "control": { 
...
  }`
  
  The expected output is one with the same parent key. Running this also on file with multiple parent keys expands them all.

**Comment by six7** [comment]
That's the sole reason of token-transformer currently, do generate an output file that does not include the concept of "sets".

What's your use case of running token-transformer? How would you expect the output to look like if there's references between token sets?
