### ISSUE TITLE
Sensitive header values in Generic Versioned Storage

### ISSUE THREAD

**Issue by SorsOps** [tokens-studio/figma-plugin#1504]
**Is your feature request related to a problem? Please describe.**
There are cases where the headers added to the Generic Versioned Storage provider are sensitive , eg Authorization bearer token headers, and I don't want these to be visible when performing demos.

**Describe the solution you'd like**
A tickbox next to the additional headers that can be used to hide the values once inputted.

**Comment by six7** [comment]
This should be as easy as adding the `isMasked` flag to the `Input` in the generic versioned storage form in `src/app/components/StorageItemForm/GenericVersioned.tsx`
