### ISSUE TITLE
Create styles command is not working

### ISSUE THREAD

**Issue by Ahmad-Fahmi** [tokens-studio/figma-plugin#1505]
**Describe the bug**
I used to create styles whenever I create a new tokens, to have native figma styles
**To Reproduce**
1. Go to 'Styles beside the update button'
2. Click on 'Create styles'
4. Nothing got created

**Comment by six7** [comment]
There's two things which can cause this:
- Can you make sure `Ignore first part of token name for styles` in Settings is disabled?
- Can you make sure that your token sets are "checked"? The ones on the left? Only "checked" sets will get created.

<img width="914" alt="image" src="https://user-images.githubusercontent.com/4548309/210335706-f45b91b9-6f81-456b-8137-add55e33acb3.png">

**Comment by ibnfahmi** [comment]
Thank you it has been fixed now, however what I did is to uncheck "Treat as source"( although it worked fine before) and give my sets the normal check.

**Comment by six7** [comment]
Ah, yes - `Treat as source` means that the tokens inside this set will only be used to resolve references, but not create styles. I'll make sure to update Docs and make it clear in the UI what this is.
