### ISSUE TITLE
A Token search-field for inspect mode

### ISSUE THREAD

**Issue by keeganedwin** [tokens-studio/figma-plugin#1518]
I currently have to scroll to find certain tokens, it takes a bit of slowing down to find the ones I want to edit.
Current behaviour:

<img width="480" alt="OG" src="https://user-images.githubusercontent.com/93133012/210607874-fdfb9993-3b91-427e-bf31-8492ba91a9b2.png">

It would help if inspect mode had a modal show-up on screen or had a search-field of sorts to quick search the token set the user wants to edit

Design:

![Image](https://user-images.githubusercontent.com/4548309/212466909-bae65826-9653-41bf-9d47-3e9aa09cb37a.png)

**Comment by six7** [comment]
Closing this in favor of https://github.com/tokens-studio/figma-plugin/issues/1056
