### ISSUE TITLE
When renaming a token group, we only update the current selection instead of user's choice

### ISSUE THREAD

**Issue by six7** [tokens-studio/figma-plugin#1528]
Currently when users rename a group of tokens we ask them for the new name of the group as well as where they want to do the bulk remap on (selection, page, document).

However, we seem to ignore that choice, and only ever perform that change on selection (as we're just calling the bulk remap function, which works on selection by default).

Let's give the bulk remap function an option on where to remap.

![Image](https://user-images.githubusercontent.com/4548309/210979102-17fe907a-045e-454d-a6f4-fae0c7199334.png)

![Image](https://user-images.githubusercontent.com/4548309/210979090-3c8e797b-aac4-4174-8cdd-7e7ecd7cc642.png)

![Image](https://user-images.githubusercontent.com/4548309/210979044-a87aa457-c596-4ac1-8ee9-376273ec1372.png)

**Comment by lukas-dne** [comment]
So good this issue has been solved. 👍 Can you estimate, when this change will be released to public? I'm working on a bigger design system, where it would take hours, to update all elements manually after some structural rework of the token system...  Regardless of this: Thanks for offering this great plugin! :)

**Comment by six7** [comment]
We'll likely do another patch release sometime early next week where this one will be part of.

**Comment by lukas-dne** [comment]
Awesome. Thanks!

**Comment by six7** [comment]
Shipped in 134
