### ISSUE TITLE
Incorrect value name when referencing between sets in JSON

### ISSUE THREAD

**Issue by kalin9411** [tokens-studio/figma-plugin#1549]
Considering the following setup: 
3 Sets: "core", "sem", 'com"
values in "sem" set are reference to values in "core" set:
![MicrosoftTeams-image (5)](https://user-images.githubusercontent.com/68055485/212713437-68882998-725c-4230-8dfe-36b99deaf18f.png)

When generating JSON file, in the "sem" set each value's reference doesn't specify from which set the value is taken:
![image](https://user-images.githubusercontent.com/68055485/212704382-88960ccb-bce4-454a-8664-0a204ad7e2e8.png)
instead of each value containing "core". E.g:

"value" : "{core.color.purple.300}".

This makes parsing with style-dictionary impossible, since it doesn't know which set contains the referenced variable.
![image](https://user-images.githubusercontent.com/68055485/212714858-13bc1c52-a49d-4b8e-88b2-e4b99bfc12e9.png)

**Comment by six7** [comment]
This is how sets work.

Just like in style dictionary, the file name is never part of a token name. Consider the sets as files. The initial level of the single-file sync is the set name. I'd recommend to either use multi-file sync so you can just use your files as-is, or split your one .json file into multiple.

This should be easy to setup, here's a script: https://gist.github.com/six7/ddb9b1f0d0c6e434be4f1cdb8bfe56e1 - just have this run before you run SD and you're good to go.

**Comment by kalin9411** [comment]
Thanks for the super quick answer. The "set" functionality is particularly useful in my company case, since it allows to turn sets on/off in order to change themes. However the purpose of our/the design system is to have a **single source of truth**, so basically we need a single "core" set for both of my themes, which have different "sem" sets, both sourcing values from "core". 

I simply cannot understand why you would want to limit the plugin deliberately to prevent cross-set referencing? In the plugin It is possible to select vars from other sets.

Also what is the point of splitting sets into multiple files? In my case there is no way to benefit from this feature at all.

At the mean time, what I am going to do is place all the vars in each set in a group with the same name as the set, so that at least I can see the name, which I am going to programmatically duplicate for each referenced value so that style-dictionary can parse the file.

**Comment by six7** [comment]
> I simply cannot understand why you would want to limit the plugin deliberately to prevent cross-set referencing? In the plugin It is possible to select vars from other sets.

You can have references from other sets, totally possible. As I said it's just that our single-file format is not what style dictionary expects and you need a step before that to make it understand it. It's easy to integrate into your build-chain, you'd still have a single source of truth, you just need to transform one json into many before passing it to SD.

> Also what is the point of splitting sets into multiple files? In my case there is no way to benefit from this feature at all.

1) Better structure
2) Less merge conflicts
3) You can use it with style dictionary without an intermediary step

> At the mean time, what I am going to do is place all the vars in each set in a group with the same name as the set, so that at least I can see the name, which I am going to programmatically duplicate for each referenced value so that style-dictionary can parse the file.

I wouldn't recommend that, I would recommend just splitting that file up.

**Comment by kalin9411** [comment]
Ok, using your script I successfully split the sets into multiple files, then added them to source in style-dictionary config like that:
![image](https://user-images.githubusercontent.com/68055485/213124477-569ca2bb-4637-432b-9aa1-98b008fe6230.png)
However, references still cannot be read:
![image](https://user-images.githubusercontent.com/68055485/213124545-d5f06c23-7811-4794-8826-d60e980ec974.png)
This is coming from sem-light.json, which has core references like this:
![image](https://user-images.githubusercontent.com/68055485/213124794-e69adaa4-2589-41cc-935c-9863470c0184.png)
