### ISSUE TITLE
No --expandBorder option in token-transformer

### ISSUE THREAD

**Issue by thomasmattheussen** [tokens-studio/figma-plugin#1550]
**Describe the bug**
On of our designers uses the new border 'composition' tokens, but there's no way to expand these with `token-transformer` (where as it is possible for shadows, typography and custom composition tokens)

**Expected behavior**
I would expect a `--expandBorder` parameter in `token-transformer`

**Comment by yashiel** [comment]
currently facing this problem :(

**Comment by matko13** [comment]
I have the same issue. Anything new around this topic?
