### ISSUE TITLE
Allow multiple text colors and styles inside one text element

### ISSUE THREAD

**Issue by JakobIChoosr** [tokens-studio/figma-plugin#1554]
**Is your feature request related to a problem? Please describe.**
Whenever I want to make a part of my text bold or blue for a hyperlink it turns the whole text block bold of blue.

**Describe the solution you'd like**
It would be nice to have control to add tokens to a hightlighted selection of text. Just like Figma allows it.

**Describe alternatives you've considered**
Right now I'm simply removing text tokens on bigger portions of text to allow this. This sadly allows the design to be out of sync on some elements.

**Additional context**
![image](https://user-images.githubusercontent.com/37074341/213189187-644ea4e9-432d-4f25-90bc-cff8e93b7df9.png)

**Comment by six7** [comment]
Thanks for creating this. I would recommend to use Styles and use the plugin to create/manage those styles. We cannot apply tokens on segments, styles are made to do that.
