### ISSUE TITLE
Design elements seem to have lost reference to the design tokens

### ISSUE THREAD

**Issue by jnicouleaud** [tokens-studio/figma-plugin#1555]
My design elements (buttons) seem to have lost part of their links to the design tokens.

**To Reproduce**
1. Click on one of the design elements (a button)
2. The reference to the design tokens appears in the bottom right panel in Figma (Plugin > Tokens > borderRadius) — see attached screenshot
3. In the main Tokens Studio window, the border radius token is not highlighted anymore
4. If I make changes to the design token, it is not applied to my design element any longer

**Expected behavior**
Changing the design token should change the design element accordingly.

➜ I have recently started to sync my tokens with jsonbin.io in order to make sure I have a backup, but I haven't made any changes on jsonbin.io that should sync with Tokens Studio
➜ Only my color tokens and my shadow token are properly linked to my design elements

**Screenshots**
![image](https://user-images.githubusercontent.com/30346806/213242125-229f0c61-29a1-4b68-937a-2686c8c02493.png)

**JSON**
The JSON file does not seem to have any issues, I've downloaded it through the console as the troubleshooting page suggests, and there is no formatting error.

**Comment by six7** [comment]
Can you share a screenshot of how the `Inspect` tab inside the plugin looks like?

**Comment by jnicouleaud** [comment]
Hi Jan, thanks for the quick reply. Here is the screenshot :
<img width="666" alt="image" src="https://user-images.githubusercontent.com/30346806/213307598-906138f3-f18f-4d36-aeb6-70d44991d33e.png">

**Comment by jnicouleaud** [comment]
The last token in the list is now called `actions.buttons.generic.border.radius` and not `actions.buttons.primary.generic.border.radius` ➜ any reason it could have lost the reference? I have made changes directly on the parent nodes in the Tokens Studio plugin, rather than on the token itself, is that what could have caused the issue?

**Comment by six7** [comment]
When you rename tokens we give you the option to 'remap' any occurrences of that token in your document, page or selection - however it's up to you where you want to make that change.

However you can do it manually too. In the Inspect tab in the plugin you notice the token has that broken link symbol. Just click next to the token name and enter the correct token name.

**Comment by jnicouleaud** [comment]
Hi Jan, those were the settings I had, it should have remapped automatically then, right?
<img width="150" alt="image" src="https://user-images.githubusercontent.com/30346806/213659120-ac59db7a-159f-4a35-9ab9-f42897c791ef.png">

Thanks, I've remapped them manually using the inspect tab.

**Comment by six7** [comment]
We had a bug in previous versions where sometimes the remap would only have worked on the current selection, however that is fixed since version 134.

I'll close this issue for now, given I expect it had to do with that bug we fixed. If it persists, please reopen!
