### ISSUE TITLE
Add support for renaming tokens to rename styles without themes

### ISSUE THREAD

**Issue by six7** [tokens-studio/figma-plugin#1556]
> Hey all, new to the plugin, have a question about synch.
> 1. I import styles from my library file
> 2. Changed a few things, etc
> 3. Now, can I synch between the plugin and this file? Ex: if I change the name of a color, can the plugin update the style in this figma library? If yes, It doesn’t seem to work.

[Slack Message](https://tokens-studio.slack.com/archives/C02DEJMS9AP/p1674045658698999?thread_ts=1674045658.698999&cid=C02DEJMS9AP)

**Comment by rbosker** [comment]
same reported issue: #1382

**Comment by six7** [comment]
Let's close this one then

**Comment by six7** [comment]
Duplicate of #1382
