### ISSUE TITLE
Dashed border style set by Tokens Studio looks completely different from CSS dashed

### ISSUE THREAD

**Issue by silviowolf** [tokens-studio/figma-plugin#1558]
**Describe the bug**
When I use the "dashed" border style in Tokens Studio the Figma property "Dash" gets set to "10". This value is far away from the look of the CSS dashed style. 

**To Reproduce**
1. Open Tokens Studio plugin
2. Create a Border token with border style "dashed"
3. Apply this token to a Figma layer

**Expected behavior**
The dashed style applied by Tokens Studio should at least look similar to the CSS border-style "dashed".  
Proposal: Set Figma's dash properties (unfortunately, depending on border width) to:  
- 1px: Dash = 3, Gap = 2
- 2px: Dash = 6, Gap = 3
- 3px: Dash = 6, Gap = 3
- 4px: Dash = 8, Gap = 4
- 5px: Dash = 10, Gap = 5

**Screenshots or Screencasts**
![image](https://user-images.githubusercontent.com/115155312/213684451-b6091b5b-8933-4160-899f-5edc194a6ea7.png)

**Comment by six7** [comment]
Thanks for creating this, I agree we should provide better defaults there! 👍 

as dashed is only available in `border` tokens so far we can just take the border width property into account that we set from the `border` token.
