### ISSUE TITLE
HSL colors with channels exceeding "default range" are not applied as colors

### ISSUE THREAD

**Issue by dominikschreiber** [tokens-studio/figma-plugin#1574]
**Describe the bug**
HSL colors with channels exceeding their "default range" are not applied as color. E.g. `hsl(0, 101%, 0%)` or `hsl(0, 0%, 101%)`.

(On a side note, only the legacy comma-separated syntax is supported, i.e. `hsl(0 0% 0% / 1)` is not evaluated as a color, but this is probably stuff for a new feature request.)

**To Reproduce**
1. Go to "Token" > "JSON"
2. Paste the following JSON:
```json
{
  "ok": {"value": "hsl(0, 0%, 0%, 0)", "type": "color"},
  "notOkBecauseS": {"value": "hsl(0, 101%, 0%)", "type": "color"},
  "notOkBecauseL": {"value": "hsl(0, 0%, 101%)", "type": "color"}
}
```
3. Press "Save JSON"
4. Go to "Token" > "Listing"
5. Hover over the color previews for "ok", "notOkBecauseS" and "notOkBecauseL"
6. Observe that "ok" is correctly evaluated to `#00000000` but "notOkBecauseS" and "notOkBecauseL" are not evaluated at all
7. Apply the colors to an element
8. Observe that "ok" is correctly applied, apparently "notOkBecauseS" as well, but not "notOkBecauseL"

**Expected behavior**

The CSS `hsl(…)`/`hsla(…)` notation allows for channel values above or below the "default":

> If the saturation or lightness are less than 0% or greater than 100%, they are clamped to those values at computed value time, before being converted to an sRGB color.  
> *in [7. HSL Colors: 'hsl()' and 'hsla()' functions](https://www.w3.org/TR/css-color-4/#the-hsl-notation)*

This behavior is crucial when values depend on each other and the "root" color is not known beforehand, e.g. to express a `lighten(…)`/`darken(…)`, `saturate(…)`/`desaturate(…)`, `fadeIn(…)`/`fadeOut(…)` or even `spin(…)`:

```json
{
  "_H": {"value": "120", "type": "internal"},
  "_S": {"value": "80%", "type" "internal"},
  "_L": {"value": "80%", "type": "internal"},
  "_A": {"value": "1", "type": "internal"},
  "root": {"value": "hsl({_H}, {_S}, {_L}, {_A})", "type": "color"},
  "spinBy180": {"value": "hsl({_H} + 180, {_S}, {_L}, {_A})", "type": "color"},
  "saturatedBy30": {"value": "hsl({_H}, {_S} + 30%, {_L}, {_A})", "type": "color"},
  "lightenedBy30": {"value": "hsl({_H}, {_S}, {_L} + 30%, {_A})", "type": "color"},
  "fadeInBy30": {"value": "hsl({_H}, {_S}, {_L}, {_A} + .3)", "type": "color"}
}
```

Now if someone changes `_L` (without knowing all usages of this variable), this shouldn't break depending colors, they should still be able to be applied.

**Screenshots or Screencasts**
Observe the calculated color in the tooltip of the color previews, as well as the applied fill when a color is selected:

![output](https://user-images.githubusercontent.com/1219916/215415419-a7cb919a-3e8f-4682-8fba-b476c25d2ae0.gif)

**Figma file (optional)**
N/A

**JSON (optional)**
see above

*Edit:* I've tried [`clamp(…)`](https://developer.mozilla.org/en-US/docs/Web/CSS/clamp) around the channels, e.g.
```json
{"notOkBecauseS": {"value": "hsl(clamp(0, 250, 360), clamp(0%, 0%, 100%), clamp(0%, 101%, 100%), clamp(0, 1, 1))", "type": "color"}}
```
but this as well is not evaluated/applied as a color.

**Comment by LukeFinch** [comment]
This request has been moved to our new feedback tool. Go check out https://tokensstudio.featurebase.app/ to create a free account. You can upvote and comment on existing posts, make a new request, and subscribe to be notified when requests move into our roadmap.

**Comment by UdayHyma** [comment]
Added to FeatureBase Roadmap : [🎨 Expanded support for color spaces
](https://tokensstudio.featurebase.app/p/expanded-support-for-color-spaces)
