### ISSUE TITLE
Better indication of overwritten tokens

### ISSUE THREAD

**Issue by rbosker** [tokens-studio/figma-plugin#1586]
**Is your feature request related to a problem? Please describe.**
(See screenrecording below). If you have a token that is overwritten by another set, the overwritten value is shown in the tooltip. The token name and also the color swatch will keep its original value.

**Describe the solution you'd like**
1. Show the token as it is in the current set
2. Add an indication that the token is overwritten.

**Describe alternatives you've considered**

**Additional context**
https://tokens-studio.slack.com/archives/C04MGHM82TV/p1675243905114279

https://user-images.githubusercontent.com/109062656/216575112-cfb18fe2-83c4-4363-9c60-1e561ee8a1de.mov

**Comment by color2life** [comment]
Hi @rbosker and @six7 

What your thought on this 

![Image](https://user-images.githubusercontent.com/69331/230278372-c494a7ac-7b86-4bc6-814e-0a4668647632.png)

**Comment by color2life** [comment]
Live examples - CSS
![Image](https://user-images.githubusercontent.com/69331/230278524-d34535d0-cbf0-420c-a458-6bf852f696ae.png)

**Comment by six7** [comment]
Thanks @color2life - I extracted the designs you had in the Figma:

![image](https://user-images.githubusercontent.com/4548309/233804435-8500c1db-640c-4d72-815a-4628b1a2249b.png)

I'd say lets try with just the tooltip for a start. If that's not enough, we can try the dot option.

**Comment by UdayHyma** [comment]
[Migrated to Featurebase](https://tokensstudio.featurebase.app/p/theme-management-enhancements)
