### ISSUE TITLE
GUI Drop-downs not working as expected

### ISSUE THREAD

**Issue by jamesgrubb** [tokens-studio/figma-plugin#1589]
**Describe the bug**
Im trying to populate a Typography token using the dropdown menus "Aliases" The dropdown shows the available options but when I select an option the field is not populated.

**To Reproduce**
Click '+' on typography panel
Click dropdown icon
Select alias

https://user-images.githubusercontent.com/22652/216764938-88cad931-0e75-4388-b4a9-5bfced1d0fc1.mov

**Expected behavior**
Populate field with alias

**Screenshots or Screencasts**

**Figma file (optional)**
Send us the link to a Figma file containing a reproducible example

**JSON (optional)**
If possible, attach the JSON that leads to this bug.

**Comment by six7** [comment]
Are you using the mac or the browser Figma version?

**Comment by jamesgrubb** [comment]
Hi, Mac version.

**Comment by six7** [comment]
Can't reproduce here, will need more details.

**Comment by SamIam4Hyma** [comment]
Closing as it can't be reproduced.
