### ISSUE TITLE
Token transformer changes hsl to rgb

### ISSUE THREAD

**Issue by BobbyJoStefflTR** [tokens-studio/figma-plugin#1593]
**Describe the bug**
The `token-transformer` plugin is automatically changing values from hsl to rgb. We would like to keep these in sync from Figma to the code as HSL.

**To Reproduce**
file from Figma
```
"color": {
      "white": {
        "value": "hsl(0, 0%, 100%)",
        "type": "color",
        "description": "hsl(0, 0%, 100%)"
      },
      "custom-item": {
              "value": "hsla({color.white}, {opacity.0})",
              "type": "color"
            }
          }
        }
      },
```
after running `token-transformer` plugin
```
"white": {
      "value": "#ffffff",
      "type": "color",
      "description": "hsl(0, 0%, 100%)"
    },
"custom-item": {
            "value": "hsla(#ffffff, 0)",
            "type": "color"
          }
        }
      }
    },
```
After style dictionary the value of `custom-item` equals `hsl(0, 0%, 100%)` which is missing opacity of 0.

**Expected behavior**
I would expect the token-transformer to honor the format from FIgma or have a method to turn this off in token-transformer. In this case we'd like to be able to use default Style dictionary transformers if necessary (i.e. color/hsl or color/hsl-4).

**Comment by six7** [comment]
I think some way of defining the output color format would be great, so any color would be transformed to that one, or if chosen to respect the input format.

so i could see
`color-format`: `rgba` | `hsla` | `hex` | `input` to be parameters we could pass to token-transformer

**Comment by SamIam4Hyma** [comment]
@jorenbroekema tagging you for awareness, feel free to relabel as needed

**Comment by jorenbroekema** [comment]
token-transformer deprecated in favor of using sd-transforms, issue doesn't arise there, [example](https://configurator.tokens.studio/#project=fVLLTsMwEPyVlSXUh9K6cCwXDhVckcoNV8iNncaQ2JHXKVRV/x0/2rQJEj7kMTu7O97ZI0HXCmXmn2g0WZIj0wCM5KYyFhlZQgQC9F0qJ2+QgO151UaMkRKr8SKDxV0G94vF3YSR7Mpzh+ZMi4UZSaFTePnHiWTEyp1CJ+169dzq3Cmj0WvyilTdGOtg7Q6VXKkY4fYAhTU1jDCgM9HBo0emzwlHuJR8s1xjYWyNcDrnPTnzJTXO0uUpipnrSKEG05RCD83gQQtouOW19DXBg2CaqBNyrmErgQshRcxcSwnC5LiE0rkGl5TulCvb7Tw3Nf2nNdN/NY8HN594eX5eudGF2g1sQ9PaPE76/WLbdEqnkZWGvskSs6m4Sy1vPc4RBw532l6saZvkYe8CPZ8bKwv1k1goeqFtqyrxyl2ZovGX+n60xypUJfFGfzjH62egCIlOaR6mkUp97LlVfOsT51F/1ucH8dydt8/369iXLew2MZzNcDNPvw==)
