### ISSUE TITLE
Color modifier: make it possible document the modify of a token

### ISSUE THREAD

**Issue by rbosker** [tokens-studio/figma-plugin#1596]
**Request:**
Add the possibility, under the Documentation Tokens dropdown, to document the modify that is applied to the token.

**Note:** this only applies for tokens that use a color modifier.

Screenshots:
![Image](https://user-images.githubusercontent.com/109062656/217267268-4996869c-304e-48a8-be5e-f5907e1a5ccf.png)
![Image](https://user-images.githubusercontent.com/109062656/217267400-7f59d337-6d63-4fef-834b-9fdd4ef7ebdd.png)

**Slack:** https://tokens-studio.slack.com/archives/C04LMFQV8QL/p1675456002109279

**Comment by rbosker** [comment]
@six7 Do you want to add this as a separate option or as part of the Raw value?

**Comment by six7** [comment]
Let's add it with the raw value:

`{color} / lighten(0.2) / lch`
