### ISSUE TITLE
Support stroke style tokens

### ISSUE THREAD

**Issue by usethetics** [tokens-studio/figma-plugin#160]
Would it be possible to incorporate tokens for border style (solid/dashed, dash and gap size) in a future version?

**Comment by six7** [comment]
I think this would make sense, although I fear this might come with quite a bit of complexity. To my knowledge there is no css standard for border dashes, so we can't use a familiar syntax.

> Note: There is no control over the spacing of the dots and dashes, nor over the length of the dashes. Implementations are encouraged to choose a spacing that makes the corners symmetrical.
https://www.w3.org/TR/css-backgrounds-3/#the-border-style

**Comment by usethetics** [comment]
> To my knowledge there is no css standard for border dashes, so we can't use a familiar syntax.

Yeah, it does make sense not to include anything that is not going to be reproducible in front-end code! Maybe having the ability to include a token for either a dashed or a solid border style would suffice!

**Comment by six7** [comment]
Update on this issue: The W3C has added a [stroke style composite token](https://tr.designtokens.org/format/#stroke-style) to the draft. So I guess we'll start with this one in a while.

**Comment by SamIam4Hyma** [comment]
@six7 suggest to close as this is accomplished within border composite tokens within W3c

**Comment by six7** [comment]
I think this is different. StrokeStyle is the style of the line itself eg dashed or solid (or custom)
