### ISSUE TITLE
Text-decoration 'none' not applied

### ISSUE THREAD

**Issue by rbosker** [tokens-studio/figma-plugin#1606]
**Describe the bug**
The text-decoration token and the text decoration in the typography token work fine with 'underline' & 'line-through', but 'none' doesn't work.

**Expected behavior**
If text-decoration: none is applied, no text decoration should be applied to the text.

**Figma file (optional)**
Send us the link to a Figma file containing a reproducible example
https://user-images.githubusercontent.com/109062656/218036035-b27c0509-3671-4f8a-a2ad-68fd3b474e49.mp4

**Comment by lorenzoromagnoli** [comment]
I'm also having issues applying underline text decoration token

**Comment by six7** [comment]
Fixed in 1.35.3

**Comment by keeganedwin** [comment]
Would it be possible to reopen this issue? Or shall I create a new one because it only works if it's written with a capital `None` and does not work as `none`. The other two decorations work without a capital letter.

**Comment by six7** [comment]
Seems we only fixed this in `typography` tokens. Let's fix this when applied as a regular `textDecoration` token as well. Reopening and adding to bug bash next week.
