### ISSUE TITLE
HSB/HSBA support for color definitions

### ISSUE THREAD

**Issue by zaccb** [tokens-studio/figma-plugin#1608]
**Is your feature request related to a problem? Please describe.**
My Design team has rationalized their color scale in HSB, and not HSL, RGB, or HEX. As such, both Designers and Engineers have to translate Design intent from HSB into HSLA before we input color values in Tokens Studio plugin.

**Describe the solution you'd like**
[Solid colors](https://docs.tokens.studio/available-tokens/color-tokens#solid-colors) support HSBA in addition to the existing Hex, RGB, RGBA, and HSLA.

### Current state 😢 
![image](https://user-images.githubusercontent.com/3512878/218160781-d2ebb268-2759-4eda-ae03-26d9fe8ba8b1.png)
![image](https://user-images.githubusercontent.com/3512878/218161218-33bf6e84-65f0-48b0-a214-bd5443711fd8.png)

### Ideal state 😉 
![image](https://user-images.githubusercontent.com/3512878/218161049-86825835-1d40-489e-aa71-96caaf8b425b.png)
![image](https://user-images.githubusercontent.com/3512878/218161229-b5069743-f1b1-4735-8639-eb2bfda4df19.png)

**Describe alternatives you've considered**

- **Just using HSL/HSLA to conform to the existing Tokens Studio constraints**. [They are not logically equivalent concepts](https://medium.com/innovaccer-design/rgb-vs-hsb-vs-hsl-demystified-1992d7273d3a) and, as far as entering token values, HSB and HSL are just as different as HSL and RGB. Doing this would require going to Design and rebuilding our color scales from the ground up (okay well maybe not the ground up but there was intention in using HSB vs. HSL here and that would need to be thrown out).
- **Transforming values before entering values in Tokens Studio to conform to the existing Tokens Studio constraints**. This is what we do today. What I don't like it about this is it violates principles of unifying the language between Design and Engineering--if Design is using HSB in their language but it's implemented/stored in a different value, then we're creating a collaboration gap and introduce room again for mis-interpretation of design intent.

**Additional context**
- [TS Slack thread w/Jan](https://tokens-studio.slack.com/archives/C02DEJMS9AP/p1675904396066129) that prompted this issue getting logged
- [Figma supports both HSB and HSL color models](https://help.figma.com/hc/en-us/articles/360043042113-Color-models-in-Figma)
- [Sketch supports both HSB and HSL color models](https://www.sketch.com/docs/designing/styling/the-color-popover/)

**Comment by six7** [comment]
Thank you for creating this issue, this context really helps 🙏

**Comment by LukeFinch** [comment]
This request has been moved to our new feedback tool. Go check out https://tokensstudio.featurebase.app/ to create a free account. You can upvote and comment on existing posts, make a new request, and subscribe to be notified when requests move into our roadmap.

**Comment by UdayHyma** [comment]
Added to FeatureBase Roadmap : [🎨 Expanded support for color spaces](https://tokensstudio.featurebase.app/p/expanded-support-for-color-spaces)
