### ISSUE TITLE
Show diff before pushing and pulling changes

### ISSUE THREAD

**Issue by six7** [tokens-studio/figma-plugin#1609]
Instead of just overriding local tokens or pushing without knowing what's being pushed, let's introduce a modal that shows the user what's changed.

When pulling we show the user the changes in a UI, showing them all the values that changed. We do this by comparing the current state and the remote state and we show those changes to the user.

![Image](https://user-images.githubusercontent.com/4548309/218465201-6458c856-c759-4cad-b0d9-fc77afa5ca48.png)

When pushing we show the user in two ways: JSON and UI. The JSON is the json that is being pushed, while the UI view shows the actual changed tokens. We should make sure to also include files such as $themes.json and $metadata.json

![Image](https://user-images.githubusercontent.com/4548309/218465475-2d1b420f-a74a-4207-ac6e-dce87d83f2a4.png)

**Comment by mikejyoung** [comment]
In the Push modals, it's specified which branch is being pushed to. It would be great to see this information in the Pull modals too. There's been a couple of times where I've pushed and pulled from the wrong branch. 

Also, some more visual emphasis on the branch name would help to distinguish it from the helper text. Such as bolding the text or putting it in a code block.


![Image](https://user-images.githubusercontent.com/75724470/229340856-ddb77283-03bc-4512-a200-a260c6957258.png)

**Comment by mikejyoung** [comment]
Also, I think having the ability to only push / pull specific tokens sets would be very helpful (but may be best handled in a separate enhancement).
