### ISSUE TITLE
Extend/import compositions

### ISSUE THREAD

**Issue by Akronae** [tokens-studio/figma-plugin#1614]
**Is your feature request related to a problem? Please describe.**
We have a button component that has four parameters `type`, `size`, `shape` and `state`.
So the token tree looks like that. (this is also how it is used in the code)
```js
comp.button[shape || `rectangular`][type || `primary`][size || `md`][state || `default`]['container' | 'label' | 'icon']
```
So we have to repeat ourselves a lot for the common parts of `container`, `label` and  `icon`
And if we have a change to make (mostly adding or removing properties) we have to change every "buds" of this "tree" (that is to say every `container` `label` `icon`)

**Describe the solution you'd like**
A solution would be to have the ability to import compositions into other compositions, juste like a JavaScript spread operator
```js
const myBtn = {...btnBase, color: 'red'}
```
The "spread" way of thinking would be even better than a more traditional "inheritance" way of thinking as it would give the ability to have "children" add/override properties of the "parent composition" while also giving the ability to the parent to import first then ovrride some imported children properties.

**Describe alternatives you've considered**
Creating "intermediate" tokens that are used in every "buds" compsitions, but this does not solve issues when we have to remove/add base properties, as we will have to go throught every "bud" to add/remove the token references

**Additional context**
All of these buttons share common properties that should be abstracted using a "base" composition
![image](https://user-images.githubusercontent.com/17302866/219004876-f74c98ac-945c-4161-a18b-627413c93cc2.png)

**Comment by six7** [comment]
Thanks for creating this, let's use this one to track inheritance for composition tokens, thanks for all the extra context - very useful!

I wonder how we'd see this defined. As you said, the spread would be more powerful, but it's going into a direction that doesn't seem like it'd be supported by the design tokens format at all (granted, composition tokens itself aren't defined in the format at all).

I feel the spread would be _really_ powerful, as you'd be able to insert multiple tokens. However, my worry is that this is going to be very hard to define via the UI.

What if we'd have a `inherit` prop on composition tokens that you could assign to another one? Like `inherit: {button.base}`? Would that solve your use case?
