### ISSUE TITLE
Add option to choose json indentation type

### ISSUE THREAD

**Issue by MaiLeeTR** [tokens-studio/figma-plugin#1618]
**Is your feature request related to a problem? Please describe.**
Our project uses Prettier code formatter and tabs instead of spaces for indentation. Our team is currently setting up and applying tokens to components in Figma and code. 

What our process currently looks like:
1. Designer pushes up their changes to a tokens branch in GitHub with json file using the default spaces instead of tabs indentation
2. Checks always fail due to Prettier indentation error 
3. Developer pulls down changes from the tokens branch into their own branch, fixes the error, applies tokens in code, and merges changes
4. The tokens branch gets conflicts due to differences in formatting, and the developer has to fix conflicts and revert the formatting to what's coming from the plugin for the designer's next push

Due to the indentation formatting differences between the Figma json file and our code, we always have to fix formatting issues and perform additional and time-consuming steps. 

**Describe the solution you'd like**
Add an option to change the indentation formatting of the json file to tabs.

**Additional context**
Error
<img width="537" alt="Screen Shot 2023-02-15 at 8 15 45 AM" src="https://user-images.githubusercontent.com/55507048/219051936-98d27087-d128-4ae9-871e-245cd300aaa5.png">

Current indentation
<img width="469" alt="Screen Shot 2023-02-15 at 8 14 08 AM" src="https://user-images.githubusercontent.com/55507048/219051544-0873fb6f-0c74-4081-b380-731e4635b6fb.png">

Option for preferred indentation
<img width="507" alt="Screen Shot 2023-02-15 at 8 13 47 AM" src="https://user-images.githubusercontent.com/55507048/219051576-8942ff1b-8fd8-40ff-ad4e-d0e73b2593c5.png">

**Comment by six7** [comment]
I think this would make a nice config parameter that users can define in the settings and we save in the `$metadata.json` (or `$metadata key` in the single file sync)

We basically currently stringify our JSON by using 2 spaces, but that could be something users could configure to be `tabs` instead.

**Comment by MaiLeeTR** [comment]
@six7 Thanks for the response. Any idea about the priority of getting this implemented?

**Comment by six7** [comment]
It's not very high on our list so far, but I'll add it to our quick wins which means it might get picked up sooner during sprints.

**Comment by MaiLeeTR** [comment]
> It's not very high on our list so far, but I'll add it to our quick wins which means it might get picked up sooner during sprints.

I hope it gets picked up sooner due to being a quick win. Thanks for the update!

**Comment by UdayHyma** [comment]
[Migrated to Featurebase](https://tokensstudio.featurebase.app/p/sync-external-storage-enhancements)
