### ISSUE TITLE
Ability to collapse/expand all token groups

### ISSUE THREAD

**Issue by batsper** [tokens-studio/figma-plugin#1621]
We have the ability to collapse/expand individual token groups today, but when working with a large number of groups like in compositions it would very helpful when navigating the tokens and working on specific groups to collapse/expand all token groups.

It could be done through shortcuts like "alt+click" or "cmd+click" or by placing a button in the UI.

**Comment by UdayHyma** [comment]
Added to Featurebase Roadmap : [🪙 Token organization enhancements
](https://tokensstudio.featurebase.app/p/token-organization-enhancements)

**Comment by UdayHyma** [comment]
[Migrated to Featurebase](https://tokensstudio.featurebase.app/p/token-organization-enhancements)
