### ISSUE TITLE
Plugin closes when using "Copy as PNG" or "Copy as SVG"

### ISSUE THREAD

**Issue by josholsen-ab** [tokens-studio/figma-plugin#1622]
**Describe the bug**
Both `Copy as PNG` and `Copy as SVG` functions (from menu or keyboard shortcut) seem to crash the plugin. Other copy actions work as expected. On version 116.6.3 of Figma and 134 of Tokens Studio.

**To Reproduce**
1. Select anything in a given file with the plugin running
2. Open the menu and select `Copy/Paste as`
3. Select either `Copy as PNG` or `Copy as SVG` form the menu
4. Plugin closes and displays a "Saving in progress" tooltip w/ option to open Console

**Expected behavior**
The plugin wouldn't be impacted by either copy function.

**Screenshots or Screencasts**
This is in a test account without the plugin actually hooked up. Same behavior happens in my actual account when logged in.
https://user-images.githubusercontent.com/117752829/219490859-38c0bf59-bf23-4f26-b4bf-5140165e819e.mov

**Comment by six7** [comment]
This is unfortunately a bug that affects all Figma plugins and was reported to Figma a few months back.

**Comment by six7** [comment]
Closing as it's out of our reach
