### ISSUE TITLE
[Token-Transformer] rgba() raw values transformed to invalid hex colors, also loosing transparency

### ISSUE THREAD

**Issue by DarioSoller** [tokens-studio/figma-plugin#1628]
**Describe the bug**
First of all thanks for sharing this token-transformer. It already saved me a lot of work. Nevertheless I stumbled over some token values that can't be transformed out-of-the-box by the token-transformer library in a meaningful way. The screenshot shows how the token-transformer lib is currently converting it to a invalid hex value: 
![Bildschirm­foto 2023-02-10 um 09 58 53](https://user-images.githubusercontent.com/2143409/219687863-8de7046a-58c9-4808-bf98-f32e42ff27a6.png) 

An underlying problem here is that either
```background-color: rgba(rgb(150,140,130), 0.5);```
or
```background-color: rgba(#cc33ff, 0.5);```
are invalid CSS values.
For rgba to work it needs to have the format
```background-color: rgba(150,140,130, 0.5);```

**To Reproduce**
1. Assuming following tokens.json file being synced from the Figma Token Plugin into the repo:
```
{
  "base": {
    "base": {
      "color": {
        "primary": {
          "0": {
            "value": "rgb(255, 255, 255)",
            "type": "color"
          }
        }
      }
    }
  },
  "shared": {
    "shared": {
      "color": {
        "primary-inverted": {
          "resting": {
            "value": "{base.color.primary.0}",
            "type": "color"
          },
          "hover": {
            "value": "rgba({base.color.primary.0}, 0.8)",
            "type": "color"
          },
          "pressed": {
            "value": "rgba({base.color.primary.0}, 0.6)",
            "type": "color"
          },
          "disabled": {
            "value": "rgba({base.color.primary.0}, 0.25)",
            "type": "color"
          }
        }
      }
    }
  },
  "$themes": [],
  "$metadata": {
    "tokenSetOrder": [
      "base",
      "shared"
    ]
  }
}
```
2. run the follwing token-transform command with the token-transformer v0.0.29:
```
token-transformer tokens.json tokens-transformed.json --expandTypography=true --expandShadow=true --expandComposition=true --preserveRawValue=true --resolveReferences=true --throwErrorWhenNotResolved=true
```
3. Resulting in the following output in the tokens-transformed.json file:
```
{
  "shared": {
    "color": {
      "primary-inverted": {
        "hover": {
          "value": "#ffffffcc",
          "type": "color",
          "rawValue": "rgba({base.color.primary.0}, 0.8)"
        }
      }
    }
  },
  "base": {
    "color": {
      "primary": {
        "0": {
          "value": "#ffffff",
          "type": "color",
          "rawValue": "rgb(255, 255, 255)"
        }
      }
    }
  },
  "tokenSetOrder": {
    "0": {
      "value": "base",
      "type": "other",
      "rawValue": "base"
    },
    "1": {
      "value": "shared",
      "type": "other",
      "rawValue": "shared"
    }
  }
}
```
4. raw value `rgba({base.color.primary.0}, 0.8)` is converted to invalid hex color `#ffffffcc`.

**Expected behavior**
A raw value like `rgba({base.color.primary.0}, 0.8)` with the reference itsself being `base.color.primary.0 = "rgb(255, 255, 255)"` should be transformed in a away that keeps the transparency. Therefore my expected output would be no transformation to hex values for values with rgba(), but instead keeping the separate rgb values of the original reference, resulting in:
```
    "hover": {
      "value": "rgba(255, 255, 255, 0.8)",
      "type": "color",
      "rawValue": "rgba({base.color.primary.0}, 0.8)"
    },
```

Would be super neat to have that working! Thank you!

**Comment by six7** [comment]
We convert to [8-digit hex values](https://caniuse.com/css-rrggbbaa), would you consider those invalid?

I think one thing we might want to introduce to token-transformer is to specify output format (e.g. of colors but also of units) so that you could choose if you want `rgba`, `hex` or something else entirely

**Comment by DarioSoller** [comment]
@six7 thanks for your answer. Seems that I maybe have been mislead by other incorrect things, that these values seemed invalid. I have to admit, that it is the first time coming across the 4/8-digit hex color values, but I like them. Browser support seems fine, as well. I also think that these values a much better for actual token values, instead of relying on a rgba CSS function for tokens.

In the long term in still might make sense for a good UX/DX of the token-transformer, to make the output value format configurable. But idk if there is actually a use case or need for it?
