### ISSUE TITLE
Token references between Token Studio and the Style dictionary output

### ISSUE THREAD

**Issue by RobbyUitbeijerse** [tokens-studio/figma-plugin#1633]
Hi there!

We are trying to keep references between different kinds of tokens "alive" in between the Tokens Studio plugin and the style-dictionary output for css/sass variables. I'll start of by describing our desired scenario.

This is the format that we would like to output  from style-dictionary:

```
:root {
  --global-color-red: #ff000;
  
  
   --global-brand-primary: var(--global-color-red);
   
   
   --component-button-background: var(--global-brand-primary);
}
```

Instead, this is what we are getting:

```
:root {
  --global-color-red: #ff000;
 
  
   --global-brand-primary: #ff000;
   
   
   --component-button-background: #ff000;
}
```

This could be problematic, because for our dark team we want to override `--global-color-red` to be slightly darker. In order to do this, we would do something that looks like:

```
[data-theme="dark"] {
  --global-color-red: #8b0000;
}
```

The whole problem that we now have, is that even though the `--global-color-red` has been overwritten, it doesn't automatically propagate/cascade down through the rest of the variable structure.

We are using the `token-transformer` package to get from our Tokens Studio output to something that style-dictionary can handle, but it seems to 'break' the references in a way that doesn't allow us to re-structure them using style-dictionary. 

Are we missing something in the current scope of `token-transformer`? I tried fiddling with the `resolveReferences` option but once I'm turning that to false, style-dictionary chokes on the file and can't handle the references that are preserved. 

Not entirely sure if this is a new feature or a bug/misusage from our side but happy to hear back on your thoughts!

**Comment by RobbyUitbeijerse** [comment]
Hey, I think we figured it out. We now use:

```
  resolveReferences: false,
```

**Comment by six7** [comment]
Glad you were able to figure it out, sorry for the late reply!

I'd also suggest using our official sd transforms which remove the need for token-transformer: https://www.npmjs.com/package/@tokens-studio/sd-transforms
