### ISSUE TITLE
Uppercase doesn't work when I use it through the typography

### ISSUE THREAD

**Issue by as-smirnov** [tokens-studio/figma-plugin#1634]
**Describe the bug**
Uppercase doesn't work when I use it through the typography. But it works when I apply it separately.

**To Reproduce**
https://tokens-studio.slack.com/archives/C02DLQXNY6Q/p1675849014713069

**Expected behavior**
When applying a typographic composition with UPPERCASE, the appropriate styles will be applied and the text will become UPPERCASE.

**JSON**
Single file - [tokens-uppercase-bug.zip](https://github.com/tokens-studio/figma-plugin/files/10796560/tokens-uppercase-bug.zip)
Multiple files - [tokens-uppercase-bug.zip](https://github.com/tokens-studio/figma-plugin/files/10796540/tokens-uppercase-bug.zip)

**Comment by six7** [comment]
We weren't able to reproduce this issue @as-smirnov - your provided JSON doesn't contain any tokens of type: `typography`.

Can you provide a minimal JSON to reproduce this?

**Comment by buildtheui** [comment]
This is also happening to me, I'll attach the JSON file so you can reproduce it, thanks
[design-tokens.json.zip](https://github.com/tokens-studio/figma-plugin/files/11044800/design-tokens.json.zip)

**Comment by as-smirnov** [comment]
I really don't understand what's going on with the json file. I have prepared a figma file with typography tokens and styles. More information can be found here: https://clck.ru/33rTYR
