### ISSUE TITLE
LCH support for color definitions

### ISSUE THREAD

**Issue by bewarai** [tokens-studio/figma-plugin#1637]
Currently you support 
Hex
RGBA
HSLA

I would be great if you support also LCH.

HSL lightness resembles the amount of black or white added to a pure color. For example, a light blue color can be created by adding white to a pure blue hue.

LCH lightness describes the relative brightness of a color compared to a similarly illuminated white.
In contrast, LCH ensures that different colors with the same lightness have almost identical contrast ratios, **making it easier to ensure accessibility**.

**Comment by six7** [comment]
Thanks for creating this, this would fit right in extending what colors are available.

Note that the W3C color spec notes that colors [need to be typed in hex](https://tr.designtokens.org/format/#color), so maybe add your feedback over there as well that this is a limitation.

On our end we'll extend this to also allow LCH, but note that it won't be compliant.

**Comment by LukeFinch** [comment]
This request has been moved to our new feedback tool. Go check out https://tokensstudio.featurebase.app/ to create a free account. You can upvote and comment on existing posts, make a new request, and subscribe to be notified when requests move into our roadmap.

**Comment by UdayHyma** [comment]
Added to FeatureBase Roadmap : [🎨 Expanded support for color spaces](https://tokensstudio.featurebase.app/p/expanded-support-for-color-spaces)
