### ISSUE TITLE
GitLab users get read-only access if they are on `maintainer` on repo, but `guest` on subgroup

### ISSUE THREAD

**Issue by RYamashita3** [tokens-studio/figma-plugin#1644]
There seems to be an issue with GitLab where when a user has `maintainer` access on a repository, but only `guest` on a the group the repository is part of, we give the user only read-only access.

To reproduce:
- Create a repository in a subgroup
- Give the user `guest` access in the subgroup
- Give the user `maintainer` access in the repo

Expected: User has write access to the repo
Actual outcome: User has read-only access to the repo

<details><summary>Original issue description</summary>
<p>

**Describe the bug**
I've set up a sync connection to Gitlab using an api scope personal access token on a maintainer-level account, and am able to add branches and files to the Gitlab repo from the plugin. However, all buttons in the plugin for adding tokens or sets, editing or duplicating existing tokens, or pushing to Gitlab are greyed out. The JSON isn't directly editable either. I have a Pro level Tokens Studio account. Also, when Gitlab is selected as the source, the token set names in the left-hand pane are misaligned from where they usually are.

**To Reproduce**
None

**Expected behavior**
I should be able to edit, add, and remove tokens stored in a Gitlab repo

**Screenshots or Screencasts**
Local source:
![local](https://user-images.githubusercontent.com/118766580/221301715-e902e7ff-207a-46d7-8b9f-a4b9e482a8b6.png)

Gitlab source:
![gitlab](https://user-images.githubusercontent.com/118766580/221301731-4340eb9d-2497-44e2-80d0-6d9b13988206.png)

**Figma file (optional)**
None

**JSON (optional)**
None

</p>
</details>

**Comment by six7** [comment]
As long as you are not on `Pro` you need your filePath to end in `.json` (to sync to one json file). If your filePath doesn't end with a .json it will sync to multiple files, which is a Pro feature. From your screenshots I'm unable to tell, so ideally share the sync setup form

**Comment by six7** [comment]
Did you set your access token to write on repo?

CC'ing @rbosker who might know more about that one

**Comment by RYamashita3** [comment]
Yes, the current access token is set to "api". I've also tried with all options checked: "api, read_api, read_user, read_repository, write_repository, read_registry, write_registry".

**Comment by RYamashita3** [comment]
@six7 , @rbosker : I've triple checked personal token settings; I'm at Pro level of Tokens Studio; I have Maintainer level permissions on Gitlab; I've relaunched Figma, the plugin, and my machine; and the plugin functions without issues on Github and local sync but not Gitlab. We have to work in Gitlab, but I'm out of ideas on our end for connecting properly and using the full functionality of the Pro plugin.

**Comment by RYamashita3** [comment]
@six7, @rbosker  : Any update on this issue? It's preventing us from moving forward with our tokens setup, and it's been 2 weeks

**Comment by six7** [comment]
I updated the issue description - we'll work on it this week during bug bash

**Comment by six7** [comment]
@RYamashita3 just tried to reproduce with the same setup you have, was able to do so. Can you create a new issue with a description of the issue and what settings you have? Also the scopes your api token has.
