### ISSUE TITLE
Add Hue & Saturation Color Modifiders

### ISSUE THREAD

**Issue by chriskerr-performio** [tokens-studio/figma-plugin#1647]
**Is your feature request related to a problem? Please describe.**
Our style guide has a design rule that hovering interactions should adjust colours to bring the users attention to the component they are interacting with. Often this requires our colours to increase saturation to lift the brightness of the colour, but without washing it out (lighten alone).

In some cases, such as colours like yellow, using darken (adding black) alone leads to the colour becoming a "dirty yellow/brown" colour. Currently we solve this manually and shift the hue value towards the red spectrum which makes allows us to darken the colour and make it more orange than brown.

In both cases, lightness and darkness controls alone cannot resolve the desired visual outcome

**Describe the solution you'd like**
When editing a colour token, and using a modifier, include the ability to change the hue and saturation values of the colour as well as the existing options

As the Hue, Saturation and lighten/darken need to be used together to achieve full colour control, it might be necessary to think about being able to apply multiple modifiers

**Describe alternatives you've considered**
Manually defining values, as we have today

**Comment by vnys** [comment]
I need this too, for similar reasons. We normally increase saturation in dark mode, and also create muted variants of some of the colours in our pallette. It would also be great if we could add more than one modifier to the same colour.

**Comment by jac31885** [comment]
Likewise, would be good to include this as a modifier

**Comment by UdayHyma** [comment]
Added to FeatureBase Roadmap : [🎨 Expand functionality of color modifiers](https://tokensstudio.featurebase.app/p/expand-functionality-of-color-modifiers)

**Comment by UdayHyma** [comment]
[Migrated to featurebase](https://tokensstudio.featurebase.app/p/expand-functionality-of-color-modifiers)
