### ISSUE TITLE
Hope to add multi-language support

### ISSUE THREAD

**Issue by yamazakitouma** [tokens-studio/figma-plugin#1650]
希望可以支持界面的多语言支持，可以通过提供汉化接口，供社区来帮助进行汉化。

We hope to support multi-language support for the interface, which can be done by providing a Chinese interface for the community to help with the Chineseization.

**Comment by six7** [comment]
This was shipped a while ago, we never closed it. You can change language in the Settings! If there's any issues with the translations please feel free to reach out or create a PR 🙏
