### ISSUE TITLE
Add new color modes to color input

### ISSUE THREAD

**Issue by six7** [tokens-studio/figma-plugin#1651]
We currently only support `rgba`, `hsla` as well as 3-/4-digit hex values.

We've received requests to extend this to other color modes:

```[tasklist]
### Tasks
- [ ] https://github.com/tokens-studio/figma-plugin/issues/1637
- [ ] https://github.com/tokens-studio/figma-plugin/issues/1608
``` 

Feel free to comment on this issue to request additional color modes.

**Comment by EllyLoel** [comment]
LCH would be good, but OKLCH would be great. I won't write an essay on why as this [article by Evil Martians](https://evilmartians.com/chronicles/oklch-in-css-why-quit-rgb-hsl) already does a great job covering it.

**Comment by lepszy** [comment]
HSLuv support would be awesome, since I cannot use the brand colors in a project I'm working on currently. HSLuv extends the CIELUV color space. 
Read more here: https://www.hsluv.org

**Comment by SamIam4Hyma** [comment]
I've added these and other color space requests in a combined post on Feature base. Please go upvote! (: Added to Featurebase Request-	[💡 Expand functionality of color space](https://tokensstudio.featurebase.app/p/expand-functionality-of-color-modifiers)

**Comment by UdayHyma** [comment]
[Migrated to Featurebase](https://tokensstudio.featurebase.app/p/expand-functionality-of-color-modifiers)
