### ISSUE TITLE
Token transformer: colour modifiers are applied multiple times

### ISSUE THREAD

**Issue by dryton** [tokens-studio/figma-plugin#1653]
**Describe the bug**
When working with colour modifiers we're finding that sometimes they are applied multiple times to the original colour value.

In our case we're attempting to darken a colour by 30% and the result comes out much darker.

It appears to be unrelated to the colour modification code itself, as that produces the correct value, but does seem to be related to how the token values are processed.

It looks like the same token goes through the darken function more than once.

**To Reproduce**
Here's a repo that contains the steps and code to reproduce the issue:
[Minimal reproduction for color modifier issue](https://github.com/dryton/token-transformer-repro)

**Expected behavior**
For the example provided in the repo, the expectation is that the colour `#00a2ba` is darkened by 30% to produce the colour `#007182` for the button press background colour.

**Comment by QRusinTomasz** [comment]
Experiencing the same problem. At the moment the plugin is not usable. It would be great to have a fix soon.

**Comment by six7** [comment]
Are you all sure you're running version 30? This does seem to happen on 29, but not anymore on 30.

**Comment by six7** [comment]
You're right - we've now published 0.0.32 which fixes this.
