### ISSUE TITLE
Add possibility to reorder tokens starting with numbers

### ISSUE THREAD

**Issue by rbosker** [tokens-studio/figma-plugin#1655]
**Feature Request**
Currently it's not possible to reorder tokens when they start with a number, due to technical limitation in JSON. W

See comments for more info.

**Comment by six7** [comment]
@rbosker we cant reorder those `numerical` tokens because that's not possible in JSON. numbers always come first and are auto-sorted. unless we want to build our own sorting metadata on top of all this. however that's a significant lift that is probably not worth it.

**Comment by UdayHyma** [comment]
[Migrated to Featurebase](https://tokensstudio.featurebase.app/p/token-organization-enhancements)
