### ISSUE TITLE
Plugin crashes after a while when in a branch of the library file

### ISSUE THREAD

**Issue by Davst** [tokens-studio/figma-plugin#1658]
**Describe the bug**
After a while, the plugin crashes and is unstartable when used in a branch of a library file.
Prior to this the plugin was sitting open, without any tokens created since I was working with some basic stuff to prepare to try starting to create tokens for out primitives such as color etc. 

I've been able to replicate this 4 times so far so it seems to be fairly consistent. 

**To Reproduce**
1. Create a branch of library file
2. Open Tokens Studio
3. Do other stuff in the file for a while, mixed with being idle
4. Plugin crashes and you can't start it again with a red message to open console.

**Expected behavior**
Expect plugin to not crash.
Expect to be able to start plugin.

**Screenshots or Screencasts**
Console output: 
![image](https://user-images.githubusercontent.com/3330933/222375537-8081eb02-323c-4877-b682-a75b1007cb54.png)

**Figma file (optional)**
Can't share due to NDA. 
The file is a component library for a project, it has some 16 pages with assorted components. Nothing complex is displayed on the page I have been on during the crash, just a bunch of base colors with their styles. 

**JSON (optional)**
No JSON yet.. purely existing in a Figma library branch causes the crash.

**Comment by Davst** [comment]
The plugin actually seemed to have recovered when starting again with the console open.

Here is a more complete console output for more reference:

![image](https://user-images.githubusercontent.com/3330933/222376515-cb1b1456-a2e9-4e22-8528-b84baf748fd3.png)


The last 3 rows, beginning with "[jsvm-cpp] main called (emscripten version 2.0.31)" are from when the plugin started up again.

The plugin starts up in a new empty file state, (not sure if it ever saves a file state before you add a token) so it seems to be starting from scratch.

**Comment by Davst** [comment]
Just happened again, this is the console output:


![image](https://user-images.githubusercontent.com/3330933/222464397-49d517b2-dccc-4262-a7d8-6684adbd9af2.png)


```
figma_app.min.js.br:5 Error: null
    at a (figma_app.min.js.br:598:8552)
    at Object.callFunction (figma_app.min.js.br:598:11458)
    at urr.callFunction (figma_app.min.js.br:627:3601)
    at yte.fireEventSync (figma_app.min.js.br:1491:7539)
    at figma_app.min.js.br:1490:12112
    at figma_app.min.js.br:1491:7374
    at n (figma_app.min.js.br:12:5941)
(anonymous) @ figma_app.min.js.br:5
figma_app.min.js.br:5 Error: Plugin runtime aborted
    at D (figma_app.min.js.br:1517:27928)
    at urr._abortHandler (figma_app.min.js.br:1517:27551)
    at ml.onAbort (figma_app.min.js.br:627:162)
    at abort (jsvm-cpp.js.br:9:12959)
    at _abort (jsvm-cpp.js.br:9:17620)
    at jsvm-cpp.wasm.br:0x89817
    at jsvm-cpp.wasm.br:0x76e4
    at jsvm-cpp.wasm.br:0x8d61
    at a (figma_app.min.js.br:598:8487)
    at Object.getPropStr (figma_app.min.js.br:598:10785)
    at urr.callFunction (figma_app.min.js.br:628:18)
    at yte.fireEventSync (figma_app.min.js.br:1491:7539)
    at figma_app.min.js.br:1490:12112
    at figma_app.min.js.br:1491:7374
    at n (figma_app.min.js.br:12:5941)
(anonymous) @ figma_app.min.js.br:5
jsvm-cpp.wasm.br:0x1858 Uncaught (in promise) RuntimeError: null function or function signature mismatch
    at jsvm-cpp.wasm.br:0x1858
    at jsvm-cpp.wasm.br:0x5cd3
    at Object.reset (figma_app.min.js.br:598:8703)
    at urr.destroy (figma_app.min.js.br:629:674)
    at figma_app.min.js.br:1517:28619
    at H (figma_app.min.js.br:1517:27799)
    at async D (figma_app.min.js.br:1517:27955)

**Comment by six7** [comment]
thanks for posting these, i hope we'll be able to fix some of the memory related issues on our own

**Comment by Davst** [comment]
After more exploration, the common trigger seems to be when Figma has been idle long enough that it doesn't have an active "connection" to the file anymore and forces a reload. This seems to solidly crash the plugin and once Figma is connected to the file, it can be started again

**Comment by six7** [comment]
Yeah this is what we've also been experiencing. Figma is disposing references to things we still have in memory. 

cc'ing @SorsOps here for memory issues
