### ISSUE TITLE
Excessive memory usage

### ISSUE THREAD

**Issue by seraremes** [tokens-studio/figma-plugin#1659]
**Describe the bug**
When making changes to a large-ish document, memory usage grows linearly and doesn't decrease. This continues until system memory limits are reached and Figma displays an error (see screenshot)

**To Reproduce**
Steps to reproduce the behaviour:
1. Make a change to a token
2. Click on "Apply to document"
3. Observe as memory usage grows
4. Repeat
5. Observe as memory usage grows again and never decreases
(Repeating the above enough times will cause the computer to run out of memory)

**Expected behavior**
Computer does not run out of memory

**Screenshots or Screencasts**
<img width="2550" alt="image" src="https://user-images.githubusercontent.com/112854522/222437827-8c7ef6c6-cf56-4df0-b1c9-e7f65137a1dc.png">

**Figma file (optional)**
(not applicable)

**JSON (optional)**
(not applicable)

**Comment by six7** [comment]
@SorsOps this could be related to the issue you recently mentioned on resolving references

**Comment by SorsOps** [comment]
Hi @seraremes, would it be possible for you to share your token set that's causing the issue so that I can use that to debug the memory problems ?

**Comment by seraremes** [comment]
@SorsOps 
{
  "primary": {
    "default": {
      "value": "{blue.P300}",
      "type": "color"
    },
    "hover": {
      "value": "{blue.P400}",
      "type": "color"
    },
    "active": {
      "value": "{blue.P200}",
      "type": "color"
    }
  },
  "bg": {
    "default": {
      "value": "{white}",
      "type": "color"
    },
    "muted": {
      "value": "{grey.Z900}",
      "type": "color"
    },
    "subtle": {
      "value": "{grey.Z700}",
      "type": "color"
    }
  },
  "accent": {
    "default": {
      "value": "{blue.P800}",
      "type": "color"
    },
    "bg": {
      "value": "{blue.P900}",
      "type": "color"
    }
  },
  "fg": {
    "default": {
      "value": "{grey.Z100}",
      "type": "color"
    },
    "muted": {
      "value": "{grey.Z300}",
      "type": "color"
    },
    "subtle": {
      "value": "{grey.Z500}",
      "type": "color"
    }
  },
  "support": {
    "error": {
      "value": "{red.A400}",
      "type": "color"
    },
    "waiting": {
      "value": "{yellow.C500}",
      "type": "color"
    },
    "success": {
      "value": "{green.K200}",
      "type": "color"
    }
  },
  "fontFamilies": {
    "scto-grotesk-a": {
      "value": "Scto Grotesk A",
      "type": "fontFamilies"
    }
  },
  "lineHeights": {
    "0": {
      "value": "14",
      "type": "lineHeights"
    },
    "1": {
      "value": "16",
      "type": "lineHeights"
    },
    "2": {
      "value": "18",
      "type": "lineHeights"
    },
    "3": {
      "value": "22",
      "type": "lineHeights"
    },
    "4": {
      "value": "20",
      "type": "lineHeights"
    },
    "5": {
      "value": "24",
      "type": "lineHeights"
    },
    "6": {
      "value": "28",
      "type": "lineHeights"
    },
    "7": {
      "value": "36",
      "type": "lineHeights"
    }
  },
  "fontWeights": {
    "scto-grotesk-a-0": {
      "value": "Regular",
      "type": "fontWeights"
    },
    "scto-grotesk-a-1": {
      "value": "Bold",
      "type": "fontWeights"
    }
  },
  "fontSize": {
    "0": {
      "value": "10",
      "type": "fontSizes"
    },
    "1": {
      "value": "12",
      "type": "fontSizes"
    },
    "2": {
      "value": "14",
      "type": "fontSizes"
    },
    "3": {
      "value": "16",
      "type": "fontSizes"
    },
    "4": {
      "value": "20",
      "type": "fontSizes"
    },
    "5": {
      "value": "28",
      "type": "fontSizes"
    }
  },
  "letterSpacing": {
    "0": {
      "value": "1.5%",
      "type": "letterSpacing"
    },
    "1": {
      "value": "0.2%",
      "type": "letterSpacing"
    },
    "2": {
      "value": "0.1%",
      "type": "letterSpacing"
    },
    "3": {
      "value": "0.15%",
      "type": "letterSpacing"
    },
    "4": {
      "value": "0%",
      "type": "letterSpacing"
    }
  },
  "paragraphSpacing": {
    "0": {
      "value": "0",
      "type": "paragraphSpacing"
    }
  },
  "utility-01": {
    "value": {
      "fontFamily": "{fontFamilies.scto-grotesk-a}",
      "fontWeight": "{fontWeights.scto-grotesk-a-0}",
      "lineHeight": "{lineHeights.0}",
      "fontSize": "{fontSize.0}",
      "letterSpacing": "{letterSpacing.0}",
      "paragraphSpacing": "{paragraphSpacing.0}",
      "paragraphIndent": "{paragraphIndent.0}",
      "textCase": "{textCase.none}",
      "textDecoration": "{textDecoration.none}"
    },
    "type": "typography"
  },
  "utility-02": {
    "value": {
      "fontFamily": "{fontFamilies.scto-grotesk-a}",
      "fontWeight": "{fontWeights.scto-grotesk-a-0}",
      "lineHeight": "{lineHeights.1}",
      "fontSize": "{fontSize.1}",
      "letterSpacing": "{letterSpacing.1}",
      "paragraphSpacing": "{paragraphSpacing.0}",
      "paragraphIndent": "{paragraphIndent.0}",
      "textCase": "{textCase.none}",
      "textDecoration": "{textDecoration.none}"
    },
    "type": "typography",
    "description": "This is a multipurpose type style that can be used for field labels in components, error messages, and captions in dense layouts. It should not be used for body copy."
  },
  "body-compact-01": {
    "value": {
      "fontFamily": "{fontFamilies.scto-grotesk-a}",
      "fontWeight": "{fontWeights.scto-grotesk-a-0}",
      "lineHeight": "{lineHeights.2}",
      "fontSize": "{fontSize.2}",
      "letterSpacing": "{letterSpacing.2}",
      "paragraphSpacing": "{paragraphSpacing.0}",
      "paragraphIndent": "{paragraphIndent.0}",
      "textCase": "{textCase.none}",
      "textDecoration": "{textDecoration.none}"
    },
    "type": "typography",
    "description": "This is for short paragraphs with no more than four lines and is commonly used in dense components."
  },
  "body-compact-02": {
    "value": {
      "fontFamily": "{fontFamilies.scto-grotesk-a}",
      "fontWeight": "{fontWeights.scto-grotesk-a-0}",
      "lineHeight": "{lineHeights.3}",
      "fontSize": "{fontSize.3}",
      "letterSpacing": "{letterSpacing.3}",
      "paragraphSpacing": "{paragraphSpacing.0}",
      "paragraphIndent": "{paragraphIndent.0}",
      "textCase": "{textCase.none}",
      "textDecoration": "{textDecoration.none}"
    },
    "type": "typography",
    "description": "This is for short paragraphs with no more than four lines. Use in medium sized components, such as button and link."
  },
  "body-01": {
    "value": {
      "fontFamily": "{fontFamilies.scto-grotesk-a}",
      "fontWeight": "{fontWeights.scto-grotesk-a-0}",
      "lineHeight": "{lineHeights.4}",
      "fontSize": "{fontSize.2}",
      "letterSpacing": "{letterSpacing.2}",
      "paragraphSpacing": "{paragraphSpacing.0}",
      "paragraphIndent": "{paragraphIndent.0}",
      "textCase": "{textCase.none}",
      "textDecoration": "{textDecoration.none}"
    },
    "type": "typography"
  },
  "body-02": {
    "value": {
      "fontFamily": "{fontFamilies.scto-grotesk-a}",
      "fontWeight": "{fontWeights.scto-grotesk-a-0}",
      "lineHeight": "{lineHeights.5}",
      "fontSize": "{fontSize.3}",
      "letterSpacing": "{letterSpacing.3}",
      "paragraphSpacing": "{paragraphSpacing.0}",
      "paragraphIndent": "{paragraphIndent.0}",
      "textCase": "{textCase.none}",
      "textDecoration": "{textDecoration.none}"
    },
    "type": "typography"
  },
  "heading-01": {
    "value": {
      "fontFamily": "{fontFamilies.scto-grotesk-a}",
      "fontWeight": "{fontWeights.scto-grotesk-a-1}",
      "lineHeight": "{lineHeights.4}",
      "fontSize": "{fontSize.2}",
      "letterSpacing": "{letterSpacing.4}",
      "paragraphSpacing": "{paragraphSpacing.0}",
      "paragraphIndent": "{paragraphIndent.0}",
      "textCase": "{textCase.none}",
      "textDecoration": "{textDecoration.none}"
    },
    "type": "typography"
  },
  "heading-02": {
    "value": {
      "fontFamily": "{fontFamilies.scto-grotesk-a}",
      "fontWeight": "{fontWeights.scto-grotesk-a-1}",
      "lineHeight": "{lineHeights.5}",
      "fontSize": "{fontSize.3}",
      "letterSpacing": "{letterSpacing.4}",
      "paragraphSpacing": "{paragraphSpacing.0}",
      "paragraphIndent": "{paragraphIndent.0}",
      "textCase": "{textCase.none}",
      "textDecoration": "{textDecoration.none}"
    },
    "type": "typography"
  },
  "heading-03": {
    "value": {
      "fontFamily": "{fontFamilies.scto-grotesk-a}",
      "fontWeight": "{fontWeights.scto-grotesk-a-0}",
      "lineHeight": "{lineHeights.6}",
      "fontSize": "{fontSize.4}",
      "letterSpacing": "{letterSpacing.4}",
      "paragraphSpacing": "{paragraphSpacing.0}",
      "paragraphIndent": "{paragraphIndent.0}",
      "textCase": "{textCase.none}",
      "textDecoration": "{textDecoration.none}"
    },
    "type": "typography"
  },
  "heading-04": {
    "value": {
      "fontFamily": "{fontFamilies.scto-grotesk-a}",
      "fontWeight": "{fontWeights.scto-grotesk-a-0}",
      "lineHeight": "{lineHeights.7}",
      "fontSize": "{fontSize.5}",
      "letterSpacing": "{letterSpacing.3}",
      "paragraphSpacing": "{paragraphSpacing.0}",
      "paragraphIndent": "{paragraphIndent.0}",
      "textCase": "{textCase.none}",
      "textDecoration": "{textDecoration.none}"
    },
    "type": "typography"
  },
  "textCase": {
    "none": {
      "value": "none",
      "type": "textCase"
    }
  },
  "textDecoration": {
    "none": {
      "value": "none",
      "type": "textDecoration"
    }
  },
  "paragraphIndent": {
    "0": {
      "value": "0px",
      "type": "dimension"
    }
  },
  "button": {
    "small": {
      "value": "32px",
      "type": "sizing"
    },
    "medium": {
      "value": "40px",
      "type": "sizing"
    },
    "primary": {
      "default": {
        "background": {
          "value": "{primary.default}",
          "type": "color"
        },
        "border": {
          "value": "{primary.default}",
          "type": "color"
        },
        "text": {
          "value": "{white}",
          "type": "color"
        }
      },
      "hover": {
        "background": {
          "value": "{primary.hover}",
          "type": "color"
        },
        "border": {
          "value": "{primary.hover}",
          "type": "color"
        },
        "text": {
          "value": "{white}",
          "type": "color"
        }
      },
      "focus": {
        "background": {
          "value": "{primary.hover}",
          "type": "color"
        },
        "border": {
          "value": "{primary.hover}",
          "type": "color"
        },
        "text": {
          "value": "{white}",
          "type": "color"
        }
      },
      "active": {
        "background": {
          "value": "{primary.active}",
          "type": "color"
        },
        "border": {
          "value": "{primary.active}",
          "type": "color"
        },
        "text": {
          "value": "{white}",
          "type": "color"
        }
      },
      "disabled": {
        "background": {
          "value": "{bg.subtle}",
          "type": "color"
        },
        "border": {
          "value": "{bg.subtle}",
          "type": "color"
        },
        "text": {
          "value": "{fg.subtle}",
          "type": "color"
        }
      }
    },
    "secondary": {
      "default": {
        "background": {
          "value": "{transparent}",
          "type": "color"
        },
        "border": {
          "value": "{primary.default}",
          "type": "color"
        },
        "text": {
          "value": "{primary.default}",
          "type": "color"
        }
      },
      "hover": {
        "background": {
          "value": "{accent.bg}",
          "type": "color"
        },
        "border": {
          "value": "{primary.default}",
          "type": "color"
        },
        "text": {
          "value": "{primary.default}",
          "type": "color"
        }
      },
      "focus": {
        "background": {
          "value": "{accent.bg}",
          "type": "color"
        },
        "border": {
          "value": "{primary.default}",
          "type": "color"
        },
        "text": {
          "value": "{primary.default}",
          "type": "color"
        }
      },
      "active": {
        "background": {
          "value": "{accent.default}",
          "type": "color"
        },
        "border": {
          "value": "{primary.default}",
          "type": "color"
        },
        "text": {
          "value": "{primary.default}",
          "type": "color"
        }
      },
      "disabled": {
        "background": {
          "value": "{transparent}",
          "type": "color"
        },
        "border": {
          "value": "{fg.subtle}",
          "type": "color"
        },
        "text": {
          "value": "{fg.subtle}",
          "type": "color"
        }
      }
    },
    "tertiary": {
      "default": {
        "background": {
          "value": "{transparent}",
          "type": "color"
        },
        "border": {
          "value": "{transparent}",
          "type": "color"
        },
        "text": {
          "value": "{primary.default}",
          "type": "color"
        }
      },
      "hover": {
        "background": {
          "value": "{accent.bg}",
          "type": "color"
        },
        "border": {
          "value": "{accent.bg}",
          "type": "color"
        },
        "text": {
          "value": "{primary.default}",
          "type": "color"
        }
      },
      "focus": {
        "background": {
          "value": "{accent.bg}",
          "type": "color"
        },
        "border": {
          "value": "{accent.bg}",
          "type": "color"
        },
        "text": {
          "value": "{primary.default}",
          "type": "color"
        }
      },
      "active": {
        "background": {
          "value": "{accent.default}",
          "type": "color"
        },
        "border": {
          "value": "{accent.default}",
          "type": "color"
        },
        "text": {
          "value": "{primary.default}",
          "type": "color"
        }
      },
      "disabled": {
        "background": {
          "value": "{transparent}",
          "type": "color"
        },
        "border": {
          "value": "{transparent}",
          "type": "color"
        },
        "text": {
          "value": "{fg.subtle}",
          "type": "color"
        }
      }
    }
  },
  "borderradius": {
    "20": {
      "value": "20",
      "type": "borderRadius"
    }
  },
  "text": {
    "primary": {
      "value": "{fg.default}",
      "type": "color"
    },
    "secondary": {
      "value": "{fg.muted}",
      "type": "color"
    },
    "on-color": {
      "value": "{white}",
      "type": "color"
    }
  },
  "togglebutton": {
    "container": {
      "background": {
        "value": "{bg.default}",
        "type": "color"
      },
      "border": {
        "value": "{primary.default}",
        "type": "color"
      }
    },
    "active": {
      "background": {
        "value": "{primary.default}",
        "type": "color"
      },
      "text": {
        "value": "{text.on-color}",
        "type": "color"
      }
    },
    "default": {
      "background": {
        "value": "{transparent}",
        "type": "color"
      },
      "text": {
        "value": "{primary.default}",
        "type": "color"
      }
    }
  },
  "field": {
    "default": {
      "value": {
        "color": "{bg.subtle}",
        "width": "1px",
        "style": "solid"
      },
      "type": "border"
    },
    "hover": {
      "value": {
        "color": "{primary.default}",
        "width": "1px",
        "style": "solid"
      },
      "type": "border"
    },
    "error": {
      "value": {
        "color": "{support.error}",
        "width": "1px",
        "style": "solid"
      },
      "type": "border"
    },
    "focus": {
      "value": {
        "color": "{primary.default}",
        "width": "2",
        "style": "solid"
      },
      "type": "border"
    },
    "active": {
      "value": {
        "color": "{primary.default}",
        "width": "1.5",
        "style": "solid"
      },
      "type": "border"
    }
  },
  "dropdown": {
    "options": {
      "background": {
        "value": "{accent.bg}",
        "type": "color"
      },
      "active": {
        "value": "{accent.default}",
        "type": "color"
      }
    }
  }
}

**Comment by SorsOps** [comment]
Thank you @seraremes . I've seen larger sets than this without any crashes (though I need to determine how many times the loop of applying new values was done).

Would it be possible for you to give me a rough estimate of the amount of elements you have the above tokens applied to ?

**Comment by seraremes** [comment]
@SorsOps it did not seem to be about the amount of elements where the token is applied, mostly it was just few elements in one page. The problem occurs when "Apply to document" is chosen instead of "Apply to page". My document has around 20 pages, the tokens are not used in most of them but going through all of it causes the crash eventually even while the token changes made by editing token would be super small.

**Comment by bewarai** [comment]
I have the same issue, and a double amount of tokens. I start to wonder if referencing tokens in the plugin with large files is such a good idea. Finding and caching tokens seem to take forever. Multiple crashes. and after 3 hours still trying to update everything.
