### ISSUE TITLE
Declare a token set as a dynamic set

### ISSUE THREAD

**Issue by six7** [tokens-studio/figma-plugin#1664]
Most of the times when you're creating tokens for a theme you want that token to be created for all themes, with variations.

We could offer users a way to declare a `theme / dynamic token set` that mirrors across other themes, with a way to declare a defaultValue so you don't have to declare it again and again for every theme but can just declare once and override per theme as required.

**Comment by keeganedwin** [comment]
**Use-case:**

_We're building a design and token system that we're using across multiple brands. We want each brand to use the same set of components while the styling of these components is controlled by tokens. To this end, we've set up a Figma library and applied global and brand-specific sets of tokens to its components. For each of our brand, we now duplicate the brand-specific token sets and adjust their values and references to fit the brand's styling. This is making the management of token changes very cumbersome as any minor and major updates have to be reflected in each brand-specific token set - we have to go through and make the adjustments set-by-set, which opens us up to a lot of human error. We cannot globalise these tokens unless we sacrifice customisability, which we don't really want to do unless absolutely necessary. Is there a way to manage and update tokens duplicated across multiple sets in one go?_

**Comment by SamIam4Hyma** [comment]
@LukeFinch pretty sure this is in your plan for V2X. There are labels for some of the upcoming releases already, and I've added the category labels. Although you might want you merge/close etc.

**Comment by LukeFinch** [comment]
This request has been moved to our new feedback tool. Go check out https://tokensstudio.featurebase.app/ to create a free account. You can upvote and comment on existing posts, make a new request, and subscribe to be notified when requests move into our roadmap.

**Comment by UdayHyma** [comment]
Added to Featurebase Roadmap : [🌜Theme management (pro) enhancements](https://tokensstudio.featurebase.app/p/theme-management-enhancements)
