### ISSUE TITLE
When editing a token with `cmd+click` and you have a layer selected, that token is applied

### ISSUE THREAD

**Issue by swordEdge** [tokens-studio/figma-plugin#1669]
When you cmd + click on a token to go to the Edit mode, we apply that as well.

Expected: We edit, but we do not apply it.

`Note: fix on main`

**Comment by six7** [comment]
@swordEdge users reported this still happens on `Windows`, can you check on this?

**Comment by swordEdge** [comment]
> 

@six7 I tested it on windows again. The video on this pr was recorded on windows. I'd like to know whether editing modal pop up or not. What I mean is while the token is applied, does the modal pop up? or only the token is applied without popping up the modal?

**Comment by six7** [comment]
> @six7 I tested it on windows again. I clicked the token with windows key. The video on this pr was recorded on windows. I'd like to know whether editing modal pop up or not. What I mean is while the token is applied, does the modal pop up? or only the token is applied without popping up the modal?

you're right, I think I just miscommunicated `ctrl + click` to do it, when `windowskey + click` does it. My bad!
