### ISSUE TITLE
wrong order in metadata tokenSetOrder

### ISSUE THREAD

**Issue by C3PablO** [tokens-studio/figma-plugin#1673]
**Describe the bug**
The "Listing" view displays the wrong value for a token.
The "JSON" view displays the correct value for a token.
The "edit" token dialog displays the correct value for a token.
Applying the token to an element in Figma sets the wrong value.

We found that the issue is caused by the position of the sets being correct in the GUI but incorrect in the metadata JSON file.
Workaround:
- A plugin user can drag the set to a different position and then drag it back to its original place (I guess the metadata gets re-written)
- Update the metadata file manually (We use GitHub as a source)

This recording shows the issue:
https://user-images.githubusercontent.com/3966942/223721078-feb84245-c190-4557-bf8f-4f3109e5a5b7.mov

This recording shows the workaround through the plugin
https://user-images.githubusercontent.com/3966942/223720637-167b3f25-e9f6-4e92-9cad-3f4776f801ad.mov

This is what the metadata JSON looks like:
```
{
  "tokenSetOrder": [
    "reference",
    "decision/base",
    "decision/component",
    "component/button",
    "component/iconButton",
    "brand/electrolux",
    "brand/aeg",
    "brand/zanussi",
    "component/link",
    "component/tag"
  ]
}
```
The correct order should be the following to reflect the order in the GUI (see recordings):
```
{
  "tokenSetOrder": [
    "reference",
    "decision/base",
    "decision/component",
    "component/button",
    "component/iconButton",
    "component/link",
    "component/tag"
    "brand/electrolux",
    "brand/aeg",
    "brand/zanussi",
  ]
}
```
Link to the thread in Slack: https://tokens-studio.slack.com/archives/C02DLQXNY6Q/p1678275253126429

**Comment by six7** [comment]
I'd say the correct order would be

```
{
  "tokenSetOrder": [
    "reference",
    "decision/base",
    "decision/component",
    "component/button",
    "component/iconButton",
    "component/tag"
    "component/link",
    "brand/electrolux",
    "brand/aeg",
    "brand/zanussi",
  ]
}
```

given children of folders would all be grouped together

**Comment by C3PablO** [comment]
> I'd say the correct order would be
> 
> ```
> {
>   "tokenSetOrder": [
>     "reference",
>     "decision/base",
>     "decision/component",
>     "component/button",
>     "component/iconButton",
>     "component/tag"
>     "component/link",
>     "brand/electrolux",
>     "brand/aeg",
>     "brand/zanussi",
>   ]
> }
> ```
> 
> given children of folders would all be grouped together

Yeah, sorry. I corrected my comment.
