### ISSUE TITLE
Token / Inspect not showing applied tokens on component instance

### ISSUE THREAD

**Issue by wolfXDnet** [tokens-studio/figma-plugin#1683]
**Describe the bug**
Tokens / Inspect do not show the applied tokens on component instances.
The tokens are correctly applied (validated by changing respective value) but only update when using the apply button.
Tokens on child nodes work as expected and are shown in Tokens and Inspect and update automatically on value changes.

Assumption: Selection of the component instance is not handled correctly

**To Reproduce**
1. Create a component with tokens applied
2. Create a instance of it
3. Select instance to view or change tokens

**Expected behavior**
Selection of the instance depict applied tokens in Tokens and Inspect, values are applied automatically when changing the token value.

**Screenshots or Screencasts**
![Bildschirm­foto 2023-03-13 um 10 46 19](https://user-images.githubusercontent.com/56354826/224670571-5b7975ed-af00-4755-848e-fd627e92a268.png)
Selected instance not showing tokens applied.

![Bildschirm­foto 2023-03-13 um 10 46 37](https://user-images.githubusercontent.com/56354826/224670923-9402001b-8772-4dda-bba0-fddb96da843e.png)
Inspect not showing applied tokens.

![Bildschirm­foto 2023-03-13 um 10 47 13](https://user-images.githubusercontent.com/56354826/224671117-7ed33eca-4c00-4925-a637-0657c4f6f64a.png)
Selecting a child node showing applied tokens correctly

![Bildschirm­foto 2023-03-13 um 10 47 33](https://user-images.githubusercontent.com/56354826/224671388-f0ffb4dd-a015-47a3-b5dc-29d5fab99435.png)
Changing selection back to instance does not update Tokens nor Inspect

**Comment by wolfXDnet** [comment]
Found the root cause and it's not related to instances but color styles...

The components throwing the error were utilising a color style that did not have a color property applied. So basically a color-less color style.

Updating the respective color style to use a fully transparent color did resolve the issue.

**Comment by SamIam4Hyma** [comment]
@keeganedwin is this one still an issue or can it be combined with another ticket? Its 1yr old.

**Comment by SamIam4Hyma** [comment]
I've tested and confimed what the OP is saying still exists, lets close this ticket and I can create a new one with more details and test cases, as the information above and the title are not accurate to what the issue actually is @LukeFinch please close.
