### ISSUE TITLE
High Priority Vulnerabilities

### ISSUE THREAD

**Issue by SorsOps** [tokens-studio/figma-plugin#1691]
**Describe the bug**
The prod bundle we emit for the figma plugin only has 2 remaining high priority vulnerabilities. 

1. Prototype pollution arising from `set-value` https://github.com/advisories/GHSA-4jqc-8m5r-9rpr
2. ReDos vulnerability for `minimatch` https://github.com/advisories/GHSA-f8q6-p94x-37v3

Neither have any real impact to the security of the plugin, however they are affecting auditing reports. 

1 relies on a major version upgrade, https://github.com/tokens-studio/figma-plugin/actions/runs/4431195197 shows that this introduces a major regression

2. Seems more manageable, https://github.com/tokens-studio/figma-plugin/actions/runs/4431205127 shows that it does also cause a regression , but is localized for the cypress testing. 

We will likely need to get surgical with the package-lock.json and manually remediate these

**Comment by SorsOps** [comment]
The minimatch vulnerability should be solved in https://github.com/tokens-studio/figma-plugin/pull/1707

Set-value is much harder to resolve

**Comment by six7** [comment]
Fixed in 1.35.3
