### ISSUE TITLE
Process of duplicating token group to another token set is not so clear as expected

### ISSUE THREAD

**Issue by maxkdpos** [tokens-studio/figma-plugin#1693]
**Describe the bug**
When duplicating a token group from one token set to another it keeps the original path by default adding the destination path, separating them with comma in text field.

**To Reproduce**
1. Select any existing token set containing token groups like spacings or colors
2. Right-click on any token group like `button.style.warning` and choose Duplicate in the context menu
3. In Duplicate Group there is a dropdown control set to the current set path by default
4. Choosing another token set as the destination doesn't replace or remove the source path

**Expected behavior**
It was expected that when you duplicate a group to another token set there is only one copy will be created at the path you specified. Meaning the source path is excluded.

**Proposal**
1. Marking the selection of duplicate destination(s) in more obvious way like checking some boxes could improve the user experience. Displaying multiple paths as a simple text string separated with a comma is not so clear.
2. Or text field display could be improved by putting different paths to some containers like chips so it is more obvious and visible that they are different values.

**Comment by UdayHyma** [comment]
[Migrated to Featurebase](https://tokensstudio.featurebase.app/p/token-organization-enhancements)
