### ISSUE TITLE
TypeError: operand 'prototype' property is not an object

### ISSUE THREAD

**Issue by thecodingfrog** [tokens-studio/figma-plugin#1695]
Got that error when launching the plugin compiled on my own

**Comment by six7** [comment]
Can confirm, I've reverted the commit that caused this.

@SorsOps let's look into this on Monday and re-implement #1688

![image](https://user-images.githubusercontent.com/4548309/226164680-e4a28309-cb0d-43ec-8e36-f133b3a06a39.png)

**Comment by six7** [comment]
I'll close this issue as it's been fixed.
