### ISSUE TITLE
Importing library, using library styles but tokens not selected

### ISSUE THREAD

**Issue by bewarai** [tokens-studio/figma-plugin#1713]
Not sure this is a bug or it's just like that. We do not want to bother our designers with tokens and just give them styles. So we prepared a library with figma tokens, light and dark theme. So our designers are creating a new document, start a new flow and import the library and styles, no tokens. They made a bunch of light themes and did that with the styles of the library. Now we were thinking if one person opened all these flows, had tokens and just did a switch from light to dark theme we would feel awesome. But noppe. Since all our designers attached styles via the the library the tokens were not automatically attached so nothing worked. Is this normal? Can we only use styles created via figma tokens and do we need for each new doc to import local styles for it to work?

**Comment by six7** [comment]
Yeah you can just use the `Swap styles` feature, as described here: https://docs.tokens.studio/styles/swap-styles

**Comment by six7** [comment]
Yes, you'll need to attach your styles to the Theme and then enable `Swap styles` to be able to swap between themes (by using the Theme dropdown) by just using styles.

https://docs.tokens.studio/themes/themes-pro
https://docs.tokens.studio/styles/swap-styles

![Image](https://user-images.githubusercontent.com/4548309/227722048-f353c2bc-fa19-4f57-a608-1e2e7fdb99d6.png)

That way you can swap themes by only having styles applied, no tokens needed

**Comment by six7** [comment]
Have you made sure they're using `Swap styles`? It sounds like they're not.

![Image](https://user-images.githubusercontent.com/4548309/227722048-f353c2bc-fa19-4f57-a608-1e2e7fdb99d6.png)

**Comment by UdayHyma** [comment]
[MIgrated to Featurebase](https://tokensstudio.featurebase.app/p/non-local-support-of-variables)

**Comment by SamIam4Hyma** [comment]
Added to Featurebase Request-	[Tokens applied via styles and variables in the Figma UI are fragile](https://tokensstudio.featurebase.app/p/tokens-applied-as-variables-or-styles-are-fragile)
