### ISSUE TITLE
Composition Token Value Edit

### ISSUE THREAD

**Issue by robin-deriv** [tokens-studio/figma-plugin#1728]
**Describe the bug**
If we edit the composition token value, changes not affect in the selected component, we have to reselect the token again to see the changes.

**To Reproduce**
1. Go to 'any composition token that is already created'
2. Edit 'one token value in the composition token'
3. See the changes not reflect in the selected components.
4. To see the changes we have to reassign the composition token again by reselecting the token.

**Comment by six7** [comment]
I'm not able to reproduce, please provide a screen recording.

**Comment by robin-deriv** [comment]
> I'm not able to reproduce, please provide a screen recording.

@six7 I just checked it again, it is looks fixed and working now. The issue was if I edit any composition token value the component didn't change, i have to reapply token again to see the new changes. But now it is working fine. Thanks

**Comment by keeganedwin** [comment]
@six7 This issue still seems to be present, changed the borderWidth value from **1** to **4px**, and the radii from **2** to **4px**, the component did not update. Reapplying the token then updates the component:

https://github.com/tokens-studio/figma-plugin/assets/93133012/6e23e374-506e-47bf-b791-2697e10f4706

**Comment by six7** [comment]
> @six7 This issue still seems to be present, changed the borderWidth value from 1 to 4px, and the radii from 2 to 4px, the component did not update. Reapplying the token then updates the component:
tried hitting `Apply` again?

**Comment by keeganedwin** [comment]
I read the release notes and then saw your comment : )
