### ISSUE TITLE
Support for corner-smoothing property via `percentage` tokens

### ISSUE THREAD

**Issue by ratsuns** [tokens-studio/figma-plugin#1729]
I'd like to document iOS corner smoothing (anti-alias bezier smoothing) to a border-radius token value.

I'm not sure if there are any alternatives at the moment since the math to accomplish this is quite complex.

Here is a reference to a Figma article that lays out the math involved:
https://www.figma.com/blog/desperately-seeking-squircles/

**Comment by six7** [comment]
I think we could introduce `percentage` tokens which would allow users to set

- opacity
- corner smoothing

Adding the docs for corner-smoothing here: https://www.figma.com/plugin-docs/api/properties/nodes-cornersmoothing/ in case it will be relevant for development

**Comment by ratsuns** [comment]
Awesome and thank you Jan!

**Comment by LukeFinch** [comment]
This request has been moved to our new feedback tool. Go check out https://tokensstudio.featurebase.app/ to create a free account. You can upvote and comment on existing posts, make a new request, and subscribe to be notified when requests move into our roadmap.

**Comment by UdayHyma** [comment]
Added to Featurebase Roadmap : [🪙 Expand token types](https://tokensstudio.featurebase.app/p/expand-token-types)
