### ISSUE TITLE
Pattern On Color Token To Indicate Opacity

### ISSUE THREAD

**Issue by keeganedwin** [tokens-studio/figma-plugin#1730]
**Describe current behaviour**
Transparent token is _white_ with a transparent value
<img width="235" alt="Screenshot 2023-03-23 at 3 47 26 PM" src="https://user-images.githubusercontent.com/93133012/227173005-54dbc7bb-a0f9-4922-91f2-8cd841330541.png">

**Describe expected behaviour**
Show a _‘Photoshop’_ like pattern if the value of the token is _‘transparent'._

![image](https://user-images.githubusercontent.com/93133012/227160111-5152b5e5-d565-42a1-ac43-89a5de44aa89.png)

**Comment by six7** [comment]
I think that'd be a quick win, but I'd like to extend it by changing the way we display semi-opaque tokens. Let's do a half-half for tokens that are not fully transparent. Bottom left = Full color. Top right = Color with transparency laid on top of the checkered background

![Image](https://user-images.githubusercontent.com/4548309/227655334-2b43773a-08eb-4bbd-92bc-539cc344d65e.png)

**Comment by keeganedwin** [comment]
Closing as migrated to [Featurebase](https://tokensstudio.featurebase.app/p/token-organization-enhancements)

**Comment by keeganedwin** [comment]
Changing status to `Not Closed` as it's only migrated

**Comment by keeganedwin** [comment]
Changing status to Not Closed as it's only migrated

**Comment by keeganedwin** [comment]
Changing status to Not Closed as it's only migrated
