### ISSUE TITLE
Typography Input Mode doesn't pick up values in `value` mode

### ISSUE THREAD

**Issue by keeganedwin** [tokens-studio/figma-plugin#1731]
**Describe the bug**
When switching back to _input_ mode from _reference_ mode in the Typography type token, the input fields don't take on any values being _typed_ in 

https://user-images.githubusercontent.com/93133012/227164890-89b06ff0-c649-4e37-a105-667c39497577.mov

**Steps to reproduce the behaviour:**
1. Create or edit already created typography token in _reference_ mode and save
2. Edit token again, switch to _input_ mode and type in any of the fields - plugin doesn't register inputs

**Comment by swordEdge** [comment]
@six7 Already fixed in next.
