### ISSUE TITLE
When entering the `color token` field, `#` should already be present to make entering values easier

### ISSUE THREAD

**Issue by keeganedwin** [tokens-studio/figma-plugin#1732]
**Current function:**
User can't copy hex-value with # from Figma panel
User has to key in # and paste the copied hex value

https://user-images.githubusercontent.com/93133012/227167929-389308d6-4014-48e9-b8b3-965f09e5cf76.mov

**Expected function:**
When creating color token, input-field already has # present, users only have to past value

_If users are using other formats - hsl, rgba, reference - deleting the # is a simple step before pasting/typing in color reference_

https://user-images.githubusercontent.com/93133012/227169326-e710498d-f248-476c-8e94-712bcc9f9efb.mov

**Comment by six7** [comment]
>  When creating color token, input-field already has # present, users only have to past value

I like this solution, simple and a quick win!
