### ISSUE TITLE
Is there a way to bulk remap tokens by replacing patterns in token names?

### ISSUE THREAD

**Issue by ozgurgunes** [tokens-studio/figma-plugin#1733]
When I want to create new outline buttons, I'm duplicating the solid buttons and remapping all tokens by replacing the "solid" with "outline" one by one for every token. There are too much variants, sizes and states, so I need to remap hundreds of tokens.

My token names are like this:
```
color.button.solid.primary.idle.bg
font.button.solid.medium
space.button.solid.medium.padding
```

I want to bulk remap all buttons by replacing the `solid`s with `outline`s in token names for all types of tokens.

**Comment by six7** [comment]
Have you tried the `Buk remap` feature?

This works like that! You can add a `match` and a `remap` input.

![Image](https://user-images.githubusercontent.com/4548309/227654473-6e38ee57-7775-40f3-9ce0-6ae103409b5d.png)

![Image](https://user-images.githubusercontent.com/4548309/227654568-7b60e365-7d4f-4264-8988-2eefb3fca5f7.png)

Note this will apply to the selection

**Comment by ozgurgunes** [comment]
Man, I thought it needs complete token name and never tried. Sorry for bothering.

**Comment by six7** [comment]
I'll make sure we add a proper description to this modal there.
