### ISSUE TITLE
Typography tokens input-field order 

### ISSUE THREAD

**Issue by keeganedwin** [tokens-studio/figma-plugin#1734]
**Current Display**:
_Users find themselves clicking in the wrong field sometimes as they are used to a different order_

![image](https://user-images.githubusercontent.com/93133012/227225837-cc95234c-0bca-40a9-9457-999969e32392.png)

**Proposal 1 - Follow W3C Design Tokens standard**:

W3C Order: ✅  (lets go with this one)
1. fontFamily
2. fontSize
3. fontWeight
4. letterSpacing
5. lineHeight

**Proposal 2 (by user):**
1. fontFamily
2. fontSize
3. lineHeight
4. fontWeight

**Additional request:**
Tooltip displaying `typography tokens does not reflect the same order`

![Screenshot 2023-03-30 at 17 00 30](https://user-images.githubusercontent.com/93133012/229066435-67dd613f-2525-4300-9df0-a1a2fca2898f.png)

**Expected behavior:**
Tooltip `should reflect the order of tokens` the same as in the typography fields

**Comment by six7** [comment]
I'd propose

```
fontFamily
fontWeight
fontSize
lineHeight
...
```

This would follow what Figma has

**Comment by donludwig** [comment]
I agree to what someone else said in Slack: 

> "I've caught myself putting the font size at line height a few times."

I think it will definitely be helpful if we go for plain text (rather than a mix of symbols and text), but I'm not sure about the order yet.

For me, the following order sounds more reasonable:
- Font-Family
- Font-Size
- Line-Height
- Font-Weight
- ...

simply because I think most designers have to care more about size than font weight.

**Comment by keeganedwin** [comment]
**Additional request:**
Tooltip displaying `typography tokens does not reflect the same order`

![Screenshot 2023-03-30 at 17 00 30](https://user-images.githubusercontent.com/93133012/229066435-67dd613f-2525-4300-9df0-a1a2fca2898f.png)

**Expected behavior:**
Tooltip `should reflect the order of tokens` the same as in the typography fields

**Comment by victorjanin** [comment]
As a product designer, here is what I would consider important regarding the order. 

`line-height` follows `font-size` --> I can only set a proper line height after I have selected a font-size. Also if you have a look at CSS, in the font shorthand it's `font-size/line-height`

`font-weight` follows `font-family`--> Here is where I think W3C order is wrong. A font is a file, and so when I choose a font, I'm choosing a `font-family` and a `weight`. Also, not all font-families have all weights available, so weight is heavily dependent on the font-family.

As @six7 suggested, I think this makes the most sense 

```
fontFamily
fontWeight
fontSize
lineHeight
...
```
