### ISSUE TITLE
textAlign tokens

### ISSUE THREAD

**Issue by keeganedwin** [tokens-studio/figma-plugin#1735]
**Request:**
Support for text-align tokens - to be able to manipulate text alignment:

left text-align
center text-align
right text-align, and text-align: justify - which is the same found in Figma.

**Key Information**:
These tokens are not specified as part of the W3C Design Token Format Module

**Comment by six7** [comment]
We have an issue for fontStyle. Can you rename this to be about text align?

Also, can you describe what you'd like to see in it?

**Comment by straef** [comment]
+1
being able to specify alignment horizontally (text: align-left, align-center, align-right, and align-justified) and vertically (align-top, align-middle, and align-bottom) would be nice to have.

**Comment by six7** [comment]
> probable duplicate of #1138 
> 
> +1
> 
> being able to specify alignment horizontally (text: align-left, align-center, align-right, and align-justified) and vertically (align-top, align-middle, and align-bottom) would be nice to have.

Thanks, agree lets close this in favor of #1138
