### ISSUE TITLE
Rearrange token groups within the plugin

### ISSUE THREAD

**Issue by keeganedwin** [tokens-studio/figma-plugin#1741]
**Current Behaviour:**
Users can only change the order of token groups in a code-editor

**Request:**
To rearrange, users can click and drag groups

<img width="424" alt="Screenshot 2023-03-24 at 3 17 54 PM" src="https://user-images.githubusercontent.com/93133012/227487112-8821581b-0580-4b0c-8f8e-bc21901e11f1.png">

[Slack Message 1](https://tokens-studio.slack.com/archives/C02JAL48UDN/p1677808683797519)
[Slack Message 2](https://tokens-studio.slack.com/archives/C02JAL48UDN/p1677596135849889)

**Comment by LukeFinch** [comment]
This request has been moved to our new feedback tool. Go check out https://tokensstudio.featurebase.app/ to create a free account. You can upvote and comment on existing posts, make a new request, and subscribe to be notified when requests move into our roadmap.

**Comment by UdayHyma** [comment]
Added to Featurebase Roadmap : [🪙 Token organization enhancements
](https://tokensstudio.featurebase.app/p/token-organization-enhancements)
