### ISSUE TITLE
[token-transformer] Document --theme option in README

### ISSUE THREAD

**Issue by RobbyUitbeijerse** [tokens-studio/figma-plugin#1743]
Hey there! We currently have a tokens studio set-up with multiple themes, and generate split-up JSON files in our repository. Previously, this was all written into a single file - but since we started implementing theming we decided to split-up the token source files. You can see our current set-up here:

<img width="1027" alt="Screenshot 2023-03-24 at 13 56 48" src="https://user-images.githubusercontent.com/10176709/227529165-2c54e430-07ac-421f-ba9b-265ecccb2911.png">

The problem we are facing: `token-transformer` doesn't seem to be able to handle a file structure like this, even though the $themes.json contains all the information needed to generate an output.

if we use the following:

`"generate:token-transform": "npx token-transformer src/themes/$themes.json output.json"`

We are left with a single output file, which is not useful for us.

**Describe the solution you'd like**
It would be helpful if token-transformer is able to generate multiple output files based on a $themes input file with multiple defined themes, as we want to compile each output file into a separated css variables file through style dictionary.

**Describe alternatives you've considered**
Currently I've programmatically resolved this solution by creating a custom script as seen below. It loops over the $themes.json, creates a token object in memory for each of the themes as defined in $themes.json, and creates an output file based on the name property of each theme, and the token sets provided in the `selectedTokenSets` .

Let us know if there's a better way! The documentation of `token-transformer` doesn't seem to suggest a solution for this use case specifically. Here's the entire script we now use to reach our goal:

```
import { transformTokens } from 'token-transformer';

import themes from './src/themes/$themes.json' assert { type: 'json' };

import fs from 'fs';

/**
 * Create the dist  directory
 */

fs.mkdir('./dist', null, () => null);

/**
 * Write a directory if it doesn't already exist
 */

for await (const theme of themes) {
  fs.mkdir(`./dist/${theme.name}`, { recursive: true }, () => null);

  /** Get all the partials that aren't disabled */
  const partials = Object.entries(theme.selectedTokenSets)
    .filter((key, value) => value !== 'disabled')
    .map(([key]) => key);

  /** load all the partial jsons and put them in a single object */
  let source = {};
  for await (const partial of partials) {
    const { default: loaded } = await import(`./src/themes/${partial}.json`, {
      assert: { type: 'json' },
    });

    source = { ...source, [partial]: loaded };
  }

  /** Use the combined object to generate tokens */
  const tokens = transformTokens(source, [], [], {
    expandTypography: false,
    expandShadow: false,
    expandComposition: false,
    preserveRawValue: false,
    throwErrorWhenNotResolved: true,
    resolveReferences: true,
  });

  /** Write the output json in the dist directory for style dictionary to pick up */
  fs.writeFile(`./dist/${theme.name}/design-tokens.json`, JSON.stringify(tokens), err => {
    if (err) throw err;
  });
}

```

**Comment by six7** [comment]
There is a feature on token-transformer that allows it to read a `$themes.json` (or $themes key in a single file environment), and generate the theme files one by one.

```
npx token-transformer tokens --theme --themeOutputPath output
```

Let me know if that helps

**Comment by RobbyUitbeijerse** [comment]
Hey @six7! That's really helpful, works like a charm. Seems rather hidden, I was using `token-transformer` based on what I read on the README. Can I help out with documenting it?

**Comment by six7** [comment]
Oh sure, if you'd like to - go ahead! 🙏
