### ISSUE TITLE
Store "treat as source" as a flag in JSON file.

### ISSUE THREAD

**Issue by txcrew** [tokens-studio/figma-plugin#1744]
I have tokens distributed with URL sync provider. When applied, the tokens sync properly in a read-only state.

As a token studio user, the expectation is that I can treat a token set as a source prior to creating styles from tokens. However with URL sync provider applied, the read-only state prevents the me from doing that.

It'd be ideal to store `treat as source` as a flag in the JSON file. This would be one less step for a read-only tokens user to consider.

Alternatively, permit the user set to source in read-only state.

**Comment by six7** [comment]
There should be a `$metadata` key in your JSON where the token sets that are set to source are marked with a `SOURCE` parameter. Is that not the case with you? If not, can you share your JSON?

**Comment by txcrew** [comment]
That's where I thought it'd be. `global` is marked as `source` in the UI but not in the JSON.
```
 "$themes": [],
  "$metadata": {
    "tokenSetOrder": [
      "global",
      "sys",
      "sys-dk",
      "ios",
      "android",
      "web"
    ]
```

**Comment by six7** [comment]
Ah, i see. You're not using the Themes feature then.

We currently let you store this information what sets are activated in Themes, we dont have support to read the 'last activated sets' otherwise.

https://docs.tokens.studio/themes/themes-pro

**Comment by txcrew** [comment]
ah yep. That's what I was missing. Thank you so much!
