### ISSUE TITLE
Forbid `{` or `}` characters in token names, forbid `$` at the beginning

### ISSUE THREAD

**Issue by six7** [tokens-studio/figma-plugin#1747]
The W3C draft [specifies](https://tr.designtokens.org/format/#character-restrictions) that token names must not begin with `$` characters. Let's introduce this rule.

It also states that `{` or `}` characters are not to be used at all in token names.

Let's add a validation that users cannot save their tokens with these characters in name, or `$` at the beginning.

**Comment by keeganedwin** [comment]
@six7 can we look into more of these cases? 
A user recently used **Value** as a part of their token name `progress-bar.value.typography` (the json uses this to define the value of a token) and this resulted in the plugin to creating this token in the `Other` type after pushing and pulling from their repo. 

Also created a ticket for displaying error messages when users are trying to use these names and or characters:

**Comment by six7** [comment]
Will be part of 2.0

**Comment by SamIam4Hyma** [comment]
Do we have it documented somewhere what error messages come up and what causes them? Could be nice/helpful to link to the new doc I wrote on naming tips based on technical specs which includes these items, the "value" or other token properties in the name, as well as the "flattening" issue to be aware of that @jorenbroekema raised to us.

**Comment by SamIam4Hyma** [comment]
Added to Featurebase Roadmap-	[❇️ W3C - DTCG Specification Alignment](https://tokensstudio.featurebase.app/p/w3c-dtcg-specification-alignment)

**Comment by SamIam4Hyma** [comment]
Added to Featurebase Roadmap-	[❇️ W3C - DTCG Specification Alignment](https://tokensstudio.featurebase.app/p/w3c-dtcg-specification-alignment)
