### ISSUE TITLE
Introduce `transition` token type

### ISSUE THREAD

**Issue by six7** [tokens-studio/figma-plugin#1748]
The DTCG Format specifies that there's a `transition` token type.

https://tr.designtokens.org/format/#transition

```
{
  "transition": {
    "emphasis": {
      "$type": "transition",
      "$value": {
        "duration": "200ms", (must be a reference to a duration token or a duration value)
        "delay": "0ms", (must be a reference to a duration token or a duration value)
        "timingFunction": [0.5, 0, 1, 1] (must be a reference to a cubicBezier token or a cubicBezier value)
      }
    }
  }
}
```

### Application
Users can apply this to a prototype node, similar to `cubicBezier` or `duration` token. This would effectively be a composite token of those other tokens.

Applying this token would influence the `node.reactions[].action` property of all reactions. If there is no reaction on a layer, don't do anything.

Links to Figma API:
https://www.figma.com/plugin-docs/api/Reaction
https://www.figma.com/plugin-docs/api/FrameNode#reaction-prototyping-related-properties
https://www.figma.com/plugin-docs/api/Transition

**Comment by LukeFinch** [comment]
This request has been moved to our new feedback tool. Go check out https://tokensstudio.featurebase.app/ to create a free account. You can upvote and comment on existing posts, make a new request, and subscribe to be notified when requests move into our roadmap.

**Comment by UdayHyma** [comment]
Added to Featurebase Roadmap : [🪙 Expand token types](https://tokensstudio.featurebase.app/p/expand-token-types)
