### ISSUE TITLE
[Performance]: Improve performance of resolveTokenValues function

### ISSUE THREAD

**Issue by six7** [tokens-studio/figma-plugin#1755]
When we're resolving token values based on the currently active sets in order for us to display the right swatches for each token, we currently use the `resolveTokenValues` function to do so. Code for it is here: https://github.com/tokens-studio/figma-plugin/blob/1af88513722baa15722dc59a5a1a6ff1247b1288/src/plugin/tokenHelpers.ts#L22

We call this function in `Tokens.tsx` when we're resolving all so e.g. the color swatches get the right values displayed.

https://github.com/tokens-studio/figma-plugin/blob/1af88513722baa15722dc59a5a1a6ff1247b1288/src/app/components/Tokens.tsx#L120-L126

This is currently a blocking function, meaning users sometimes wait up to 5 seconds for a token set to appear after they've clicked!

Obviously, this is inefficient.

Let's find ways how we can
- improve that function
- find a different way where that resolver is non-blocking. It is only to display the values after all, we already know what tokens there are in this token set.

## What references need to be resolved?
- any reference that is mentioned in any of the keys. Currently we only look in the `value` key, but we should extend that so users can define references inside any other key (e.g. description)
- a reference that points to a token like `{token.name}` should returns its value
- however, users can also deep-reference tokens for typography, boxshadow or border tokens (composite). That means i can reference the `fontFamily` key of a `typography` token: `{typographytoken.fontFamily}`
- a reference should be able to reference another token by itself, e.g. a `boxshadow` token referencing another boxshadow token (which can be a composite token)

**Comment by LukeFinch** [comment]
This is the mock used in the flame graph: 

https://github.com/tokens-studio/figma-plugin/pull/2080/files#diff-2c1188a07cde817c65615ba7de9772d507d965963cb70deeafdb04f72924b6bb
