### ISSUE TITLE
`border` tokens called the same name as a color style mistakenly apply that color style instead of the raw hex value

### ISSUE THREAD

**Issue by six7** [tokens-studio/figma-plugin#1758]
This happened after we the recent change to `border` tokens.

It seems if a border token is named the same as a color token that has a style created (with the same name), we seem to apply that color style, even though it's using a raw hex value as the style.

To reproduce:
- Create a new color token called `red`
- Hit Create Styles so the color style is created
- Create a new set
- Create a border token called `red` in that new set using `#ff0000` as a color value, `12px` as width and `solid as style
- Apply that border token

Notice that we apply the color style. This did not happen on prior versions of the plugin.

I don't expect that a lot of users will hit this, given the naming has to match between color tokens and border tokens (which I'd say is usually a no-go), but nevertheless this shouldn't happen.

**Comment by keeganedwin** [comment]
Also when applying the border-token, (as you mentioned) unlike the color tokens, it only displays the `hex value` and not the `style` (also) connected to the token. Would it not make sense to add that? Or do we want to have it only display the hex value?

**Comment by six7** [comment]
could you create a new issue for this? that's a separate topic, but one we should fix 👍

**Comment by rbosker** [comment]
the created issue for the issue in the comments: https://github.com/tokens-studio/figma-plugin/issues/1792

**Comment by keeganedwin** [comment]
Closing this bug as it is no longer reproducible after testing it on Prod - 1.38.9 and Beta V2-rc5.
