### ISSUE TITLE
Typography input-field Tooltip direction

### ISSUE THREAD

**Issue by keeganedwin** [tokens-studio/figma-plugin#1759]
**Describe the issue:**
The tooltip that pops-up in the input-fields of the typography token type blocks users from viewing the value
![Screenshot 2023-03-27 at 15 14 26](https://user-images.githubusercontent.com/93133012/228003754-79c707c1-851f-49a5-b804-e6ee05ec4727.png)

**Suggestion:**
Place the tooltip above the the property icons/text to have a visible input-field
<img width="685" alt="Screenshot 2023-03-27 at 9 52 54 PM" src="https://user-images.githubusercontent.com/93133012/228004121-0a6ebb25-228e-4c1f-b469-0ea5e92bfe1d.png">

**Comment by six7** [comment]
Fixed in 1.38 🚢
