### ISSUE TITLE
Colors manipulation with 'color modifier' - shown color in preview is not the same result as after token transformation

### ISSUE THREAD

**Issue by tada-seilebri** [tokens-studio/figma-plugin#1762]
**Describe the bug**
not consistent outcome of an Color modifier --> The shown color in the Figma Token Studio Plugin preview is not the same as in the JSON output after token transformation.
Also mention in Slack: https://tokens-studio.slack.com/archives/C02DLQXNY6Q/p1678277833220099

**To Reproduce**
1. Go to 'Token Studio for Figma Plugin'.
2. Create a color token with #d3d7db (e.g. name it standard.grey.light-mode.500)
3. Create a 2nd color token reference 'standard.grey.light-mode.500' and apply a color modifier with lighten(0.9) with the method 'lch' (e.g. name it standard.grey.light-mode.50)
4. check 'standard.grey.light-mode.50' in the preview of the Token Studio Plugin for Figma (in my case it was #fbfbfb)
5. run token transformation (version token-transformer@0.0.30)
6. check the color asigned to standard.grey.light-mode.50 in the output file (in my case it has been '#fff')

**Expected behavior**
I expect that the color of standard.grey.light-mode.50 in the preview of the Token Studio Plugin for Figma and in the output of token-transformer is the same

**Screenshots or Screencasts**
preview in the the Token Studio Plugin for Figma 
![image](https://user-images.githubusercontent.com/125663070/228265557-e4bb6976-611c-4de3-a829-005467cce4a5.png)

outcome after token transformation
![image](https://user-images.githubusercontent.com/125663070/228265360-5ce1afb7-386b-466d-a5d4-833a218ddfba.png)

**Comment by six7** [comment]
This was fixed in version 32
