### ISSUE TITLE
Annotation for color-modifiers

### ISSUE THREAD

**Issue by keeganedwin** [tokens-studio/figma-plugin#1765]
**Describe issue:**
Currently when annotating color-modifiers, the convention used to represent this is _fill_
<img width="1088" alt="Screenshot 2023-03-29 at 1 23 50 PM" src="https://user-images.githubusercontent.com/93133012/228465275-43cc0853-d325-4119-9a6f-a35bc2b960c8.png">

Proposals:
Since the annotation displays only the alias of the token, the convention used can be one of the following:
<img width="1150" alt="Screenshot 2023-03-29 at 1 28 15 PM" src="https://user-images.githubusercontent.com/93133012/228466128-4d03ae28-bf57-4933-9c4f-e06f28a83ffe.png">

**Comment by six7** [comment]
Can you expand on that one? I'm not sure what `fillModify` does yet or where a user would pick this or what the intended outcome is

**Comment by LukeFinch** [comment]
This request has been moved to our new feedback tool. Go check out https://tokensstudio.featurebase.app/ to create a free account. You can upvote and comment on existing posts, make a new request, and subscribe to be notified when requests move into our roadmap.
