### ISSUE TITLE
Allow to merge in main branch while pulling

### ISSUE THREAD

**Issue by keeganedwin** [tokens-studio/figma-plugin#1766]
**Describe the issue:**
Currently we only pull from the branch that a user is in, but we don't provide a way to merge in the main branch.

**Proposal:**
Hold down _⌘Cmd_ and click on Pull from Git to pull main branch into existing one.

## Open questions
- How do we deal with merge conflicts?
- Are we able to fetch the main branch name from all git clients? (It's not always `master` or `main`)

<img width="158" alt="Screenshot 2023-03-29 at 1 35 41 PM" src="https://user-images.githubusercontent.com/93133012/228468022-410aa63f-76af-4d53-a3c9-2340881c0e0d.png">

**Comment by mikejyoung** [comment]
It would be great to have the ability to merge a branch into the active one. 

Right now, it's a cumbersome process to merge Figma branches. Our designers create separate token branches for each Figma branch, but the only "safe" was I've found to merge the tokens is manually. 

Some ideas for consideration:

- I think this action should be limited to tokens, no themes or any other configurations
- On merge, I think it should only import missing or change existing tokens, not delete ones not present in the source branch
- Visually you are kept in the same branch, but the merge should probably only happen locally (you can then push to update the remote branch of the branch you're in)
- The same modal planned in #1609 would be very helpful
- I would suggest adding this as an action in the branch menu

<img width="167" alt="Screenshot 2023-04-02 at 9 31 43 AM" src="https://user-images.githubusercontent.com/75724470/229341667-830cff52-cc6a-4d7e-8c7d-1a50989828a9.png">

Long-term, some way to merge pull requests within Token Studio would be great (is possible)

**Comment by LukeFinch** [comment]
This request has been moved to our new feedback tool. Go check out https://tokensstudio.featurebase.app/ to create a free account. You can upvote and comment on existing posts, make a new request, and subscribe to be notified when requests move into our roadmap.

**Comment by UdayHyma** [comment]
Added to Featurebase Roadmap : [↕️ Git sync enhancements - push, pull, merge, branching](https://tokensstudio.featurebase.app/p/git-sync-enhancements)
