### ISSUE TITLE
Selection and Deselection of Groups of Tokens in Inspect Tab

### ISSUE THREAD

**Issue by keeganedwin** [tokens-studio/figma-plugin#1767]
**Describe the issue:**
users can only select and deselect all token groups in inspect
<img width="341" alt="Screenshot 2023-03-29 at 1 43 09 PM" src="https://user-images.githubusercontent.com/93133012/228469884-794ce1ac-42b0-4fac-9f5f-7b7ef5107ac0.png">

**Proposed solution:**
Each token group has the checkbox option of selecting and deselecting
![image (1)](https://user-images.githubusercontent.com/93133012/228470285-3a7811d1-4adb-4a10-90a4-3d30df194900.png)

**Comment by six7** [comment]
Can you move the checkbox in front of the title? the we should be good to go. Also provide a `indeterminate` state as in only some items are selected.

**Comment by keeganedwin** [comment]
Closing as migrated to [Featurebase](https://tokensstudio.featurebase.app/p/name-enhancements-for-tokens-and-groups)

**Comment by keeganedwin** [comment]
Changing status to `Not Close` as it's only migrated
