### ISSUE TITLE
Figma style for Dimension background-blur token

### ISSUE THREAD

**Issue by keeganedwin** [tokens-studio/figma-plugin#1771]
**Describe the issue:**
users can apply the dimension background-blur token but can't create a style in Figma, hence not having the token and style linked
<img width="386" alt="Screenshot 2023-03-30 at 3 32 12 PM" src="https://user-images.githubusercontent.com/93133012/228801751-8e5ab58d-0530-49ef-a652-e0ed556676c0.png">

**Comment by six7** [comment]
Wondering how we should make it possible without introducing a custom type 🤔

**Comment by LukeFinch** [comment]
This request has been moved to our new feedback tool. Go check out https://tokensstudio.featurebase.app/ to create a free account. You can upvote and comment on existing posts, make a new request, and subscribe to be notified when requests move into our roadmap.

**Comment by UdayHyma** [comment]
Here's the URL to the featurebase post that is linked to this ticket:https://tokensstudio.featurebase.app/p/enhanced-functionality-for-boxshadow-tokens-greater-effects-in-figma
