### ISSUE TITLE
Allow uploading a standard color palette scheme json

### ISSUE THREAD

**Issue by yarinsa** [tokens-studio/figma-plugin#1773]
**Is your feature request related to a problem? Please describe.**
It's annoying to change the whole pallet as the base brand color affects everything. 
The required input of DesignTokensStudio is 
```
 "gray": {
      "50": {
        "value": "#F7FAFC",
        "type": "color"
      },
      "100": {
        "value": "#EDF2F7",
        "type": "color"
      },
    // more shades...
    },
```
While most generators export JSON like this
```
    "gray": {
        "50": "#f9fafa",
        "100": "#f1f1f2",
        "200": "#e6e7e9",
        "300": "#d2d4d7",
        "400": "#a9adb2",
        "500": "#797f88",
        "600": "#4d5560",
        "700": "#2e3744",
        "800": "#19202b",
        "900": "#141a23"
    },
```

**Describe the solution you'd like**
Would be nice to have a built in feature that accept the colors json as exported from scheme generator, and it will update the relevant.
Other option is to accept "brand color" and "tint color" and generate it on your own.
https://palette.saas-ui.dev

**Describe alternatives you've considered**
 - Map my self
 - use ChatGPT to map this

**Additional context**
I am a developer working on the DesignOps so I can open a bug here or find creative solutions. Designers can't. We don't want something like this to be a blocker in our workflow.

**Comment by six7** [comment]
I'd say a "standard" would rather be closer to https://tr.designtokens.org/ instead of a json that doesn't include any types?

However, I totally understand that request - I think we could have something like an import that would detect any values and let you pass in the type of the tokens that you're entering here.

**Comment by yarinsa** [comment]
> I'd say a "standard" would rather be closer to https://tr.designtokens.org/ instead of a json that doesn't include any types?
> 
> However, I totally understand that request - I think we could have something like an import that would detect any values and let you pass in the type of the tokens that you're entering here.

That's a great answer :) Thanks

**Comment by LukeFinch** [comment]
This request has been moved to our new feedback tool. Go check out https://tokensstudio.featurebase.app/ to create a free account. You can upvote and comment on existing posts, make a new request, and subscribe to be notified when requests move into our roadmap.

**Comment by UdayHyma** [comment]
Added to Featurebase Roadmap : [🎨🧑‍💻 JSON enhancements for color tokens
](https://tokensstudio.featurebase.app/p/json-enhancements-for-color-tokens)
