### ISSUE TITLE
Wrong color value after running the transformer command

### ISSUE THREAD

**Issue by Ahmad-Fahmi** [tokens-studio/figma-plugin#1775]
Hello Jan, the issue is happening only after running the "npm run transform" command, although everything is working fine on figma.
I run the command line but the output shows wrong hex values
**To Reproduce**
1. Go to 'VS code'
2. Check the token reference which is: `"billboard": {
        "text-overline": {
          "value": "{color.primary.30}",
          "type": "color",
          "description": "Color of billboard overline text"
        }`
        
 {color.primary.30} value is: **#7c92dd**
        
3. Run  % npm run transform
4. Check the output of the same token in "_tokens-variables.scss" file
5. The token shows different value: --color-billboard-text-overline: #3051bb;

**Expected behavior**
Final variable value should be #7c92dd not #3051bb

**Comment by Ahmad-Fahmi** [comment]
Further clarifications: This issue happens only when color token is manipulated by the new modify option, so the problem solved after rolling back to give tokens normal Hex values

**Comment by SamIam4Hyma** [comment]
closing this issue until there is new information as I can not replicate.
