### ISSUE TITLE
Annotation produced out of frame

### ISSUE THREAD

**Issue by keeganedwin** [tokens-studio/figma-plugin#1776]
**Describe the bug:**
On creating an annotation for components within _groups_, the annotation card is created out of frame
<img width="1450" alt="Screenshot 2023-03-31 at 1 30 16 PM" src="https://user-images.githubusercontent.com/93133012/229061226-5f655170-b6ae-4311-b587-ccdead383b25.png">

**Expected behaviour:**
Annotation should be created right next to the selected component as within _frames_ and _auto-layout_
<img width="549" alt="Screenshot 2023-03-31 at 1 31 08 PM" src="https://user-images.githubusercontent.com/93133012/229061421-f12efa09-f9ae-4711-9651-9ae14c1483d1.png">

**Comment by LukeFinch** [comment]
This request has been moved to our new feedback tool. Go check out https://tokensstudio.featurebase.app/ to create a free account. You can upvote and comment on existing posts, make a new request, and subscribe to be notified when requests move into our roadmap.

**Comment by UdayHyma** [comment]
Added to Featurebase Roadmap : [🤓 Document and annotate design token enhancements
](https://tokensstudio.featurebase.app/p/documentation-and-annotate)
