### ISSUE TITLE
Not able to delete or edit tokens in custom types

### ISSUE THREAD

**Issue by keeganedwin** [tokens-studio/figma-plugin#1777]
**Describe the bug**
Not able to `delete or edit tokens in custom type token`

![image](https://user-images.githubusercontent.com/93133012/228830337-7c94572d-ee24-40c2-9ca7-8ba9dfb5bac1.png)

**Expected behaviour:**
Should be able to `delete or edit tokens in custom type token`

**Comment by six7** [comment]
To reproduce: Change the `type` value in JSON to something else that the plugin doesnt have as a native type, e.g. `type: 'something'`

**Comment by esthercheran** [comment]
No longer able to reproduce this issue @keeganedwin
