### ISSUE TITLE
Theme name accesible in Figma

### ISSUE THREAD

**Issue by tada-seilebri** [tokens-studio/figma-plugin#1778]
**Is your feature request related to a problem? Please describe.**
We will use Token Studio to design 50+ customer brands with Figma (to change colors, typography, shadows, rating and padding based on theme). It's very likely that we'll lose track of which theming we're looking at.

**Describe the solution you'd like**
In order not to lose track of which theme I'm looking at, it would be great if I could use the TokenStudio theme name as a text value in the figma. This changes depending on which theme is currently active. (e.g. provide the theme name automatically as a token)
![image](https://user-images.githubusercontent.com/125663070/229082340-b0f3aa6a-5899-4083-b440-4590b4169146.png)

**Describe alternatives you've considered**
Current workaround is that  we added manually an additional token which holds the value
`"extensions": {
    "theming": {
      "figma-only": {
        "theme-name": {
          "value": "FNN",
          "type": "other"
        }
      }
    }`
This solution works, but is error prone in case a theme is duplicated and we forget to adapt the token.

**Comment by six7** [comment]
Have you tried to create a token that contains the actual theme name, and then insert that with `Documentation tokens -> Value` ? This would do what you're after! It just requires the creation of a token that holds the theme name value.

Not ideal, and I think we should find a way to have this more natively, but it would solve it for you for now.

**Comment by LukeFinch** [comment]
This request has been moved to our new feedback tool. Go check out https://tokensstudio.featurebase.app/ to create a free account. You can upvote and comment on existing posts, make a new request, and subscribe to be notified when requests move into our roadmap.

**Comment by UdayHyma** [comment]
Added to Featurebase Roadmap : [🤓 Document and annotate design token enhancements
](https://tokensstudio.featurebase.app/p/documentation-and-annotate)
