### ISSUE TITLE
Swapping a component keeps tokens of the previous component

### ISSUE THREAD

**Issue by surfinzap** [tokens-studio/figma-plugin#1779]
**Describe the bug**
I'm using [Swap components and instances](https://help.figma.com/hc/en-us/articles/360039150413-Swap-components-and-instances) Figma functionality. When I swap a placeholder component with another one and reapply tokens, the Tokens Studio will apply some of the tokens from the previous placeholder component. Let me share detailed steps to reproduce:

I have a Placeholder component with defined background and border (violet shades, instancePlaceholder... tokens):
![image](https://user-images.githubusercontent.com/1387798/229093238-0e73d427-989a-4dd3-a05b-c694e5d9bc0d.png)

I have a component that uses Swappable Instance. This instance Swapping is set for Placeholder Component:
![image](https://user-images.githubusercontent.com/1387798/229093525-c9639473-b1c9-4e0a-802b-a88d37d01c32.png)

I have a component with custom content, having a blue border and gray background (widget... tokens):
![image](https://user-images.githubusercontent.com/1387798/229093899-4d69e369-6903-423b-993f-83ac1053976f.png)

Now I create an instance of the component with swappable content and swap the placeholder with custom content. This is what the result looks like. A "custom content component" that should only show "widget..." tokens. It also remembers "border" token "instancePlaceholder..." from the previous component. Also, for some reason, the border attribute is labeled as "border" for placeholder and "borderColor" for custom content, even though I applied border in the same way (right-clicking on the token and selecting border):
![image](https://user-images.githubusercontent.com/1387798/229095459-1d282750-bc87-42db-b604-8b73a05a382b.png)

Now, I'll re-apply tokens to an instance of the component with a swappable instance...
![image](https://user-images.githubusercontent.com/1387798/229097150-c4afd49b-5104-410e-8497-dc83190172c5.png)

The custom component gets a violet border, and the information about the widget token is lost:
![image](https://user-images.githubusercontent.com/1387798/229097311-a85cb36f-9957-4bb0-8e2f-599845bbed80.png)

**Expected behavior**
My expectation would be that swapped custom content component would keep its styles, e.g. blue border

**Comment by six7** [comment]
Unfortunately Figma doesn't provide an event to listen for this "component swap" change. I told this to Figma several months back.

An alternative that I think we should pursue could be that we implement some kind of polling when the selection is only 1 layer. This should be almost instant, and we could do it once every 5 seconds or so. That way, we wouldn't necessarily block the user from interacting with the document, and we'd get somewhat accurate results.

**Comment by SamIam4Hyma** [comment]
Migrated to featurebase
