### ISSUE TITLE
Problems with sets editing

### ISSUE THREAD

**Issue by thecodingfrog** [tokens-studio/figma-plugin#1786]
**Describe the bug**
I'm working on multicharte tokens, each company entity has his own colors but common text tokens.
So each one has a set with the same color definitions.
FileA is using ThemeA with ColorA set enabled + TextCommon set enabled
FileB is using ThemeB with ColorB set enabled + TexCommon set enabled
When I open Design Tokens plugin while editing the FileB, I see : 
- Selected set (the one selected by default) is on set ColorA, and this set is disabled (OK)
- Set ColorB is enabled (OK)
- Set TextCommon is enabled (OK)
- Tokens shown are the ones from ColorB not from the selected set

Problem : when you edit the tokens, you think editing the ones from ColorB but the selected token is the disabled ColorA set.
When you change one the token, you think it changes the one you see and in fact you change the one from the disabled set.
Maybe it's missing the set name in top of the token list to avoid making mistakes, it would be the easier solution.
Another solution would be to make the rendering different when you select a disabled set to show users they are not editing the enabled set

**Comment by six7** [comment]
I think this will be solved by #1586 where we want to better surface tokens that are being overwritten. Thanks for raising this!

**Comment by UdayHyma** [comment]
[Migrated to Featurebase ](https://tokensstudio.featurebase.app/p/typography-styles-with-variables)
