### ISSUE TITLE
Token-transformer readme wrong command - npx instead of node

### ISSUE THREAD

**Issue by paula-roesler** [tokens-studio/figma-plugin#1787]
Moin!

I'm working on a Next.js project, using Figma, Figma Tokens Studio, Style-Dictionary and token-transformer.
I couldn't get token-transformer running, bc `node token-transformer tokens.json output.json` didn't work for me. 

Error message says : "Error: Cannot find module ... token-transformer"

`npx token-transformer tokens.json output.json` works fine.

Since I'm new to development (coming from design) I couldn't figure it out by myself, but gladly found another tutorial, where `npx` was used instead of `node.`

https://garden.mirahi.io/how-to-use-the-color-tokens-from-your-design-system-directly-in-tailwind-css/

**Comment by six7** [comment]
So `npx` is a way in node to run packages without first installing them locally, `node` means that you'd run the command using existing installed node libraries. So if there's `token-transformer` installed globally, it will be able to use it.

I think we could add both commands to the readme for clearer instructions to non-developers. 👍

**Comment by paula-roesler** [comment]
Thank you very much for the explanation!! Was trying to get on track with that.
Probably I messed up while installing token-transformer... 😅

**Comment by SamIam4Hyma** [comment]
@jorenbroekema if this is still an issue please tag as needed, if not please close (:

**Comment by jorenbroekema** [comment]
As token-transformer is deprecated, let's close this
