### ISSUE TITLE
Typography alias links persist after un-linking through the Edit Tokens dialog

### ISSUE THREAD

**Issue by atlas-ui** [tokens-studio/figma-plugin#1789]
**Describe the bug**
When I alias link a typography token (the non expanded composite token), I am unable to revert to an un-aliased token.  The GUI allows me to disconnect the alias, but won't let me type anything in the property fields.  When I save with the alias disconnected and return to edit the token, it reverts to being aliased.

**To Reproduce**
1. Create a typography token (Token A) & fill in all properties sans the paragraph spacing property.
2. Create another unique typography token (Token B).
3. Use the alias link button in the GUI to link it to token A.
4. Save Token B.
5. Edit Token B and detach the alias using the unlink button in the GUI.
6. Attempt to fill in the property fields.
7. Save and re-edit Token B.

**Expected behavior**
User should be able to detach an aliased typography token and edit property fields.  Detaching an alias should remain detached after saving and closing the edit tokens dialog.

**Screenshots or Screencasts**
[Screen recording](https://drive.google.com/file/d/17A5WoVZH0pDIYJetJZSsJ3whUmvyOGx1/view?usp=sharing)

**Comment by six7** [comment]
So I think we should do 2 things here:

1) When you detach a token that was using a reference, fill in the values with what the token had
2) Allow editing after you detached

Thanks for raising this!
