### ISSUE TITLE
Border-token color not linking to style

### ISSUE THREAD

**Issue by keeganedwin** [tokens-studio/figma-plugin#1792]
**Describe the issue:**
When applying the `border-token`, unlike the color tokens, it only displays the `hex value` and not the `style` connected to the token. 

**Proposal:**
When applying the border-token, the color applied should have the token/style linked; and displayed in the right panel. 

https://user-images.githubusercontent.com/93133012/230371304-a5bcdea6-fd55-45e3-92cd-52d36cff419d.mov

Is this related to #1855 ?

**Comment by theikid** [comment]
Hi there. Any ETA on when this will be fix ? Just subscribe to pro to be able to use styles across multiple files and the fact that border style can't be use is really a miss.

**Comment by esthercheran** [comment]
Hi @theikid this should be fixed by next week, thank you for your patience :)
