### ISSUE TITLE
Ability to add letter-spacing token in rem units 

### ISSUE THREAD

**Issue by keeganedwin** [tokens-studio/figma-plugin#1794]
**Describe the issue:**
Not able to input `rem` as a value in the `letter-spacing` type.

A similar issue had submitted earlier for the `line-height` type:
https://github.com/tokens-studio/figma-plugin/issues/1045

**Proposal:**
Would require the same fix but for letter-spacing.

**Comment by UdayHyma** [comment]
[Migrated to Featurebase](https://tokensstudio.featurebase.app/p/typography-styles-with-variables)
