### ISSUE TITLE
Use token reference in element properties, instead of evaluated value.

### ISSUE THREAD

**Issue by kalin9411** [tokens-studio/figma-plugin#1797]
Hello there :) 

We have the following situation:
When selecting the token from the dropdown menu from properties panel all works well and we can see the token's name in the input (in our case the name is **fg/deep**):
![image](https://user-images.githubusercontent.com/68055485/230918972-d1172889-7c77-42c6-824a-083004f649a3.png)

When selecting the token from the plugin, the reference to the token is evaluated to the token value (in this case the color HEX) and the token name is lost:
![image](https://user-images.githubusercontent.com/68055485/230918991-24d5bd27-f547-4d8f-b599-450e25f978b0.png)

This behaviour is not ideal for our case, since the developers can't see which token is used in the design and they only see the HEX. Any suggestions? 
Thanks in advance.

**Comment by six7** [comment]
I'd recommend to look into Connecting tokens to styles, so those are applied when you apply using the plugin: https://docs.tokens.studio/styles/non-local-styles
