### ISSUE TITLE
Remember `Rename styles` choice

### ISSUE THREAD

**Issue by XavierVilars** [tokens-studio/figma-plugin#1799]
**Describe the bug**
In the studio, renaming a token will not necessarely rename the according style. It seems the checkbox "Rename style" is unticked by default. it should ideally remember the last used choice.

**To Reproduce**
1. Rename a token binded with a style in Figma
2. click on validate
3. check the rename style textbox
4. Validate. At this point all is ok.
5. Take another token binded with a style in Figma and rename it
6. validate
7. the tick box "rename style" is now already checked.
8. Validate
9. the style is not modify.

**Expected behavior**
It is good to keep the previous choice of the user. I'm modifying some token's name and I don't want to check and check again the same settings to validate. So, you just need to correct this bug.

**Screenshots or Screencasts**
![image](https://user-images.githubusercontent.com/104128778/231090804-e056660f-c1ee-4463-b60b-7722e67514fc.png)

**Comment by six7** [comment]
Shipped in 1.37.10
