### ISSUE TITLE
Ability To Display Token References In The Inspect Panel

### ISSUE THREAD

**Issue by keeganedwin** [tokens-studio/figma-plugin#1800]
Related to https://github.com/tokens-studio/figma-plugin/issues/1093

**Describe the issue:**
It would benefit the user if when hovering over a `value` in the inspect panel, a tooltip is shown displaying the `token's reference`

**Proposal 1:**
<img width="747" alt="Screenshot 2023-04-11 at 9 26 36 PM" src="https://user-images.githubusercontent.com/93133012/231220290-1400760c-17c5-4705-843e-15fb2c964014.png">

**Comment by keeganedwin** [comment]
**To consider**
We can think about whether or not it makes sense to expand this into other token `types`, and not just `values`

<img width="751" alt="Screenshot 2023-04-11 at 9 26 53 PM" src="https://user-images.githubusercontent.com/93133012/231221122-9ad94ed3-3a67-4d36-a105-e80bd344284c.png">

**Comment by six7** [comment]
Yeah we should just be reusing the same tooltips we are using elsewhere

**Comment by oorhon70** [comment]
This recently became a big need for developers who use the inspect tool as contextual reference when building a new tokenized design system. Especially since this will also allow you to see what makes up composite tokens (shadows, composition, typography, etc.).

**Comment by LukeFinch** [comment]
This request has been moved to our new feedback tool. Go check out https://tokensstudio.featurebase.app/ to create a free account. You can upvote and comment on existing posts, make a new request, and subscribe to be notified when requests move into our roadmap.

**Comment by UdayHyma** [comment]
Here's the URL to the featurebase post that is linked to this ticket: https://tokensstudio.featurebase.app/p/enhance-inspect-page-in-the-plugin
