### ISSUE TITLE
Delay issue when assigning tokens to an element

### ISSUE THREAD

**Issue by cuongphan05** [tokens-studio/figma-plugin#1802]
**Describe the bug**
Delay issue when assigning a token to an element

Sometimes it delays, and sometimes I have to restart the plugin (mostly)
**Screenshots or Screencasts**

https://user-images.githubusercontent.com/95276933/231408277-23996cfd-c4ee-403f-b61f-c021bd9b0067.mp4

**Comment by six7** [comment]
This should be fixed by https://github.com/tokens-studio/figma-plugin/pull/1753 once we merge this
