### ISSUE TITLE
font-feature-settings

### ISSUE THREAD

**Issue by Wolfi-evo** [tokens-studio/figma-plugin#1804]
I am urgently missing the possibility to define font-feture-settings for open type. Even a plain csv of strings would be ok, like so:

`font-feature-settings: 'tnum' on, 'lnum' on, 'cv01' on, 'cv02' on, 'cv03' on, 'cv04' on;`

Figma supports this. Import ignores this. No manual setting for open type features are possible yet.

To define this as a token under "other" lets you define the token, but "other"-tokens cannot be applied to typography-tokens nor to compositions.

**Comment by six7** [comment]
Unfortunately Figma doesn't support this yet in their Plugin API.

Marking as `blocked by Figma` and putting to Backlog

**Comment by Wolfi-evo** [comment]
> Unfortunately Figma doesn't support this yet in their Plugin API.
> Marking as `blocked by Figma` and putting to Backlog

This explains why the import fails. But there is also no way to define it manually. Typography-tokens don't have font-feature-settings options. And if I define it under "others" I cannot apply it to a composition or typography.

**Comment by six7** [comment]
We dont allow to define it because Figma has no support for it yet.

**Comment by Wolfi-evo** [comment]
> We dont allow to define it because Figma has no support for it yet.

Well, Figma does support OTF font-feature-settings. Inter is a good example for that. Here some of the settings you can set:
<img width="263" alt="image" src="https://user-images.githubusercontent.com/77406274/232422253-6e842283-45f3-4fef-9e02-f4427363e7df.png">
The settings also show up in the inspect panel.
Maybe the import is not possible. But there should be a way to define it in the plugin via UI or directly in JSON to have a complete style library to hand over.

**Comment by six7** [comment]
As stated initially Figma's Plugin API does not support that, we can only build support for it once Figma adds this.

**Comment by Wolfi-evo** [comment]
> As stated initially Figma's Plugin API does not support that, we can only build support for it once Figma adds this.

But it may be worth considering even if not supported by figmas API for exchange, to be able to manually define it, so that at least the repository of tokens is is holding it for a workflow outside of figma.

**Comment by SamIam4Hyma** [comment]
Moved to featurebase for typography improvements as Figma enhances the plugin API options avail to us.

**Comment by SamIam4Hyma** [comment]
Added to Featurebase Request-	[Enhanced typography support](https://tokensstudio.featurebase.app/p/enhanced-typography-support)
