### ISSUE TITLE
Variable fonts support for typography

### ISSUE THREAD

**Issue by El-Mansur** [tokens-studio/figma-plugin#1806]
**Is your feature request related to a problem? Please describe.**
We are using variable font called Robot Flex made by Google. One of the most important part of our work is to share json file of our typography with front-end developers, though, due to the fact that we are using variable font with its own special parameters like width, slant, grad etc. that token studio plugin isn't supporting right now, we can't share the whole typography with front-end developers and as a result all we can do is manually adjust json file and fill in these parameters. 

**Describe the solution you'd like**
It would be great to be able to fill in the variable fonts parameters as tokens and also use them when creating typography token.

**Describe alternatives you've considered**
I've described one of the solution that we came up with but it requires too much manual work so that solution doesn't work for us.

**Additional context**
Here is image of how figma supports variable fonts, just in case you need it. :D
<img width="482" alt="Снимок экрана 2023-04-13 в 17 16 38" src="https://user-images.githubusercontent.com/55206047/231742487-81785d7f-e082-45af-a21c-5a1b7468f1d6.png">

**Comment by six7** [comment]
Unfortunately Figma doesn't support this yet in their Plugin API.

Moving to `Blocked by Figma`

**Comment by SamIam4Hyma** [comment]
Archiving as we will introduce this when Figma has options for this in their plugin API

**Comment by SamIam4Hyma** [comment]
Added to Featurebase Request-	[Enhanced typography support](https://tokensstudio.featurebase.app/p/enhanced-typography-support)

**Comment by SamIam4Hyma** [comment]
Added to Featurebase Request-	[Enhanced typography support](https://tokensstudio.featurebase.app/p/enhanced-typography-support)
