### ISSUE TITLE
Documentation token: Name (as short name)

### ISSUE THREAD

**Issue by denis-strong** [tokens-studio/figma-plugin#1807]
**description**
Currently we have a documentation token **Name** available, but it displays the full token path. I would love to have to versions of this token as **Name** and **Full-name**

**Solution**

Name = `100`
Full-name = `core.color.red.100`

![image](https://user-images.githubusercontent.com/72541735/231975652-fcd2f8f3-f854-4a45-a907-4622b7cbab53.png)

**Comment by SamIam4Hyma** [comment]
Migrated to Featurebase with other documentation requests.
