### ISSUE TITLE
Token reference not removed after clicking on remove button

### ISSUE THREAD

**Issue by dongeerts** [tokens-studio/figma-plugin#1808]
**Describe the bug**
The applied token reference remains active after removing the token link in the Figma interface. 

**To Reproduce**

1. Apply token to layer
2. Select layer with applied token
3. Click on the remove token button
4. Deselect layer
5. Edit value of token

**Result**
The layer where you removed the token link from is updated with the new value. 

**Expected result**
The layer where you removed the token link from isn't updated with the new value.

**Screencast**

- [video on imgur](https://i.imgur.com/CecGq4P.mp4)

**Comment by six7** [comment]
So this thing you see in Figma on the bottom right doesn't remove the token, it just removes the little preview itself.

To remove a token you'd go to `Inspect` in the plugin, select the token to be removed, and then hit `Remove selected`.

**Comment by mnieber** [comment]
Since the tokens inspect tab is so useful, maybe it's an idea to have it directly in the figma inspector? (i.e. on the right hand side of the screen)

**Comment by six7** [comment]
Unfortunately that's not something plugins can do. Consider requesting that from Figma ❤️ (we already have)
