### ISSUE TITLE
multiple properties in color styles ignored at import

### ISSUE THREAD

**Issue by Wolfi-evo** [tokens-studio/figma-plugin#1814]
Figma allows multiple color properties to be defined in a color style. Import ignores these styles fully. Even without messeage that this style was not imported. Took me some time to find out the reason.

And I did not find a way to reproduce these color styles in the plugin or even create styles like this from the plugin back to figma.

Screenshot of multiple color properties for demonstration:
<img width="318" alt="image" src="https://user-images.githubusercontent.com/77406274/232223931-b5f7f91d-cdbf-4c52-9dc0-c54b91158e53.png">

**Comment by six7** [comment]
We're only importing color styles with a single fill which are solids or linear-gradients, that's all that's supported so far.

**Comment by Wolfi-evo** [comment]
> We're only importing color styles with a single fill which are solids or linear-gradients, that's all that's supported so far.

Would be good to have a report note on the ones that not get imported. Took me a while to figure out that not all style were imported and why.

**Comment by Wolfi-evo** [comment]
> We're only importing color styles with a single fill which are solids or linear-gradients, that's all that's supported so far.

Turns out that a lot of design systems use a set of fills for eg button states like so:
![image](https://user-images.githubusercontent.com/77406274/234032646-3ddd7fe5-fc61-4d55-859a-bdbb91599865.png)
I think there is a need to be able to apply a set of fills. At the moment there is no way to reproduce this.

**Comment by chrisyalamov** [comment]
Big +1 for this feature. Looking at the Group Tokens section of the draft spec for design tokens (https://design-tokens.github.io/community-group/format/#groups-versus-composite-tokens), it seems to describe something similar to the composition tokens feature in Tokens Studio:

> [Groups](https://design-tokens.github.io/community-group/format/#groups) are for arbitrarily grouping tokens for the purposes of naming and/or organization.

Perhaps the plugin could allow for a composition token to contain several color/gradient tokens which apply the 'fill' property?

**Comment by esthercheran** [comment]
@Wolfi-evo we are enhancing how styles and variables are getting imported and we will showing the styles/variables that gets skipped and the reasons for skipping. This will be covered in #2211

**Comment by esthercheran** [comment]
Closing this ticket as the issues are covered in other tickets
