### ISSUE TITLE
Display opacity suggestions under the alpha operation

### ISSUE THREAD

**Issue by keeganedwin** [tokens-studio/figma-plugin#1815]
**Is your feature request related to a problem? Please describe.**
The dropdown-field under the `alpha` operation of the color-modifier does not display `opacity` suggestions. 

**Key information:**
Neither does the field allow you to reference `opacity` tokens

<img width="464" alt="Screenshot 2023-04-17 at 2 33 41 PM" src="https://user-images.githubusercontent.com/93133012/232438108-d3b1134b-32ea-465c-b004-615c9d62f6d2.png">

**Describe the solution you'd like**
Display `opacity` suggetions under the alpha operation dropdown-field

**Comment by six7** [comment]
One thing to note: the `amount` field only accepts a value from 0 to 1. Opacity tokens can either be 0 to 1 but also `%` based (50%). While we could suggest all, I would say let's stay strict with just allowing values from 0 to 1 to work, and then inform users of that if they enter something else.

**Comment by SamIam4Hyma** [comment]
@keeganedwin can you check to see if this is still an issue and if not close with comment? I just tried in the plugin and can not replicate what is in the screenshots.
