### ISSUE TITLE
Option to select only required styles when creating 

### ISSUE THREAD

**Issue by keeganedwin** [tokens-studio/figma-plugin#1820]
**Is your feature request related to a problem? Please describe.**
Currently, the creating styles modal displayed does not allow users to _only_ select the styles they want to create
<img width="224" alt="Screenshot 2023-04-19 at 8 02 22 PM" src="https://user-images.githubusercontent.com/93133012/233109840-f18dbe15-eecb-48c4-abfd-c0f72da41539.png">

**Describe the solution you'd like**
It would benefit the user by having a similar modal displayed when importing styles
![Screenshot 2023-04-19 at 7 51 26 PM](https://user-images.githubusercontent.com/93133012/233110160-08f4f301-c0e6-438a-844e-6ac2d1a1c746.png)

**Definition of done**
- On create styles from tokens display a modal allowing user to select the tokens which should be created as styles
- Only the selected tokens should be created as styles
- When there is an update in the token, the difference should be shown in red and green

![Image](https://github.com/tokens-studio/figma-plugin/assets/66366384/e9b64608-1cfa-47d4-9c5a-379bad816b02)

**Comment by SamIam4Hyma** [comment]
@LukeFinch proposing we close as this feature exists in the plugin today
