### ISSUE TITLE
Leading trim feature

### ISSUE THREAD

**Issue by derryfoldable** [tokens-studio/figma-plugin#1827]
Is the new Figma type settings feature for Leading trim going to be added to the app so can be used with typography tokens? 

In the type settings menu leading trim is called Vertical trim, with the following options:
Standard, Cap height to baseline

It appears in the Plugin API:
https://www.figma.com/plugin-docs/api/TextNode#leadingtrim

**Comment by six7** [comment]
Thanks for creating this, seems like Figma added that in their March 31 update. I wonder how we'd want to surface this in typography tokens.

I guess a `leadingTrim` property in typography tokens which can be set to either `true` or `false` might do the job.
I don't think we have to support this as an individual token type, instead we can introduce this properly inside the `boolean` token type which is going to be part of the next release.

## Definition of done
- [ ] `leadingTrim` property in `typography` tokens which can be `true` | `false` | `reference to another token`
- [ ] `Leading trim` as an apply dropdown option for tokens of type `boolean

**Comment by keeganedwin** [comment]
Here's a recent [slack thread](https://tokens-studio.slack.com/archives/C02DEJMS9AP/p1703268009325109) also requesting this.

**Comment by SamIam4Hyma** [comment]
Added to Featurebase Request-	[Enhanced typography support](https://tokensstudio.featurebase.app/p/enhanced-typography-support)
