### ISSUE TITLE
Extra spaces in gradient token reference not recognised

### ISSUE THREAD

**Issue by keeganedwin** [tokens-studio/figma-plugin#1836]
**Describe the bug**
When adding references for a gradient token, if there are extra spaces in the function, the color keeps resolving correctly but you can't apply it in Figma

**To Reproduce**
1. Create a gradient token 
2. After a comma and 2 spaces and save the token
3. Token+value saved, but can't be applied until unless the extra space is removed

**Expected behavior**
Maybe as an enhancement, have the plugin recognise the extra space and correct it so that users don't have to pay extra attention to the spaces in the following tokens types which can have multiple references:
- gradient
- spacing 
- border
- border radius

**Screenshots or Screencasts**

https://user-images.githubusercontent.com/93133012/235152688-76f7d77f-35c5-4272-ade5-9bfec640b05b.mov

**Definition of done**
Token values should be trimmed on input and when passing to figma. Similar to https://github.com/tokens-studio/figma-plugin/issues/432

**Comment by keeganedwin** [comment]
This is also the issue with `spacing-tokens`. If possible we should have this resolved across token types that have the option of multiple references.

![image (4)](https://github.com/tokens-studio/figma-plugin/assets/93133012/65b6a14d-d4c7-4cb3-9c4b-035ad334e922)

**Comment by LukeFinch** [comment]
This request has been moved to our new feedback tool. Go check out https://tokensstudio.featurebase.app/ to create a free account. You can upvote and comment on existing posts, make a new request, and subscribe to be notified when requests move into our roadmap.

**Comment by UdayHyma** [comment]
Added to Featurebase Roadmap : [🎨 Expand gradient color support](https://tokensstudio.featurebase.app/p/add-gradient-token-type-and-expand-functionality-past-linear)
