### ISSUE TITLE
Undo button also for when editing tokens

### ISSUE THREAD

**Issue by keeganedwin** [tokens-studio/figma-plugin#1837]
**Is your feature request related to a problem? Please describe.**
Currently users are only able to undo tokens when creating a new one.

![Screenshot 2023-05-01 at 3 51 59 PM](https://user-images.githubusercontent.com/93133012/235440836-4e316749-5305-434f-aa0f-9388cdd8ef78.png)

**Describe the solution you'd like**
It could benefit users if the undo button was also displayed when editing already existing tokens

**Definition of done**
- Edit token action can be reverted with the undo button
- If the previous action is edit token, tooltip on the Undo button displays ' Undo "Edit Token"'

**Comment by UdayHyma** [comment]
Added to Featurebase Roadmap : [🪙 Token organization enhancements
](https://tokensstudio.featurebase.app/p/token-organization-enhancements)

**Comment by UdayHyma** [comment]
[Migrated to featurebase](https://tokensstudio.featurebase.app/p/greenheart-v2-quality-of-life-enhancements)

**Comment by SamIam4Hyma** [comment]
Added to Featurebase Request-	[Undo and emergency exit](https://tokensstudio.featurebase.app/p/undo-enhancements)
