### ISSUE TITLE
Remember previously used grid/list view for color type

### ISSUE THREAD

**Issue by keeganedwin** [tokens-studio/figma-plugin#1838]
**Is your feature request related to a problem? Please describe.**
Users have to manually change the view (grid/list) of the color token type after they restart the plugin.

![image](https://user-images.githubusercontent.com/93133012/235441380-da89d6c6-5a01-4dac-adef-075e6c36ede2.png)

**Describe the solution you'd like**
Remember this upon plugin restart and save in the user's clientStorage.

**Comment by UdayHyma** [comment]
Added to Featurebase Roadmap : [🪙 Token organization enhancements
](https://tokensstudio.featurebase.app/p/token-organization-enhancements)

**Comment by UdayHyma** [comment]
[Migrated to Featurebase](https://tokensstudio.featurebase.app/p/token-organization-enhancements)
