### ISSUE TITLE
Generic Versioned provider asks to "Recover" every time the plugin runs

### ISSUE THREAD

**Issue by Jexordexan** [tokens-studio/figma-plugin#1839]
**Describe the bug**

When using the Generic Versioned provider, the plugin always asks to "Recover local changes" even if nothing has changed, then breaks Sync.

**To Reproduce**
1. clone  [figma-tokens-generic-storage-example](https://github.com/SorsOps/figma-tokens-generic-storage-example)
2. install and run the server as instructed
3. Create a new Figma document and add Tokens Studio
4. Add Generic Versioned provider and use `http://localhost:8000/tokens` as the URL
5. Create a new token (`foo: #F00`) and apply to the page
6. Press "sync" to ensure that the token was saved
7. Close the plugin
8. Run the plugin again — Notice the "Recover local changes" screen is visible (Image 1)
10. Click "Yes" or "Cancel"
11. Click "Sync" — Notice it doesn't do anything and throws a console error (Image 2)
12. Edit the provider again and hit save, now everything works

**Expected behavior**

I expect that the Generic Versioned provider will work on reboot of the plugin, and pressing Sync will actually pull changes or tell me something went wrong, 

**Screenshots or Screencasts**

Image 1: Recover screen
![Screen Shot 2023-05-01 at 10 01 10 AM](https://user-images.githubusercontent.com/7380810/235464633-4f187844-9ed7-44ef-b428-fc8bf15c28ee.png)

Image 2: Console error after clicking "sync"
![Screen Shot 2023-05-01 at 10 13 05 AM](https://user-images.githubusercontent.com/7380810/235465081-258ecb4f-c5c3-4412-b16e-01c89567ad6d.png)

**Figma file (optional)**
Send us the link to a Figma file containing a reproducible example

**JSON (optional)**
If possible, attach the JSON that leads to this bug.

Platform:
MacOS 12.6.5
Tokens Studio [V 1.35.3](https://tokens.studio/changelog)
[figma-tokens-generic-storage-example](https://github.com/SorsOps/figma-tokens-generic-storage-example) latest

**Comment by Jexordexan** [comment]
I did some sleuthing regarding the "Recover modal"...

Here are some similar issues for JSONBin provider #1395 #1108 
Porting these changes could solve the issue.

The modal shows up because the `checkForChanges` flag is always set to `true` for genericVersioned.
The flag get set to true because of a bug in [Footer](https://github.com/tokens-studio/figma-plugin/blob/main/src/app/components/Footer.tsx#L50-L62). The metadata for genericVersioned is different than the normal `{ tokenSetOrder: string[] }`. Leading to a deep equality check for the following:
![Screen Shot 2023-05-01 at 2 46 30 PM](https://user-images.githubusercontent.com/7380810/235753471-846316df-3454-4142-afb1-e4f94864b8a6.png)

**Comment by SorsOps** [comment]
@Jexordexan Thanks for this 

Here is the culprit https://github.com/tokens-studio/figma-plugin/blob/1af88513722baa15722dc59a5a1a6ff1247b1288/src/app/components/AppContainer/startupProcessSteps/pullTokensFactory.ts#L37 

PR is here https://github.com/tokens-studio/figma-plugin/pull/1853

@six7  We should look into prioritizing that refactor of storage providers to keep all the logic consolidated in a single area

**Comment by Jexordexan** [comment]
@SorsOps Ha, didnt check the issue this morning and ended up making my own PR (#1854). I'll pull yours and verify the fix works. Your PR is much simpler than mine, so its probably better to merge that is it works

**Comment by Jexordexan** [comment]
@SorsOps Your fix resolves the console error, and preserves syncing to remote after resarting the plugin, awesome!

However, the issue of getting the "Recover" prompt continues. I think this is because `compareLastSyncedState` is still always evaluating to true. In my PR, the[ first commit](https://github.com/tokens-studio/figma-plugin/pull/1854/commits/9359a307ae79b982807553ccc3eccdc4847c1895) addresses this issue.

**Comment by SorsOps** [comment]
@Jexordexan Yeah both of these PRs are required to solve it. If you're ok with it, I'd like to merge your changes into mine. I'll add some additional testing and then we can solve this all in a single merge

**Comment by Jexordexan** [comment]
Thats fine with me, thanks!

**Comment by SorsOps** [comment]
@Jexordexan I was going to address them after your consent to merge, but thanks for addressing them!
