### ISSUE TITLE
When syncing/renaming styles, theme name changes instead of token name (when these have the same name)

### ISSUE THREAD

**Issue by rbosker** [tokens-studio/figma-plugin#1840]
**Describe the bug**
Edge case: When syncing tokens with styles (and renaming styles), the theme name changes instead of token name, if you're using the same name for both.

**Expected behavior**
In the example I'd expect the token called 'test' changes name, instead of the theme prefix that is now changing

**Screenshots or Screencasts**
<img width="889" alt="image" src="https://user-images.githubusercontent.com/109062656/235476863-81272474-bca8-45cc-97d7-934b64f5f0c0.png">
https://user-images.githubusercontent.com/109062656/235474460-11620781-81f4-4727-8a64-2e4099eb3626.mov

**Comment by SamIam4Hyma** [comment]
@rbosker can you check to see if this issue still exists? I'm not sure how to test on my end based on the description. If its solved, please close.

**Comment by keeganedwin** [comment]
Just tested and this is no longer an issue; closing the ticket.
