### ISSUE TITLE
Add ability to enter `Edit token group (Rename)` by cmd+clicking the group

### ISSUE THREAD

**Issue by six7** [tokens-studio/figma-plugin#1844]
Let's add a way to open the Edit token group dialog when cmd+clicking it, which would be consistent how we do it for tokens itself.

![Image](https://user-images.githubusercontent.com/4548309/235501695-afb50780-5f52-4859-8979-c1fd49462bce.png)

**Comment by SamIam4Hyma** [comment]
@six7 would this be covered in #1811 and therefore we can close?

**Comment by six7** [comment]
No, this is about the shortcut - the other about the ability to add descriptions

**Comment by UdayHyma** [comment]
Added to Featurebase Roadmap : [🪙 Token organization enhancements
](https://tokensstudio.featurebase.app/p/token-organization-enhancements)

**Comment by SamIam4Hyma** [comment]
closing for now as its added into Featurebase for future work consideration.
