### ISSUE TITLE
Pushing to Gitlab fail

### ISSUE THREAD

**Issue by thecodingfrog** [tokens-studio/figma-plugin#1851]
When trying to push to gitlab, now I get this error :
Error pushing to GitLab HTTPError: Request failed with status code 403

**Comment by six7** [comment]
Your access token likely doesn't have the correct scopes defined, 403 means Forbidden

**Comment by thecodingfrog** [comment]
yup you are right, my bad
Looks like I didn't setup correct role when renewing my token
