### ISSUE TITLE
Multi value border width token

### ISSUE THREAD

**Issue by rbosker** [tokens-studio/figma-plugin#1857]
**Is your feature request related to a problem? Please describe.**
Add the possiblity to add multiple values for border width, so you can define all border width sizes separately (just like we have for the radii and spacing tokens).

> Single value (like today)
> will apply to the gap property (like today)
> 10px
> 
> Two values
> will apply top-and-bottom | left-and-right
> 10px 5px
> 
> Three values
> will apply top | right-and-left | bottom
> 2px 4px 2px
> 
> Four values
> will apply top | right | bottom | left
> 1px 0 3px 4px

Related: https://github.com/tokens-studio/figma-plugin/issues/110

**Comment by SamIam4Hyma** [comment]
Migrated to Featurebase https://tokensstudio.featurebase.app/p/expand-token-types

**Comment by keeganedwin** [comment]
Closing as migrated
