### ISSUE TITLE
Applying colour sets (overrides) to re-theme the design doesn't work

### ISSUE THREAD

**Issue by Arno-Sympower** [tokens-studio/figma-plugin#1858]
**Describe the bug**
Applying colour sets (overrides) to re-theme the design doesn't work in an external Figma file with the library linked and studio tokens synced (Github).

**To Reproduce**
1. When in the component library (MUI in my case) I can add a set of alternate colours, apply It and It works perfectly.
2. Then I create a new file, put a screen with some components in It, link the library, sync the token studio colours, apply the new colour set: nothing happens. 
3. When I go back to the library an apply the colours with the token studio colour tokens again manually (toggeling the colour on/off), publish the library and accept changes in the other file, It does work. But why does It work within the library itself out of the box and not on external files out of the box since It's already proven to be linked?

It's very tedious to now having to go through every layer with colour properties in all components. Especially because It seems to work out of the box within the library Itself. I'm confused.

**Expected behavior**
That It works?

**Comment by keeganedwin** [comment]
Hey @Arno-Sympower are still facing this issue?

**Comment by SamIam4Hyma** [comment]
@keeganedwin please investigate and if its not still occuring lets close with comment. (:

**Comment by SamIam4Hyma** [comment]
Added to Featurebase Roadmap as a known issue in progress of being fixed -	[🚧 ❖❇️ Export styles and variables using sets (free plan) ](https://tokensstudio.featurebase.app/p/export-to-figma-using-token-sets)

**Comment by UdayHyma** [comment]
Added to FeatureBase Roadmap- [❖ ❇️ Non-local support of variables and styles](https://tokensstudio.featurebase.app/p/non-local-support-of-variables)

**Comment by SamIam4Hyma** [comment]
if a person is wanting to use theming they should use a pure token flow or theme groups. It has dependencies on non-local file support or choosing if tokens should be style, variables etc.

**Comment by SamIam4Hyma** [comment]
closing this ticket for now until we have more info from the OP.
