### ISSUE TITLE
Improve status message displayed for all sync providers

### ISSUE THREAD

**Issue by SimonLeclercq** [tokens-studio/figma-plugin#1859]
Provide status message for all sync providers when the sync provider is down.

**Is your feature request related to a problem? Please describe.**
Github was down this afternoon (cf: https://status.github.com) so nothing happened when I push and believe to crash or error.

**Describe the solution you'd like**
Could be great to have a short message: "Something went wrong. Please retry later. For more info: https://status.github.com"

You rock folks, thanks!

**Comment by UdayHyma** [comment]
[Migrated to Featurebase](https://tokensstudio.featurebase.app/p/sync-external-storage-enhancements)
