### ISSUE TITLE
Base font size not propagating correctly across token sets

### ISSUE THREAD

**Issue by txcrew** [tokens-studio/figma-plugin#1863]
**Describe the bug**
When using two token sets with `Font Size` and `Base Font Size` tokens, the base font size does not propagate until the token set is disabled and enabled twice.

**To Reproduce**
1. Create a token set labeled `set A` 
2. Add a few `Font Size` tokens in REM (ex: 50 = 0.75rem, 100 = 1rem, 200 = 1.50rem), label the group of tokens `fontSizes`
3. Create a base font size token in px (ex: 16px) as a `Font Size` type, label the group` baseFontSize`
4. Set the base font size in the `settings` panel to reference the `baseFontSize` token.
5. Create an additional token set, labeled `set B`
6. Duplicate the group `fontSizes` to `set B`
7. Duplicate the `baseFontSize` group to `set B`
8. Style text in Figma using tokens from `set A`
9. With `set A` activated, enable `set B`

**Expected behavior**
* Font size tokens update
* Base font size tokens update

**Actual behavior**
* Font size changes
* Base font size does not change

**It will work if...**
Toggle `set B` on and off twice it will first change the font size tokens, then on the second activation it'll update the base font size.

**Comment by keeganedwin** [comment]
[Test File](https://www.figma.com/file/yaiExdXQOKe3AZrIG76h8V/Github-Issue-%231863?type=design&node-id=0%3A1&mode=design&t=i1CyqJx8jpjt0xKp-1) for this Issue

**Comment by SamIam4Hyma** [comment]
@six7 I am not able to replicate this bug with the V2B build so I believe it can be closed for now.
