### ISSUE TITLE
Tokens not found? (Reset?)

### ISSUE THREAD

**Issue by nathanmckean** [tokens-studio/figma-plugin#1864]
**Describe the bug**

Cannot reproduce sorry, but I opened the Token Studios plug-in on a file that I have used it on before and it just isn't opening. I get the initial welcome screen with "new empty file" and "load example"

**Expected behavior**
The plug in opens as normal and user can resume using and creating tokens.

**Screenshots or Screencasts**

![token_studio](https://user-images.githubusercontent.com/60857220/236611603-4c8643d4-6635-4542-8c26-76e9277e76f7.jpg)

**Comment by keeganedwin** [comment]
Hey @nathanmckean, have you faced this issue since this ticket was submitted?

**Comment by esthercheran** [comment]
Closing this ticket due to lack of information
