### ISSUE TITLE
[next/beta]: Ability to edit Theme group name

### ISSUE THREAD

**Issue by esthercheran** [tokens-studio/figma-plugin#1874]
Once a theme group name is created in the Multi Dimensional Theme, there is no easy option to edit the group name.
Quick win: allow to rename the theme group name from the theme dropdown. 

- On hover of group names show a pencil iconbutton
- On click of the pencil, replace the whole thing with an input that is focused.
- pressing esc cancels (no save)
- pressing enter saves
- on save, update all themes

![Image](https://github.com/tokens-studio/figma-plugin/assets/4548309/be207845-97c2-4672-88e8-652cbc45d08b)

**Comment by six7** [comment]
Moving to shaping, we will need designs for this (can do so tomorrow)
