### ISSUE TITLE
expandShadow option on token transformer doesn't fully expand shadow tokens which contain multiple items

### ISSUE THREAD

**Issue by liamco** [tokens-studio/figma-plugin#1878]
**Describe the bug**
When using the token transformer, shadows containing multiple items don't transform correctly. Instead, they transform to `[object Object]` (much like all shadows do if the option is turned off). If a shadow is removed from the token so it only contains a single shadow, the token is transformed correctly. 

**To Reproduce**
1. Create a shadow token in the plugin which contains more than one shadow
2. Export the tokens to JSON
3. Transform the JSON using the token transformer
4. The multi-shadow token will contain `[object Object]` rather than the expanded shadow properties

**Expected behavior**
Shadows should transform to seperate properties like a single shadow e.g. `shadow.0.color`, `shadow.0.x`, `shadow.y.color`, `shadow.y.x`

**JSON (optional)**
[light.json.zip](https://github.com/tokens-studio/figma-plugin/files/11433232/light.json.zip)

**Comment by braddialpad** [comment]
I'm getting this too. I just confirmed this is a bug in the latest version of token-transformer (0.0.32). Downgraded to 0.0.31 and everything works as expected.

**Comment by liamco** [comment]
@braddialpad Thanks for the heads up!

**Comment by RockAtRockwell** [comment]
Thanks for the fix @braddialpad ! This was broken for me in 0.0.33 as well

**Comment by SamIam4Hyma** [comment]
@jorenbroekema is this still an issue? I see something related above marked as closed.

**Comment by jorenbroekema** [comment]
token-transformer deprecated in favor of using sd-transforms, definitely works there
