### ISSUE TITLE
List-spacing token option

### ISSUE THREAD

**Issue by keeganedwin** [tokens-studio/figma-plugin#1884]
**Is your feature request related to a problem? Please describe.**
Currently Figma have support for list-spacing but the plugin does not support tokens for this yet.

https://github.com/tokens-studio/figma-plugin/assets/93133012/c3158a50-9aea-4e6f-a508-923e770fc4a6

**Describe the solution you'd like**
1. When applying a spacing token, we could show an option for list-spacing in the tooltip.
<img width="249" alt="Screenshot 2023-05-10 at 3 43 22 PM" src="https://github.com/tokens-studio/figma-plugin/assets/93133012/6545be4c-933e-46ce-90e3-e8b28109ce49">

2. We could create a _type_ for list-spacing
<img width="1068" alt="Screenshot 2023-05-10 at 3 42 12 PM" src="https://github.com/tokens-studio/figma-plugin/assets/93133012/fa6e14a0-c268-43be-85dd-f7f6dfc0d71c">

**Comment by esthercheran** [comment]
Currently W3C Design Tokens draft does not support list spacing.

**Comment by SamIam4Hyma** [comment]
@LukeFinch can confirm but I'm pretty sure this isn't a CSS property either (my 3sec google search might not be accurate). If thats true, lets close/archive this one. We don't want to be in the habit of accommodating the figma-specific decisions that don't align with design token fundamentals of being in a common language to be shared across platforms.
