### ISSUE TITLE
Sync providers conflict when both have the same branch selected due to shared access token

### ISSUE THREAD

**Issue by keeganedwin** [tokens-studio/figma-plugin#1892]
**Describe the bug**
When users are utilising two sync providers with distinct branches, they may inadvertently activate the same branch for both providers within the settings due to various reasons. This results in both providers becoming linked and active, likely due to the shared access token. Consequently, deleting one provider leads to the unintended deletion of the other due to their linked status.

https://github.com/tokens-studio/figma-plugin/assets/93133012/3055a8e8-5521-4a8a-becf-499920af84f7

**To Reproduce**
1. Add a new provider 
2. The new provider should use the same repo as the original provider, but use a different branch
3. Make sure both the providers are using the same access token
4. When switching the branch of the _new one_ to the same _branch_ as the original provider, both should be active in the settings
5. After deleting one, both are consequently deleted.

**Expected behavior**
To avoid having both being active, maybe a modal that indicates that this is not possible since there is already a provider with the same details active, and that the user can't have two providers active with the same branch. 

<img width="507" alt="Screenshot 2023-05-12 at 3 25 43 PM" src="https://github.com/tokens-studio/figma-plugin/assets/93133012/9e303b23-409a-48c7-b6b3-1280426f02f3">

**Comment by LukeFinch** [comment]
This request has been moved to our new feedback tool. Go check out https://tokensstudio.featurebase.app/ to create a free account. You can upvote and comment on existing posts, make a new request, and subscribe to be notified when requests move into our roadmap.

**Comment by UdayHyma** [comment]
Added to Featurebase Roadmap : [🧑‍💻 Sync to external token storage enhancements](https://tokensstudio.featurebase.app/p/sync-external-storage-enhancements)
