### ISSUE TITLE
[Performance]: Improve performance for large documents

### ISSUE THREAD

**Issue by six7** [tokens-studio/figma-plugin#1901]
Next would be how we handle updates to large documents. There are 2 pieces to this, 1 maintaining some form of index so we don't have to walk the entire tree each time if nothing has changed. This would need to listen to events to determine if a change has occurred and then invalidate the index if need be. Using a weakmap would be the best here to make sure we don't keep references in memory. I know we currently have the NodeManager for this but we iterate across all nodes on the update. While we do have O(1) lookups, we do O(n) changes by iterating through every node when making changes.

**Comment by SorsOps** [comment]
We should also be adding async messages to push metrics like the amount of nodes. time for walk etc  to the front end to report to Sentry

**Comment by SorsOps** [comment]
Added the above as #2058

**Comment by SorsOps** [comment]
Note for the initial task, we should consider this to be dependent on #2053 , #2058  and #2057   to give us additional insights on tasks and follow up for this issue
