### ISSUE TITLE
[Performance]: Detect changes performantly

### ISSUE THREAD

**Issue by six7** [tokens-studio/figma-plugin#1902]
Second would be the diffing algorithm for us to do the above (#1901 ) we would need to build a map of the applied tokens to id lookups so that if a change is detected from the previous application, that we can restrict the changes to only the nodes that are detected for 1 but also to only apply what has changed instead of iterating through properties that aren't necessary.

**Comment by six7** [comment]
This would only ever be useful if we apply changes to document directly after editing one single token (as we then would know the type of change). That way we would then be able to detect all nodes that were using that specific token compared to operating on all nodes that contain plugin data. This would just require us to filter on the result of findAllWithCriteria based on the token name / id.

We'd also need to account for references where this token is used and update those layers as well.

Once we have made these changes we should be able to re-introduce `Update on change` as the performance implications of this would be minimal.

**Comment by SamIam4Hyma** [comment]
@six7 update on change is in the current plugin. Does that mean this ticket can be closed?
