### ISSUE TITLE
[Performance]: Integrate performance profiling using Sentry

### ISSUE THREAD

**Issue by six7** [tokens-studio/figma-plugin#1906]
Let's add performance profiling to any expensive interactions to understand how we fare and where to improve.

https://docs.sentry.io/product/profiling/

The resolveTokenValues and any interactions on the plugin side where the most expensive transactionslike walking the document should be wrapped with a Sentry transaction so we can proactively detect these bottlenecks in performance

**Comment by SorsOps** [comment]
We cannot use profling as it depends on node apis to track cpu usage, etc.

Note that we do have existing transaction in sentry for performance testing 

![Image](https://github.com/tokens-studio/figma-plugin/assets/80043879/59fabe8a-e051-439c-9ddd-e6f6632f7730)

We should annotate the custom transactions we have with additional spans to help detect potential slow downs , as well as
