### ISSUE TITLE
Tokens can't get applied to a certain component

### ISSUE THREAD

**Issue by Blyawon** [tokens-studio/figma-plugin#1909]
**Describe the bug**
I've got one component and a copy of this certain component to which no tokens can get applied. When applying a token the component takes the visual appearance of the token, but the token is not connected to it and also doesn't get shown in the inspect mode. Other tokens can't also get applied. It's just this one component.

**To Reproduce**
No reproducible until now

**Screenshots or Screencasts**
Can only share in private

**Comment by six7** [comment]
Can you give us more information? What kind of component is this? Anything in the console? Ideally, a reproducible example would be great (you can just extract that component, remove all its children and share privately, if it's an issue with the component then all we need is that layer that you tried to apply it on.

**Comment by Blyawon** [comment]
Looks like I'm getting this in the console.
<img width="841" alt="Bildschirmfoto 2023-05-30 um 15 34 39" src="https://github.com/tokens-studio/figma-plugin/assets/78965152/115ca06b-5421-49ee-97b2-7d64af9d0e05">

We are having the issue now with multiple components, and there seems no way to fix it without recreating the component.

**Comment by esthercheran** [comment]
Closing this issue as this has been fixed
