### ISSUE TITLE
Save Correct Output In JSON When Selecting Color-Space

### ISSUE THREAD

**Issue by keeganedwin** [tokens-studio/figma-plugin#1914]
**Is your feature request related to a problem? Please describe.**
Currently, a user has to manually paste the `RGBA` or `HSL` value in the field to get the selected space's value as output in json. However, when using the color-picker the plugin saves it as a hex-value in json regardless of which space is selected.

**Describe the solution you'd like**
Support for saving the corresponding value depending on what space is selected.

**Screenshots & Recordings:**
Selecting space via the color-picker:
![CleanShot 2023-11-24 at 14 33 18@2x](https://github.com/tokens-studio/figma-plugin/assets/93133012/648b41fe-d4b8-46ec-a0d3-a2ae8ddd9169)

Color-picker only gives hex-value as output
https://github.com/tokens-studio/figma-plugin/assets/93133012/418ba3b5-deca-4eff-8e23-20566f5ebd99

**Comment by LukeFinch** [comment]
This request has been moved to our new feedback tool. Go check out https://tokensstudio.featurebase.app/ to create a free account. You can upvote and comment on existing posts, make a new request, and subscribe to be notified when requests move into our roadmap.

**Comment by UdayHyma** [comment]
Added to FeatureBase Roadmap : [🎨 Expanded support for color spaces](https://tokensstudio.featurebase.app/p/expanded-support-for-color-spaces)
