### ISSUE TITLE
Number Styles: e.g. proportional uppercase/lining

### ISSUE THREAD

**Issue by litemeup-cyprus** [tokens-studio/figma-plugin#1915]
It would be great if you could define the style for the numbers in a text style or typography token. In Figma, this can be found in the text styles and details "Numbers".

**Comment by six7** [comment]
Unfortunately Figma's Plugin API does not support this yet.

**Comment by SamIam4Hyma** [comment]
CLosing as this will be added as soon as we have a Figma API option for this and other typography properties
