### ISSUE TITLE
Slashed zero / type properties

### ISSUE THREAD

**Issue by ilikeyourdog** [tokens-studio/figma-plugin#1917]
**Is your feature request related to a problem? Please describe.**
I need to be able to select slashed zero for my numbers in a text style.

**Describe the solution you'd like**
Typography properties as a token (slashed zero, alternative ligatures etc)

**Comment by six7** [comment]
Unfortunately Figma's plugin API does not support this yet.

**Comment by SamIam4Hyma** [comment]
Closing as this will be added when there is an official token type for this and there is plugin API support for this property
