### ISSUE TITLE
Can't apply styles to library components but to single newly created elements

### ISSUE THREAD

**Issue by last-skywalker** [tokens-studio/figma-plugin#1918]
**Describe the bug**
I have a existing component library with defined tokens.
I created based on my design tokens 2 sets.
If I click on the components it recognizes the relevant design tokens.
If I activate the second set nothing happens.
If I create a new text element, add a token and then activate the second set it changes but only the values, it is even removing the design token.

**To Reproduce**
no description

**Expected behavior**
I expect that my components react to the change in sets correctly.

**Screenshots or Screencasts**
Added video.

**Figma file (optional)**
Send us the link to a Figma file containing a reproducible example

**JSON (optional)**
If possible, attach the JSON that leads to this bug.

https://github.com/tokens-studio/figma-plugin/assets/134526327/e2d7b3b9-97ee-4d9d-b339-09acc6bf12b4

**Comment by rbosker** [comment]
@last-skywalker can you check if you have the Setting 'Update Styles' enabled in the bottom right of the plugin?

**Comment by last-skywalker** [comment]
@rbosker it is activated. 
If I create everything new it is fine. It is not working with my current design system. But probably because it is in different files and I would need Pro to really update it.

**Comment by keeganedwin** [comment]
hey @last-skywalker, from the video it looks like you were trying to theme switch published components that were styled from another library. I think you're comment above also mentions that and if that's the case then you are correct. You would need Pro to updates styled components from published libraries.

**Comment by keeganedwin** [comment]
@last-skywalker were you able to resolve this issue?
