### ISSUE TITLE
Introduce `text` tokens

### ISSUE THREAD

**Issue by six7** [tokens-studio/figma-plugin#1919]
**Note: Work on this in the internal repository on the `next` branch**. Let's introduce tokens of `type: string`!

- Those tokens have a single `Value` input of type string
- Applying that token by default inserts the value into the `node.characters`

**Comment by color2life** [comment]
@six7 can you provide some examples what kind of string tokens we will have?

**Comment by six7** [comment]
for the start this will just replace the node's characters when applied. however, given Figma supports text content in component properties, there is more use to this, wherever a text string is to be inserted.
