### ISSUE TITLE
Scrolling down the dropdown menu also scrolls the plugin screen

### ISSUE THREAD

**Issue by keeganedwin** [tokens-studio/figma-plugin#1925]
**Describe the bug**
When duplicating a token and scrolling down the dropdown, the entire plugin screen also scrolls simultaneously, losing all content until clicked on `cancel` or `duplicate`. 

**Key information:**
This happens in conjunction with scrolling but mainly when moving the mouse in a downwards direction.

**To Reproduce**
1. Click on duplicate token
2. Open the following dropdown menu
3. Scroll down with the mouse while simultaneously also moving the mouse in a downwards direction. 
4. See glitch

https://github.com/tokens-studio/figma-plugin/assets/93133012/9db964f8-a5c0-410a-880d-72235db08b43

**Comment by six7** [comment]
Fixed in 1.38 🚢
