### ISSUE TITLE
Theme groups not respected on URL sync or file import (JSON)

### ISSUE THREAD

**Issue by txcrew** [tokens-studio/figma-plugin#1926]
**Describe the bug**
When a remote (or local) JSON file that contains multidimensional theme groups is synced (or imported), the group data is stripped from themes metadata.

**To Reproduce**
1. Create a multidimensional theme groups and themes
2. upload JSON file to remote source (or export locally)
3. download JSON from report source (or import)
4. Go to themes menu, notice the groups are gone

**Expected behavior**
The groups meta data is persists with each update.

**NOTES:**
This also applies to ADO and JSONBin

**Comment by rbosker** [comment]
@swordEdge this issue is fixed (tested in Development version) by #1970

**Comment by esthercheran** [comment]
Closing this as this is fixed by #1970
