### ISSUE TITLE
Swatch not displaying color for border type

### ISSUE THREAD

**Issue by keeganedwin** [tokens-studio/figma-plugin#1928]
**Describe the bug**
In the `Border-token`, the color-swatch 'only' displays CSS color values and hex values, but does not display `color-token` references. 

**Expected behavior**
Swatch needs to display even referenced color-tokens. 

**Screenshots or Screencasts**
https://github.com/tokens-studio/figma-plugin/assets/93133012/e416a42a-2198-4de4-b2ec-9dcba761a5a3

**Comment by SamIam4Hyma** [comment]
Referenced in Featurebase https://tokensstudio.featurebase.app/p/enhance-color-swatch-functionality

**Comment by SamIam4Hyma** [comment]
Added to Featurebase Request-	[💡🎨 Enhance color functionality across all token types](https://tokensstudio.featurebase.app/p/bulbart-enhance-color-functionality-across-all-token-types)

**Comment by keeganedwin** [comment]
This is bug is reproducible after having tested it in **Prod 1.38.9** and **Beta V2-rc5**. 
![CleanShot 2024-05-14 at 20 32 31@2x](https://github.com/tokens-studio/figma-plugin/assets/93133012/10eff695-afec-4f3a-a89e-8114d2f846fb)
