### ISSUE TITLE
Unable to remove license key

### ISSUE THREAD

**Issue by deepsweet** [tokens-studio/figma-plugin#1935]
**Describe the bug**
I'm unable to completely remove an expired license key – it reappears every time I reopen the plugin along with the red error message about the key being suspended.

**To Reproduce**
1. Go to 'Settings'
2. Click on 'Remove key'
3. Close plugin window
4. Open it again

**Expected behavior**
Key is not there anymore.

**Actual behavior**
1. Key is still there
2. Error message about the key being suspended

Screenrecording:
https://github.com/tokens-studio/figma-plugin/assets/109062656/f142a028-e46a-4a49-b692-df5b70d25a52

**Comment by rbosker** [comment]
relates to: #1590
