### ISSUE TITLE
Add `outline` token type

### ISSUE THREAD

**Issue by lukethacoder** [tokens-studio/figma-plugin#1937]
**Is your feature request related to a problem? Please describe.**

Similar to the way `border` currently works, I would love to see an `outline` option. This would be great for mapping to [`outline`](https://developer.mozilla.org/en-US/docs/Web/CSS/outline) in the web spec. `outline` is a great tool to use, especially when considering accessibility in design.
 
**Describe the solution you'd like**

Creating a new token type called `Token`. It would function similar to the existing `Border` token type.

<img width="542" alt="image" src="https://github.com/tokens-studio/figma-plugin/assets/13529535/d7b4cd25-c502-4673-9c49-7c756b30d04d">

Proposing 4 sub fields as a part of the outline token type:
- `color`
- `width`
- `style`: [outline-style](https://developer.mozilla.org/en-US/docs/Web/CSS/outline-style) - `none` | `dotted` | `dashed` | `solid` | `double` | `groove` | `ridge` | `inset` | `outset`
- `offset`: would map to [`outline-offset`](https://developer.mozilla.org/en-US/docs/Web/CSS/outline-offset)

**Describe alternatives you've considered**

Using the `Box Shadow` token type is somewhat of a work around, but does not allow for `offset` line outline does.

**Additional context**

N/A

**Comment by six7** [comment]
We're currently sticking close to the W3C DTCG spec for any new token types, so this one is not on the list so far.

**Comment by SamIam4Hyma** [comment]
@six7 proposing to archive as outline as a token type not in the spec today and we will be aligning with new token types as they appear moving forward
