### ISSUE TITLE
on switch theme --> colors on library components not applied in figma

### ISSUE THREAD

**Issue by tada-seilebri** [tokens-studio/figma-plugin#1939]
**Describe the bug**
when I switch the theme in token studio the colors of Library components don't change.

**To Reproduce**
1. Use the attached Token Files and you can also use the attached Figma Files
2. Make sure that the setup is as described

> 1. Have a Figma File (MASTER Screen Collection) with local color styles
> 2. Publish the Figma File 'MASTER Screen Collection' as Library
> 3. Have a 2nd Figma File 'DEV Source WIP' consuming the 'MASTER Screen Collection'
> 4. Define in 'DEV Source WIP' components (main-navigation) using the colors from 'MASTER Screen Collection'
> 5. Publish 'DEV Source WIP' as a library
> 6. In 'MASTER Screen Collection' consume 'DEV Source WIP' as a library and use the component 'main-navigation'
> 7. In 'MASTER Screen Collection' create a Figma Branch (e.g. 'Demo')
> 8. Go to the new Figma Branch 'Demo' and open the Token Studio for Figma

3. In Token Studio for Figma activate "Update styles"; switch to another Theme (e.g. KIDS) and press "Apply to document" 

**Expected behavior**
The Libary component 'main-navigation' is shown in the correct colors in Figma. 
Same color as shown in Token Studio in inspect mode
<img width="674" alt="image" src="https://github.com/tokens-studio/figma-plugin/assets/125663070/b9494ce0-1416-4672-82df-1d2b7ec8683f">

And the same color showed in Figma in the Selection Colors section
<img width="571" alt="image" src="https://github.com/tokens-studio/figma-plugin/assets/125663070/580c6b48-c229-44c7-b43a-c56d9c143203">

Some side note - For local components this seems to work
<img width="776" alt="image" src="https://github.com/tokens-studio/figma-plugin/assets/125663070/3aaea3e3-3d08-4727-8cf5-e3ff14318a94">
<img width="561" alt="image" src="https://github.com/tokens-studio/figma-plugin/assets/125663070/a2e701f1-8636-4110-808f-bfacfe8082eb">

**Figma file (optional)**
[Figma Files.zip](https://github.com/tokens-studio/figma-plugin/files/11650496/Figma.Files.zip)

**JSON (optional)**
[tokens.zip](https://github.com/tokens-studio/figma-plugin/files/11650596/tokens.zip)

**Comment by tada-seilebri** [comment]
Maybe this is a similar / linked issue https://github.com/tokens-studio/figma-plugin/issues/1858

**Comment by keeganedwin** [comment]
Hey @tada-seilebri, were you able to resolve this issue?

**Comment by tada-seilebri** [comment]
Hi @esthercheran, my assignment to the project where I found this issue has ended and I don’t have a Figma Token license anymore.

Ask @wavestyle for help if you need someone to retest.

**Comment by tada-seilebri** [comment]
And no I was not able to solve the issue.

**Comment by SamIam4Hyma** [comment]
@LukeFinch proposing to close as the issue is stale and it will come back up again if it needs to be investigated. If you agree please close.
