### ISSUE TITLE
Lost access to tokens after purchasing Pro version

### ISSUE THREAD

**Issue by MunirAhmedJaved12** [tokens-studio/figma-plugin#1944]
**Description**
I lost access to my tokens after purchasing Pro version. I am getting this error.
Following are the errors that I am getting, although i have checked my credentials multiple times and they are correct.
I have also tried restarting figma as well as token studio plugin. 

**Error syncing with Github. Check credentials.**

**To Reproduce**
1. Open Token studio Plugin.
2. Add new Github
3. Enter Credentials
4. Save Credentials

**Expected behavior**
See repo and tokens

**Screenshots or Screencasts**
<img width="390" alt="Screenshot 2023-06-06 at 4 23 31 PM" src="https://github.com/tokens-studio/figma-plugin/assets/124209266/3fae99f8-3ed5-4ec4-8d96-dd6aefdd89db">

<img width="373" alt="Screenshot 2023-06-06 at 4 19 01 PM" src="https://github.com/tokens-studio/figma-plugin/assets/124209266/c1f9c19a-35b0-4ec4-bb33-b1e22049b040">

**Comment by six7** [comment]
Tokens don't have anything to do with the pro version or not. In your case I assume the tokens aren't stored properly on the source, e.g. GitHub in your case. Make sure the personal access token is still valid and the tokens exist at that path.

**Comment by ilxsil** [comment]
We've regenerated github tokens multiple times(10+) for him and went through 10+ 'Add New' journey in the token plugin, but it still gave us the same error. We tried it on 2 different days too.
I helped troubleshoot other 2 designers in my team. Both had the same error, but it was fixed after we delete tokens in the plugin, regenerated github tokens, and go through the 'Add New' journey once.

**Comment by straef** [comment]
i have run into weird failed credentials when entering project names in the credentials. with pro vs not the file or folder path is also important because pro has access to multi-file tokens. so those are two things that i would noodle with: remove project from credentials and try listing just a folder instead of a specific file ([tokens].json) or vice versa.

**Comment by SamIam4Hyma** [comment]
@LukeFinch this one needs some digging and then it can be closed or remove the archive label and its a bug to be dealt with.
