### ISSUE TITLE
Can I use local font families? 

### ISSUE THREAD

**Issue by melijimenez11** [tokens-studio/figma-plugin#1945]
I'm trying to set my base font family token to a local font, but I can't find it when I search under font family. [Here's where I'm stuck](https://imgur.com/a/G2f7H3Y)
 
Here are the steps:

1. Go to base theme
2. Edit font family token
3. Set the name to my font name
4. Click the dropdown under Font Family
5. Try to search my font name under Fonts > I get "No suggestions found"

My font is installed locally. I'm using the Figma app. When I use the font in my file directly, it all works well. 

How can I fix this? Alternatively, are there any other ways I can change my base font, without having to go manually into every typography style and changing it?

**Comment by six7** [comment]
Hey! Local fonts work as long as they're available in Figma. We're really just communicating with Figma's Plugin API, so we're not doing anything special on top of this. As long as it shows up in Figma, it will show up in the plugin.
