### ISSUE TITLE
Allow TAB function to select entire text when selecting inputs

### ISSUE THREAD

**Issue by keeganedwin** [tokens-studio/figma-plugin#1947]
**Is your feature request related to a problem? Please describe.**
Currently when using the TAB function to select switch/select input fields, the cursor is placed at the beginning of _existing_ text. 

**Describe the solution you'd like**
In case of existing text, it would benefit the users if the entire text is highlighted upon using the TAB function. 

**Current function:**
![CleanShot 2023-06-07 at 12 14 08](https://github.com/tokens-studio/figma-plugin/assets/93133012/e8e582f8-cf9c-4a7b-8793-0a1aafce92f0)

**Expected function:**
![CleanShot 2023-06-07 at 12 16 04](https://github.com/tokens-studio/figma-plugin/assets/93133012/3badb2fd-9b51-4b08-b84a-da330453b19d)

**Comment by UdayHyma** [comment]
Added to Featurebase Roadmap : [🪙 Token organization enhancements
](https://tokensstudio.featurebase.app/p/token-organization-enhancements)

**Comment by UdayHyma** [comment]
Migrated to featurebase
