### ISSUE TITLE
Tokens Color and Typography not swapping

### ISSUE THREAD

**Issue by adavila17** [tokens-studio/figma-plugin#1948]
**Describe the bug**
Using sets to swap defined out token values was working up to a few hours ago while building out in the plugin panel. Several crashes with the plugin dunno if that the latest may have anything to do with it. But yeah swapping works with all but the color and typography styles.

**To Reproduce**
1. Open Plugin
2. Default token set is chosen
3. Checkmark off the default
4. Checkmark the tokens wa want to swap to
5. Select "Apply to Document"
6. Everything swaps as far as what's defined minus font and colors even the Figma Local styles do not swap

**Expected behavior**

Every defined out token should swap

**Screenshots or Screencasts**
<img width="1008" alt="color token values not swapping" src="https://github.com/tokens-studio/figma-plugin/assets/26416133/935d9dd3-4b13-4f10-8cee-5a9b317d6d87">
<img width="927" alt="font token not swapping" src="https://github.com/tokens-studio/figma-plugin/assets/26416133/3643040b-9fb5-441d-bb76-8258408ccce9">

**Figma file (optional)**
https://www.figma.com/file/bK6UIT0Ypc6eUFKWb9YSbD/base-file-rework-(DO-NOT-USE)?type=design&node-id=1%3A6&t=bH38Pt6oNdQD0vZ4-1

**JSON (optional)**
https://learfield.sharepoint.com/:u:/s/SIDEARMCreative/EQ5QgDZU9oBJm30LYTNr1o4ByUjCx5GVAIZKxS87EXPUYw?e=fnVqG6

**Comment by six7** [comment]
It seems your style is called `desktop` but your token is called `epic.desktop` -> the names would need to match. Same for your color style, it seems there's also a discrepancy in naming.

**Comment by keeganedwin** [comment]
Hey @adavila17, were you able to resolve this issue?

**Comment by SamIam4Hyma** [comment]
@six7 propose to close as the issue appears to be related to naming and not something for us to action
