### ISSUE TITLE
Add color modifier support to token-transformer

### ISSUE THREAD

**Issue by fwielstra** [tokens-studio/figma-plugin#1950]
**Is your feature request related to a problem? Please describe.**

Our designer uses Token Studio in Figma, and hands it over to us developers.

We pass the tokens through [token-transformer](https://github.com/tokens-studio/figma-plugin/tree/main/token-transformer) to resolve all the references to concrete color values, then transform it into a Theme object for our [react-native-paper](https://reactnativepaper.com/) components.

In a recent version (Feb? March?) of token studio, support for [color modifiers](https://docs.tokens.studio/tokens/color-modifiers) was added; our designer applied it to the Figma designs.

However, after grabbing the token files and pulling them through token-transformer, the colors in our app are no longer correct; basically, the modifiers are not being applied. The modifiers are retained in the output JSON, but this would mean our application code needs to check for the existence of and apply the modifier itself.

**Describe the solution you'd like**

That token-transformer applies the modifiers, so that a new RGB(A) or hex value is output that can be used in our app.

**Describe alternatives you've considered**

- Writing our own transformer or post-process
- Ask the designer to revert the tokens to hardcoded values (e.g. no longer use color-modifiers)
- Ask the designer if there's a way to export the resolved color values of modified colors
- Manually copying the resolved colors from Figma's generated CSS, but that would be a step back

**Additional context**

Here's a snippet from the token file as we get it / as it's stored in the git repository by token studio; note that the full version contains named colors matching Material Design's naming scheme that will refer to the `ref` set of colors again.

ref.json:

```json
{
  "ref": {
    "color": {
      "base": {
        "grey": {
          "value": "rgb(105, 105, 113)",
          "type": "color"
        }
      },
      "grey": {
        "10": {
          "value": "{ref.color.grey.500}",
          "type": "color",
          "$extensions": {
            "studio.tokens": {
              "modify": {
                "type": "lighten",
                "value": "0.98",
                "space": "srgb"
              }
            }
          }
        },
        "500": {
          "value": "{ref.color.base.grey}",
          "type": "color"
        }
      }
    }
  }
}
```

theme.json:

```json
{
  "sys": {
    "theme": {
      "color": {
        "core": {
          "background": {
            "value": "{ref.color.grey.10}",
            "type": "color"
          }
        }
      }
    }
  }
}
```

The current output; note that in the `ref` colors, it retains the `"$extensions"` key, but in the `theme` it only picks the `value` of `grey.10`.

```json
{
  "sys": {
    "theme": {
      "color": {
        "core": {
          "background": {
            "value": "#696971",
            "type": "color"
          }
        }
      }
    }
  },
  "ref": {
    "color": {
      "base": {
        "grey": {
          "value": "#696971",
          "type": "color"
        }
      },
      "grey": {
        "10": {
          "value": "#696971",
          "type": "color",
          "$extensions": {
            "studio.tokens": {
              "modify": {
                "type": "lighten",
                "value": "0.98",
                "space": "srgb"
              }
            }
          }
        },
        "500": {
          "value": "#696971",
          "type": "color"
        }
      }
    }
  }
}
```

The expected / desired output:

```json
{
  "sys": {
    "theme": {
      "color": {
        "core": {
          "background": {
            "value": "#FCFCFC",
            "type": "color"
          }
        }
      }
    }
  },
  "ref": {
    "color": {
      "base": {
        "grey": {
          "value": "#696971",
          "type": "color"
        }
      },
      "grey": {
        "10": {
          "value": "#FCFCFC",
          "type": "color",
        },
        "500": {
          "value": "#696971",
          "type": "color"
        }
      }
    }
  }
}
```

**Comment by six7** [comment]
token-transformer does support color modifiers!

However I would recommend to start using sd-transforms, as this library will make token-transformer obsolete. http://npmjs.com/@tokens-studio/sd-transforms

**Comment by SamIam4Hyma** [comment]
@six7 looks like from comments this was solved with better guidance and docs. Can we close?
