### ISSUE TITLE
Synching with GitHub Enterprise

### ISSUE THREAD

**Issue by diomededavid** [tokens-studio/figma-plugin#1954]
**Describe the bug**

- Unable to sync with Github Enterprise repo
- Error is "Error synching with GitHub, check credentials"
- tried using both Github 
- Once restarting app or Figma  all tokens are lost and do not recover

**To Reproduce**
1. Go to settings
2. Ensure tokens are added to Tokens Studio prior
3. Add incorrect credentials and allow the setting to fail
4. Get recover message
5. Does not matter if I attempt to recover or not

**Expected behavior**
Ability to sync with Github seamlessly

**Screenshots or Screencasts**

**Figma file (optional)**
Send us the link to a Figma file containing a reproducible example

**JSON (optional)**
If possible, attach the JSON that leads to this bug.

**Comment by UdayHyma** [comment]
[Migrated to Featurebase](https://tokensstudio.featurebase.app/p/git-sync-enhancements)

**Comment by six7** [comment]
Closing as transitioned and we've had reports that GHES works fine
