### ISSUE TITLE
Copying and pasting token path when remapping a token adds extra lines

### ISSUE THREAD

**Issue by keeganedwin** [tokens-studio/figma-plugin#1955]
**Is your feature request related to a problem? Please describe.**
When double clicking to copy and paste a token path in the _remap_ modal, the plugin adds _extra lines_ which forces the user to delete the extra lines first before remapping.

**Describe the solution you'd like**
Allow for users to also double click, copy and paste the path without the extra lines being added.

**Describe alternatives you've considered**
As seen in the recording the current workaround is to drag and select the path and paste it which does not cause for the extra lines error.

**Recording:**
![CleanShot 2023-06-15 at 11 27 22](https://github.com/tokens-studio/figma-plugin/assets/93133012/91a82a1a-a0f5-40ae-8a88-07e3e4f0b467)

**Definition of done:**
- Double clicking the token name in the inspect panel copies the token name
- Pasting it in the remap input field does not add extra lines in the input field

**Comment by LukeFinch** [comment]
This request has been moved to our new feedback tool. Go check out https://tokensstudio.featurebase.app/ to create a free account. You can upvote and comment on existing posts, make a new request, and subscribe to be notified when requests move into our roadmap.

**Comment by UdayHyma** [comment]
Added to Featurebase Roadmap : [🪙 Token organization enhancements](https://tokensstudio.featurebase.app/p/token-organization-enhancements)
