### ISSUE TITLE
[Performance]: GitLab sync takes a long time

### ISSUE THREAD

**Issue by six7** [tokens-studio/figma-plugin#1957]
Syncing with GitLab currently takes a long time if a user has a lot of nested token sets, e.g. files in folders of folders.

We should see if we can speed up that operation. I think what's causing it to take so long is that we walk the tree in a weird way, sometimes taking up to 4 minutes to perform a simple push, for something that is done much faster in other applications.

Some users reported also GitHub sync takes a long time, let's see if we can make fixes to the speed of this here too.

**Comment by six7** [comment]
I remember you mentioned this before @SorsOps - if you have any insights in this feel free to edit the issue description.

**Comment by SamIam4Hyma** [comment]
@six7 is this still an issue? I've labelled as best I can just in case.

**Comment by UdayHyma** [comment]
[Migrated to Featurebase](https://tokensstudio.featurebase.app/p/sync-external-storage-enhancements)
