### ISSUE TITLE
Preserve package.json file

### ISSUE THREAD

**Issue by yringler** [tokens-studio/figma-plugin#1960]
**Describe the bug**
I added some JS to token studio's JSON folder in the repo to build the css. When the designer checked out the branch and pushed a change, the package.json file was changed to `{}`

I would like to have the build code side by side with the JSON (which is how it would generally be done if you were using straight style dictionary).

**To Reproduce**
1. Create a node project (package.json) inside the folder where token studio copies the style dictionary JSON
2. Push a change to the branch from the plugin
3. Observe that package.json is now empty

**Expected behavior**

**Screenshots or Screencasts**
![image](https://github.com/tokens-studio/figma-plugin/assets/4070825/1453188b-323c-4e73-b12a-91eeb2efb544)

**Figma file (optional)**
Send us the link to a Figma file containing a reproducible example

**JSON (optional)**
If possible, attach the JSON that leads to this bug.

**Comment by SamIam4Hyma** [comment]
@LukeFinch this one needs an assessment and labels or closed, I'll add what I can to get you started
