### ISSUE TITLE
SVG Support (Asset 2.0)

### ISSUE THREAD

**Issue by keeganedwin** [tokens-studio/figma-plugin#1961]
**Is your feature request related to a problem? Please describe.**
We currently don't support SVG tokens, could potentially add it as a part of the Asset token (2.0)

**Describe the solution you'd like**
Not sure of the logistics of implementing this feature, will need extra information to this ticket.

**Comment by LukeFinch** [comment]
This request has been moved to our new feedback tool. Go check out https://tokensstudio.featurebase.app/ to create a free account. You can upvote and comment on existing posts, make a new request, and subscribe to be notified when requests move into our roadmap.

**Comment by UdayHyma** [comment]
Added to Featurebase Roadmap : [🪙 📸 Asset token enhancements
](https://tokensstudio.featurebase.app/p/asset-token-enhancements)
