### ISSUE TITLE
Clicking on token in inspect redirects user to token source

### ISSUE THREAD

**Issue by keeganedwin** [tokens-studio/figma-plugin#1965]
**Is your feature request related to a problem? Please describe.**
Users have to manually find the source (from the set and group it's applied from) of the applied token by the search and find method.

**Describe the solution you'd like**
As a possible solution, in the inspect panel maybe clicking on the token can redirect the user to the set/group from which the token is applied. 

**Alternative solutions:**
- I don't think clicking on the name as a link for redirecting would make sense since users also click on the name for copy paste cases. 
- Maybe an icon at the end of the token line that redirects the user?

**Additional context**
![CleanShot 2023-06-21 at 15 10 15@2x](https://github.com/tokens-studio/figma-plugin/assets/93133012/4927f671-5ad9-402b-87ad-bd0123ce2fee)
![CleanShot 2023-06-21 at 15 13 27@2x](https://github.com/tokens-studio/figma-plugin/assets/93133012/ff18bb45-7f8a-4f4e-baa9-cbb3cbe3ac52)

**Comment by esthercheran** [comment]
@keeganedwin what would be the flow when there is multiple token with the same name in different sets? Which one would should it be redirected to?

**Comment by LukeFinch** [comment]
This request has been moved to our new feedback tool. Go check out https://tokensstudio.featurebase.app/ to create a free account. You can upvote and comment on existing posts, make a new request, and subscribe to be notified when requests move into our roadmap.

**Comment by UdayHyma** [comment]
Here's the URL to the featurebase post that is linked to this ticket: https://tokensstudio.featurebase.app/p/enhance-inspect-page-in-the-plugin
