### ISSUE TITLE
Allow creation of Variables from sets (when not using Themes)

### ISSUE THREAD

**Issue by CITguy** [tokens-studio/figma-plugin#1969]
In #2406 an option `Export to Figma` is added on clicking the button `Styles & Variables`

![Image](https://github.com/tokens-studio/figma-plugin/assets/66366384/f790ec40-f759-4e37-8a60-35e2f18f37d0)

If the user is a non-pro user they will have the option to create variables from sets. 

![Image](https://github.com/tokens-studio/figma-plugin/assets/66366384/e2de97eb-94dd-4e46-abf5-eadaf55faafd)

- The number of enabled sets will be shown
- ~Show the summary of variables `Created`, `Removed`, `Changed` and `Issues`~

![Image](https://github.com/tokens-studio/figma-plugin/assets/66366384/7c65339f-e562-4355-8fde-23ac76aa09e3)

- Clicking on `Export to Figma` will create each set as a variable collection. There will be no modes created when creating variables from sets.

A pro user can also create variables from sets by toggling to `Sets`

If a user does not have any tokens created the below screen will be shown:

For non-pro user

![Image](https://github.com/tokens-studio/figma-plugin/assets/66366384/808d26f2-81be-4889-a372-410f746a0af6)

For pro user

![Image](https://github.com/tokens-studio/figma-plugin/assets/66366384/0c5d3d24-744e-4736-a5ba-3baf973e3b63)

-------
<details><summary>Original issue description</summary>
<p>
Allow users using the non pro version of the plugin to create variables from sets.

This is now captured in #2302 

>**Describe the bug**
Clicking Styles & Variables > Create variables doesn't seem to work.

>**To Reproduce**
See Screenshots below.

>**Expected behavior**
I would expect `Local variables` to have been updated to include newly created variables.

>**Screenshots or Screencasts**

>**Step 1: No styles or variables**
![PixelSnap 2023-06-21 at 12 48 15@2x](https://github.com/tokens-studio/figma-plugin/assets/545605/0bc899a4-df92-4077-9278-84232f15738d)

>**Step 2: Click "Create variables"**
![PixelSnap 2023-06-21 at 12 48 48@2x](https://github.com/tokens-studio/figma-plugin/assets/545605/584ae795-0992-4ca9-9a41-359319c68349)

>**Step 3: Result of Step 2**
- No change in Local variables
- No feedback to indicate if action started, succeeded, or failed.
- No console errors or messages to indicate success or failure.

>![PixelSnap 2023-06-21 at 12 49 00@2x](https://github.com/tokens-studio/figma-plugin/assets/545605/0a477cbf-446a-4dcd-a6dc-5442ec11994f)>

</p>
</details>

**Comment by neiltonline** [comment]
the same happens to me

**Comment by six7** [comment]
Make sure you're using `Themes` and `Theme groups`, such as creating a theme called `Light` in a group called `Color`, another theme called `Dark` inside the same group. This will create a collection called `Colors` of the two modes Light and Dark.

https://docs.tokens.studio/variables/creating-variables
as well as https://docs.tokens.studio/variables/references

we'll put some video guides out soon, please let us know if the docs aren't helpful 🙏

**Comment by GRosewarneFever** [comment]
So you have to have the PRO version for it to work?

**Comment by six7** [comment]
Yes for now it only works for the Pro version. Eventually we will change it so it works for Free too but our focus for now is on making sure it works great with Themes. I get the frustration, but time is limited - if you'd like to contribute PRs are welcome 🙏

**Comment by SamIam4Hyma** [comment]
Added to Featurebase Roadmap-	[🚧 ❖❇️ Export styles and variables using sets (free plan) ](https://tokensstudio.featurebase.app/p/export-to-figma-using-token-sets)
