### ISSUE TITLE
Variables: color token with alpha loses the alpha when creating variables

### ISSUE THREAD

**Issue by mihkeleidast** [tokens-studio/figma-plugin#1972]
**Describe the bug**
If a color token has an alpha value:
![image](https://github.com/tokens-studio/figma-plugin/assets/1892091/cb215082-4de1-45d1-9f1a-1f48e766d47b)

And you create variables from such tokens, the resulting variable has no alpha:

![image](https://github.com/tokens-studio/figma-plugin/assets/1892091/999314c0-1198-4f58-b696-8124eb9aaec0)

**To Reproduce**
1. Create a color token that has an alpha value
2. Create variables
3. See that the created variable has no alpha value.

**Expected behavior**
The created color variable should keep it's alpha value.

**Screenshots or Screencasts**
see above

**Figma file (optional)**
-

**JSON (optional)**
-

**Comment by chriskerr-performio** [comment]
+1
