### ISSUE TITLE
when i use like this var,the color no show "linear-gradient({LineGradDeg.default}, {Brand.primary.active} 0%, {Brand.primary.default} 100%)"

### ISSUE THREAD

**Issue by Linhaolong** [tokens-studio/figma-plugin#1973]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots or Screencasts**

**Figma file (optional)**
Send us the link to a Figma file containing a reproducible example

**JSON (optional)**
If possible, attach the JSON that leads to this bug.

**Comment by six7** [comment]
Can you describe the issue you are experiencing? Your issue description is just the template

**Comment by Linhaolong** [comment]
> Can you describe the issue you are experiencing? Your issue description is just the template

“I define a color using a variable, then use another variable to call this color, and then use a third variable to call the second variable. For example, color1=#000000, color2=color1, color3=linear-gradient(180deg, {color2} 0%, #ffffff 100%). However, color3 does not display the color in the panel.”  
![123](https://github.com/tokens-studio/figma-plugin/assets/105919496/8c2ac474-6199-4b3c-9918-06b7ab2f9a3d)
