### ISSUE TITLE
Allow users to select which themes to export as variables

### ISSUE THREAD

**Issue by XavierVilars** [tokens-studio/figma-plugin#1974]
**Allow users to select the themes to be created as variables.**
Currently all themes present are created as variables on clicking `Create Variables`

In #2406 we introduce a new flow for creating variables from the `Export to Figma` option

![Image](https://github.com/tokens-studio/figma-plugin/assets/66366384/5a7ada79-7091-4a7d-b2e0-1b4ba7a620df)

- Allow users to select the themes that is to created as variables
- Only the selected themes groups will be created as Variables collection and the selected themes will be created as modes

This will allow the users to create local variables on different Figma files
#2023 will allow the references of variables from different Figma files to be maintained
-----------------
<details><summary>Original Issue</summary>
<p>
**Describe the bug**
I have 3 Figma files to manage Core, Semantic and Components tokens/variables. 
- Core file to manage Core tokens/variables,
- Semantic file to manage brands and themes related to them. 
- Components file to manage and publish the components library and hold tier 3 tokens (without publishing them).

Today if I open my Core file in Figma and then open Token Studio and enabling only Core sets. Then if I click on 'Create Variables' it created variables for all my tokens in TS, not only the one enabled...

**Expected behavior**
So what I want is to be able to export variables to Figma depending on themes enabled in Token Studio. Not everything, just themes enabled. 
And of course to be able to generate cross references through my Figma Files automatically (if my Core tokens are in a Core file and if in my Semantic file have references to tokens in my Core file I want a cross reference file token to be created).

It's important in term of maintenance because I can't imagine doing everything manually each time I add a token in Token Studio.

Cheers.
</p>
</details>

**Comment by XavierVilars** [comment]
Aslo I was thinking if possible to check the "hide from publishing" checkbox when a set of tokens is used as a source.

**Comment by davidmcneroe86** [comment]
+1

**Comment by esthercheran** [comment]
We have an issue for `Hide from publishing` in #2300 for individual tokens and #2186 for token groups. But was wondering if you have a different use case

**Comment by XavierVilars** [comment]
Hello @esthercheran sorry for the delay I was sick. Yes it could be both token set or theme. And also all token marked as "Source" in a theme. 
My main concern when I wrote this issue was to be able to create my differents variables library (in different Figma file) corresponding to my actual headless design system tiers.
So if you give the possibility to sync token in variables in different file then it will fullfill my need.
