### ISSUE TITLE
Color Modifiers do not carry across to Figma variables

### ISSUE THREAD

**Issue by SorsOps** [tokens-studio/figma-plugin#1975]
**Is your feature request related to a problem? Please describe.**
Currently color modifers are not applied to Figma variables. This is likely to do with non hex based color types

**Additional information:**
This issue is produced only when referencing another color token, not when using plain hex values. 

**Describe the solution you'd like**
Colors should be converted into hex space before creating variables to preserve the modifiers when creating a variable

**Additional context**
![image](https://github.com/tokens-studio/figma-plugin/assets/80043879/58741768-a215-45d3-bcd7-46ee4c109746)

**Related issue:**
Also related to issue #1972 where alpha modifiers don't work with hex values or references.

**Comment by stuffimade** [comment]
I have the same issue - explained here https://forum.figma.com/t/tokens-studio-colors-figma-variables/45827
