### ISSUE TITLE
Allow for Truncation of multiple Font fallbacks

### ISSUE THREAD

**Issue by keeganedwin** [tokens-studio/figma-plugin#1984]
**Is your feature request related to a problem? Please describe.**
The plugin disorderly displays a large amount of font-fallbacks overlapping each other. This is evident in the inspect panel, as well as when referencing/editing a token.

**Describe the solution you'd like**
Allow for the fallback containers/fields to be _truncated_ or as a _dropdown_ for users to be able to view them without being visually disordered. 

**Additional context**
Inspect panel:
![Screenshot 2023-06-23 at 12 52 49](https://github.com/tokens-studio/figma-plugin/assets/93133012/12443131-fa06-48c2-8fd0-dcf6850adbca)

Referencing/editing token:
![Screenshot 2023-05-26 at 08 29 55 (1)](https://github.com/tokens-studio/figma-plugin/assets/93133012/7061e23b-d025-4b71-a281-bb9e06f67729)

**Comment by LukeFinch** [comment]
This request has been moved to our new feedback tool. Go check out https://tokensstudio.featurebase.app/ to create a free account. You can upvote and comment on existing posts, make a new request, and subscribe to be notified when requests move into our roadmap.

**Comment by UdayHyma** [comment]
Here's the URL to the featurebase post that is linked to this ticket: https://tokensstudio.featurebase.app/p/enhance-inspect-page-in-the-plugin

**Comment by SamIam4Hyma** [comment]
Added to Featurebase Request-	[🕵️ Enhance the inspect panel functionality](https://tokensstudio.featurebase.app/p/enhance-inspect-page-in-the-plugin)
