### ISSUE TITLE
Token Values not calculated if one token is a dimension type

### ISSUE THREAD

**Issue by wolfXDnet** [tokens-studio/figma-plugin#1988]
**Describe the bug**
Value calculation fails when using math on multiple tokens of which at least one is a dimension type 

**To Reproduce**
Create a set of token of which one is a dimension type
Tokens used:
- Component.Switch.thumb.padding (10px, dimension type)
- Component.Switch.thumb.size (20, size type)
- Component.Switch.track.height (14, size type)

Create new token using math:
Raw Value:
`.5*( {Component.Switch.thumb.padding} *2 + {Component.Switch.thumb.size} - {Component.Switch.track.height})`

Current Value:
`.5*( 10px *2 + 20 - 14)`

Expected Value:
`13px` or `13`

Same applies when trying to use 'ceil' or 'floor' on a simple math operation using a dimension type token e.g.:
`{Component.Switch.thumb.padding} * 1.125` returns correctly `11.25px`
Where `ceil({Component.Switch.thumb.padding} * 1.125)` returns `ceil(10px * 1.125)` and not `11px` or `11` as expected

**Screenshots or Screencasts**
<img width="530" alt="Screenshot 2023-06-24 at 18 58 15" src="https://github.com/tokens-studio/figma-plugin/assets/56354826/089ca0e6-892e-4330-bbd3-550c56f270fe">

**Comment by six7** [comment]
We currently fail to parse these units when there's some units involved.

Docs on this are here: https://docs.tokens.studio/tokens/using-math#adding-units

@jorenbroekema have you found a way to parse these in a somewhat reliable way for `sd-transforms` ?

**Comment by jorenbroekema** [comment]
Yes, `.5*( 10px *2 + 20 - 14)` gives `13px`.

I always take out the `px` units in expressions, and then if I found a px unit in the expression I'll put it back in the final result after resolving the expression.

**Comment by SamIam4Hyma** [comment]
@six7 @jorenbroekema is this issue something that can be closed? If so please do, if not, remove the archived tag. 

I've noticed a few tickets like this so perhaps we need a content wizard (read me) to make sure this is covered in the new technical docs in detail for using math?

**Comment by jorenbroekema** [comment]
Well no this cannot be closed imo, while this works fine in sd-transforms, the plugin does not reuse its calc math utility afaik, so still bugged there. @roppazvan tagging you coz I commented on your PR with a related comment about reusing utils from sd-transforms and style-dictionary. Maybe something to pick up?

**Comment by LukeFinch** [comment]
This request has been moved to our new feedback tool. Go check out https://tokensstudio.featurebase.app/ to create a free account. You can upvote and comment on existing posts, make a new request, and subscribe to be notified when requests move into our roadmap.

**Comment by SamIam4Hyma** [comment]
Added to Featurebase Request-	[Math in value enhancements ](https://tokensstudio.featurebase.app/p/math-in-value-enhancements)
