### ISSUE TITLE
"Apply to..." remove all variables references to other files.

### ISSUE THREAD

**Issue by FossilsCompany** [tokens-studio/figma-plugin#1993]
**Describe the bug**
If I've got a list of variables refering to external variable (published variables in Figma) then if I click on "apply to..." in Token Studio all references are replace by the value...

**To Reproduce**
1. Open Token Studio and load your tokens.
2. Click on "create variables"
3. Redo all references of your variable so they are correctly bind to external published variables in Figma
4. Click on "Apply to this document"
5. Then all your references are replaced by harcoded value.

**Expected behavior**
References should be kept.

Tks.

**Comment by keeganedwin** [comment]
Hey @FossilsCompany, would it be possible for you to share a recording of this issue please?

**Comment by FossilsCompany** [comment]
Hello, sorry I just see your reply now... Ok so it seems the issue is corrected.
