### ISSUE TITLE
Variables are in a plane list

### ISSUE THREAD

**Issue by FossilsCompany** [tokens-studio/figma-plugin#1994]
**Describe the bug**
I'm using sets and group of sets in Token Studio to organize my token. I want to be able to choose to apply this structure in my variable list too.

**To Reproduce**
1. Create variable from Token Studio
2. Groups no longer exists.

tks.

**Comment by six7** [comment]
Can you elaborate in more detail? I'm not sure I follow what's the issue here. Do you mean that your groups no longer exist? Because we do keep groups when creating variables:



![Image](https://github.com/tokens-studio/figma-plugin/assets/4548309/26a15961-ee9a-4baa-8093-43eb49c165e0)

**Comment by six7** [comment]
Closing, feel free to reopen
