### ISSUE TITLE
When switching to variables, border radius becomes borderradiusTopLeft

### ISSUE THREAD

**Issue by rbosker** [tokens-studio/figma-plugin#1995]
**Describe the bug**
When switching to Variables, a BorderRadius which applies to all corners, shows as borderRadiusTopLeft

**To Reproduce**
1. Apply a border radius to all corners
2. Switch to Variables
3. Only TopLeft radius shows in inspect.

**Note**
When only using variables, the border is applied correctly.

**Screenshots or Screencasts**
First part video untill 1:20: https://www.loom.com/share/c5d0c14751b64546842014103ef8999d

**Comment by swordEdge** [comment]
@six7 @rbosker This is because of the API bug. I discussed with Jan already.

**Comment by six7** [comment]
Seems to be working now
