### ISSUE TITLE
When working with Variables, borderColor is applied as style instead of Variable

### ISSUE THREAD

**Issue by rbosker** [tokens-studio/figma-plugin#1996]
**Describe the bug**
When working with Variables, borderColor is applied as Style instead of Variable. This works for fill, but for BorderColor the style gets applied.

**Expected behavior**
The Variable to be applied as border color instead of the Style.

**Screenshots or Screencasts**
2nd part video from 1:20 > https://www.loom.com/share/c5d0c14751b64546842014103ef8999d

**Important information:**
If there is no style existent in the file, then there is no variable applied either.

**Screenshots:**
![CleanShot 2023-06-27 at 15 46 36@2x](https://github.com/tokens-studio/figma-plugin/assets/93133012/a4b4387d-c155-4f45-ae74-eb87e12c8a1b)

**Comment by bewarai** [comment]
yeah I have the same issue, no border var attached. Very annoying when I want to switch form styles to vars. Hope gets fixed soon.
