### ISSUE TITLE
Variables: when syncing with ADO the link to variables get lost.

### ISSUE THREAD

**Issue by rbosker** [tokens-studio/figma-plugin#1997]
**Describe the bug**
When using variables and Azure DevOps, pushing/pulling causes issues with the Themes data (also reported losing Groups: #1981 ). The Variables link is gone and can't be used anymore (in the same file or different file).

**To Reproduce**
1. Create variables
2. Push to ADO
3. Pull from ADO
4. Themes information is gone.

**Expected behavior**
The Variables/Themes option to be synced for ADO properly. For other syncing providers this is working as expected. 

**Note**
Information is not present in the JSON file (see screenrecording for examples).

**Screenshots or Screencasts**

https://github.com/tokens-studio/figma-plugin/assets/109062656/fa3c70f1-4623-4813-8c5a-cf1abf1df875

**Comment by beauroberts** [comment]
@rbosker FYI while investigating a further issue in #1981 I discovered that [`src/storage/schemas/multiFileSchema.ts`](https://github.com/tokens-studio/figma-plugin/blob/main/src/storage/schemas/multiFileSchema.ts#L8) is missing some keys, so these values get filtered out by the schema validator.
