### ISSUE TITLE
Import and Sync variables from Figma to Token Studio

### ISSUE THREAD

**Issue by XavierVilars** [tokens-studio/figma-plugin#1999]
Currently our variables feature is only offering a one-way operation, meaning we create variables from the plugin. Users have requested the need to do both ways, they want to import existing variable collections into the plugin. We can do that using Themes.

Definition of done:
- Add an entry `Import variables` to the Styles & Variables menu
- //UPDATE: Create all the local variables as tokens. [This will be picked up in later iteration: When clicked, open a dialog that lets users pick from local variable collections, showing the collection name and the modes inside. Users can check/uncheck all collections they want to import. By default, check all.]
- When importing, try to see if there's existing theme groups / themes with the name matching that Collection and modes. If not, create a new theme group and theme matching those names. 
- When a new theme group / mode is imported, also create matching sets for it.
- Let the user choose what happens with overrides, using the same dialog that appears when users Import styles where they see the before / after value and can decide.
- If users import variable references to another collection, properly create those as references, such as `{colors.gray.500}`
- For created variables, check if we can store the last created variable raw value inside the variable's sharedPluginData so that we can compare the raw value, not the actual value // UPDATE: This does not work. Figma does not allow us to set shared plugin data on variables

---

<details><summary>Original issue description</summary>
<p>

**Is your feature request related to a problem? Please describe.**
Today it is not possible to add variables from Figma in Token Studio. Figma is proposing a new Ui to do the same job as Token Studio. And if I decide to work on my token using Figma then I want to be sure there will be sync back to Token Studio as well.

**Describe the solution you'd like**
Buttons "Sync from Fimga" and "Sync from Token Studio" to create/import/export/remove variables and tokens to Token Studio or Figma. I need a 1/1 between Figma and Studio without thinking too much about it (no need to tell if I want to change update variable's names or things like that). 

</p>
</details>

**Comment by SamIam4Hyma** [comment]
There is also the job to be done that is related to this ticket which should be considered in the solution if possible (: 

I have variables set up in Figma (via Tokens Studio) and I edited the variables in Figma and I want to connect them to my design tokens that match

**Comment by six7** [comment]
Released in 1.38.8

**Comment by SamIam4Hyma** [comment]
Added to Featurebase Roadmap with more details on how Sync is working -	[❖ 🪄 Sync variables and styles is now Export to Figma](https://tokensstudio.featurebase.app/p/sync-styles-and-variables-is-now-export-to-figma)
