### ISSUE TITLE
Moving groups deletes/merges other groups

### ISSUE THREAD

**Issue by keeganedwin** [tokens-studio/figma-plugin#2002]
**Describe the bug**
In the `manage themes` dropdown when you move groups around - especially when moving groups **into** other groups - the plugin deletes other existing groups.

**To Reproduce**
1. Go to 'manage themes'
2. Drag a 'group around or into another group'

**Expected behavior**
The plugin should not merge groups when dragged around or into other groups

**Screenshots or Screencasts**
https://github.com/tokens-studio/figma-plugin/assets/93133012/b23b16e0-c769-4f15-aea9-0089c3ea756d

**Comment by esthercheran** [comment]
Closing this as resolved
