### ISSUE TITLE
"Create varbales" and "Sync vaiables" are greyed out

### ISSUE THREAD

**Issue by StanLaurent** [tokens-studio/figma-plugin#2003]
**Describe the bug**
Even if I create a new clean file and create local variables or tokens in Token Studio, the options are greyed out.

**To Reproduce**
1. Open the dropdown
2. 
![image](https://github.com/tokens-studio/figma-plugin/assets/109153151/6d9d9df9-6cc5-4cd9-abf2-ec209cf811ed)

**Expected behavior**
The options are not disabled

**Comment by Joanie324** [comment]
I am seeing this as well.

**Comment by Joanie324** [comment]
This is happening on the Pro plan as well. I just upgraded to Pro so I could use this single feature, but the options are still greyed out.

**Comment by keeganedwin** [comment]
@StanLaurent @Joanie324 you need your Themes defined in order to be able to create variables.
