### ISSUE TITLE
Store header secrets for Generic Versioned Storage

### ISSUE THREAD

**Issue by SorsOps** [tokens-studio/figma-plugin#2004]
**Describe the bug**
Copied verbatim from  https://tokens-studio.slack.com/archives/C02DLQXNY6Q/p1687866270998469
```Hey I’m wondering if what I’m encountering is a bug or a feature (or something wrong on my end).
Whenever I add a generic versioned with an api key in the header its automatically shared with all users in the file (so person X adds a generic versioned sync with header abcd, now person Y has the same generic versioned sync in their plugin with header abcd)
Im wondering if this is a bug / feature / something going wrong on my end. :slightly_smiling_face:
```

It appears that the secret headers are not being stored in the backend secret storage like PAT tokens, etc

**To Reproduce**
1. Create a generic versioned storage adapter
2. Add secret headers
3. Use a seperate user in a file and confirm that the headers are accessible

**Expected behavior**
Secrets in the header should be obscured from other users

**Todo**

1. Either implement a per header checkbox that marks a header as sensitive and store it in the backend 
2. Set all headers to be sensitive and store as a background secret

**Comment by UdayHyma** [comment]
[Migrated to Featurebase](https://tokensstudio.featurebase.app/p/sync-external-storage-enhancements)
