### ISSUE TITLE
Improve Input Field Legibility by Enabling Name Wrapping

### ISSUE THREAD

**Issue by keeganedwin** [tokens-studio/figma-plugin#2006]
**Is your feature request related to a problem? Please describe.**
When aliasing a gradient token in the input-field, the token name is cut-off. When creating tokens that have multiple references in them, trying to add 5x reference tokens to create a gradient or complex math function is a hinderance. 

**Describe the solution you'd like**
The input-field should wrap along with the token name to be legible for the user.

**Screencapture:**
![Screenshot 2023-06-28 at 8 38 10 AM](https://github.com/tokens-studio/figma-plugin/assets/93133012/455ef931-8402-4e03-b2d1-0e005d078a3f)

**Comment by six7** [comment]
I think it'd be great if the input automatically grew if we notice it is wider than what the input allows. I wouldn't change to a textarea by default, but grow by user demand. We'd need to make sure the left-side of the input is still properly aligned to the top but spans the full height as well.

**Comment by SamIam4Hyma** [comment]
This was the last issue I submitted before I joined the team via Keegan. 🫶

**Comment by SamIam4Hyma** [comment]
@LukeFinch tagging you here to selfishly push this into one of the future releases. I've set up some labels for V2.X but feel free to add more and add as needed.

**Comment by LukeFinch** [comment]
This request has been moved to our new feedback tool. Go check out https://tokensstudio.featurebase.app/ to create a free account. You can upvote and comment on existing posts, make a new request, and subscribe to be notified when requests move into our roadmap.

**Comment by UdayHyma** [comment]
Added to Featurebase Roadmap : [🪙 Token organization enhancements
](https://tokensstudio.featurebase.app/p/token-organization-enhancements)
