### ISSUE TITLE
'Sync variables' action should ignore renamed Figma Variables that retain a connection to an existing Token and not create a new token

### ISSUE THREAD

**Issue by atlas-ui** [tokens-studio/figma-plugin#2008]
First of all, thank you for being proactive with the Figma variables update, it's been fairly easy for us to create variables from our existing token sets.

**Steps to reproduce**

- Use the action `Create Variables` on an existing set of tokens with kebab syntax e.g. `icon-small`
- Rename a the generated Figma variable to `Icon/small`
- Add a new token in the Token Studio plugin called `icon-medium`
- Use the action `Create Variables`
- Use the action `Sync variables`

**Expected behavior**
Token Studio creates one new variable called `icon-medium`and recognizes that `icon-small` has been renamed and is already created.

**Current behavior**
Token Studio generates an `icon-small` and `icon-medium` variable and sees `icon-small` as a new token despite it being linked to the existing renamed variable Icon/small.

**Comment by six7** [comment]
I was not able to reproduce, we might have this fixed already.

However, I did encounter a bug where using `Sync variables` creates the variable twice, even though it should detect the rename correctly. I'll use this issue to track this work.

If you're still able to reproduce the original bug, let me know 🙏

**Comment by esthercheran** [comment]
@six7 @atlas-ui I am unable to recreate either of the issues

**Comment by SamIam4Hyma** [comment]
Added to Featurebase Roadmap as a known issue to avoid duplicate tickets -	[❖ 🪄 Sync variables and styles is now Export to Figma](https://tokensstudio.featurebase.app/p/sync-styles-and-variables-is-now-export-to-figma)

**Comment by six7** [comment]
Completed in 2.0
