### ISSUE TITLE
Allow for Truncation of Branches

### ISSUE THREAD

**Issue by keeganedwin** [tokens-studio/figma-plugin#2011]
**Is your feature request related to a problem? Please describe.**
Studio currently displays the branch in multi-line

**Describe the solution you'd like**
Truncate the branch name, and maybe display (open) it only upon clicking. 

**Additional context**
![image (3)](https://github.com/tokens-studio/figma-plugin/assets/93133012/dc781492-3579-4ad2-bfbf-b2a36e285910)

**Comment by UdayHyma** [comment]
[Migrated to Featurebase](https://tokensstudio.featurebase.app/p/git-sync-enhancements)
