### ISSUE TITLE
Variables Not Created when Tokens are referenced from another Set

### ISSUE THREAD

**Issue by keeganedwin** [tokens-studio/figma-plugin#2012]
**Describe the bug**
When referencing an `opacity` token from another set, Studio does not create the calculated value as a variable.

**Key information:**
This does however work when an opacity token is being referenced from within the same set. 

**To Reproduce**
1. Create a token with a RGBA value + referencing an `opacity` token from another set
2. Create a token with a RGBA value + referencing an `opacity` token from within the same set
3. Create variables 

**Expected behavior**
The opacity token being referenced from within the same set has a calculated value when variables are created, the token referencing opacity from another set does not

**Screenshots or Screencasts**
![CleanShot 2023-06-29 at 18 41 41@2x](https://github.com/tokens-studio/figma-plugin/assets/93133012/e923b8d8-4cf4-4671-91e2-7f8acf260005)

![CleanShot 2023-06-29 at 18 41 54@2x](https://github.com/tokens-studio/figma-plugin/assets/93133012/a0d7c5ee-49bb-482c-8ebe-e3babd9f596c)

**Comment by swordEdge** [comment]
Aleady fixed. @keeganedwin 
![image](https://github.com/tokens-studio/figma-plugin/assets/25951419/bc05cb38-8948-49b2-9463-4ce055c29209)

**Comment by keeganedwin** [comment]
@swordEdge It works when referencing tokens within the **same** set, not when referencing from other sets:
![Image](https://github.com/tokens-studio/figma-plugin/assets/93133012/bf8eac86-f90a-41db-9851-cce5ed1d73d9)

**Comment by keeganedwin** [comment]
This issue is also present with dimension tokens. 

When referencing both dimension tokens within a `set` and adding mathematical operations, the calculated result is created as a variable.  

**Screenshot:**
![CleanShot 2023-07-26 at 17 41 23@2x](https://github.com/tokens-studio/figma-plugin/assets/93133012/eeba2308-9c9f-4acb-a91a-a49a2b4b599a)

**Bug:**
When referencing one dimension from another set and referencing a dimension token from the current/active set with mathematical operations, the calculated result is not not created as a variable

**Screenshot:**
![CleanShot 2023-07-26 at 17 42 43@2x](https://github.com/tokens-studio/figma-plugin/assets/93133012/06ed076a-542f-4f74-84b8-64855d984684)

**Comment by six7** [comment]
I think this is also related to https://github.com/tokens-studio/figma-plugin/issues/2059

Adding to current iteration

**Comment by swordEdge** [comment]
Confirmed this is resolved with @keeganedwin
