### ISSUE TITLE
Boolean values are represented by strings

### ISSUE THREAD

**Issue by niggeulimann** [tokens-studio/figma-plugin#2013]
**Describe the bug**
The json-representation of the new boolean flags are not boolean but strings. Unfortunately this breaks the style-dictionary-export....

**To Reproduce**
1. create a boolean token
2. switch to the json-representation
3. it looks like this
`"TEST TOKEN": {
    "value": "true",
    "type": "boolean"
}`
which is not parsable by the style-dictionary.

**Expected behavior**
The value has to be a boolean - not string
`"TEST TOKEN": {
    "value": true,
    "type": "boolean"
}`

**export**
https://configurator.tokens.studio/#project=rVVdb9MwFP0rVxFS2yltJB54aAEhsY1JSIBoxQuZmJvcLC6JHdnOWBXlv3NtJ2mTwV4gD61zP889PrGbIJEi4/erg5YiWAdNLADiQMtaJRgHa/huDdZ0cRFdrIz8iUK74DiwntvQJ1QFM5lUpbY5TZ+T6PN3azGKCW0DPyhZV9ZJNld0qU2dchkH4Sm6UpjxRx+l05FrX/Mi/cJM7r3uNaJ+0Sgq4wXqszHs05yWNiRFbbhghtuRbKkfD0xxtqfElcMfjuMteGZ8qO03RHtC/NP2y1u/aMOeksO/MfLHsQ//YerT0IfnZz6wB6YTxSsToX717ND2j37aIAwU3nNtUG0vr2uR2La2EQmOl5VUBrbmWOAldx6mjpApWcJMW+syHcyzTSy6hAb6krueQA1tl/duRGCk0+XAsrY1YhFFMLKG8FKkUDHFSqSaQEaQlcMJCROwR2BpiqnL3CJCKhO9htyYSq+j6J6bvN6vEllGz7SOxVPM88nkix4ePrKyKhAeWFEjDEVC+JXzJIdDrQ1RYGpFCE1OEbYvMA2c+kyKrp70nTs9mGOFfvOpR7frghiwtvL4nlrIckjp/CSEJEe1hrnruIA3b6Hx+h5ATt1eDx6tB7oBGvH1cnnKsdAFouPYy2bRMeHVBzkWFSrtt3iqjFjQOaatLKz4b5ClqMIu02D6rVc3SeTNVGwrH3bj60/5p2+8q/N3Wq+d33Pq+Zv19HnXzPHTwyF2su4rmDenGUKHPex11y564vrRZG2q2nzFDBWKpBumi96MOL570Zx4mLt1u2jXSkpji5L3CTPzzkbYaeRZCOfApp2pGG3Q3WbYKlrRV+5Ff35LDFeKcAfJ7mq7g93nj1efRvdEpz939KlBie50JIV2R52UBbLu2nGnSvsb

**Comment by SamIam4Hyma** [comment]
@jorenbroekema is this still an issue? I've added some labels for SD and transformation in case it is. If not feel free to close with comment.

**Comment by jorenbroekema** [comment]
This is an issue still but it seems to me that it is an issue in the figma plugin, boolean token values are serialized as string values in the JSON format, by the plugin?

**Comment by niggeulimann** [comment]
Thanks a lot, that looks much better!
