### ISSUE TITLE
Show a warning in the plugin when you’re switching to Multi-dimensional themes that you need to switch over fully

### ISSUE THREAD

**Issue by rbosker** [tokens-studio/figma-plugin#2014]
**Is your feature request related to a problem? Please describe.**
Show a warning in the plugin when you’re switching to Multi-dimensional themes that you need to switch over fully, so without ungrouped themes.

**Describe the solution you'd like**
Give a clear error that the themes are not properly configured.

**Describe alternatives you've considered**
Discussed in call about SD Transforms/Configurator

**Comment by six7** [comment]
I'm not sure I understand the intent here, can you elaborate @rbosker ? What is the warning? Why is it needed?

**Comment by SamIam4Hyma** [comment]
@jorenbroekema is this still an issue? If so, can we close? @rbosker perhaps you have more insight?

**Comment by rbosker** [comment]
no issue anymore > this was for switching over to multi-dimensional themes, when we introduced the feature.

**Comment by SamIam4Hyma** [comment]
Closing this issues as its no longer an issue.
