### ISSUE TITLE
Variables color modifiers: strange behaviour on saving a modified color

### ISSUE THREAD

**Issue by rbosker** [tokens-studio/figma-plugin#2015]
**Describe the bug**
Create and sync variables seems to work good in combination with color modifiers, only if you save a color modified token, you get unexpected behaviour.

**To Reproduce**
See screen recording. In this test 'update on change' was checked, but 'update styles & variables' were not checked.

**Screenshots or Screencasts**
https://github.com/tokens-studio/figma-plugin/assets/109062656/058c4f5b-ae33-47aa-ad46-ac1147b62771

Relates to: https://github.com/tokens-studio/figma-plugin/pull/1989

**Comment by keeganedwin** [comment]
Issue is still present
https://github.com/tokens-studio/figma-plugin/assets/93133012/41b7afcd-91f0-4bb3-bfb7-ed619cd48125

**Comment by rbosker** [comment]
issue fixed with linked pull request
