### ISSUE TITLE
Changing References does not Auto-update Variables

### ISSUE THREAD

**Issue by keeganedwin** [tokens-studio/figma-plugin#2016]
**Describe the bug**
Changing the reference of a token does not `auto-update` the variable. If a user is using a Hex color-value, then the variable is auto-updated. When using a reference as a value, the variable is only updated upon clicking `sync variables`.

**To Reproduce**
1. Change the token to a hex-value - **variable auto-updated**
2. Change the token to a reference
3. **See error**

**Expected behavior**
The variable should also be auto-updated when changing a token-value to a reference. 

**Screenshots or Screencasts**
https://github.com/tokens-studio/figma-plugin/assets/93133012/48dc66f2-6f19-44e9-8126-4de6c6309f12

**Comment by swordEdge** [comment]
https://github.com/tokens-studio/figma-plugin/assets/25951419/83a36dd2-450d-469b-91b9-eb6abc244255

This issue has been fixed in the past.

**Comment by six7** [comment]
@keeganedwin can you confirm this is fixed on the `epic/performance` branch?

**Comment by keeganedwin** [comment]
@six7 I tested it on my end but feel there's something wrong with me trying to test this in the correct branch. However, I was on call with Robbert who tested it and it works, so can confirm.
