### ISSUE TITLE
Add support for referencing non-local variables

### ISSUE THREAD

**Issue by vnys** [tokens-studio/figma-plugin#2023]
Users need to be able to publish their variable collections into different files. The plugin currently does not allow that. Currently, when users hit `Create variables`, we create all possible variable collections, making it impossible to spread them out to different files. With the work in #2211 we'll have a Dialog that asks users what collections and tokens to create from, meaning we should now be able to have variables that can be references to other files variables.

**Definition of done:**
- When a token references another token from another collection, do not just check the local file, but instead if the token is part of another collection, use the reference from that. We do have the collection and mode id stored in `$figmaVariableReferences`, so we should be able to detect those remote references too.

---

<details><summary>Original issue description:</summary>
<p>
In order to allow design system designers to share core tokens across multiple files, I need to publish core tokens as variables in a separate Figma library.

I’d like there to be an option when exporting tokens from Tokens Studio where I can choose which themes to export, so that only the core tokens are imported in the core file – instead of having to delete unwanted collections afterwards.

I’d also like to be able to export only the semantic tokens without breaking the connection to the core tokens if there are non-local core tokens available in the file.

</p>
</details>

**Comment by yapjonathan** [comment]
+1

It would be great if we're able to approach it similarly to non-local styles. Right now, creating variables will create all of them even if I have a theme set that is marked as source.

**Comment by SimonLeclercq** [comment]
+1 absolutely need it!

**Comment by danvpeterson** [comment]
To keep managing our tokens in TS this is possibly a requirement for us. I'm looking at what changes we need to make now to support variables, and keeping our base tokens in a separate from our semantic tokens feels like a necessity at first glance. Digging in to see if I can figure out a workaround, but would love to see this added!

**Comment by six7** [comment]
> To keep managing our tokens in TS this is possibly a requirement for us. I'm looking at what changes we need to make now to support variables, and keeping our base tokens in a separate library from our semantic tokens feels like a necessity at first glance. Digging in to see if I can figure out a workaround, but would love to see this added!

you could just have everything in 1 library, but mark the Collection that is not supposed to be exposed as "hide from publishing". We do support having multiple Collections.

**Comment by chongchizhang** [comment]
Currently, the plugin does allow creating Variables in different files. However, when we need to update (ex: change a name of a token for all Variables across different files), it will not sync the change for the file that doesn't have matching Variables IDs. I have recorded a [video](https://drive.google.com/file/d/1vb6foSXZ_PCVKnJ5THOamvWEkVUJjave/view?usp=sharing) here to demonstrate what I mean.

**Comment by danvpeterson** [comment]
> you could just have everything in 1 library, but mark the Collection that is not supposed to be exposed as "hide from publishing"

Unfortunately we need to be able to use them within the design system team in other files so we can't just hide from publishing. We reference base tokens in some component specific tokens (not many, but it's a need we've found). And we don't want a mono-library where all variables and all components are in the same file to make this work.

**Comment by LukeFinch** [comment]
This request has been moved to our new feedback tool. Go check out https://tokensstudio.featurebase.app/ to create a free account. You can upvote and comment on existing posts, make a new request, and subscribe to be notified when requests move into our roadmap.

**Comment by UdayHyma** [comment]
Added to Featurebase Roadmap : [❖ ❇️ Non-local support of variables and styles
](https://tokensstudio.featurebase.app/p/non-local-support-of-variables)

**Comment by six7** [comment]
Reopening as we're actively working on this, hoping to get it into 2.0 still.

**Comment by six7** [comment]
Closing this, will be part of 2.0 and the next release candidate.
