### ISSUE TITLE
Monaco editor is being loaded in via CDN

### ISSUE THREAD

**Issue by SorsOps** [tokens-studio/figma-plugin#2027]
**Describe the bug**
Currently the monaco editor is being loaded via CDN

![image](https://github.com/tokens-studio/figma-plugin/assets/80043879/34141065-5f0f-4809-bfd8-3eb95161facd)

This impacts offline capabilities if a user has no opened the JSON editor prior to losing connect.

In addition, the Monaco editor is attempt to load a webworker which is throwing an unnecessary error in the error tracking 

```
{
arguments: [
Uncaught NetworkError: Failed to execute 'importScripts' on 'WorkerGlobalScope': The script at 'https://cdn.jsdelivr.net/npm/monaco-editor@0.36.1/min/vs/base/worker/workerMain.js' failed to load.
], 
logger: console
}
```

This is currently responsible for **1.5K** errors in our telemetry

**To Reproduce**
1. Go offline
2. Open the plugin
3. Goto the json inspector

**Expected behavior**
The JSON monaco editor works if I open it and do not have internet connectivity

An error is not thrown regarding the webworker execution

**Comment by six7** [comment]
Note: This is default Monaco behavior. We should however look into either providing a fallback raw textarea that is shown to the user if Monaco cannot load, or attempt to fix this so that the Monaco editor loads even without internet, or in some cases, the CDN being blocked by the user's ISP.

**Comment by LukeFinch** [comment]
Could we use the webpack plugin for this? https://github.com/microsoft/monaco-editor/tree/main/webpack-plugin

We're also passing our schema to monaco for validation - which is on a uri, so that will need offlining too somehow.

**Comment by six7** [comment]
Removing from current sprint, feels like something we want to do as a 2.0 followup rather.

**Comment by six7** [comment]
I'm going to close this out, havent heard this issue reported by users
