### ISSUE TITLE
Remapping Tokens Changes the 'Apply To' Setting

### ISSUE THREAD

**Issue by keeganedwin** [tokens-studio/figma-plugin#2031]
**Describe the bug**
After remapping a token and selecting an option to update all token layers, the _`Apply To`_ setting is changed according to the option selected in the modal. 

**To Reproduce**
1. Select an initial 'Apply to' setting
2. Rename a token
3. Check Page or Document
4. See error - 'Apply to' changes to the option checked

**Expected behavior**
Have the plugin retain the initial selected setting, and not change based on the option selected when remapping a token. 

**Screenshots or Screencasts**
https://github.com/tokens-studio/figma-plugin/assets/93133012/d970e3c4-3775-4d47-b6b8-269522d20256

**Comment by six7** [comment]
Shipped in 1.37.10
