### ISSUE TITLE
Add an all tokens, or active tokens, option to the Token tab

### ISSUE THREAD

**Issue by jeromefarnum** [tokens-studio/figma-plugin#2032]
**_As a product designer using Token Studio, I should have an option to view all tokens that are currently available within the constraints of the active theme options from a single view in the Tokens tab, so that I can quickly find and use a token._**

**Is your feature request related to a problem? Please describe.**
As a design system team we provide a multi-dimensional set of themes with axes on color mode, dimensional scaling, density, and brands. In order to provide tokens for all those dimensions in a reasonably maintainable way we have token definitions spread across over a dozen files. Our product designers, or design system users, are experiencing a significant amount of friction with the current UX of the Tokens tab as they have to guess at which file in the left navigation will contain the token that they want to use.

**Describe the solution you'd like**
I think our product designers, and all users of Token Studio, would experience greatly improved token discoverability and reduced frustration when searching for a token if there was an option to populate the Tokens tab with all tokens available with the currently selected theme or theme options. This would put all available tokens at the designers fingertips, presumably enable a global search of the entire token set using the search bar at the top of the Token tab, and effectively let our product designers use the tokens without having to learn or concern themselves with the file structure of the token themes. I'd expect that most of the time they'd collapse the left navigation and simply choose tokens from the master list and change theme options as needed.

I think this could be relatively easily addressed (from a design and UX perspective, no comments on implementation difficulty) by adding an "All Tokens" option at the top of the file list, similar to how Figma does with the "All variables" option in the variables editor:
<img width="535" alt="image" src="https://github.com/tokens-studio/figma-plugin/assets/1072935/825af888-5518-430d-8b16-88334c780689">

As these values would be calculated against the current theme configuration, one challenge I could see arising is if a user attempted to Edit a token from the proposed "All Tokens" view, since that view is an aggregate of several files at any particular point in time. One approach would be to edit the token definition from whichever file is being expressed for that particular token at that moment, perhaps changing the menu option from "Edit token" to "Edit token in [filename] file". Another would be to simply forgo the ability to edit the token while in the "All Tokens" context.

**Describe alternatives you've considered**
1. We've made some attempts to mitigate this by having a 'base' tokens file that includes an instance of each token in the system as the top file in our token package file sets, that we synchronize to our "default" theme values. This has created another set of challenges as it causes us to maintain an extra set of duplicate token entries in our token packages. Additionally, the concept of "default" is increasingly difficult to define as our token theming options have expanded. Our implementation of this approach has been difficult to get to work as expect with "Create styles" and "Create variables" features; requiring us to manually update style/variable references in the $themes.json files to get sensible results. Some early experiments lead us to believe that we would have to refactor our token themes away from this 'base' file approach if we want to effectively use Token Studios variable creation feature.
2. We've also experimented with using our token transform tool to generate a product designer only (read only) version of our token package. This process creates single files with definitions for all tokens for each permutation of our theme options. While this is sort of workable, it doesn't scale well as we add more theming options and are generating an ever increasing number of files. This approach requires that we QA a larger set of design outputs for our token themes, build non-trivial logic into our token pipeline, and to pay special attention to Figma style and variable references as we generate in these files.

Both approaches, while mitigating the overall issue to a certain extent, don't provide relief for all Token Studio users, deviate from DRY principles, and feel like anti-patterns for maintaining and scaling design token usage across our organization.

**Comment by jeromefarnum** [comment]
Here is a mockup of one way this might be handled:

![image](https://github.com/tokens-studio/figma-plugin/assets/1072935/b3add0ca-de02-4e53-b519-0a57ab27ac70)

**Comment by six7** [comment]
One thing I'd add here is that `Create token`, `Edit token`, `Delete token` as well as `Duplicate token` would work very differently in this view. The plugin currently works very set-centric (and should move away from that a bit), but I'd see huge value in this feature so I'd like to see it sooner than later.

I would suggest for the short term we do the following:
### Create token
When users hit `+` to create a new token in any category while viewing `All tokens`, we show a dropdown letting users choose which token to create in.

### Edit token
When users hit `Edit token` show a secondary menu showing all the token sets this token exists in, letting them choose the one they want to edit

### Delete token
When users hit `Delete token`, show them a secondary menu showing all sets this token exists in, but add an additional `Delete from all sets`. When clicking a set, it would delete from that set (or all)

### Duplicate token
When users hit `Duplicate token` let them choose the token from the original set they want to copy from.

---

Note that these are not ideal, and as a user I just want a single `Edit` operation. This would require a refactor of how we let users edit tokens (and show values from other sets side by side for example, or with a simple switch), but that can be a second step and one we include in a general refactor of Editing.

**Comment by jeromefarnum** [comment]
@six7 this request feels a little similar to #1139

**Comment by LukeFinch** [comment]
This request has been moved to our new feedback tool. Go check out https://tokensstudio.featurebase.app/ to create a free account. You can upvote and comment on existing posts, make a new request, and subscribe to be notified when requests move into our roadmap.

**Comment by UdayHyma** [comment]
Added to Featurebase Roadmap : [🪙 Token organization enhancements
](https://tokensstudio.featurebase.app/p/token-organization-enhancements)
