### ISSUE TITLE
Support min and max width/height

### ISSUE THREAD

**Issue by HumixRenco** [tokens-studio/figma-plugin#2034]
**Is your feature request related to a problem? Please describe.**
There is no way to assign a token to the min or max width/height functionality in Figma.

**Describe the solution you'd like**
I would like to assign a width/height value as min or max value and keep the element it's applied to, to remain on fill instead of switching to fixed.

**Describe alternatives you've considered**
Create a min/max width token but not apply it to the element. Additionally we inform Dev that we want the element to have a min/max width.

**Additional context**
The Figma plugin docs have been updated to support the following:
1. https://www.figma.com/plugin-docs/api/node-properties#maxheight
2. https://www.figma.com/plugin-docs/api/properties/nodes-counteraxisspacing

([**Slack thread**](https://tokens-studio.slack.com/archives/C02JAL48UDN/p1687429323574419))

**Comment by jamesrdavis** [comment]
- Providing the option of the min and max height and width when using control and click on a sizing token.
- Allow composition tokens to set min and max height and width.
