### ISSUE TITLE
Allow selection of an existing token set when launching plugin from a new file 

### ISSUE THREAD

**Issue by jac31885** [tokens-studio/figma-plugin#2040]
**Is your feature request related to a problem? Please describe.**
When launching the plugin on a new file, I must select a 'new empty file' and then go into settings to select an existing token set or load an example file.

**Describe the solution you'd like**
It would be great to be able to load from existing hosted token sets when launching the plugin on a new file.

**Additional context**
Screen when loading plugin on new file.
<img width="498" alt="Screenshot 2023-07-07 at 12 00 22" src="https://github.com/tokens-studio/figma-plugin/assets/17296208/612b0279-b96c-46b1-a76f-8c193bff87cc">

Could be something like?

![image](https://github.com/tokens-studio/figma-plugin/assets/17296208/aabe3f1b-5c60-49b8-b920-d0e5ab9b4ee6)

**Comment by esthercheran** [comment]
@jac31885 Would it helpful to have a link on the startup screen directly to the settings page to apply an existing sync provider?

**Comment by jac31885** [comment]
@esthercheran Yeah, I think that would be a good solution. That would also be good if you already had a repo and just needed to add the settings.

**Comment by esthercheran** [comment]
@jac31885 other than this, is there a use case that I am missing here?

**Comment by jac31885** [comment]
@esthercheran not that I can think of currently.

**Comment by UdayHyma** [comment]
[Migrated to Featurebase](https://tokensstudio.featurebase.app/p/token-organization-enhancements)
