### ISSUE TITLE
Add support for more unobfuscated telemetry

### ISSUE THREAD

**Issue by rbosker** [tokens-studio/figma-plugin#2049]
Currently for replays , we mask everything by default. This should be the default policy, however there may be cases where an error is due to some additional specific data that the user is inputting. For this we need to add a checkbox to disable masking if enabled by the user to assist with debugging 

DOD 

- Add mask checkbox in settings
- Persist user settings to storage
- An example replay to show that unmasking works correctly

**Comment by six7** [comment]
I'm wondering if we should punt on that, as of now we haven't had a use for this?
