### ISSUE TITLE
Auto complete broken for Typography tokens

### ISSUE THREAD

**Issue by rbosker** [tokens-studio/figma-plugin#2051]
**Describe the bug**
When you want to reference any typography (font family, weight etc) in a Typography token, the auto complete doesn't show any available options.

**Note**
You can still reference when typing the token without using the auto complete.

**Screenshots or Screencasts**
https://github.com/tokens-studio/figma-plugin/assets/109062656/abf734c2-db61-4d88-bcda-9d16360a1b4d

**Comment by tobiasBurkill** [comment]
I'm also experiencing this same issue. Even tried uninstalling figma (as I couldn't find a way to just remove the tokens studio plugin) and reinstalling to check it wasn't an update issue.

**Comment by davidmcneroe86** [comment]
Experiencing this too

**Comment by sosafe-matias-bejas** [comment]
Same bug here as well.
