### ISSUE TITLE
Change boxShadow values from `x` and `y` to `offsetX` and `offsetY`

### ISSUE THREAD

**Issue by six7** [tokens-studio/figma-plugin#2052]
The [W3C DTCG draft for shadows](https://tr.designtokens.org/format/#shadow) specifies the following format for boxShadow tokens:

```
{
  "shadow-token": {
    "$type": "shadow",
    "$value": {
      "color": "#00000080",
      "offsetX": "0.5rem",
      "offsetY": "0.5rem",
      "blur": "1.5rem",
      "spread": "0rem"
    }
  }
}
```

That is different to what we specify today:

```diff
{
  "shadow-token": {
    "$type": "shadow",
    "$value": {
      "color": "#00000080",
-      "x": "0.5rem",
-      "y": "0.5rem",
+      "offsetX": "0.5rem",
+      "offsetY": "0.5rem",
      "blur": "1.5rem",
      "spread": "0rem"
    }
  }
}
```

We should make sure that when users are working in the DTCG compliant version that their `x` and `y` properties are being saved as `offsetX` and `offsetY`, and we pick them up accordingly. We do not have to still listen for the old values, but we should make sure that when users switch to the DTCG compliant version that we transform their properties to `offsetX` and `offsetY`, and when they work in the old version that we detect `x` and `y`.

**Comment by six7** [comment]
Still blocked by https://github.com/tokens-studio/figma-plugin/issues/999

**Comment by SamIam4Hyma** [comment]
Added to Featurebase Roadmap-	[❇️ W3C DTCG Spec boxShadow values JSON schema ](https://tokensstudio.featurebase.app/p/w3c-dtcg-spec-boxshadow-values-json)

**Comment by SamIam4Hyma** [comment]
closing as not planned for now, we can reopen when the time is right. 

It is linked to Added to Featurebase Roadmap- [W3C DTCG Spec boxShadow values JSON schema](https://feedback.tokens.studio/p/w3c-dtcg-spec-boxshadow-values-json)
