### ISSUE TITLE
Add ID to track token usage

### ISSUE THREAD

**Issue by SorsOps** [tokens-studio/figma-plugin#2056]
We currently do not have support to uniquely identify tokens. Since tokens could use the same name between sets , when we squash the sets down for token resolution, we cannot track which tokens are currently being applied, nor can we detect the difference between deleting a token and recreating it, or editing an existing value.

For this we need to store a [UUID ](https://en.wikipedia.org/wiki/Universally_unique_identifier) on token creation. 

This is also useful for our storage adapters like Tokens Studio or Supernova that work on a per token basis rather than a per set

Since this is a new change for tokens we should store this within the $extensions property of a token 

DOD 

- Add id property on token within extensions
- Duplicated tokens should generate a new ID
- It should not fail if duplicate ids are detected( This might happen due to user error in storage)
- We should attempt to stop users from editing the id in json
- We should add a utility to generate Ids for older tokens to enrich them with ids if they do not exist.

**Comment by six7** [comment]
Few open questions:

Do we need this for all users or opt-in? I kind if think it needs to be opt-in, but open to hearing other thoughts.

How do we deal with tokens with the same name across different sets? Should these have the same id? If not, how do we make sure applying a token from one set properly applies the other one?

How do we prevent users from editing the id in their json outside the plugin, eg in git storage?

**Comment by SorsOps** [comment]
IDs should be completely unique as they will likely need to be tracked by the remote provider across sets.

I'd like it to be opt in tbh. There is a side effect of altering the schema of the tokens and causing a large amount of changes to be shown on a commit for a user.

Editing outside the plugin should be fine, if a user changes an id we treat it as if another token has been applied. I mainly just want to prevent user error if they are using the json editor(as unlikely as that is) . We should probably just automatically create new ids if a user copy pastes in tokens that do not have ids

**Comment by six7** [comment]
Agree, sounds great to me!
