### ISSUE TITLE
Change sync frequency

### ISSUE THREAD

**Issue by SorsOps** [tokens-studio/figma-plugin#2061]
We are currently checking our remote providers every 3 seconds for changes. 

This is causing issues for users as they are hitting rate limits which then throws additional errors in sentry.

We should allow users to select their autosync frequency in the settings  so that they can throttle the plugin if need be

**Comment by six7** [comment]
I'd suggest we change this to 60 seconds, which shouldn't be an issue with rate limits. I would not make this configurable.
