### ISSUE TITLE
Format Documentation Token Values

### ISSUE THREAD

**Issue by keeganedwin** [tokens-studio/figma-plugin#2064]
**Is your feature request related to a problem? Please describe.**
Currently when applying documenting tokens using 'Value', the plugin applies the JSON in-line.

**Describe the solution you'd like:**
1. Option to automatically format the JSON (line-wrapping etc)
2. Option to display the value in YAML format (more readable) (e.g. fontSize: {fontSize.displayXL})

**Screenshots:**
![image (5)](https://github.com/tokens-studio/figma-plugin/assets/93133012/67478b63-4e1d-4771-a433-bf277df9a03f)

**Key information:**
This is also applicable when documenting `Composition` and `Border` token types.

**Comment by six7** [comment]
I'd say we should add something to `Settings` that lets users configure how to treat complex tokens in Documentation, and possibly have a section about Documentation values. Users have mentioned they'd like some control over the output of values.

```
Documentation tokens
- Composition tokens: [Raw JSON (current), JSON with line wrapping, YAML]
```

There'd be more options for e.g. how colors are treated, in the future.

**Comment by keeganedwin** [comment]
Migrated to [Featurebase](https://tokensstudio.featurebase.app/p/documentation-and-annotate)

**Comment by UdayHyma** [comment]
[Migrated to Featurebase](https://tokensstudio.featurebase.app/p/documentation-and-annotate)
