### ISSUE TITLE
Allow reordering between different token groups

### ISSUE THREAD

**Issue by six7** [tokens-studio/figma-plugin#2065]
When users need to rearrange their tokens, they can do so only within the same token group now, and only when the token are not `numbers`.

We should expand that, and also allow:
- Moving a token to another group
- Moving a token to the root
- Moving a token group to a different place

@keeganedwin can you create some mocks for this?

**Comment by keeganedwin** [comment]
Here's the link to the Figma file with the mockups: https://www.figma.com/file/F7Pp2Jqfs28VLJfJ5ttwm4/Studio-Mocks?type=design&node-id=0%3A1&mode=design&t=mAPO1ZsVcC7Wr0Yy-1

Add or tag me in the file if there something needs to be worked on

**Comment by six7** [comment]
> @six7, is this something we could put in for the next iteration? Do I need to expand on it anymore? A user on twitter mentioned that this is one feature that would help as users could then manipulate token-group positions just via the plugin UI and not through any code editor. 

Let's add it with a P2 or so - It's a smallish item that would make a lot of people happy.

**Comment by UdayHyma** [comment]
[Migrated to Featurebase](https://tokensstudio.featurebase.app/p/token-organization-enhancements)
