### ISSUE TITLE
Allow setting a `sort` on tokens in Settings

### ISSUE THREAD

**Issue by six7** [tokens-studio/figma-plugin#2066]
Some users would prefer their tokens to always be ordered alphabetically. This would remove the need to reorder anything, and would lead to predicable outcome.

Definition of done:
- Introduce an option in `Settings`: `Order alphabetically` with a description `When enabled, your tokens, token sets, and token groups will be ordered alphabetically automatically.`
- When this setting is disabled, do what we do today
- When this setting is enabled, keep tokens automatically sorted alphabetically
- When this setting is enabled, keep token sets automatically sorted alphabetically.

**Comment by SamIam4Hyma** [comment]
@LukeFinch and another one for your future planning.

**Comment by LukeFinch** [comment]
This request has been moved to our new feedback tool. Go check out https://tokensstudio.featurebase.app/ to create a free account. You can upvote and comment on existing posts, make a new request, and subscribe to be notified when requests move into our roadmap.

**Comment by UdayHyma** [comment]
Added to Featurebase Roadmap : [🪙 Token organization enhancements
](https://tokensstudio.featurebase.app/p/token-organization-enhancements)
