### ISSUE TITLE
Differentiate `variable` icon in Inspect depending on what was applied

### ISSUE THREAD

**Issue by keeganedwin** [tokens-studio/figma-plugin#2067]
**Describe the bug**
We currently show a `variable` icon next to the applied item in the `Inspect` tab. Right now, we do this only when users have applied a `Variable` without using the plugin. It's hard to understand when a token was applied, when a token was applied which is using a variable, and when just a variable without any token connection was applied.

We should make that easier to distinguish.

- When a token is applied which in turn applies a variable: Do what we do today (no icon)
- When a token is applied which in turn does **not** apply a variable: Do what we do today (no icon)
- When a variable is applied through Figma which does **not** have a token connected: Show the variable icon, in the `Tokens` tab do **not** mark any token as "active" even though the name matches
- When a variable is applied through Figma which **would** have a token connected: Show the variable icon, in the `Tokens` tab **mark the token as active** because it has a variable/token connection

**Comment by LukeFinch** [comment]
This request has been moved to our new feedback tool. Go check out https://tokensstudio.featurebase.app/ to create a free account. You can upvote and comment on existing posts, make a new request, and subscribe to be notified when requests move into our roadmap.

**Comment by UdayHyma** [comment]
Here's the URL to the featurebase post that is linked to this ticket: https://tokensstudio.featurebase.app/p/enhance-inspect-page-in-the-plugin
