### ISSUE TITLE
Highlight currently selected token within drop down when editing or duplicating a token

### ISSUE THREAD

**Issue by tristanpeters237** [tokens-studio/figma-plugin#2073]
**Is your feature request related to a problem? Please describe.**
When editing or duplicating a token, I am frustrated by having to carefully scroll though a very long list of tokens in order to find the token that is currently being referenced, so I can change it to the next in the list - i.e. changing from color.background.primary to color.background.secondary

**Describe the solution you'd like**
As a first iteration I would like to see the currently selected token highlighted so that it stands out when scrolling fast. Secondly, an in an ideal world, I would like the drop to open where the selected token is within the list.

**Describe alternatives you've considered**
Typing in the token name, but this often results in a not found error.

**Additional context**
We have hundreds of tokens and repeatedly scrolling through them reduces efficiency and builds frustration in the team.

**Comment by UdayHyma** [comment]
[Migrated to Featurebase](https://tokensstudio.featurebase.app/p/greenheart-v2-quality-of-life-enhancements)

**Comment by SamIam4Hyma** [comment]
Added to Featurebase Request-	[🪙 Token organization enhancements](https://tokensstudio.featurebase.app/p/token-organization-enhancements)
