### ISSUE TITLE
Theme Settings for Figma and Development

### ISSUE THREAD

**Issue by keeganedwin** [tokens-studio/figma-plugin#2074]
**Is your feature request related to a problem? Please describe.**
Currently, when working with themes in GitHub, users find themselves repeatedly modifying settings to enable _sets_ for when creating styles in Figma, and then switching them back to _source_ for development purposes when running Style Dictionary. This process can be cumbersome and error-prone.

**Describe the solution you'd like**
Implement a way for users to switch between Development and Figma settings which should then be applied when running Style Dictionary.

**Comment by six7** [comment]
Can you give some more context on this? Why were they not using `Themes` for this? Themes let you easily toggle from one configuration to another. Is it because of the need to create a Theme for a `Core` configuration for Figma Variables? 

Any Slack thread to link to?

**Comment by keeganedwin** [comment]
Here's the slack link: https://tokens-studio.slack.com/archives/C02JAL48UDN/p1688890517400129

**Comment by vkogmail** [comment]
I do use themes to create Figma Styles, but I don't want to create them for every 'theme'.
For instance, I do have component tokens for Light / Dark, but in order not to flood my figma file with styles, I don't create styles for the underlying Light/Dark Semantic tokens.

Now to accomplish this I have to turn off/on the create styles checkbox, which I sometimes forget...
So my idea was, what if you could manage that a bit easier, like 'set as source" but in a different way.

**Comment by keeganedwin** [comment]
Another used-case:

> The problems we have been facing are conflicts between developers and designers. They set up a theme configuration that works well for creating variables in Figma, but it causes issues on the development side. When they adjust it to work properly on the development side, it creates issues on the designer side. They suggest having the ability to create two (or more) distinct theme configurations, allowing them to choose which one will be used by developers and which one will be used for Figma.
Like creating:
- “Dev config” with themes configured for the Devs
- “Figma mobile config” with themes configured for the mobile designer team
- “Figma web config” with themes configured for the web designer team

**Comment by LukeFinch** [comment]
This request has been moved to our new feedback tool. Go check out https://tokensstudio.featurebase.app/ to create a free account. You can upvote and comment on existing posts, make a new request, and subscribe to be notified when requests move into our roadmap.

**Comment by UdayHyma** [comment]
Added to Featurebase Roadmap : [🌜Theme management (pro) enhancements](https://tokensstudio.featurebase.app/p/theme-management-enhancements)
