### ISSUE TITLE
Refactor Duplicate token to not duplicate the same set and improve UX

### ISSUE THREAD

**Issue by keeganedwin** [tokens-studio/figma-plugin#2077]
We implemented the `Duplicate token` feature in a way where it also lets users duplicate into another set in the same go as the regular Duplicate operation.

I'd say let's move `Duplicate to other set` to its own operation.

To do:
- Remove the `Set` input from the Duplicate token form
- Add a `Duplicate to other set` option to the right click menu of tokens
- Introduce this to token groups as well
- When clicked, show a dialog that shows the user the same input we show today, letting them pick token sets. By default, nothing is selected.
- In that dialog, do not show the current set and let users not pick from the current set
- Allow users to select multiple sets in this dialog still

<details><summary>Original issue description</summary>
<p>

**Describe the bug**
When duplicating a token, even though the current set is _deselected_ and the intended set is selected for duplication, the plugin still duplicates a token within the active (deselected) set. 

**To Reproduce**
1. Edit token
2. Deselect current set
3. Select set to duplicate token in
4. Duplicate token
4. See error 'token is also duplicated in the current set'

**Expected behavior**
The plugin should only duplicate the token into the selected set. 

**Screenshots or Screencasts**
https://github.com/tokens-studio/figma-plugin/assets/93133012/1da1362b-edb9-4a2d-a531-f88ec52c81a0

</p>
</details>

**Comment by alexkovachevic** [comment]
One additional thing -- it is not allowing me name it the same in another set (possibly because it is duplicated in the same set)

**Comment by rbosker** [comment]
Linking #2165 , that is showing the issue mentioned in the comments by @alexkovachevic

**Comment by SamIam4Hyma** [comment]
Closing this issue as not planned as its been migrated to featurebase - [🪙 Token organization enhancements](https://tokensstudio.featurebase.app/p/token-organization-enhancements)

Please click the link to create a free account and upvote the request so we can notify you when we start working on it. 🚀
