### ISSUE TITLE
Cannot deselect a `dimension` token once it has been set

### ISSUE THREAD

**Issue by tristanpeters237** [tokens-studio/figma-plugin#2078]
**Describe the bug**
Cannot deselect a`dimension` token once it has been set

**To Reproduce**
1. Select a rectangle
2. Click on a token within `dimension` to apply it
3. Route 1 - Try to deselect token by clicking on token does not deselect token
4. Route 2 -  Right clicking to bring up menu and trying to deselect either Height or Width from there does not deselect token
5. Route 3 - Selecting Inspect tab, check token, click remove, does not deselect token
6. Route 4 - Changing the Width or Height value in the Frame panel within Figma UI does remove token

**Expected behavior**
1. Clicking a selected token should deselect that token
2. Right clicking a selected token and clicking either Height or Width should deselect that as a token value
3. Selecting a token with Inspect tab and clicking remove  should deselect that token

**Screenshots or Screencasts**

**Figma file (optional)**
Send us the link to a Figma file containing a reproducible example

**JSON (optional)**
If possible, attach the JSON that leads to this bug.

**Comment by six7** [comment]
Fixed in 1.38 🚢
