### ISSUE TITLE
Second screen is adding a space after reference selection causing issues when syncing to variables

### ISSUE THREAD

**Issue by jackbrind** [tokens-studio/figma-plugin#2090]
**Is your feature request related to a problem? Please describe.**
When using second screen to add a token (in this example a color token) in the value field, when selecting another token to reference (e.g. palette.blue.500) a space is added after the token value. This is fine in the plugin but when creating the variable using the Create Variables option, the reference is invalid because it has a space on the end of the referenced value.

**Describe the solution you'd like**
Remove spaces when referencing variables or ignore when creating figma variables

**Describe alternatives you've considered**
N/A apart from ensuring that the space is manually removed when adding the token reference.

**Additional context**
It took me a while to determine why it wasn't working - the token itself was converted into the Figma variable but the value it was created with was just a hex #FFFFFF. This is fine when creating the variable from tokens created in the plugin, it's just when creating tokens in second screen.
I appreciate second screen is in beta so issues like this are expected but I wanted to flag in any case.

**Comment by six7** [comment]
cc @roppazvan

**Comment by XavierVilars** [comment]
Just seeing this right now after 3 hours spent on the secondary screen (very usefull by the way).
