### ISSUE TITLE
Streamlined token editing experience (edit tokens directly)

### ISSUE THREAD

**Issue by molecule-raz** [tokens-studio/figma-plugin#2093]
**Is your feature request related to a problem? Please describe.**

There are a lot of clicks to edit a single token. Steps:
1. Right click the token
2. Select edit
3. Edit the value
4. Save

Especially in the beginning of the process when token values change often, it takes a long time to update tokens. I tried the second screen plugin as well, but it works the same way. 

This can be quite frustrating when there is a project deadline.

**Describe the solution you'd like**

I would love to edit tokens directly, similar to Figma's variables. After opening the variables window, the steps are:
1. Edit token (directly)

**Describe alternatives you've considered**

I've considered that some people might want the edit-save pattern to prevent making a mistake. If we want to keep that pattern, perhaps there could be a single edit button that enables edit mode. Once activated, people can update tokens directly. Then users can click save once.

**Additional context**

n/a

**Comment by mikekamminga** [comment]
The spreadsheet view allows direct editing and keyboard navigation. This should speed up editing, including batch editing.

**Comment by SamIam4Hyma** [comment]
@molecule-raz have you tried the `cmd/ctrl + click` keyshort to access the edit menu?

**Comment by SamIam4Hyma** [comment]
@LukeFinch I feel like this is in the same relm of what you are thinking about.
