### ISSUE TITLE
Option to disable application of tokens when clicked (or edit vs use mode)

### ISSUE THREAD

**Issue by molecule-raz** [tokens-studio/figma-plugin#2094]
**Is your feature request related to a problem? Please describe.**

I often accidentally click on a token in the plugin and apply it's value to a figma element I previously selected. Sometimes I forget that I have an object off screen. After hours of work, I scroll around my page and realize I've applied a lot of tokens. This can be frustrating as it takes a lot of time to fix.

**Describe the solution you'd like**

Ideally, it would be nice if there were two separate experiences.
1. Edit mode (to edit tokens). Clicking doesn't apply tokens.
2. Use mode (to use tokens). Clicking on a token applies it to the selected Figma element.

By separating the content into two views / modes, IMO it opens up the future development to specialize and streamline the experience for each view (edit view can have additional controls that view mode doesn't have, and vice versa... e.g.m Multi-edit, etc.)

**Describe alternatives you've considered**

Another solution could be that it's an option users could toggle.

**Additional context**

n/a

**Comment by six7** [comment]
Funny enough the plugin had a dedicated Edit Mode / View mode switch in the early days, but I removed it as it was barely used.

I think we might want to reintroduce that in some other form, for example a spreadsheet view or so similar to Figma's Collections screen.

**Comment by six7** [comment]
Out of interest, have you tried [Second screen](https://docs.tokens.studio/sync/second-screen)?

**Comment by LukeFinch** [comment]
This request has been moved to our new feedback tool. Go check out https://tokensstudio.featurebase.app/ to create a free account. You can upvote and comment on existing posts, make a new request, and subscribe to be notified when requests move into our roadmap.

**Comment by UdayHyma** [comment]
Added to Featurebase Roadmap :[🪙 ➕ Apply token workflow enhancements
](https://tokensstudio.featurebase.app/p/apply-token-workflow-enhancements)
