### ISSUE TITLE
Feat: create variables & synchronize variables programmatically by API

### ISSUE THREAD

**Issue by SimonLeclercq** [tokens-studio/figma-plugin#2095]
**Is your feature request related to a problem? Please describe.**
Just as we generate our CSS, Compose & SwiftUI variables thanks to style-dictionary when the JSON provided by Tokens Studio is merged through a GitHub action, we'd also like to be able to create and synchronize Figma variables.

**Describe the solution you'd like**
At merge on main, we'd like to trigger the creation and synchronization of Figma variables in a Figma branch of a given file (probably thanks to Figma REST API). Once this Figma branch has been merged (probably thanks to Figma webhook), a second GitHub pull request would appear to update the `$themes.json` accordingly.

**Describe alternatives you've considered**
Today we do it manually, but it's a real pain (tons of improvements / feats / refactors every day).

Thanks in advance for your help!

**Comment by six7** [comment]
Out of interest, are you on the Enterprise plan? Figma's REST API does allow Write to Variables, but only for users on Enterprise.

So basically this feature request would not be about something inside the plugin, but rather about something elsewhere that is able to trigger Figmas REST API, right?

**Comment by SimonLeclercq** [comment]
Agree, this is something that should trigger the Figma's REST API. We had imagined that this could be supported by TS's ability to generate variables. Like a tool that listens to GithHb and triggers the variable creation feature proposed by TS.
Since you have a lot of xp in plugin design, we'll ping you. if you have any tips or advice, we'd love to hear from you 👍

**Comment by SamIam4Hyma** [comment]
@six7 this might need to have a status change updates [based on this note](https://www.figma.com/file/kJzDs5dA0ytcFgYCWQATdp/Variables-Planning?type=whiteboard&node-id=437-3142&t=LqylntnEFo9LGZDM-11)

**Comment by UdayHyma** [comment]
[Migrated to Featurebase](https://tokensstudio.featurebase.app/p/git-sync-enhancements)
