### ISSUE TITLE
Allow To Manually Select Input-field

### ISSUE THREAD

**Issue by keeganedwin** [tokens-studio/figma-plugin#2097]
**Is your feature request related to a problem? Please describe.**
When editing a token, the user selects the value field to edit, but the plugin automatically selects (auto-focus) the name-field for the user to edit.

**Key information:**
User only seems to be facing this issue on a Windows system. 

**Describe the solution you'd like**
Allow the user to select the field they want to edit.

**Additional context**
https://github.com/tokens-studio/figma-plugin/assets/93133012/84afa36b-de36-47dd-9b83-e340ad206ebf

**Comment by six7** [comment]
Reason for that is likely the 50ms timeout we have on focusing the first input. I've never been able to work around that, but maybe someone else wants to pick that up.

https://github.com/tokens-studio/figma-plugin/blob/4a2253d1375a8d3dc2f9018321d1d5f6df437a63/src/app/components/Input.tsx#L187

**Comment by six7** [comment]
Shipped in 1.37.10
