### ISSUE TITLE
When there is an ongoing task in the plugin, starting another task leads to unexpected results

### ISSUE THREAD

**Issue by esthercheran** [tokens-studio/figma-plugin#2098]
**Describe the bug**
When there is an ongoing operation in the plugin (eg switching theme), if another operation is started (eg create color token and apply color token) the following happens:
- whole operation takes unusually long time
- the second action appears not to take place (eg applying of color token)
- any other operation after this takes unusually long time

**To Reproduce**
1. Switch theme on a large Figma document
2. When the operation is still onoing, create a new color token
3. Apply the color token 
4. The color token does not apply and it takes long time to finish the first operation

**Expected behavior**
If a new task is started during an ongoing task, the tasks should merge instead of happening one after the other.

**Screenshots or Screencasts**

https://github.com/tokens-studio/figma-plugin/assets/66366384/05342857-c22b-4751-878b-f0165670ccd9

**Comment by six7** [comment]
Not able to reproduce anymore on the `epic/performance` branch.
