### ISSUE TITLE
Variable reverts back to old value on published variables

### ISSUE THREAD

**Issue by esthercheran** [tokens-studio/figma-plugin#2107]
**Describe the bug**
When using variables created by the plugin and published as a library we encounter a behavior that reverts the variable back to old values even after changing the value of the token and variable.

**To Reproduce**
1. Create variables from the plugin and push to remote sync
2. Publish the variable library in Figma, enable library in file A and use tokens connected to variables. Eg `color.primary`
3. Change `color.primary` in the plugin in the library file, sync variables, push to remote, publish library changes 
4. Pull tokens from remote in the plugin in file A, accept incoming library updates. `color.primary` has the new changes and can be switched between modes in Figma UI
5. Switch the theme from theme dropdown in the plugin, `color.primary` variable reverts back to the original value and Figma file has incoming updates again

**Expected behavior**
Once change is pushed to remote from plugin and library changes are published and accepted in Figma. The variable should not revert back to old values

**Screenshots or Screencasts**

https://github.com/tokens-studio/figma-plugin/assets/66366384/ec453d81-c577-4b91-876a-f540a7b344d0

**Comment by six7** [comment]
Marking as `Blocked by Figma` as this is a Figma bug with their plugin API I reported to them today.

**Comment by SamIam4Hyma** [comment]
@esthercheran is this issue still occuring? I assume if @six7 reported to Figma 6 months ago it might not be but I could be wrong. If it's solved please close.
