### ISSUE TITLE
Provide a way to start a blank project on the plugin after connecting to a preset or remote storage

### ISSUE THREAD

**Issue by esthercheran** [tokens-studio/figma-plugin#2108]
**Is your feature request related to a problem? Please describe.**
I would like to create a blank project even after connecting with a preset, remote storage or tokens on local document. Currently a blank project can only be created on a new Figma file where there is no tokens, not connected to a preset or remote storage. 

**Describe the solution you'd like**
An option to create a blank project at any point in the workflow. If there are tokens in the local document, they will be deleted so appropriate warning needs to be in place.

```[tasklist]
### Tasks
- [ ] Design required
```

**Comment by UdayHyma** [comment]
[Migrated to Featurebase](https://tokensstudio.featurebase.app/p/settings-page-enhancements-v2)

**Comment by UdayHyma** [comment]
[Migrated to Featurebase](https://tokensstudio.featurebase.app/p/settings-page-enhancements-v2)

**Comment by SamIam4Hyma** [comment]
Added to Featurebase Request-	[Token template requests](https://tokensstudio.featurebase.app/p/enhancements-when-starting-a-new-project)
