### ISSUE TITLE
Save raw token value when creating / updating styles or variables

### ISSUE THREAD

**Issue by six7** [tokens-studio/figma-plugin#2115]
Currently when we update the value of a style or variable, we do so in a way that is destructive. Meaning, when we have token values that Figma doesnt recognize, we convert it to just a raw hex output, or a raw number.

However, this is an issue if users later want to import styles or variables back into the plugin, as we will not know the raw value of it anymore.

Definition of done:
- When creating or updating styles, save the raw value that leads to this in the sharedPluginData space that we can set on styles
- When creating or updating variables, save the raw value that leads to this in the sharedPluginData space that we can set on variables
- When importing styles from Figma to the plugin, dont just compare the output value, instead compare the shared plugin data.

We can then later on use this information also in DevMode to display the applied token values for applied styles or variables.

https://www.figma.com/plugin-docs/updates/2023/10/27/version-1-update-80/

**Comment by SamIam4Hyma** [comment]
@six7 

I think we need to adjust this ticket to be out of scope or backlog as [per this note](This one is out - not possible in Variables) but I could be wrong 

![CleanShot 2023-11-08 at 16 22 29@2x](https://github.com/tokens-studio/figma-plugin/assets/141044745/a700ca71-1273-4377-a0ed-d7d4491013b9)

**Comment by six7** [comment]
> [@six7](https://github.com/six7)
> 
> I think we need to adjust this ticket to be out of scope or backlog as [per this note](This one is out - not possible in Variables) but I could be wrong
> 
> ![CleanShot 2023-11-08 at 16 22 29@2x](https://user-images.githubusercontent.com/141044745/281546789-a700ca71-1273-4377-a0ed-d7d4491013b9.png)

This is possible since the latest update: (Updated the issue description) https://www.figma.com/plugin-docs/updates/2023/10/27/version-1-update-80/

**Comment by SamIam4Hyma** [comment]
@six7 reminder to close
