### ISSUE TITLE
Feature Request - Introduce "Gap" Value for Dash Border Style in Figma Tokens

### ISSUE THREAD

**Issue by PhonePe-GlobalDSRepo** [tokens-studio/figma-plugin#2117]
Introduce Dash length and Gap value in Border token

Allow to define Dash length and Gap value in the Border token, currently we can define the following in the border token:
- Border color,
- Border Width,
- Border Style
And the json is defined as below:
{
"border": {
    "new": {
      "value": {
        "color": "#070707",
        "width": "{border-width.1}",
        "style": "dashed"
      },
      "type": "border"
    }
  }
  }

![image](https://github.com/tokens-studio/figma-plugin/assets/66366384/31d6f294-c714-499b-80a4-f0e53b1c932a)

In the Figma API we get the following option for border dash values :
strokeDashesNumber[] default: []
An array of floating point numbers describing the pattern of dash length and gap lengths that the vector path follows. For example a value of [1, 2] indicates that the path has a dash of length 1 followed by a gap of length 2, repeated.

In the W3C design tokens draft border token is defined as:
{
  "border": {
    "heavy": {
      "$type": "border",
      "$value": {
        "color": "#36363600",
        "width": "3px",
        "style": "solid"
      }
    },
    "focusring": {
      "$type": "border",
      "$value": {
        "color": "{color.focusring}",
        "width": "1px",
        "style": {
          "dashArray": ["0.5rem", "0.25rem"],
          "lineCap": "round"
        }
      }
    }
  }
}

**Definition of done**
Have an input for dash values if the border style selected is `dashed`.
The input should take 2 values, the first value should be the length of the dash and the second value is the gap.
The input should be validated to always have two values.
The json should look like this:
{
"border": {
    "new": {
      "value": {
        "color": "#070707",
        "width": "{border-width.1}",
        "style": {
        "dashArray": ["1px", "2px"]
        }
      },
      "type": "border"
    }
  }
  }

> Original Issue
One feature that would significantly enhance our workflow is the ability to control dash border spacing directly within Token Studio.

>Currently, when using the Dash border style in Token Studio, we face limitations in adjusting the spacing between dashes. This leads to extra manual effort and makes it challenging to maintain consistency across our designs. To address this issue, I propose the introduction of a "Gap Value" within the border tokens for the Dash border style **_(also if possible the other values in the Advance border panel which exist in figma)_**.

>With the Gap Value in place, we will have the flexibility to adjust the spacing between dashes using the token itself. This means we can easily fine-tune the dash border style, achieving pixel-perfect precision without the need for additional workarounds. 

>Moreover, the Gap Value in Token Studio will promote consistency across our design system, ensuring that all team members follow the same guidelines for dash border styles. This will lead to a cohesive visual language across various components and screens, ultimately improving the overall user experience.

>By implementing this feature request, our design process will become more streamlined and productive. We look forward to leveraging the Gap Value in border tokens for the Dash border style, allowing us to create visually appealing and consistent designs without unnecessary complexities.

>![image](https://github.com/tokens-studio/figma-plugin/assets/107837760/660bd4b3-2143-4a0e-b79c-5ab0af43e9b7)
https://tokens-studio.slack.com/archives/C02DEJMS9AP/p1690433287235919

**Comment by UdayHyma** [comment]
[Migrated to Featurebase](url)
