### ISSUE TITLE
Allow For The JSON View To Remember Last Viewed Position

### ISSUE THREAD

**Issue by keeganedwin** [tokens-studio/figma-plugin#2119]
**Is your feature request related to a problem? Please describe:**
When viewing the JSON and switching back to list view, users have to again scroll to the previous position when back in JSON view.

**Describe the solution you'd like**
All the JSON view to remember last used position. 

**Screen recording:**
https://github.com/tokens-studio/figma-plugin/assets/93133012/87e5668d-27d0-4ffb-beeb-74e53bc30a49

**Comment by LukeFinch** [comment]
This request has been moved to our new feedback tool. Go check out https://tokensstudio.featurebase.app/ to create a free account. You can upvote and comment on existing posts, make a new request, and subscribe to be notified when requests move into our roadmap.

**Comment by UdayHyma** [comment]
Added to Featurebase Roadmap : [🧑‍💻 JSON view/edit enhancements](https://tokensstudio.featurebase.app/p/json-viewedit-enhancements)
