### ISSUE TITLE
Allow For Bulk Remapping With Variables & Styles

### ISSUE THREAD

**Issue by keeganedwin** [tokens-studio/figma-plugin#2120]
**Is your feature request related to a problem? Please describe.**
You can currently only use the bulk-remap feature if you have `tokens` applied.

**Describe the solution you'd like**
Allow to also bulk-remap if either `variables` or `styles` are applied.

Currently in the inspect tab we show the tokens, variables or styles that are applied in the selected frame. We have the option to bulk remap the tokens via the bulk remap action. 
We do not allow the users to remap the variables or styles from the plugin. 

We want to allow users to bulk remap variables and styles from the plugin similar to how tokens are bulk remapped. 
- In the inspect panel, select the applied variable or style to be remapped
- Click on `Bulk remap` button
- Enter the value to be matched and the value to be remapped
- The variable/style applied should be changed to the new value

![Image](https://github.com/tokens-studio/figma-plugin/assets/66366384/79eebfa9-8b3e-4198-b80a-7060db98e080)

![Image](https://github.com/tokens-studio/figma-plugin/assets/66366384/74b82c86-eae8-4eaa-b21d-4f48654c8674)

![Image](https://github.com/tokens-studio/figma-plugin/assets/66366384/4e932f69-0bc7-4fa5-8f59-ab17a1104443)

Allow all variables/styles to be bulk remapped:
- Linked to tokens
- Not linked to tokens
- Local variables/styles
- Variables and styles from published libraries

**Comment by LukeFinch** [comment]
This request has been moved to our new feedback tool. Go check out https://tokensstudio.featurebase.app/ to create a free account. You can upvote and comment on existing posts, make a new request, and subscribe to be notified when requests move into our roadmap.

**Comment by SamIam4Hyma** [comment]
Added to Featurebase Request-	[Tokens applied via styles and variables in the Figma UI are fragile and have less features in Tokens Studio](https://tokensstudio.featurebase.app/p/tokens-applied-as-variables-or-styles-are-fragile)
