### ISSUE TITLE
Json5 support for uploads, json field or syncing from github

### ISSUE THREAD

**Issue by mikeokijohn** [tokens-studio/figma-plugin#2121]
Hi.

Thanks for the great work on the plugin!

From what I can see in this previous [feature enhancement](https://github.com/tokens-studio/figma-plugin/issues/283), the plugin supports loading a json5 file or adding json5 contents into the json field, but that's not something I'm able to make work currently?

Was this feature removed again?

**Comment by rbosker** [comment]
Just tested this and indeed json5 files doesn't seem to be accepted anymore. Also reported in this slack thread: https://tokens-studio.slack.com/archives/C02HN88QARL/p1692136925133939

**Comment by UdayHyma** [comment]
[Migrated to Featurebase](https://tokensstudio.featurebase.app/p/git-sync-enhancements)

**Comment by six7** [comment]
Closing this - we currently do not have plans to add JSON5 support anytime soon (PRs welcome though!)
