### ISSUE TITLE
Change Position Of 'Show Empty Groups' Button

### ISSUE THREAD

**Issue by keeganedwin** [tokens-studio/figma-plugin#2122]
**Is your feature request related to a problem? Please describe.**
To currently show only empty groups (token-types), the user has to scroll down to find the button.

**Describe the solution you'd like**
Move the the position of the button to acces it easier

**Additional context**
![2023-08-01_15-40-29](https://github.com/tokens-studio/figma-plugin/assets/93133012/59a06298-86c7-4277-8873-b1726ebbbc3b)
```[tasklist]
### Tasks
- [ ] Add design
```

**Comment by LukeFinch** [comment]
This request has been moved to our new feedback tool. Go check out https://tokensstudio.featurebase.app/ to create a free account. You can upvote and comment on existing posts, make a new request, and subscribe to be notified when requests move into our roadmap.

**Comment by UdayHyma** [comment]
Added to Featurebase Roadmap : [🪙 Token organization enhancements
](https://tokensstudio.featurebase.app/p/token-organization-enhancements)
