### ISSUE TITLE
Show token values in Inspect

### ISSUE THREAD

**Issue by mikejyoung** [tokens-studio/figma-plugin#2124]
**Is your feature request related to a problem? Please describe.**
When tokens applied using a composition token, it's not possible to see the values of the composition in Inspect or the new supported Dev Mode. We should display token values on hover, regardless of token type - composition, box shadow, any token.

**Describe the solution you'd like**
In Inspect, show the values in a tooltip as you hover over the icon:

<img width="570" alt="Screenshot 2023-08-02 at 7 24 11 AM" src="https://github.com/tokens-studio/figma-plugin/assets/75724470/55b1ce8c-3c88-4146-8c26-b1ffde7e8b19">

Same logic could be applied for other multi-value tokens (typography, shadow, border)

**Comment by esthercheran** [comment]
Breaking this issue to two different issues https://github.com/tokens-studio/figma-plugin/issues/2263 to handle the Dev mode separately
