### ISSUE TITLE
Allow For Annotate With Deep Inspect To Detect Multiple Of The Same Properties Applied

### ISSUE THREAD

**Issue by keeganedwin** [tokens-studio/figma-plugin#2125]
**Is your feature request related to a problem? Please describe.**
Currently when using inspect to annotate, you can only view `one` (one layer) property of a type of token e.g. `one` fill even if there are `four`. 

**Describe the solution you'd like**
Allow to detect similar properties within nested layers.

**Additional context**
![CleanShot 2023-08-02 at 12 35 41@2x](https://github.com/tokens-studio/figma-plugin/assets/93133012/9e8b5d35-ef65-4b62-be57-55c575de17a3)

**Comment by LukeFinch** [comment]
This request has been moved to our new feedback tool. Go check out https://tokensstudio.featurebase.app/ to create a free account. You can upvote and comment on existing posts, make a new request, and subscribe to be notified when requests move into our roadmap.

**Comment by UdayHyma** [comment]
Here's the URL to the featurebase post that is linked to this ticket: https://tokensstudio.featurebase.app/p/enhance-inspect-page-in-the-plugin
