### ISSUE TITLE
[Performance]: Loading a file with many token sets in the plugin takes a long time or makes the plugin go blank

### ISSUE THREAD

**Issue by esthercheran** [tokens-studio/figma-plugin#2131]
When loading a token file with many tokens and token sets the plugin freezes and takes a long time. In some cases the plugin goes blank. 

Loading a token file with more than 100 token sets:
https://github.com/tokens-studio/figma-plugin/assets/66366384/a881a100-d524-491b-b7f5-bae77ff8fa7c

Blank Plugin UI:
![Image](https://github.com/tokens-studio/figma-plugin/assets/66366384/ff22b35c-6f06-4b32-887c-c9ba454fef0b)

Console log:
[www.figma.com-1690473722373 (1).log](https://github.com/tokens-studio/figma-plugin/files/12290091/www.figma.com-1690473722373.1.log)

**Comment by six7** [comment]
@esthercheran can you supply the token file?

**Comment by SamIam4Hyma** [comment]
@LukeFinch investigation needed this has been in progress for 5 months.

**Comment by keeganedwin** [comment]
Closing this ticket as this in no longer reproducible after having tested it in **Prod 1.38.9** and **Beta V2-rc5** with sets that have more than 100 tokens.
