### ISSUE TITLE
[Performance]: Loading a file with many token sets takes a lot of time when switching sets

### ISSUE THREAD

**Issue by esthercheran** [tokens-studio/figma-plugin#2132]
When loading tokens which has many token sets switching between sets becomes laggy.

https://github.com/tokens-studio/figma-plugin/assets/66366384/9e045829-d70a-47e9-81e5-c98e310c00f2

**Comment by keeganedwin** [comment]
Closing this ticket as it's no longer reproducible. It also seems to have been fixed with #2191.
