### ISSUE TITLE
Default dimension preset tokens need to be updated

### ISSUE THREAD

**Issue by markacianfrani** [tokens-studio/figma-plugin#2133]
The default preset config has a few dimension values that are using unit-less values. However, dimension tokens cannot be unitless.

Steps to reproduce: 
* Load up the default preset.
* Edit the scale token.
* Focus the value field. 
* Unfocus the field.
* See error message. 

I thought this would be an easy fix, just update the default config values to be px instead of being unitless. Except you have some tokens using math like 
`"value": "{dimension.xs} * {dimension.scale}"`

which now won't work if dimension.xs is 4px instead 4. https://docs.tokens.studio/tokens/using-math#adding-units

I'm guessing here that this was changed in response to the w3c spec, which explicitly prohibits unitless values, and these values weren't updated. But I can't think of a solution other than 1. not using dimension tokens 2. not using math

**Comment by UdayHyma** [comment]
[Migrated to Featurebase](https://tokensstudio.featurebase.app/p/expand-token-types)
