### ISSUE TITLE
[Performance]: Show a warning when an operation is going to take time

### ISSUE THREAD

**Issue by esthercheran** [tokens-studio/figma-plugin#2137]
Currently users are not aware when an action is leading to the execution of expensive operations. For eg. editing a token with the setting 'Apply to Document' and 'Update on Change'.

Adding a dialog box that will inform the user when an expensive operation is going to take place. 

![Image](https://github.com/tokens-studio/figma-plugin/assets/66366384/10690968-2d98-42f5-b15f-911f981e40c6)

Definition of an expensive operation:
- Edit token (Apply to Document with > 1000 nodes)
- Edit token (Apply to Page with >1000 nodes)
- Switching theme (Apply to Document/Page with > 1000 nodes)

**Comment by six7** [comment]
With the performance improvements I would consider this obsolete. We were able to bring down this number by a huge factor, so I don't think we should do this at this point.
