### ISSUE TITLE
Calculated values are not respected in variables within Nested Set Folders

### ISSUE THREAD

**Issue by keeganedwin** [tokens-studio/figma-plugin#2139]
**Is your feature request related to a problem? Please describe.**
This problem is similar to issues #2059 and #2012 the only difference being that the calculated values are not respected when the tokens live within nested set folders (2+).

**Describe the solution you'd like**
Calculate the value just as it is calculated when the tokens live with `one` nested set folder. 

**Screenshots:**
Correctly calculated when the token lives within `one` nested set folder:

![CleanShot 2023-08-03 at 16 45 29@2x](https://github.com/tokens-studio/figma-plugin/assets/93133012/c0341424-fc6f-4d5e-b3b7-4775cad9e88a)

When the token lives within `two` or more nested set folders:

![CleanShot 2023-08-03 at 16 45 59@2x](https://github.com/tokens-studio/figma-plugin/assets/93133012/c82a3d7d-4f96-4a5f-80dd-542c5f4e3b20)
![CleanShot 2023-08-03 at 16 46 50@2x](https://github.com/tokens-studio/figma-plugin/assets/93133012/5f0d5041-d8de-4dae-aca8-eb4ae61c7799)

**Comment by swordEdge** [comment]
Seems to work. Confirmed with @keeganedwin and Robbert.

**Comment by keeganedwin** [comment]
Confirming that this works!
