### ISSUE TITLE
Color Swatch in Box Shadow does not show Color

### ISSUE THREAD

**Issue by keeganedwin** [tokens-studio/figma-plugin#2145]
**Describe the bug**
When referencing a color-token in the box shadow type, the swatch does not update to the corresponding color-token. 

**To Reproduce**
1. Go to 'box shadow token'
2. Reference a color token
3. See error

**Expected behavior**
Color-swatch should update to corresponding token color

**Screenshots or Screencasts**
![CleanShot 2023-08-07 at 13 37 53@2x](https://github.com/tokens-studio/figma-plugin/assets/93133012/c0b7adf9-8df5-457d-9c54-931a04f7bfda)

**Comment by SamIam4Hyma** [comment]
Referenced in Featurebase https://tokensstudio.featurebase.app/p/enhance-color-swatch-functionality

**Comment by LukeFinch** [comment]
This request has been moved to our new feedback tool. Go check out https://tokensstudio.featurebase.app/ to create a free account. You can upvote and comment on existing posts, make a new request, and subscribe to be notified when requests move into our roadmap.

**Comment by UdayHyma** [comment]
https://tokensstudio.featurebase.app/p/bulbart-enhance-color-functionality-across-all-token-types
