### ISSUE TITLE
[token-transformer] Tokens not generating when sets passed with a folder src input

### ISSUE THREAD

**Issue by RockAtRockwell** [tokens-studio/figma-plugin#2146]
**Describe the bug**
Currently, we have our tokens set up to sync to a folder in GitHub, giving us the multi-file setup. When we try to run the tokens transformer and pass it the specific sets we want it to transform, it generates and empty .json file.

**To Reproduce**
1. Setup Tokens studio with at least 2 sets of tokens
2. Sync those tokens to a GitHub repo with a folder endpoint (`/tokens`)
3. Run the transformer in the repo locally
`token-transformer ./tokens ./.tmp/tokens.json Set1,Optional2 --expandTypography --expandShadow`

Note: If I run the above command **without** passing in sets, it will generate a .json file properly, just with _all_ of the tokens, which is not what I'm looking for.

**Expected behavior**
A json file containing the tokens from the selected set(s)

**Comment by brianokeefe** [comment]
Just want to +1 this, we are also seeing the same behavior.

**Comment by SamIam4Hyma** [comment]
@jorenbroekema is this still a known issue? 
- if so, remove the archive label and add additional labels as needed
- if not, please close.

**Comment by jorenbroekema** [comment]
token-transformer deprecated in favor of using sd-transforms, dont think it's a problem there, you can even pass a function to sd-transforms expand options to conditionally expand e.g. by `token.filePath` to only expand tokens from certain sets
