### ISSUE TITLE
Allow for Remapping of Selected Tokens Only

### ISSUE THREAD

**Issue by keeganedwin** [tokens-studio/figma-plugin#2152]
**Is your feature request related to a problem? Please describe.**
A user may want to map five from the 10 tokens that have a matching name, but are currently restricted to do so. Currently users can either remap a single token or use the bulk-remap feature which remaps (regardless of selected or not)`all` the tokens with matching names.

**Describe the solution you'd like**
Allow users to remap only the selected tokens. 

**Definition of done**
- Can select multiple tokens and remap only the selected tokens

```[tasklist]
### Tasks
- [ ] https://github.com/tokens-studio/figma-plugin/issues/2185
```

**Comment by davidmcneroe86** [comment]
+1

**Comment by SamIam4Hyma** [comment]
@LukeFinch proposing we close as this is a feature avail in the plugin today unless I'm not understanding the request.
