### ISSUE TITLE
 Access Token Expiry Leads to Lingering Error Message

### ISSUE THREAD

**Issue by keeganedwin** [tokens-studio/figma-plugin#2154]
**Describe the bug**
Encountered an issue with and access token that is expired. A new access token is generated and updated in the account settings. However, after updating the access token, there is an error message that persisted is the settings tab. The new access token does not seem to be recognised immediately, and the error remains visible until switched to a different tab. 

**To Reproduce**
1. Allow the access token to expire.
2. Observe the error message related to the expired access token.
3. Navigate to the settings tab.
4. Generate a new access token and update it in the account settings.
5. See error

**Expected behavior**
The error message should disappear upon confirming or validating the new access token. Users should not encounter lingering error messages related to expired access tokens after they have generated and updated a new token.

**Comment by SamIam4Hyma** [comment]
@LukeFinch please assess and label or close
