### ISSUE TITLE
Error in Applying Raw Value of a Color's Documentation Token

### ISSUE THREAD

**Issue by keeganedwin** [tokens-studio/figma-plugin#2155]
**Describe the bug**
Applying the raw value for color documentation tokens don't seem to apply correctly - no change/incorrect output. 

**To Reproduce**
1. Apply the the raw value documentation token of a color 
2. See error

**Expected behavior**
In the following screenshot, the raw value is supposed to be `{colors.onAccent.500}`

**Screenshots or Screencasts**
<img width="957" alt="CleanShot 2023-08-10 at 19 15 10@2x" src="https://github.com/tokens-studio/figma-plugin/assets/93133012/3a66a917-3c0c-49c5-a90f-ec7164fe8987">

This is also present with the following token type: [**Typography**](https://github.com/tokens-studio/figma-plugin/issues/2276#issue-1916859187)

**Comment by esthercheran** [comment]
@keeganedwin unable to reproduce the bug, was there any additional conditions for this to occur?

**Comment by keeganedwin** [comment]
Here's a recording, if I'm not mistaken, applying the raw value is supposed to change??
https://github.com/tokens-studio/figma-plugin/assets/93133012/870b445f-89ac-425b-8607-0a6124972d1c

**Comment by keeganedwin** [comment]
Closing this ticket as it's no longer reproducible after testing it in Prod 1.38.9 and Beta V2-rc5, but it's is also related to #1953.
