### ISSUE TITLE
Ability To Rename Token Groups In Subsequent Sets

### ISSUE THREAD

**Issue by keeganedwin** [tokens-studio/figma-plugin#2158]
**Is your feature request related to a problem? Please describe.**
When a group for instance is collapsed in one theme, it also collapses in all sets that contain this `same` token-group for overwriting to take place. Or when you change a single token's name, in the popup modal you are offered to rename it even in the subsequent sets that have the same defined. However, when attempting to rename a token group (parent), it is apparent that a manual change is required in `every` set containing the same token-group.

**Describe the solution you'd like**
Display and option to even rename the token-groups in subsequent sets when changed.

**Screenshots:**
When renaming tokens
![CleanShot 2023-11-07 at 14 25 38@2x](https://github.com/tokens-studio/figma-plugin/assets/93133012/b5a63f99-d184-46df-b91b-0ff6391d3f23)

When renaming token-groups (parent)
![CleanShot 2023-11-07 at 16 56 25@2x](https://github.com/tokens-studio/figma-plugin/assets/93133012/dd338ba2-2448-46b3-a0fe-59530ed260e1)

**Comment by LukeFinch** [comment]
This request has been moved to our new feedback tool. Go check out https://tokensstudio.featurebase.app/ to create a free account. You can upvote and comment on existing posts, make a new request, and subscribe to be notified when requests move into our roadmap.

**Comment by UdayHyma** [comment]
Added to Featurebase Roadmap : [🌜Theme management (pro) enhancements](https://tokensstudio.featurebase.app/p/theme-management-enhancements)
