### ISSUE TITLE
Duplicating a Token to Another Set Displays Error

### ISSUE THREAD

**Issue by keeganedwin** [tokens-studio/figma-plugin#2165]
**Describe the bug**
When duplicating a token to another set, the error `Token names must be unique` is displayed. This only happens when duplicating it from the menu when right-clicking the token itself, and not the token-group.

**To Reproduce**
1. Right-click a token
2. Click duplicate token
3. Remove `copy` from the token-name
4. Unselect current set and select another set 
5. See error

**Expected behavior**
Would it be possible to throw this error _if_ and _only_ when the user has the same/current set selected when duplicating a token?
- _This error maybe shouldn't be displayed when duplicating a token to another set as the purpose of this process is to have sets overwrite tokens_

**Screenshots or Screencasts**
The current set is `Light`, and even when having only the `Dark` set selected the error is displayed:

![CleanShot 2023-08-15 at 11 44 46@2x](https://github.com/tokens-studio/figma-plugin/assets/93133012/7f0f936d-4c9a-4246-a88b-3fcb351a50ec)

**Comment by NuthanHyma** [comment]
**Figma File**
[Test File](https://www.figma.com/file/8PAGvbwqRudtYhs2KVFTl3/Untitled?type=design&node-id=0%3A1&mode=design&t=0ExNANUJ61BRKJno-1)

**Comment by six7** [comment]
I'd say we should rework the duplicate to other set feature so that i cannot change the name there. All i should be able to do is pick one or more token sets to duplicate into, nothing else.

**Comment by esthercheran** [comment]
Closed by #2467

**Comment by SamIam4Hyma** [comment]
Added to featurebase roadmap item [💚 Naming conflict error enhancements - QOL](https://tokensstudio.featurebase.app/p/naming-conflict-error-enhancements)
