### ISSUE TITLE
Tokens Studio reverting back to a previous save state on reopening the plugin

### ISSUE THREAD

**Issue by tristanpeters237** [tokens-studio/figma-plugin#2167]
**Describe the bug**
Tokens Studio is reverting back to a previous state on reopening the plugin. This is solely linked to my (Pro) account, my other team mates (free) do not have this issue when creating, editing or applying tokens.

**To Reproduce**
I can perform all actions - add, delete, duplicate, modify and apply tokens, I can duplicate and create new token sets, BUT every time I close the plugin and reopen it, TS reverts back to a state from approximately 8.30PM last night for any changes that I have made. Any changes that my team make remain in TS as expected.
Additionally, for me to see any changes or updates that my team have created I need to quit TS and reopen it before their updates display.

We are using the default Local Storage save option. 

**Expected behavior**
I expect Tokens Studio to remember any tokens or changes I have made and save those changes. I expect Tokens Studio to present me with the latest and up to date version of our token set whenever I or anyone else associated with our Theme or file open the the TS Plugin.

**Screenshots or Screencasts**

**Figma file (optional)**

**JSON (optional)**

**Comment by SamIam4Hyma** [comment]
@LukeFinch please assign someone to look into this and manage the ticket according to what you find. I'll add as many labels as I can for you to remove as needed.
