### ISSUE TITLE
Slowdowns when moving sets

### ISSUE THREAD

**Issue by SimonLeclercq** [tokens-studio/figma-plugin#2168]
**Describe the bug**
It seems that we're experiencing significant slowdowns when rearranging token sets in the plugin. I'm wondering if perhaps the "JSON rewriting" is happening on-the-fly? (pure speculation)

**To Reproduce**
1. Create some sets, maybe 10+
2. Move one from the bottom of the list into the middle
3. See slowdown

**Expected behavior**
It's just a speculation, but I imagine that the JSON is being modified at the same time the set is being drag & dropped, which results in slowdowns during a rapid movement. I would expect something smoother, even if it means having a slight delay when I release my trackpad

**Comment by six7** [comment]
Fixed in 1.38 🚢
