### ISSUE TITLE
Support Division When Referencing A Token With Multiple Values

### ISSUE THREAD

**Issue by keeganedwin** [tokens-studio/figma-plugin#2170]
**Is your feature request related to a problem? Please describe.**
You currently can't use the division operation when referencing a token that's of multiple values. 

**User use-case:**
Currently, the system uses spacing tokens like ﻿`space.inset.squish` which correspond to padding values of 2 and 4. The user wants to create a compact variant of this spacing token that divides the values by `2` using an alias, but it doesn't seem to be working. The expected result would be to divide the respective values to: `1` & `2`

**Describe the solution you'd like**
Allow for the division operation when referencing a multi-value token.

**Describe alternatives you've considered**
User has tried various approaches such as adding brackets and parentheses to the alias, but none of them have yielded the desired result.

**Screenshots - multiple-values**
![Screen Shot 2023-08-16 at 1 44 45 PM](https://github.com/tokens-studio/figma-plugin/assets/93133012/120792d0-16c9-40af-a5fd-e78340541735)

**Dividing the referenced token:**
![Screen Shot 2023-08-16 at 1 45 08 PM](https://github.com/tokens-studio/figma-plugin/assets/93133012/58b616b3-6e66-4eab-9aec-fc107c2a1e73)

**Comment by SamIam4Hyma** [comment]
@esthercheran can you please test this one and check if the issue still exists? In my recent testing some of the requirements for writing equasions no longer matter so it might have resolved itself. 

If resolved you can close, if still exists just comment to confirm it will remain in the QOL pool

**Comment by esthercheran** [comment]
This does not work as of now. Maybe this can be moved to featurebase @SamIam4Hyma

**Comment by SamIam4Hyma** [comment]
@esthercheran I agree! I don't know why I can't tag Uday here but I'll ask him to migrate this one over.

**Comment by UdayHyma** [comment]
[Migrated to Featurebase](https://tokensstudio.featurebase.app/p/token-usage-metadata)

**Comment by SamIam4Hyma** [comment]
Added to Featurebase Request-	[Math in value enhancements ](https://tokensstudio.featurebase.app/p/math-in-value-enhancements)
