### ISSUE TITLE
Can't create variables

### ISSUE THREAD

**Issue by sannevangool** [tokens-studio/figma-plugin#2174]
**Describe the bug**
The option to create variables is disabled

**To Reproduce**
1. Open the plugin
2. Click on styles & variables
3. See disabled options

**Expected behavior**
Creating variables in Figma

**Screenshots or Screencasts**
[Scherm­afbeelding 2023-08-21 om 17 06 22](https://github.com/tokens-studio/figma-plugin/assets/138762041/78319ad7-8a92-4120-9c5b-22438563f9ba)

**Comment by keeganedwin** [comment]
Hey @sannevangool, you need have themes defined in order to create variables. You can also have a look at our docs that briefly explains creating variables: https://docs.tokens.studio/variables/creating-variables
