### ISSUE TITLE
Overwritten color tokens don't apply to Figma

### ISSUE THREAD

**Issue by HumixRenco** [tokens-studio/figma-plugin#2182]
**Describe the bug**
Some color token overwrites don't get reflected in Figma.

**To Reproduce**
When applying a set that overwrites color values of the main set. Some colors of components that are used in another component (eg. checkbox component in list item component) don't get overwritten in Figma. They are however changing in the plugin. When I apply the overwriting set to the page where the checkbox component is located and then come back it has switched colors. 
Note that in the attached video the label which is part of the checkbox component does swap correctly, the bug/issue appears to be affecting fills of frames mainly. Buttons, same thing: background remains light themed while the label and icons inside the component do swap to the dark themes primary color (light blue instead of dark blue)

**Expected behavior**
When overwriting color tokens with other color tokens, I expect to see this change in Figma without having to go to the page where the main component is of all used instances and having to swap it there manually. Apply to document is a solution for this but no option as this takes 5min due to the scale of our design system.

**Screenshots or Screencasts**

https://github.com/tokens-studio/figma-plugin/assets/127747516/c5a83d45-d9e3-46ac-a801-4b8d5b5783e3

**Comment by six7** [comment]
Fixed in 1.38 🚢
