### ISSUE TITLE
Provide the "network access" details when publishing the plugin

### ISSUE THREAD

**Issue by valioDOTch** [tokens-studio/figma-plugin#2183]
**Is your feature request related to a problem? Please describe.**
I manage Figma in the enterprise version for my organisation.
As we're a bit restrictive due to regulations, I manually approve all widgets and plugins (whitelisting).
Above all I need to manually check and documents all approved plugins concerning any network access outside of Figma (e.g. if it stores any data in Google spreadsheets as FigDone or the like).

**Describe the solution you'd like**
Figma recently introduced a field where plugin creators can define the network access of their plugin.
![image](https://github.com/tokens-studio/figma-plugin/assets/800467/a8c3cf3e-a658-4e01-bd80-e0092886278c)
I'd be happy if you could fill in this field.

**Describe alternatives you've considered**
I'd be happy if you could just give me a list of mandatory and optional connections as a reply 
(the connector to GitHub would be an optional connection e.g.).

**Additional context**
(none)

**Comment by six7** [comment]
We now added data about this
