### ISSUE TITLE
Component variant token

### ISSUE THREAD

**Issue by ryusakai** [tokens-studio/figma-plugin#2184]
**Is your feature request related to a problem? Please describe.**
When I create "device themes" such as desktop, tablet and mobile, I can currently do this for simple design attributes like widths and spacings, but I cannot control switching component variants from "desktop variant" to "mobile variant".

**Describe the solution you'd like**
To be able to create "component variant tokens", which allows you to specify a component and its variant.
This enables you to switch "header component's variant" from "desktop variant (1440px width with logo and all the menu items exposed)" to "mobile variant (375px width with logo and hamburger menu)" when you switch "device theme" from "desktop" to "mobile". 

**Describe alternatives you've considered**
It's still possible to have theme switching take care of basic design attributes, then do manual adjustments to change some components' variants appropriately.
But these manual adjustments obviously defeats the beauty and the power of "easy theme switching" in the first place.

**Additional context**
<img width="830" alt="Screenshot 2023-08-22 at 9 40 29 AM" src="https://github.com/tokens-studio/figma-plugin/assets/11201903/6d3b99b7-4aff-4d2d-a4f5-f0caf6a33c7b">

**Comment by GeorgeTaveras1231** [comment]
This would be great! And critical for our team to bridge the implementation gap between design and engineering 🙌🏽

**Comment by LukeFinch** [comment]
This request has been moved to our new feedback tool. Go check out https://tokensstudio.featurebase.app/ to create a free account. You can upvote and comment on existing posts, make a new request, and subscribe to be notified when requests move into our roadmap.

**Comment by UdayHyma** [comment]
Added to Featurebase Roadmap : [🪙 Expand token types](https://tokensstudio.featurebase.app/p/expand-token-types)
