### ISSUE TITLE
Allow users to hide certain Token groups from publishing

### ISSUE THREAD

**Issue by esthercheran** [tokens-studio/figma-plugin#2186]
As a user I want to set whole theme groups to be hidden from publishing so I dont have to manually go through all my 5000 tokens and set them to `Hidden from publishing` if the collection is supposed to be private.

This can be done by the `$extensions` property on the group. Note that we do not yet support the extensions property on the group, but we should add support for that in this issue.

[Link to Handover](https://www.figma.com/file/nZiTKM6Efsdjt6TGZ0jNml/Figma-Tokens?type=design&node-id=3521-29667&mode=design&t=QmwHhCnPkDA5YmOc-4)

**Comment by LukeFinch** [comment]
How should we handle conflicting rules?

If a group has 'hide from publishing' can a child override this rule?

**Comment by six7** [comment]
I'm kind of leaning towards if a theme group is set to hidden even the children inside won't be published 🤔 would make it cleaner on the code side and easier to communicate?

**Comment by SamIam4Hyma** [comment]
There's been requests from the community to also have these controls at the style dictionary level as well for folks who have SD as their source of truth.

**Comment by keeganedwin** [comment]
[Link to Handover](https://www.figma.com/file/nZiTKM6Efsdjt6TGZ0jNml/Figma-Tokens?type=design&node-id=3521-29667&mode=design&t=QmwHhCnPkDA5YmOc-4)

**Comment by LukeFinch** [comment]
This request has been moved to our new feedback tool. Go check out https://tokensstudio.featurebase.app/ to create a free account. You can upvote and comment on existing posts, make a new request, and subscribe to be notified when requests move into our roadmap.

**Comment by UdayHyma** [comment]
Added to Featurebase Roadmap : [✏️ Add support for scoping and publishing variables and styles
](https://tokensstudio.featurebase.app/p/add-support-for-scoping-and-publishing-variables-and-styles)

**Comment by john777555** [comment]
Is there any update on this?
