### ISSUE TITLE
Error syncing with GitHub, check credentials

### ISSUE THREAD

**Issue by imranux** [tokens-studio/figma-plugin#2188]
When attempting to synchronize with GitHub, the following message is displayed: 'Error syncing with GitHub, please verify your credentials.' Could you please guide me on the steps to successfully complete the synchronization?

**Comment by esthercheran** [comment]
@imranux One of the reasons could be that your Personal Access is expired. More information could be found here: https://docs.tokens.studio/sync/github

**Comment by SamIam4Hyma** [comment]
@esthercheran can this issue be closed?

**Comment by Arcrammer** [comment]
@six7 This issue must be reopened. The guide directed to is what caused the issue to begin with. Causing major issues at my organization, and completely blocking my workflow. I am happy to provide diagnostic information if asked.
