### ISSUE TITLE
Ability to view all tokens with broken references

### ISSUE THREAD

**Issue by esthercheran** [tokens-studio/figma-plugin#2190]
**Is your feature request related to a problem? Please describe.**
There is no easy way to know of there is broken references in the tokens via the plugin, these broken references are generally detected during transformation and can cause broken pipelines. It would be great if there was a way to do a final check in the plugin if there are any broken references before handover.
Currently if we go to each set we can see the broken links which is indicated by a red dot. But this becomes tedious when the number of sets is big. 

**Proposed Solution**
A tab or view that shows all the tokens with broken links based on the sets that are active. The name of the set should be displayed as a heading for the tokens. Clicking on a token will take the user to the actual set where he/she can fix the problem OR the issue can be fixed in the view itself.

**Additional things to consider**
Tokens have linked references based on Themes. If some themes are not turned on, they would have the possibility of broken references which does not likely mean that the token is broken per se. An ideal solution would be based on Themes and making sure that for each active theme there is no broken references.
In case of teams not using themes the broken links could be displayed based on the token sets that are turned on. 
There could also be a case of tokens residing in multiple sets, the tokens should be displayed multiple times for each set. 

```[tasklist]
### Tasks
- [ ] Design a view to check all broken links
```

**Comment by jorenbroekema** [comment]
> A tab or view that shows all the tokens with broken links based on the sets that are active

Yes please :)! I was thinking along the lines of how VS Code's terminal does it, 
![image](https://github.com/tokens-studio/figma-plugin/assets/36734656/30a0067a-b89c-4377-a6d0-4884a714737f)

I think we should show the problems only for the current theme selection and its activated sets, but when you're about to sync to git or export, there should be a warning to the users saying there are certain theme(-permutations) that result in selected tokensets in such a way that there are broken references

**Comment by UdayHyma** [comment]
[Migrated to Featurebase](https://tokensstudio.featurebase.app/p/greenheart-v2-quality-of-life-enhancements)

**Comment by UdayHyma** [comment]
[Migrated to Featurebase](https://tokensstudio.featurebase.app/p/greenheart-v2-quality-of-life-enhancements)

**Comment by SamIam4Hyma** [comment]
Added to Featurebase Request-	[↕️ Git sync enhancements - push, pull, merge, branching](https://tokensstudio.featurebase.app/p/git-sync-enhancements)
