### ISSUE TITLE
Apply to Setting Defaults back to 'Document' after Crash

### ISSUE THREAD

**Issue by keeganedwin** [tokens-studio/figma-plugin#2192]
**Is your feature request related to a problem? Please describe.**
Cannot easily replicate this, but every time the plugin crashes, the dropdown reverts back to “apply to document” the next time you open the plugin. This causes disruption when users are editing tokens as it then updates nodes document-wide. 

**Describe the solution you'd like**
Default back to the smallest scope for the setting - '_Apply To Selection_'

**Comment by six7** [comment]
I investigated this a bit just now and I can't find any reference that we store apply mode to as a default with `DOCUMENT`. I wonder what could be causing this. The default is `PAGE`.

**Comment by keeganedwin** [comment]
Can we just change the default to `SELECTION`?

**Comment by swordEdge** [comment]
The plugin saves the last applyMode before the crash. So if the applyMode is PAGE before the crash, then it'll be PAGE after reopen the plugin.

**Comment by six7** [comment]
Fixed in 1.38 🚢
