### ISSUE TITLE
Introduce Variable Scopes for Tokens

### ISSUE THREAD

**Issue by keeganedwin** [tokens-studio/figma-plugin#2194]
**Is your feature request related to a problem? Please describe.**
Currently, when creating tokens in Tokens Studio, there is a limitation in scoping options. Users are unable to specify the exact purpose of a token.

**Describe the solution you'd like**
An enhancement to Tokens Studio that introduces more granular scoping options.

**Comment by six7** [comment]
@LukeFinch mind taking on design work for this for the upcoming Variables M2 work? Together with #2193

**Comment by LukeFinch** [comment]
@six7 What do you think about having a setting to auto-scope variables?

Any time I create a border-radius token - it should by default only appear in the border-radius option in Figma



![Image](https://github.com/tokens-studio/figma-plugin/assets/23120116/7129e681-ecdb-4878-8c19-1b9b5476e09a)

**Comment by six7** [comment]
I love it! Helps reduce complexity and i think most users will want that! We'd still want to show the input though, for those where we cant scope automatically? I guess if this is on and you edit a borderRadius token this could be disabled?

**Comment by LukeFinch** [comment]
Yeah - either we could deactivate the input (maybe with a link to settings) or, this option could just tick the scope input by default, and still let users untick it

**Comment by six7** [comment]
Recap from yesterday's discussion on this: Let's try to see if we can get away without a setting, and automatically scope tokens that are of type `borderRadius` to the corner radius scope silently. Only if a user changes this scope would we set it to something differently (if a variableScope property is present)

One thing we should still add to the shaping here is how this would look like in code. I imagine the `$extensions` property on each token could contain this information in our namespace, with a `variableScope` and values of an array matching Figma's scope values of the plugin api?

**Comment by SamIam4Hyma** [comment]
[💡 Add support for scoping and publishing variables and styles](https://tokensstudio.featurebase.app/p/add-support-for-scoping-and-publishing-variables-and-styles)
