### ISSUE TITLE
Unable to Inspect Tokens on certain Components

### ISSUE THREAD

**Issue by keeganedwin** [tokens-studio/figma-plugin#2205]
**Describe the bug**
Not sure as to what the issue could exactly be, but some users have been experiencing a block when trying to use the inspect tab to inspect tokens on a component - in sometimes works for the most part but sometimes also does not. 

**Key information:**
On the file in the comments below, the component that by default does not displaying tokens in inspect, even if I apply a fresh token it still doesn't display. I can however apply a token on a new frame and can inspect this token.

**Expected behavior**
Inspect tab should just display tokens that are applied on components as it usually would. 

**Screenshots or Screencasts**
No deep inspect
<img width="1042" alt="CleanShot 2023-08-30 at 18 23 09@2x" src="https://github.com/tokens-studio/figma-plugin/assets/93133012/9194076a-d190-406b-9bfd-88fdb091873d">

With deep inspect
<img width="1052" alt="CleanShot 2023-08-30 at 18 23 02@2x" src="https://github.com/tokens-studio/figma-plugin/assets/93133012/0da1a0e2-8528-49a2-b1a1-6f3d1f8b288b">

**Figma file (optional)**
Tokens are attached to file
https://www.figma.com/file/1gdtvmejUP2bT2TaJs21o5/Ward-(slack)---inspect-token-bug?type=design&node-id=1%3A166&mode=design&t=6gwc8frcQpe2wd8X-1

**Comment by six7** [comment]
Fixed in 1.38 🚢
