### ISSUE TITLE
Applying min/max sizing tokens don't show applied fill colors

### ISSUE THREAD

**Issue by HumixRenco** [tokens-studio/figma-plugin#2209]
**Describe the bug**
Follow up on [Issue 2182](https://github.com/tokens-studio/figma-plugin/issues/2182).
The fill color not swapping correctly in Figma is caused by min/max sizing tokens. If min/max tokens were applied to a component's frame, the colour of instances of that frame would not switch when applying a separate set of tokens.

**To Reproduce**
1. Create a frame
2. First apply a min and max size token
3. Then a color token
This color token does not visually apply to the frame. It does in the inspect window.

**Expected behavior**
Color should visually apply to the frame not only in Tokens studio

**Comment by six7** [comment]
Fixed in 1.38 🚢
