### ISSUE TITLE
creating github PR - commit signature could not be verified.

### ISSUE THREAD

**Issue by NatanCoralogix** [tokens-studio/figma-plugin#2210]
Hi,

Regarding creating a PR from the plugin.
everything works, but the problem is that the commit is missing the verified tag, so we can not merge it (due to company policy).

<img width="159" alt="image" src="https://github.com/tokens-studio/figma-plugin/assets/110969383/293d98fe-000f-4453-b828-6702104f5dd3">

Is there a solution for this?

**Comment by LukeFinch** [comment]
This request has been moved to our new feedback tool. Go check out https://tokensstudio.featurebase.app/ to create a free account. You can upvote and comment on existing posts, make a new request, and subscribe to be notified when requests move into our roadmap.

**Comment by UdayHyma** [comment]
Added to Featurebase Roadmap : [🧑‍💻 Sync to external token storage enhancements](https://tokensstudio.featurebase.app/p/sync-external-storage-enhancements)
