### ISSUE TITLE
When creating variables show the user a dialog that lets them see what would be created incl. values

### ISSUE THREAD

**Issue by six7** [tokens-studio/figma-plugin#2211]
In accordance with the enhancement of creation of Styles and Variables #2302 we are reimagining how styles and variables will be created.
In the process of creating styles and variables the screen where we can see the themes and sets available, there will be an option to see what are the tokens which are added, removed, changed and skipped. 

![themes-pro](https://github.com/tokens-studio/figma-plugin/assets/66366384/d04d4c7a-ad7c-4249-88b8-eb876dec7ae4)

![set-pro](https://github.com/tokens-studio/figma-plugin/assets/66366384/34740342-1daa-433a-bb8c-a03bf2483514)

Clicking on the arrow will open a dialog with the tabs: New, Removed, Changed and Skipped. This view will be grouped by theme and sets

For New tokens

![New Tokens](https://github.com/tokens-studio/figma-plugin/assets/66366384/5774e284-a59a-4aa1-9073-cec1c027dcce)

For Removed tokens
![Removed](https://github.com/tokens-studio/figma-plugin/assets/66366384/2f9acbca-769b-4ed8-8414-b40d799497a8)

For Changed tokens
![Changed](https://github.com/tokens-studio/figma-plugin/assets/66366384/d7270bc8-d72c-4100-b96b-b86726b7cdd9)

For tokens which cannot be exported as variables `Issues`, these are tokens which would be skipped because the type is not supported in Figma. 
For Variables:
- Gradient tokens
- Box Shadow tokens
- Stroke Style
- Opacity tokens
- Cubic Bezier
- Typography
- Border Composite token
- Composite token
- Asset token
- Other token
- 5000 variable limit 

For Styles:
All except tokens are skipped except:
- Colors
- Typography
- Box Shadow
- Gradient

![METADATA-theme](https://github.com/tokens-studio/figma-plugin/assets/66366384/60c1d30a-3c02-40bb-bef7-5d59a1036b73)

![METADATA](https://github.com/tokens-studio/figma-plugin/assets/66366384/fd94932e-b57e-47e7-a3cf-97c621dc56f7)

>I need to understand what happens after hitting Create / Import / Sync. Show a dialog letting me pick which theme groups to create variables from. Also, show a dialog with `before` and `after`. once the user has made the choice on which theme groups to create from, showing the actual variables created.

>- When users hit `Create variables`, show a modal where users can see the variable collections that would be created, and they can check/uncheck them. By default, check all.
>- For this modal that appears, show all variables that would be created inside each collection. Similar to the `Import styles` dialog.
>- If there are variables that would be skipped because the type is not supported in Figma, rank these first under a group "Skipped", explain why.
>- Let the user `check` or `uncheck` items so they would be ignored from updating.
>- Only create variabls for the ones that are checked. By default, have all checked, but the user can uncheck certain or use a `Select all` to toggle selection / deselection of all.

**Comment by cchaos** [comment]
Big +1 

Can I also make a suggestion that instead of defaulting to **all** being selected, can you do a check for which theme sets are currently checked and their sources? 

For example:
<img width="524" alt="Screen Shot 2023-09-13 at 14 05 23 PM" src="https://github.com/tokens-studio/figma-plugin/assets/549577/ebda5ceb-aaa6-4a4d-a091-1a74b7d23c76">

The above would only have the following checked by default.
- Source / Foundations
- Theme / Light (and Dark?)

The outstanding question in my mind for that though is should it select all within the same theme set? So, "Light" and "Dark" in this case? My guess is that's how folks typically setup their themes.

I can imagine those who might have many brands don't want to deselect twice as many as they actually want selected.

**Comment by LukeFinch** [comment]
Edited the OP with updated visuals

Edited some icons and removed some visual noise.

**Comment by UdayHyma** [comment]
[Migrated to Featurebase](https://tokensstudio.featurebase.app/p/sync-styles-and-variables-is-now-export-to-figma)
