### ISSUE TITLE
Allow users to Delete all Token Data

### ISSUE THREAD

**Issue by keeganedwin** [tokens-studio/figma-plugin#2212]
**Is your feature request related to a problem? Please describe.**
Users would like a way to delete/remove all token data - all the tokens applied - in a file. This also concerns the token data being displayed in right bottom of Figma's design panel.

**Comment by six7** [comment]
They can currently use `Inspect` and then `Select all` with `Deep inspect` turned on to remove all token data. With the introduction of `Remove deprecated data` this also affects the token data in the bottom right.

I'd consider this good enough, better than having a dangerous `Remove all data in this document` on Settings which could lead to unintended side-effects if users just try this out.
