### ISSUE TITLE
Allow to set if Variables, Styles or Hex values are applied on applying tokens

### ISSUE THREAD

**Issue by esthercheran** [tokens-studio/figma-plugin#2213]
When I have tokens linked with variables and styles, I want to set what should be applied on Figma when tokens are applied through the plugin.

Introduce a setting in the settings tab that will allow a default to be set, with each option explained. 
- Variables
- Styles
- Raw values

This behaviour should happen for all token types depending on whether they are applicable in variables and styles. 

![Image](https://github.com/tokens-studio/figma-plugin/assets/66366384/39da398e-1763-430d-9457-86fdc4781df9)

The logic of applying the values would be as follows:
Prefer Variables:
- If variables are present and styles are present, apply variables
- If variables are not present and styles are present, apply styles
- If variables and styles not present, apply raw values
Prefer Styles:
- If styles are present and variables are present, apply styles
- If styles are not present and variables are present, apply variables
- If styles and variables are not present, apply raw value
Use raw values:
- Always apply raw values irrespective of styles or variables being present or not

**Comment by SamIam4Hyma** [comment]
It would be great to let users know which ones were skipped (and why) so they can self solve by creating manual variables or  new tokens. 

The other option @six7 mentioned in slack is to duplicating the token with a suffix, one for each value in the single token. 

So padding-token with value 0, 8 would be 
- padding-token-SUFFIX = 0 
- padding-token-SUFFIXALT = 8

**Comment by SamIam4Hyma** [comment]
This sounds great! 

If they change their mind later, how can they switch to an alternate representation? Ex: Variables today, styles tomorrow 

If the representation doesn't exist any more, like if variables are deleted, then what? 

Are the settings on the file side, or the plug-in side? If I want to have multiple files using the same tokens can I have 1 file showing styles and another showing variables? This gets into the multiple file sync needs convo.

**Comment by SamIam4Hyma** [comment]
Will there also be consideration for the Figma feature of referencing a variable in a style for this one? 

![image](https://github.com/tokens-studio/figma-plugin/assets/141044745/7ec122d8-a59a-4420-877d-c257f106c131)

**Comment by LukeFinch** [comment]
I'm going under the assumption that 'Hex' should actually be Raw value?
For example if I don't want a border-radius variable to be applied, and just want the number.

Can you confirm @esthercheran ?

**Comment by esthercheran** [comment]
@LukeFinch yes the raw value

**Comment by esthercheran** [comment]
@SamIam4Hyma would it better to have this setting specific to a document?

**Comment by SamIam4Hyma** [comment]
UX Research shows that this feature is desired, but the wording in the design mockups was confusing and most users were unsure that the settings is the best place for this menu option. 

If we have an "apply to" settings, could it also be accessed there?

**Comment by UdayHyma** [comment]
Added to FeatureBase Roadmap : [❖⚙️ Choose to express a token as a style, variable or raw design property](https://tokensstudio.featurebase.app/p/choose-to-express-a-token-as-a-style-variable-or)

**Comment by six7** [comment]
Will be part of 2.0 RC7
