### ISSUE TITLE
For multi-value number or dimension or spacing or sizing tokens, we should skip them

### ISSUE THREAD

**Issue by esthercheran** [tokens-studio/figma-plugin#2215]
Right now if we create variables, and users have multi value tokens, we just take the first value. Instead, we should skip those variables.

The skipped tokens should be shown in a modal dialogue which is covered in https://github.com/tokens-studio/figma-plugin/issues/2211

**Comment by SamIam4Hyma** [comment]
It would be great to let users know which ones were skipped (and why) so they can self solve by creating manual variables or new tokens.

The other option @six7 mentioned in slack is to duplicating the token with a suffix, one for each value in the single token.

So padding-token with value 0, 8 would be

padding-token-SUFFIX = 0
padding-token-SUFFIXALT = 8

**Comment by SamIam4Hyma** [comment]
Added to Featurebase Roadmap as a known limitation -	[🚧 ❖❇️ Export styles and variables using sets (free plan) ](https://tokensstudio.featurebase.app/p/export-to-figma-using-token-sets)
