### ISSUE TITLE
Typing [ in the Search field Crashes the plugin

### ISSUE THREAD

**Issue by keeganedwin** [tokens-studio/figma-plugin#2224]
**Describe the bug**
Typing ` [ ` in the plugin crashes the plugin.

**Expected behavior**
Have the plugin not crash when users by mistake type in any character in the search field. After testing, the following characters don't work:

- Backslash `\`
- Brackets `( )`
- Question mark `?`
- Asterisk `*`
- Forward bracket`[`
- Add sign `+`

**Screenshots or Screencasts**
![CleanShot 2023-09-06 at 14 23 23](https://github.com/tokens-studio/figma-plugin/assets/93133012/1d79edce-7154-436e-9bae-6e99f4a500c1)

**Comment by six7** [comment]
Fixed in 1.38 🚢
