### ISSUE TITLE
Ability to carry over Decimal numbers When using the Modifier

### ISSUE THREAD

**Issue by keeganedwin** [tokens-studio/figma-plugin#2225]
**Is your feature request related to a problem? Please describe.**
When using the HSL space in a modifier, its output in the plugin is often comprised of decimal numbers but this doesn't exactly translate well to Figma as it usually rounds the decimal - causing a variation in the color that is defined in the plugin and Figma. 

**Screenshot:**
![CleanShot 2023-09-06 at 15 08 26@2x](https://github.com/tokens-studio/figma-plugin/assets/93133012/439b234a-b32b-4212-a17f-3d680663c883)

**Comment by esthercheran** [comment]
I think this is a Figma limitation. It is not possible to add a decimal on Figma color picker as well

**Comment by LukeFinch** [comment]
This request has been moved to our new feedback tool. Go check out https://tokensstudio.featurebase.app/ to create a free account. You can upvote and comment on existing posts, make a new request, and subscribe to be notified when requests move into our roadmap.

**Comment by UdayHyma** [comment]
Added to FeatureBase Roadmap : [🎨 Expand functionality of color modifiers](https://tokensstudio.featurebase.app/p/expand-functionality-of-color-modifiers)
