### ISSUE TITLE
Remove Deprecated Data Button does Not Remove All Data

### ISSUE THREAD

**Issue by keeganedwin** [tokens-studio/figma-plugin#2228]
**Describe the bug**
The remove deprecated data button does remove all data in a file, but in some instances still leaves some traces behind.
There are users that would like to just erase all data without leaving any trace of it in the side panel. 

**Expected behavior**
I don't know if it would come under performance, but can we optimise the function to just delete all data?

**Screenshots or Screencasts**
https://github.com/tokens-studio/figma-plugin/assets/93133012/05a05b92-5717-4ac6-8272-953568abbea6

**Comment by six7** [comment]
It seems the user removed deprecated data on an `instance`. In this case, the `main component` contains the data itself. Given how Figma works, Figma will always push anything from the main component to the children, as long as its present on the main and hasn't been overwritten on the child.

To fix this, you'd need to perform `Remove deprecated data` on the `main component`.

**Comment by six7** [comment]
Reopening, wasn't 100% able to reproduce to it being on an instance. I'd need more info from the user on their layer setup there that could cause this.
