### ISSUE TITLE
Ability to Search in the JSON Editor

### ISSUE THREAD

**Issue by keeganedwin** [tokens-studio/figma-plugin#2231]
**Is your feature request related to a problem? Please describe.**
User wants to make changes to tokens via the JSON editor in the plugin but has to manually search and find the token they want to edit. 

**Describe the solution you'd like**
Allows users to be able to search for keywords in the plugin's JSON editor just like you would be able to in a normal code editor.

Maybe also related to #2119

**Comment by six7** [comment]
You can just cmd + f in the code editor though, does that not work?

**Comment by keeganedwin** [comment]
Oh, my bad. I wasn't aware of this, it works!

**Comment by six7** [comment]
Closing this then 👍
