### ISSUE TITLE
Set name is not imported correctly when importing multiple files

### ISSUE THREAD

**Issue by psylok** [tokens-studio/figma-plugin#2232]
**Describe the bug**
When importing using the multiple files feature, the name of the json file is NOT used as a set name, and everything gets flattened.

**To Reproduce**
1. Export token as multiple files
2. Re import them

**Expected behavior**
Everything should be as before

**Screenshots or Screencasts**
<img width="890" alt="Screenshot 2023-09-10 at 19 15 46" src="https://github.com/tokens-studio/figma-plugin/assets/239488/7cb4a3bd-b842-4098-973e-01b6fbf79c3f">
<img width="880" alt="Screenshot 2023-09-10 at 19 17 23" src="https://github.com/tokens-studio/figma-plugin/assets/239488/92e9965a-bf3e-4f64-b146-cbac6a005fab">
<img width="879" alt="Screenshot 2023-09-10 at 19 18 58" src="https://github.com/tokens-studio/figma-plugin/assets/239488/37d35591-bf3e-49a5-ae16-23e9b77ccc4a">

**Comment by six7** [comment]
It seems you are importing a single file that was exported as `multiple files export`. You'll want to choose `Load folder` instead, and choose the folder where the files are in.

**Comment by six7** [comment]
Closing this, but feel free to reopen if there are any open questions!
