### ISSUE TITLE
Automatically scope variables by token type

### ISSUE THREAD

**Issue by LukeFinch** [tokens-studio/figma-plugin#2233]
Add a setting to the plugin that automatically scopes any variables created by its token type.

Settings related to how we write styles & variables have been moved into the modal which is part of #2211 
This lives along-side those settings

**Considerations:**
Implications with W3C spec  - do we keep our studio token types which do not exist in the spec, do they become a shortcut to scopes? i.e. "Spacing" is a dimension scoped to "Gap" in Figma

```[tasklist]
### Related Tasks
- [ ] https://github.com/tokens-studio/figma-plugin/issues/2194
- [ ] https://github.com/tokens-studio/figma-plugin/issues/2300
```

**Comment by SamIam4Hyma** [comment]
We've also used the idea of scope with consideration to token name in the apply variables plug-in. 

For example, a dimension or number token with the name "radius" or "radii" would automatically scope that variable to border/corner radius. 

This allows the folks trying to keep to the W3C spec to take advantage of semi-automated scoping.

**Comment by LukeFinch** [comment]
This request has been moved to our new feedback tool. Go check out https://tokensstudio.featurebase.app/ to create a free account. You can upvote and comment on existing posts, make a new request, and subscribe to be notified when requests move into our roadmap.
