### ISSUE TITLE
Improved UI/UX for the Styles & Variables Menu

### ISSUE THREAD

**Issue by keeganedwin** [tokens-studio/figma-plugin#2246]
**Is your feature request related to a problem? Please describe.**
We've seen multiple users struggle with understanding why they can't (disabled/greyed out) create variables albeit being a Pro user. 

**Describe the solution you'd like**
Although disabled, we should be able to expose some piece of information to users on what exactly is required in order to create 'variables'.
1. Even on disable, can we expose more information as to why it's greyed out?
- Tooltip
- Popover
- Link to self-help
- Details?

2. Clicking on the disabled options - popover/tooltip that states themes need to be setup to be able to create variables.
3. We can have badge indicators that can be used for price locked features - something possible for in the menu?

**Comment by esthercheran** [comment]
The UI/UX improvements has been captured in #2302
