### ISSUE TITLE
Themes Checkbox Improved Enabling Function  

### ISSUE THREAD

**Issue by keeganedwin** [tokens-studio/figma-plugin#2247]
**Is your feature request related to a problem? Please describe.**
When creating themes in theme groups, the default behaviour of the checkboxes is `set as source` (dots) vs `enabled` checkboxes. This is causing a lot of new users to get blocked creating variables and styles.

Link to [Design Board](https://www.figma.com/file/nZiTKM6Efsdjt6TGZ0jNml/Figma-Tokens?type=design&node-id=3521-32512&mode=design&t=4qlwUJt2zUVm6c3k-4)

> Thought it was odd that I had to click 2x for every set I wanted to enable a theme. It seems counter-intuitive.

**Describe the solution you'd like**
Enabled > source
Source > disabled
Disabled > enabled

**Comment by keeganedwin** [comment]
Link to [Design Board](https://www.figma.com/file/nZiTKM6Efsdjt6TGZ0jNml/Figma-Tokens?type=design&node-id=3521-32512&mode=design&t=4qlwUJt2zUVm6c3k-4)

**Comment by SamIam4Hyma** [comment]
@six7 proposing to close and archive as the new theme management enhancements make this issue non relevant

**Comment by SamIam4Hyma** [comment]
Added to Featurebase Roadmap-	[💚 Theme management enhancements - QOL](https://tokensstudio.featurebase.app/p/theme-management-enhancements-v2)
