### ISSUE TITLE
Check credentials error when working on the same Figma file and repository in GitHub

### ISSUE THREAD

**Issue by rbosker** [tokens-studio/figma-plugin#2248]
**Describe the bug**
Check credentials error when working on the same Figma file and repository in GitHub and switching between branches in the plugin.

**To Reproduce**
Requirements:
- Work in the same Figma file
- Connect to the same repository and branch

When working in the same Figma file and on the same repo and branch with 2 users.
1. User X changes the branch from Branch A to Branch B
2. User Y still got Branch A setup and closes the plugin
3. Once you re-opens the plugin, you will get the Error check credentials and the PAT is empty. If you look closely, the branch shown in the modal is set to Branch B
4. If you close the modal and afterwards select the syncing method connected to Branch A again, this works fine.

Note: if you have in the Settings tab 2 syncing providers setup 1 for Branch A and 1 for Branch B, the issue doesn't seem to occur.

**Expected behavior**
I expect that after reopening the plugin, that the credentials entered work and that you connect to Branch B, since that is saved on the document.

**Comment by esthercheran** [comment]
Closing this as same issue described in #2200

**Comment by Arcrammer** [comment]
Tokens Studio does not support GitHub Beta tokens, will need to use Classic. This information should be documented more clearly.
