### ISSUE TITLE
Ability to create Variables from New Tokens when Variables already Exist

### ISSUE THREAD

**Issue by keeganedwin** [tokens-studio/figma-plugin#2249]
**Is your feature request related to a problem? Please describe.**
Users sometimes already have existing variables, then create new tokens and want to be able to create variables with these newly setup tokens adding to the existing collection.

**Comment by six7** [comment]
@keeganedwin I'm not sure I understand. They can do that already?

**Comment by keeganedwin** [comment]
Sorry @six7, I shall close this for now, I can't seem to find the slack thread to expand on this...
