### ISSUE TITLE
Number Token is Not Displayed as Reference 

### ISSUE THREAD

**Issue by keeganedwin** [tokens-studio/figma-plugin#2256]
**Is your feature request related to a problem? Please describe.**
There are a few token types where the Number token type works as a reference but only when clicking on save, but it however does not show as a reference. 

> We have a number token which is being used as a “utility token” for math operations and such. It does not need a unit. Some users are doing their calculations there, then referencing the number token in the dimension tokens and adding a unit at the end.
> ex: **{number-token-name}px**

Can we also display it in the dropdown looking to reference tokens? It currently shows in the dropdown when referencing it in the following token-types

**Are displayed:**
1. Spacing
2. Sizing
3. BorderRadius
4. BorderWidth

**Not displayed:**
1. Opacity
2. Line-height
3. fontSize
4. LetterSpacing
5. ParagraphSpacing

**Describe the solution you'd like**
Also support the display the Number token-type as references in the dropdown. 

**Additional context**
<img width="489" alt="CleanShot 2023-09-20 at 18 39 20@2x" src="https://github.com/tokens-studio/figma-plugin/assets/93133012/24ed349e-9131-46ba-9a8a-4d456ef66e05">

 **This is also present in Composition tokens:**
No references are displayed in the `borderBottom` dropdown property of the composition token when trying to reference a `border` type token. This is also present with other properties such as:

1. borderLeft
2. borderTop
3. borderRight

<img width="526" alt="CleanShot 2023-09-22 at 15 43 19@2x" src="https://github.com/tokens-studio/figma-plugin/assets/93133012/6b35c861-b5db-4274-8f79-349a505c0b88">

**Expected behaviour:**
Users should just be able to reference the border token type in the aforementioned token properties in a composition token.

**Comment by UdayHyma** [comment]
[Migrated to Featurebase](https://tokensstudio.featurebase.app/p/token-metadata-enhancements)
