### ISSUE TITLE
Math Operations with Multi-value References is Not Correctly Calculated

### ISSUE THREAD

**Issue by keeganedwin** [tokens-studio/figma-plugin#2257]
**Is your feature request related to a problem? Please describe.**
Using operations with multi-value references does not work as expected. In the following used-case, it is displayed as resolved but when applied in Figma, the padding values are the same as the user's global size **global.fontSize - 14.** 

> _The following: "{global.fontSize}*1.25 {global.fontSize}*1.25" does pick up the reference, but does not perform the calculations, and instead sticks to 14 (which is my global.fontSize)._

**Describe the solution you'd like**
Allow for the correct calculation when using operations with multi-value references. 

**Does not work:**
![Screenshot 2023-09-20 at 10 39 55](https://github.com/tokens-studio/figma-plugin/assets/93133012/777a9c1f-aed8-4a16-b381-9b2f97fdc72a)

**Singular works:**
![Screenshot 2023-09-20 at 10 39 12](https://github.com/tokens-studio/figma-plugin/assets/93133012/d4a6b6ae-6e33-4df0-a50e-6c8cdf94229b)

**Comment by surfinzap** [comment]
Experiencing the same issue; it limits the the use of more complex tokens.

**Comment by keeganedwin** [comment]
@surfinzap we could potentially fix this by modifying the delimiter to treat spaces as delimiters, but this could potentially disrupt existing user code, which will break functionality for users who rely on the current behavior. The workaround available for users is to create a separate token for each. We will conclude this as a limitation.

**Comment by surfinzap** [comment]
@keeganedwin, that's a rather big limitation, making large projects less maintainable. Since I cannot use complex calculations, I need to maintain moat variables just for the sake of calculation. Is there any other solution? e.g. adopting brackets as delimiters?

**Comment by keeganedwin** [comment]
> @keeganedwin, that's a rather big limitation, making large projects less maintainable. Since I cannot use complex calculations, I need to maintain moat variables just for the sake of calculation. Is there any other solution? e.g. adopting brackets as delimiters?

@six7

**Comment by six7** [comment]
> [@keeganedwin](https://github.com/keeganedwin), that's a rather big limitation, making large projects less maintainable. Since I cannot use complex calculations, I need to maintain moat variables just for the sake of calculation. Is there any other solution? e.g. adopting brackets as delimiters?

Not alternative so far, no. We don't have it on our roadmap, but we'll add it to featurebase and see if there's much desire for it - @keeganedwin will link that one here

**Comment by keeganedwin** [comment]
Migrated to [Featurebase](https://tokensstudio.featurebase.app/p/math-in-value-enhancements)
