### ISSUE TITLE
Allow more precision on color alpha values

### ISSUE THREAD

**Issue by thomasaull** [tokens-studio/figma-plugin#2262]
**Is your feature request related to a problem? Please describe.**

I'm trying to define colors with very precise alpha values, e.g. #000 with an alpha of 5.5%. When trying to enter this value in tokens studio it gives me an validation error:

![image](https://github.com/tokens-studio/figma-plugin/assets/227756/4120b69d-f7ab-464d-8be4-b2724336c089)

When not using the color picker, but putting the desired value in the rgba function I don't get a validation error:

![image](https://github.com/tokens-studio/figma-plugin/assets/227756/27e9464c-93b1-46f0-a9d7-133bfb74e070)

However, when this token is applied it applies a rounded value, in this case 5% instead of 5.5%: 
![image](https://github.com/tokens-studio/figma-plugin/assets/227756/8b12a7a1-2ad8-4dcb-b5d8-b7843c7332e0)

**Describe the solution you'd like**
- Allow inputting alpha values with more precision, I think two decimals should work for almost every case, e.g. 5.42% and two decimals is also the precision which is supported by figma
- When the token is applied, apply it with the defined precision and don't rount the alpha value

**Comment by six7** [comment]
Thanks for reporting, I think this might be due to the fact that we currently round to 2 decimals, instead of 3 as in your example (`0,055`) We should change that to 3 to allow these scenarios of low-opacity.

**Comment by LukeFinch** [comment]
This request has been moved to our new feedback tool. Go check out https://tokensstudio.featurebase.app/ to create a free account. You can upvote and comment on existing posts, make a new request, and subscribe to be notified when requests move into our roadmap.

**Comment by UdayHyma** [comment]
Added to FeatureBase Roadmap : [🎨 Expand functionality of color modifiers](https://tokensstudio.featurebase.app/p/expand-functionality-of-color-modifiers)
