### ISSUE TITLE
Show composition values in Dev Mode

### ISSUE THREAD

**Issue by esthercheran** [tokens-studio/figma-plugin#2263]
in Dev Mode, show the values of the composition applied:
![image](https://github.com/tokens-studio/figma-plugin/assets/66366384/8b33fffb-27e3-405c-941c-aa0d09a2eb79)
Same logic could be applied for other multi-value tokens (typography, shadow, border)

Describe alternatives you've considered
Either we document the composition values in the Figma design or our developers fetch them from the JSON.

**Comment by LukeFinch** [comment]
This request has been moved to our new feedback tool. Go check out https://tokensstudio.featurebase.app/ to create a free account. You can upvote and comment on existing posts, make a new request, and subscribe to be notified when requests move into our roadmap.

**Comment by UdayHyma** [comment]
Added to Featurebase Roadmap: [👨‍💻 Enhance data in Dev Mode
](https://tokensstudio.featurebase.app/p/enhance-data-in-dev-mode)
