### ISSUE TITLE
Onboarding Read more links should point to docs.tokens.studio

### ISSUE THREAD

**Issue by wayne-shih** [tokens-studio/figma-plugin#2275]
**Describe the bug**

docs.figmatokens.com is not redirecting to docs.tokens.studio

Found this out as the "read more" button in the sets callout box still links to docs.figmatokens.com

**To Reproduce**
1. Click on "read more" 
<img width="581" alt="image" src="https://github.com/tokens-studio/figma-plugin/assets/51947763/aa940957-dded-4067-b715-e2643c570839">

2. this links to ... https://docs.figmatokens.com/themes/token-sets?ref=onboarding_explainer_sets 
<img width="526" alt="image" src="https://github.com/tokens-studio/figma-plugin/assets/51947763/c375cabb-49b3-46bc-8dab-ff726b04c9fb">

**Expected behavior**
Expect to be linked here : https://docs.tokens.studio/themes/token-sets?ref=onboarding_explainer_sets

**Comment by six7** [comment]
Thanks for raising this! We'll get this fixed 🙏
