### ISSUE TITLE
Documentation Tokens / Raw Value is not working

### ISSUE THREAD

**Issue by onursenture** [tokens-studio/figma-plugin#2276]
**Describe the bug**
Documentation Tokens / Raw Value is not working for me after the 1.38 release.

**Screenshots or Screencasts**

https://github.com/tokens-studio/figma-plugin/assets/244957/063e21a5-b211-4152-bc4a-283276a1c2da

**Comment by dgiebe** [comment]
I have the same issue now.

**Comment by keeganedwin** [comment]
@six7 does this fix #2155 as well? This is also present with the other toke types
