### ISSUE TITLE
token-transformer with --throwErrorWhenNotResolved blurts out unreadable content

### ISSUE THREAD

**Issue by thomasmattheussen** [tokens-studio/figma-plugin#2279]
**Describe the bug**
I'm having a weird issue with the token-transform when using the `--throwErrorWhenNotResolved` option. It correctly throws.

However, the output is unreadable. It just blurts out the contents of the minified `token-transformer/dist/transform.js` file.

What's weird is, if I run that `token-transformer/dist/transform.js` file through prettier save it, and rerun the transform, suddenly I get a nice error output saying which token failed to resolve.

**To Reproduce**
1. have a token output with a token that will fail to resolve
2. run token-transformer with the option `--throwErrorWhenNotResolved`

**Expected behavior**
Should output a nice error message saying which token failed to resolve.

**Comment by SamIam4Hyma** [comment]
@jorenbroekema is this issue still occuring?

**Comment by jorenbroekema** [comment]
token-transformer deprecated in favor of using sd-transforms, dont think it's a problem there, error message is from style-dictionary since it uses the ref utils from style-dictionary
