### ISSUE TITLE
Very slow to update nodes when starting up Tokens

### ISSUE THREAD

**Issue by TeunIG** [tokens-studio/figma-plugin#2291]
**Describe the bug**

**To Reproduce**
- Start up Figma tokens
- Click the unchecked Foundation and Web sub folder
- The plugin starts fetching and updating nodes, and it takes a few minutes to complete
I'm on a M2 Pro Max and on a fiber network so performance on this side should not be the issue.
Also my colleagues pulling from same files do not have this issue, although they're not working in this same file, which might be getting to big or complex?

**Expected behavior**
being Instantly able to use tokens plugin without the issue 

**Screenshots or Screencasts**
![image](https://github.com/tokens-studio/figma-plugin/assets/109134714/a028ef6e-29aa-4ad9-855b-76d6e23d97ce)

**Figma file (optional)**
Cant share this file, sorry, let me know if there is any info i can share to help

**JSON (optional)**
If possible, attach the JSON that leads to this bug.

**Comment by six7** [comment]
So in your case, you:

- Start up the plugin
- Activate a few themes
- Notice slowness

Correct?

In that case, I'd recommend to change the `Apply to` settings in the bottom right to `Apply to selection`. I assume you are working in a huge document, and have this set to `Apply to document` (or `Page` and are working in a big page).

In your screenshot the plugin needs to iterate over 19k nodes, which will take a while and is expected.

As long as you do not activate / deactivate sets you are able to use the plugin instantly, but any "check" of a set / folder causes the plugin to update the `selection / page / document` (whatever you chose).

Closing this as I think this solves your problem, but feel free to reopen if you think this is a mistake.
