### ISSUE TITLE
Typography token aliases not being resolved

### ISSUE THREAD

**Issue by straef** [tokens-studio/figma-plugin#2292]
**Describe the bug**
this is a bit hard to describe because i am not sure if i understand what is going on, but i think i have isolated the behavior. oh, and there are two things that may or may not be related.

in typography tokens aliases to other typography token attributes when that attribute is an alias to a non-typography token like font family (eg setting a token's font family using {TYPOGRAPHY.sometoken.fontFamily} where TYPOGRAPHY.sometoken.fontFamily = {FONTFAMILY.familytoken}) results in a broken link. the ui displays the red dot on the token name, and the broken link icon when hovered. the attribute list displays the alias and it resolves to the value of that alias. but does not get the final value, despite the aliased token having no issue.

update: i just noticed that when i attempt to apply one of these "broken" typography tokens to a text layer, the plugin toasts an error: "Error setting font family/weight combination for [familyattribute]/[weightattribute]". but i think this is a symptom rather than a cause.

additionally: making tokens as specified below and then hovering over THREE will crash the ui to a blank window.
typographyONE(attributedirectlydefined) < typographyTWO{attribute} < typographyTHREE{attribute}

**To Reproduce**
the json contains all the issues i am attempting to describe

hover over "sem-ref-direct-fontFamily" in the gui to see the crash.
the broken link is displayed on "sem-ref_family-fontFamily".

**Expected behavior**
aliasing an attribute of a token that contains a valid value, alias or otherwise, should fully resolve

the plugin should not crash when hovering a token with an alias of an alias of a direct value.

**Screenshots or Screencasts**
![image](https://github.com/tokens-studio/figma-plugin/assets/20950411/aeeca5e9-52da-4838-b6ea-560c5680bebb)
![2023-10-02 10-24-38](https://github.com/tokens-studio/figma-plugin/assets/20950411/c0081754-a112-4e4d-8601-704096e12127)

**Figma file (optional)**
https://www.figma.com/file/0wmDLoE45VG6XjnrtTAGeQ/broken-token-alias-demo

**JSON (optional)**
https://github.com/tokens-studio/figma-plugin/issues/2292#issuecomment-1777929982

**Comment by straef** [comment]
update: the crash is because i was not specifying the attribute of the typography token i was aliasing.

new json: i attempted to make the paths more comprehensible. the problem is that an alias to an attribute of another typography token, whether the first is set directly in the token or as a token of that specific attribute (eg font family token) always despite the aliased token.attribute resolving without issue.
{
  "ref": {
    "direct": {
      "value": {
        "fontFamily": "Arial"
      },
      "type": "typography"
    },
    "family": {
      "value": "Arial",
      "type": "fontFamilies"
    }
  },
  "sem": {
    "<ref><family>": {
      "value": {
        "fontFamily": "{ref.family}"
      },
      "type": "typography"
    },
    "<ref><direct><fontFamily>": {
      "value": {
        "fontFamily": "{ref.direct.fontFamily}"
      },
      "type": "typography"
    },
    "<sem><ref-family><fontFamily>": {
      "value": {
        "fontFamily": "{sem.ref-family.fontFamily}"
      },
      "type": "typography"
    },
    "<sem><ref-direct-fontFamily><fontFamily>": {
      "value": {
        "fontFamily": "{sem.ref-direct-fontFamily.fontFamily}"
      },
      "type": "typography"
    }
  }
}

**Comment by keeganedwin** [comment]
@six7 @esthercheran also related to #2301

**Comment by straef** [comment]
in my case the tokens are actually broken. they will apply the fully resolved attributes, but anything that does not fully resolve is not applied.

**Comment by straef** [comment]
@esthercheran yeah. @keeganedwin mentioned #2301 where the tokens are functional but marked as broken. i wanted to point out that for me the tokens are broken and marked as broken, which is different than that issue.

**Comment by esthercheran** [comment]
@straef So I think there was no bug if your tokens were broken. Going to close this issue.

**Comment by straef** [comment]
there is a bug. they should not be broken. or if there is not a bug why are they not resolving?

**Comment by straef** [comment]
@esthercheran @keeganedwin to attempt to demonstrate what the bug is and why this issue should not be closed. i have added to the demo file (https://www.figma.com/file/0wmDLoE45VG6XjnrtTAGeQ/broken-token-alias-demo) tokens for colors using the same approach as typography. the color tokens do not have any issues and will resolve a chain of aliases to the root value, where typography tokens will only resolve the first link in the chain. 

defining a base font token, then using an alias to specific properties in a cta-text token, and then pointing an alias to those properties of cta-text in a button-text token, will leave the button-text token broken.

basically **typography token properties do not cascade**. typography tokens as a whole cascade, but often you need to make adjustments to individual properties for differing uses.

in css terms you would be unable to:
body { (all the font properties) }
p { (modify letter-spacing) }
p.strong { font-weight: bold }
because p.strong would not be able to resolve all the properties defined in body for some reason.

![image](https://github.com/tokens-studio/figma-plugin/assets/20950411/12d7e922-e55a-4176-8c20-1343711393d1)
![image](https://github.com/tokens-studio/figma-plugin/assets/20950411/d6cedbcf-3295-4098-97ba-c0384bb89e65)


{
  "direct": {
    "first": {
      "value": {
        "fontFamily": "Arial"
      },
      "type": "typography"
    },
    "second": {
      "value": {
        "fontFamily": "{direct.first.fontFamily}"
      },
      "type": "typography"
    },
    "third": {
      "value": {
        "fontFamily": "{direct.second.fontFamily}"
      },
      "type": "typography"
    }
  },
  "alias": {
    "first": {
      "value": "Arial",
      "type": "fontFamilies"
    },
    "second": {
      "value": {
        "fontFamily": "{alias.first}"
      },
      "type": "typography"
    },
    "third": {
      "value": {
        "fontFamily": "{alias.second.fontFamily}"
      },
      "type": "typography"
    }
  },
  "colors": {
    "direct": {
      "first": {
        "value": "#007fff",
        "type": "color"
      },
      "second": {
        "value": "{colors.direct.first}",
        "type": "color"
      },
      "third": {
        "value": "{colors.direct.second}",
        "type": "color"
      },
      "fourth": {
        "value": "{colors.direct.third}",
        "type": "color"
      },
      "adinfinitum": {
        "value": "{colors.direct.fourth}",
        "type": "color"
      }
    }
  },
  "number": {
    "direct": {
      "first": {
        "value": "1",
        "type": "number"
      },
      "second": {
        "value": "{number.direct.first}",
        "type": "number"
      },
      "third": {
        "value": "{number.direct.second}",
        "type": "number"
      }
    }
  },
  "body": {
    "value": {
      "fontFamily": "Arial",
      "fontWeight": "Regular",
      "lineHeight": "24",
      "fontSize": "16",
      "letterSpacing": "0",
      "paragraphSpacing": "0",
      "paragraphIndent": "0",
      "textDecoration": "None",
      "textCase": "As Typed"
    },
    "type": "typography",
    "description": "body font declaration for css"
  },
  "p": {
    "value": {
      "fontFamily": "{body.fontFamily}",
      "fontWeight": "{body.fontWeight}",
      "lineHeight": "{body.lineHeight}",
      "fontSize": "{body.fontSize}",
      "letterSpacing": "25%",
      "paragraphSpacing": "{body.paragraphSpacing}",
      "paragraphIndent": "{body.paragraphIndent}",
      "textDecoration": "{body.textDecoration}",
      "textCase": "{body.textCase}"
    },
    "type": "typography",
    "description": "paragraph adjusts letter-spacing. exaggerated for easy visual acquisition."
  },
  "p-strong": {
    "value": {
      "fontFamily": "{p.fontFamily}",
      "fontWeight": "Black",
      "fontSize": "{p.fontSize}",
      "lineHeight": "{p.lineHeight}",
      "letterSpacing": "{p.letterSpacing}",
      "paragraphSpacing": "{p.paragraphSpacing}",
      "paragraphIndent": "{p.paragraphIndent}",
      "textDecoration": "{p.textDecoration}",
      "textCase": "{p.textCase}"
    },
    "type": "typography",
    "description": "modifies paragraph for strong text"
  },
  "black": {
    "value": "Black",
    "type": "fontWeights"
  }
}

**Comment by straef** [comment]
{
  "direct": {
    "first": {
      "value": {
        "fontFamily": "Arial"
      },
      "type": "typography"
    },
    "second": {
      "value": {
        "fontFamily": "{direct.first.fontFamily}"
      },
      "type": "typography"
    },
    "third": {
      "value": {
        "fontFamily": "{direct.second.fontFamily}"
      },
      "type": "typography"
    }
  },
  "alias": {
    "first": {
      "value": "Arial",
      "type": "fontFamilies"
    },
    "second": {
      "value": {
        "fontFamily": "{alias.first}"
      },
      "type": "typography"
    },
    "third": {
      "value": {
        "fontFamily": "{alias.second.fontFamily}"
      },
      "type": "typography"
    }
  },
  "colors": {
    "direct": {
      "first": {
        "value": "#007fff",
        "type": "color"
      },
      "second": {
        "value": "{colors.direct.first}",
        "type": "color"
      },
      "third": {
        "value": "{colors.direct.second}",
        "type": "color"
      },
      "fourth": {
        "value": "{colors.direct.third}",
        "type": "color"
      },
      "adinfinitum": {
        "value": "{colors.direct.fourth}",
        "type": "color"
      }
    }
  },
  "number": {
    "direct": {
      "first": {
        "value": "1",
        "type": "number"
      },
      "second": {
        "value": "{number.direct.first}",
        "type": "number"
      },
      "third": {
        "value": "{number.direct.second}",
        "type": "number"
      }
    }
  },
  "body": {
    "value": {
      "fontFamily": "Arial",
      "fontWeight": "Regular",
      "lineHeight": "24",
      "fontSize": "16",
      "letterSpacing": "0",
      "paragraphSpacing": "0",
      "paragraphIndent": "0",
      "textDecoration": "None",
      "textCase": "As Typed"
    },
    "type": "typography",
    "description": "body font declaration for css"
  },
  "p": {
    "value": {
      "fontFamily": "{body.fontFamily}",
      "fontWeight": "{body.fontWeight}",
      "lineHeight": "{body.lineHeight}",
      "fontSize": "{body.fontSize}",
      "letterSpacing": "25%",
      "paragraphSpacing": "{body.paragraphSpacing}",
      "paragraphIndent": "{body.paragraphIndent}",
      "textDecoration": "{body.textDecoration}",
      "textCase": "{body.textCase}"
    },
    "type": "typography",
    "description": "paragraph adjusts letter-spacing. exaggerated for easy visual acquisition."
  },
  "p-strong": {
    "value": {
      "fontFamily": "{p.fontFamily}",
      "fontWeight": "Black",
      "fontSize": "{p.fontSize}",
      "lineHeight": "{p.lineHeight}",
      "letterSpacing": "{p.letterSpacing}",
      "paragraphSpacing": "{p.paragraphSpacing}",
      "paragraphIndent": "{p.paragraphIndent}",
      "textDecoration": "{p.textDecoration}",
      "textCase": "{p.textCase}"
    },
    "type": "typography",
    "description": "modifies paragraph for strong text"
  },
  "black": {
    "value": "Black",
    "type": "fontWeights"
  }
}

**Comment by esthercheran** [comment]
Reopening the issue with the new information from @straef

**Comment by straef** [comment]
any update on this?

**Comment by keeganedwin** [comment]
@straef are you still facing this issue? The JSON you provided does not include the broken tokens as mentioned in the ticket

**Comment by straef** [comment]
the problem is the same, despite the tokens no longer indicating they are broken. any aliases pointing to a typography-token.property (eg fontFamily) just uses the value of that property, even when it is an alias

```
font-family.default = Arial

typography.text {
    fontFamily = {font-family.default}
    ...other properties...
}

typography.link {
    fontFamily = {typography.text.fontFamily}
    ...other properties...
}
```

in the above example if i attempt to apply `typography.link` to a text layer, even if the token is not marked as broken, the application will fail because it is trying to apply `{font-family.default}` as the font family, not `Arial`.

if i am doing something wrong in how i reference things please educate me. but this only happens with typography tokens, all other token types work as expected based on my understanding of how tokens should work; à la cascading values.

these screenshots show that it knows the ultimate value i am trying to put there (arial in this case), but it ends up putting an alias there instead.
![image](https://github.com/tokens-studio/figma-plugin/assets/20950411/ae099628-24d2-412d-a80b-67d4c42d7b8d)
![image](https://github.com/tokens-studio/figma-plugin/assets/20950411/71d35981-fce5-401a-a31a-8d1fd1505616)

**Comment by keeganedwin** [comment]
Reproducible in `2.2.2`.

**Comment by six7** [comment]
From reading up on this issue it sounds like a feature request rather than a bug.

I guess it's related to wanting to extend typography tokens by using

{
  ...typography.default,
  fontfamily: "Arial"
}

The way that references are being used to target a specific property, and then later trying to make it a composite rather, is not something currently supported. I'll be closing this, we currently do not have plans to add this, as its also not covered in the DTCG.
