### ISSUE TITLE
Ensure Synchronisation between Tokens and Styles regardless of the Selected Method

### ISSUE THREAD

**Issue by keeganedwin** [tokens-studio/figma-plugin#2297]
**Is your feature request related to a problem? Please describe.**
We currently advise users to either stick to just using tokens or just styles to change properties of an element. If styles are created via the plugin and a user then proceeds to for example change the typography via Figma's styles, this change is not synced (doesn't reflect) within the plugin. i.e. if a **H1** token is applied and it's then changed to **H2** via Figma's styles, this change is not reflected in the plugin. 

**Describe the solution you'd like**
Is this something we would want to keep in sync? That even if a user changes it via Figma's styles, that this is still in sync with the plugin.

**Comment by SamIam4Hyma** [comment]
@LukeFinch proposing we close this one and reframe in a different way, if you agree please close.
