### ISSUE TITLE
Some tokens are falsely labeled as broken

### ISSUE THREAD

**Issue by surfinzap** [tokens-studio/figma-plugin#2301]
For composite token types:
- Typography
- Border
- Box shadow
There is an issue at the 3rd level of referencing which appears broken but is not really broken. The token when referenced again does not show as broken.

Detailed ways of reproduction given in the Figma file below:
**Figma File**
https://www.figma.com/file/3wBqHDuy4DnTdlcfUOQYec/Github-issue-%232301?type=design&node-id=0%3A1&mode=design&t=a0u6uR80uQEUjKkc-1

----
<details><summary>Original Issue</summary>
**Describe the bug**
I have transition tokens defined in JSON and they are used to generate CSS variables. They follow a different structure as in [Design Tokens Draft Format](https://tr.designtokens.org/format/#transition)

```JSON
    "animation-timing": {
      "50": { "value": "cubic-bezier(0.25,1,0.3,1)", "type": "animationTiming" }
    },
    "animation-duration": {
      "50": { "value": "0.25", "type": "animationDuration" },
      "100": { "value": "0.5", "type": "animationDuration" }
    },
    "animation-delay": {
      "none": { "value": "0ms", "type": "animationDelay" }
    },
    "transition": {
      "50": {
        "value": {
          "animation-timing": "{animation-timing.50}",
          "animation-duration": "{animation-duration.50}",
          "animation-delay": "{animation-delay.none}"
        },
        "type": "transition"
      },
      "100": {
        "value": {
          "animation-timing": "{animation-timing.50}",
          "animation-duration": "{animation-duration.100}",
          "animation-delay": "{animation-delay.none}"
        },
        "type": "transition"
      }
    }
```

This animation definition is then linked to the abstract `form-control` token:
```JSON
    "form-control": {
      "xs": {    
        "transition": { "value": "{transition.50}", "type": "transition" }
      },
    }
```

And then it is linked to components that share form-control definition:
```JSON
    "button": {
      "xs": {
        "transition": {
          "value": "{form-control.xs.transition}",
          "type": "transition"
        }
      },
```

When I look at the plugin, the first component to have this transition is labeled as it has a broken reference (A). The rest of the components show the reference is correct (B). 
![image](https://github.com/tokens-studio/figma-plugin/assets/1387798/ca2fc19c-3062-4da6-bd02-26877f74dcd1)

When I delete the first component in the list (e.g. I delete a button), the broken reference passes to another component (e.g., icon-button) and shows other references as correct:
![image](https://github.com/tokens-studio/figma-plugin/assets/1387798/81f86ca9-c017-490b-9dfb-1390dfe2ef7d)

**To Reproduce**
Not sure how to reproduce it, see the description of the behavior

**Expected behavior**
The broken reference should not be shown, as the reference is not broken.

**Screenshots or Screencasts**
see above

**JSON (optional)**
I'm on the Tokens Studio Slack, I can send the file via Slack if needed

**Figma File**
https://www.figma.com/file/3wBqHDuy4DnTdlcfUOQYec/Github-issue-%232301?type=design&node-id=0%3A1&mode=design&t=a0u6uR80uQEUjKkc-1

</details>

**Comment by keeganedwin** [comment]
@esthercheran can this be fixed asap? Users are thrown in confusion with being able to apply the tokens but are being displayed as broken references. Here are screenshots from another user facing the issue: 
![image (19)](https://github.com/tokens-studio/figma-plugin/assets/93133012/3e8a6145-d4ea-4fec-a15c-65d9a2e09ecf)

![image (20)](https://github.com/tokens-studio/figma-plugin/assets/93133012/fce24fa0-6eb3-4582-bcee-569f4b61b6f2)

**Comment by keeganedwin** [comment]
@esthercheran, this also seems to relate to ticket #2292

**Comment by stephen-salyer** [comment]
Hello! I found a work around to remove the error. it turned out naming tokens the exact same way in two different "collections" (speaking in Figma terms cause thats what we output to) causes this error, even though you can apply the tokens still. I renamed the first set of tokens and the badges went away. I would want to ability to have the same naming structure in two different json files within collections though without error being thrown.
