### ISSUE TITLE
Outside links open in the wrong Chrome window

### ISSUE THREAD

**Issue by ventrebleu** [tokens-studio/figma-plugin#2304]
**Describe the bug**
When clicking on "Feedback", "Docs", or "Create a Pull Request", the plug-in opens the wrong Chrome window (and the wrong profile).

**To Reproduce**
1. Open the plug-in
2. Click on any of the links and buttons with an attached URL
3. The link doesn't open in the last Chrome window used

**Expected behavior**
External links should open in the last used Chrome window

**Comment by keeganedwin** [comment]
@ventrebleu This seems to work as expected on our end. The plugin does not manipulate any such data for it to open links in other Chrome profiles. The links open in the profile that was last used/opened.

**Comment by SamIam4Hyma** [comment]
@keeganedwin proposing we close/archive this one.
