### ISSUE TITLE
Duplicating Figma file keeps some sort of "config sync" to master file. Unable to remove sync provider config.

### ISSUE THREAD

**Issue by lukethacoder** [tokens-studio/figma-plugin#2307]
**Describe the bug**

Duplicate figma files keep some sort of "sync" to the file they were duplicated from. Atempting to remove sync provider config does not seem to work as intended and removes it in the original file.

**To Reproduce**
1. Setup a sync provider (presumably any, but I'm using ADO in this instance)
2. Duplicate the figma file
3. Open the duplicate file
4. See git sync still in place
5. Remove git sync in duplicated file
6. Return to original file and see sync provider has been removed

**Expected behavior**

Each figma file should store its own sync provider config without affecting any other figma file.

**Figma file (optional)**
Send us the link to a Figma file containing a reproducible example

Unable to share file(s) in question, can create a minimal example if needed for further clarification

**Comment by keeganedwin** [comment]
Confirming that this indeed is a bug after testing @esthercheran. If I duplicate the main file and then delete the Sync provider in the main file, it also gets deleted from the duplicate file with displaying following error:
<img width="577" alt="CleanShot 2023-10-24 at 18 15 16@2x" src="https://github.com/tokens-studio/figma-plugin/assets/93133012/312206b0-2a37-42e4-9adc-5732b2664d01">

**Comment by six7** [comment]
Just chiming in that this is not a bug. Deleting a sync provider is not done on a file basis. If you delete a sync provider from the list of sync providers, it is deleted for the current user. Yes, the currently used sync provider is saved in the Figma file, but the user's credentials that you see on the `Sync providers` tab are the ones from the user. I'll add a note to this for when we redesign the Sync settings to make it clear that these are for the user.
