### ISSUE TITLE
Ability to Save Theme-group Renaming Action by Clicking

### ISSUE THREAD

**Issue by keeganedwin** [tokens-studio/figma-plugin#2309]
**Is your feature request related to a problem? Please describe.**
Users sometimes experience the plugin freezing when renaming their theme-group, clicking outside the field and then trying to close the modal **where** the plugin freezes.

To avoid this, they need hit **ENTER** when renaming to save the new theme-group name. 

**Describe the solution you'd like**
Allow users to save the renaming action by even clicking outside the field.

**Screenshots**
![Frame 474](https://github.com/tokens-studio/figma-plugin/assets/93133012/b7361b79-227f-41e2-a3e2-ffbc0668b8dd)

**Comment by six7** [comment]
Let's not do `click to save`. Let's rather have `Save` icon button to the right of the input when it is being edited.

@keeganedwin can you mock that one up?

**Comment by LukeFinch** [comment]
This request has been moved to our new feedback tool. Go check out https://tokensstudio.featurebase.app/ to create a free account. You can upvote and comment on existing posts, make a new request, and subscribe to be notified when requests move into our roadmap.

**Comment by UdayHyma** [comment]
Added to Featurebase Roadmap : [🌜Theme management (pro) enhancements](https://tokensstudio.featurebase.app/p/theme-management-enhancements)
