### ISSUE TITLE
Nested Aliases not resolving.

### ISSUE THREAD

**Issue by damirkulic** [tokens-studio/figma-plugin#2311]
**Describe the bug**
Nested 2nd level Aliases resolve within token edit mode but not once the token is saved. This was working on 1.37.

**To Reproduce**
1. Create a token that references a nested Alias as a text value within its path.

**Expected behavior**
Token should resolve to the same color value hex as it does in edit state.

**Screenshots or Screencasts**
Token showing that it is broken:
<img width="513" alt="image" src="https://github.com/tokens-studio/figma-plugin/assets/117482649/885dbd2f-e206-4b21-9f35-d10d64d98bdf">

Token when editing:
<img width="514" alt="image" src="https://github.com/tokens-studio/figma-plugin/assets/117482649/c7b2f40d-39a1-496e-99e1-14beeba4a436">

**JSON (optional)**
`{
  "ref": {
    "red": {
      "value": "#f00",
      "type": "color"
    },
    "blue": {
      "value": "#00f",
      "type": "color"
    },
    "green": {
      "value": "#0f0",
      "type": "color"
    },
    "white": {
      "value": "#fff",
      "type": "color"
    },
    "black": {
      "value": "#000",
      "type": "color"
    }
  },
  "sys": {
    "theme1": {
      "text": {
        "value": "{ref.white}",
        "type": "color"
      },
      "icon": {
        "value": "{ref.black}",
        "type": "color"
      },
      "regular": {
        "value": "{ref.red}",
        "type": "color"
      }
    },
    "theme2": {
      "text": {
        "value": "{ref.blue}",
        "type": "color"
      },
      "icon": {
        "value": "{ref.green}",
        "type": "color"
      },
      "regular": {
        "value": "{ref.white}",
        "type": "color"
      }
    }
  },
  "compositon": {
    "button": {
      "text": {
        "value": "{sys.{composition.button}.text}",
        "type": "color"
      },
      "icon": {
        "value": "{sys.{composition.button}.icon}",
        "type": "color"
      },
      "regular": {
        "value": "{sys.{composition.button}.regular}",
        "type": "color"
      }
    }
  },
  "themes": {
    "theme1": {
      "value": "theme1",
      "type": "other"
    },
    "theme2": {
      "value": "theme2",
      "type": "other"
    }
  },
  "composition": {
    "button": {
      "value": "{themes.theme1}",
      "type": "other"
    }
  }
}`

**Comment by straef** [comment]
i wonder if this is related to or in fact the same problem that i am having, where aliased aliases are not being resolved (https://github.com/tokens-studio/figma-plugin/issues/2292).

**Comment by esthercheran** [comment]
@damirkulic this was a beta feature that was not released and we decided not to go ahead with this because it was hampering the plugin performance. Would also love to know how you are handling the token transformation in case of nested aliases?

@straef the issue mentioned in #2292 is not related to this. I have reverted back on the ticket.

**Comment by damirkulic** [comment]
@esthercheran Just to be clear I am not talking about this https://tokens.studio/tools/resolvers . The JSON I have included in my example above was working in version 1.37. And it still works in 1.38 but only while editing the token. Once I save the token it breaks.

**Comment by damirkulic** [comment]
This is what we use to resolve the JSON outside of the plugin for development use https://www.npmjs.com/package/token-transformer

**Comment by esthercheran** [comment]
Hey @damirkulic and @straef would love to have more discussion on nested references in our slack channel if you are part of it: https://tokens-studio.slack.com/archives/C063P9EEH9B
