### ISSUE TITLE
Feature request: Add ability to mark tokens as private (abstract)

### ISSUE THREAD

**Issue by Everettss** [tokens-studio/figma-plugin#2312]
**I'm proposing to add ability to mark tokens as private.**

**What I mean by private?**
Tokens marked in that way **will not be able** to apply styles from them in figma. They will only exist to **create alias tokens based on them**.

**Use case**
Consider creating multi theme design system where you have structure

Theme A

```
"color.palette.neutral.1": "#D9D9D9"
"color.palette.neutral.2": "#BFBFBF"
"color.palette.neutral.3": "#A6A6A6"
"color.palette.neutral.4": "#8C8C8C"
"color.palette.neutral.5": "#404040"

"color.white": "{color.palette.neutral.1}" 
"color.black": "{color.palette.neutral.5}" 
```

Theme B

```
"color.palette.neutral.1": "#F2F2F2"
"color.palette.neutral.2": "#A6A6A6"
"color.palette.neutral.3": "#8C8C8C"
"color.palette.neutral.4": "#595959"
"color.palette.neutral.5": "#0D0D0D"

"color.white": "{color.palette.neutral.1}" 
"color.black": "{color.palette.neutral.4}" 
```

In our Design System we have an restriction **to not use palette** colors directly in figma so we prefix those tokens with `private.*`:

Theme A

```
"private.color.palette.neutral.1": "#D9D9D9"
"private.color.palette.neutral.2": "#BFBFBF"
"private.color.palette.neutral.3": "#A6A6A6"
"private.color.palette.neutral.4": "#8C8C8C"
"private.color.palette.neutral.5": "#404040"

"color.white": "{private.color.palette.neutral.1}" 
"color.black": "{private.color.palette.neutral.5}" 
```

Theme B

```
"private.color.palette.neutral.1": "#F2F2F2"
"private.color.palette.neutral.2": "#A6A6A6"
"private.color.palette.neutral.3": "#8C8C8C"
"private.color.palette.neutral.4": "#595959"
"private.color.palette.neutral.5": "#0D0D0D"

"color.white": "{private.color.palette.neutral.1}" 
"color.black": "{private.color.palette.neutral.4}" 
```

But this is just a convention and it is easy to overcome restriction "do not use private.* tokens in figma". 

**Possible solutions**
**Solution A**
Add in tokens studio figma plugin checkbox to mark token as **private**. Then this token will not be possible to apply styles in figma.
During export those fields can have `private` flag set to `true`, like:

```
{
  "color": {
    "palette": {
      "1": {
        "value": "#D9D9D9",
        "type": "color",
        "private": true
      },
     "2": {
        "value": "#BFBFBF",
        "type": "color",
        "private": true
      },
     "3": {
        "value": "#A6A6A6",
        "type": "color",
        "private": true
      },
     "4": {
        "value": "#8C8C8C",
        "type": "color",
        "private": true
      },
     "5": {
        "value": "#404040",
        "type": "color",
        "private": true
      }
   },
  "white": {
     "value":  "{color.palette.neutral.1}" 
     "type": "color"
  },
  "black": {
     "value":  "{color.palette.neutral.5}" 
     "type": "color"
  }
}
```

And later in `style-dictionary`  values: 

```
"color.white": "{color.palette.neutral.1}" 
"color.black": "{color.palette.neutral.5}" 
```
will be directly converted and we can add next step to remove all private tokens.

**Solution B**
Add in tokens studio figma plugin checkbox to mark token as **private**. Then this token will not be possible to apply styles in figma.
During export those fields with `private` flag will be removed and all tokens based on **private** tokens will be transformed:

```
{
  "white": {
     "value":  "#D9D9D9" 
     "type": "color"
  },
  "black": {
     "value":  "#404040" 
     "type": "color"
  }
}
```

Any work in `style-dictionary` is not required in this approach.

**Solution C**
Add global config in tokens studio figma plugin to enable private field by prefixing them with for example by `_` (this is opt in since this approach can introduce BREAKING CHANGES if some users already had tokens prefixed by `_`).  Tokens prefixed by `_` will not be possible to apply styles in figma.

Next my example will look like: 

```
"_color.palette.neutral.1": "#D9D9D9"
"_color.palette.neutral.2": "#BFBFBF"
"_color.palette.neutral.3": "#A6A6A6"
"_color.palette.neutral.4": "#8C8C8C"
"_color.palette.neutral.5": "#404040"

"color.white": "{_color.palette.neutral.1}" 
"color.black": "{_color.palette.neutral.5}" 
```

Export of those tokens will look like:

```
{
  "_color": {
    "palette": {
      "1": {
        "value": "#D9D9D9",
        "type": "color"
      },
     "2": {
        "value": "#BFBFBF",
        "type": "color"
      },
     "3": {
        "value": "#A6A6A6",
        "type": "color"
      },
     "4": {
        "value": "#8C8C8C",
        "type": "color"
      },
     "5": {
        "value": "#404040",
        "type": "color"
      }
   },
  "white": {
     "value":  "{_color.palette.neutral.1}" 
     "type": "color"
  },
  "black": {
     "value":  "{_color.palette.neutral.5}" 
     "type": "color"
  }
}
```

Later in `style-dictionary` we can remove tokens with `_` prefix. 

**Solution D**
Like solution C but during export fields with `_` prefix will be removed and all tokens based on prefixed tokens by `_` will be transformed (exactly like in solution B):

```
{
  "white": {
     "value":  "#D9D9D9" 
     "type": "color"
  },
  "black": {
     "value":  "#404040" 
     "type": "color"
  }
}
```

**Other possible conventions**
In all solutions we can use word **abstract** instead of **private**.

**Comment by six7** [comment]
We do have support for this in the form of token sets that are `marked as source`. Those sets will only be used for aliasing, but will not be used to create styles or variables.

Does this satisfy that need for you or is the ability to do this specifically on the token itself important to you?

**Comment by SamIam4Hyma** [comment]
@six7 proposing we archive this one.
