### ISSUE TITLE
Support for Percentage Values In The Modifier Dropdown

### ISSUE THREAD

**Issue by keeganedwin** [tokens-studio/figma-plugin#2316]
**Describe the bug**
The `Opacity` type supports % as well as a value, but when referencing an opacity token that has a percentage as value in the color alpha-modifier field, it does not accept this value.

**Expected behavior**
Is this something we could like to accommodate, to allow users to also reference opacity tokens that are using percentages as values?

**Screenshots or Screencasts**
Referencing an opacity token that has **0.6** as value
<img width="483" alt="CleanShot 2023-10-09 at 18 33 31@2x" src="https://github.com/tokens-studio/figma-plugin/assets/93133012/72f7237a-800f-4e04-8d78-0da62f86535b">

Referencing an opacity token that has **10%** as value
<img width="484" alt="CleanShot 2023-10-09 at 18 46 32@2x" src="https://github.com/tokens-studio/figma-plugin/assets/93133012/6501f62d-67c3-46ac-be57-4ff6d644c419">

**Comment by UdayHyma** [comment]
Added to FeatureBase Roadmap : [🎨 Expand functionality of color modifiers](https://tokensstudio.featurebase.app/p/expand-functionality-of-color-modifiers)

**Comment by UdayHyma** [comment]
[Migrated ti Featurebase](https://tokensstudio.featurebase.app/p/expand-token-types)

**Comment by SamIam4Hyma** [comment]
Added to Featurebase Request-	[ Expand accepted reference token types](https://tokensstudio.featurebase.app/p/expand-accepted-reference-token-types)
