### ISSUE TITLE
Remove the option to remove deprecated data

### ISSUE THREAD

**Issue by esthercheran** [tokens-studio/figma-plugin#2317]
**Is your feature request related to a problem? Please describe.**
In release 1.38 we had released a patch that removed the plugin data preview in the right bottom of Figma Design panel. While the data does not populate any more, we have given an option to `Remove Deprecated Data` in the `Settings` tab of the plugin. 
In the release 1.38.1 we have automatically removed any old data that might be populating. 
The option to `Remove Deprecated Data` is no longer needed.

**Definition of done**
Remove the button `Remove Deprecated Data` from the settings tab of the plugin
![CleanShot 2023-10-10 at 12 02 34@2x](https://github.com/tokens-studio/figma-plugin/assets/66366384/a663e04f-52ca-4944-a645-0161822085b5)

**Comment by six7** [comment]
Will be completed in 2.0
