### ISSUE TITLE
Can't remove row gap from UI, when set on multiple elements.

### ISSUE THREAD

**Issue by rbosker** [tokens-studio/figma-plugin#2318]
**Describe the bug**
When you apply a row gap to multiple elements, you can't undo that (see video). If the row gap is applied on one element, this does can be undone.

**Expected behavior**
Remove row gap when selecting an applied row gap in the dropdown.

**Screenshots or Screencasts**
https://github.com/tokens-studio/figma-plugin/assets/109062656/24369e89-cfc9-4ee7-8557-4a09ca3d540b

**Work around**
For now the token can be removed via the inspect panel

**Figma Test File:**
[Bug File](https://www.figma.com/file/pkFAogJyg0PCRrJS51mO9Z/Untitled?type=design&node-id=2-8&mode=design&t=FPhZgEdbUBOsjwEJ-4)

**Slack link**
https://tokens-studio.slack.com/archives/C02HN88QARL/p1697000871061959

**Comment by rbosker** [comment]
tested and works properly now

**Comment by SamIam4Hyma** [comment]
closing as this can not be reproduced
