### ISSUE TITLE
Theme Switching With Styles [multi-dimensional]

### ISSUE THREAD

**Issue by keeganedwin** [tokens-studio/figma-plugin#2327]
**Describe the bug**
After releasing multi-dimensional themes, in the settings tab under the `Prefix styles with active theme name` feature we mention the following: 

> **Note**: Using this with multi-dimensional themes will lead to unexpected results.

So there is currently an issue with creating styles with a multi-dimensional setup and wanting to then theme switch. The way we achieved this before multi-dimensional is by creating let's say:
1. Light mode in one library
2. Dark mode in one library 

- Publishing both of them
- Enabling them in a third library
- Switch modes

Currently this does work in a singular dimension. So if you were to only create and publish the group with `modes` and enabled a `mode` in a third library it works, but it does not work with a multi-dimensional setup. So if you now add a `brand` group to this case it breaks. You can't get both the modes and themes to successfully switch and it's often the latter that causes an error with theme switching as it always overrides all frames to one brand instead of independently like with modes.

**Comment by UdayHyma** [comment]
Added to FeatureBase Roadmap- [❖ ❇️ Non-local support of variables and styles](https://tokensstudio.featurebase.app/p/non-local-support-of-variables)

**Comment by SamIam4Hyma** [comment]
Added to Featurebase Roadmap-	[💚 Theme management enhancements - QOL](https://tokensstudio.featurebase.app/p/theme-management-enhancements-v2)

**Comment by SamIam4Hyma** [comment]
Closing this issue as not planned as its been migrated to featurebase - [💚🪄 Theme management enhancements](https://tokensstudio.featurebase.app/p/theme-management-enhancements-v2)

Please click the link to create a free account and upvote the request so we can notify you when we start working on it. 🚀
