### ISSUE TITLE
Support for Determining a Gradient's Anchor Points

### ISSUE THREAD

**Issue by keeganedwin** [tokens-studio/figma-plugin#2331]
**Is your feature request related to a problem? Please describe.**
We currently don't support the ability to determine the anchor points of gradient tokens (probably also Figma API related). 

One user's used case was that when he imported gradient styles into the plugin, the anchor points when applied through token were inaccurate compared to the way the style counterparts were setup and this caused for inconsistency across brands. 

We will need more information on this as we also weren't able to find much information of this being supported in CSS. That being said, the aforementioned user did share the following links emphasising on the support of anchor-points:

1. https://developer.mozilla.org/en-US/docs/Web/CSS/gradient/linear-gradient
2. https://developer.mozilla.org/en-US/play

**Screen-recording:**
![2023-10-16 14 58 56](https://github.com/tokens-studio/figma-plugin/assets/93133012/a12f4e69-db8d-46e4-b58f-a1ab436798ff)

**Comment by qimmiq** [comment]
we are using this method since quite some time. 
And it always worked, i don't know if Figma changed sth, or it is something else.

**Comment by guedzzz** [comment]
I think you described the issue precisely. The only thing I can add to this is the fact that the anchor points percentages are imported by Tokens Studio, but when applied back to a shape they are ignored. So, my guess is that this is indeed a bug in TS. Thanks for opening this ticket.

**Comment by qimmiq** [comment]
@keeganedwin so this is definitly a bug, because the sync/applying back works when the angle of the gradient is in 45° steps. it only brakes when other angles are used

**Comment by keeganedwin** [comment]
@qimmiq @guedzzz, I came across an old ticket that was fixed a long time ago. It also seems to be related to importing gradient styles into TS which then changes the degree: #156

**Comment by qimmiq** [comment]
@keeganedwin @guedzzz  this ticket describes the way figma -> tokenstudio ... 
what we are pointing out is the the other way. tokenstudio->figma. applying a color token to a figma shape breaks the appearance.

**Comment by qimmiq** [comment]
@keeganedwin i would also rather label it as a bug, because the position points of the gradient
Figma CSS:
background: linear-gradient(153.43deg, #AD00FF **0%**, rgba(82, 255, 0, 0) **83.33%**)
copied to Token applied back to shape, copied Figma CSS
background: linear-gradient(153.43deg, #AD00FF **8.33%**, rgba(82, 255, 0, 0) **77.78%**)

and also creating styles from tokens result in empty fills. 
linear-gradient(136.98deg, #AD00FF -28.11%, rgba(82, 255, 0, 0) 123.5%)
-> empty figma style, no fill

**Comment by LukeFinch** [comment]
This request has been moved to our new feedback tool. Go check out https://tokensstudio.featurebase.app/ to create a free account. You can upvote and comment on existing posts, make a new request, and subscribe to be notified when requests move into our roadmap.

**Comment by UdayHyma** [comment]
Added to Featurebase Roadmap : [🎨 Expand gradient color support](https://tokensstudio.featurebase.app/p/add-gradient-token-type-and-expand-functionality-past-linear)

**Comment by SamIam4Hyma** [comment]
Closing this issue as not planned as its been migrated to featurebase - [🎨 Expand gradient color support](https://tokensstudio.featurebase.app/p/add-gradient-token-type-and-expand-functionality-past-linear)

Please click the link to create a free account and upvote the request so we can notify you when we start working on it. 🚀
