### ISSUE TITLE
EOF line endings

### ISSUE THREAD

**Issue by SorsOps** [tokens-studio/figma-plugin#2332]
Currently we don't allow a user to specify the line endings option for the git sync providers which causes issues with unnecessary changes. We should add a checkbox within the sync provider settings to choose the line ending types for EOF , EOL .

Then during the sync when we stringify the sets for comparison we add the EOF character conditionally if it doesn't exist.

This should be done within the abstract git sync provider so that all other sync providers get this functionality for free

![Image](https://github.com/tokens-studio/figma-plugin/assets/80043879/fa25127a-9b15-4f27-8f9e-02f5ccb032a1)

**Comment by UdayHyma** [comment]
[migrated to Featurebase](https://tokensstudio.featurebase.app/p/git-sync-enhancements)
