### ISSUE TITLE
Allow composition token to have multiple fill properties

### ISSUE THREAD

**Issue by esthercheran** [tokens-studio/figma-plugin#2335]
**Is your feature request related to a problem? Please describe.**
Figma allows multiple fills to be applied on a layer. Currently the plugin does not support this. 

**Describe the solution you'd like**
Allow composition token to have multiple fill properties defined. 

---
<details><summary>Original Issue</summary>
From @chrisyalamov
Big +1 for this feature. Looking at the Group Tokens section of the draft spec for design tokens (https://design-tokens.github.io/community-group/format/#groups-versus-composite-tokens), it seems to describe something similar to the composition tokens feature in Tokens Studio:

[Groups](https://design-tokens.github.io/community-group/format/#groups) are for arbitrarily grouping tokens for the purposes of naming and/or organization.

Perhaps the plugin could allow for a composition token to contain several color/gradient tokens which apply the 'fill' property?
</details>

**Comment by six7** [comment]
Shouldnt this be part of a Composition Tokens M2? Feels like that would be a good fit

**Comment by LukeFinch** [comment]
This request has been moved to our new feedback tool. Go check out https://tokensstudio.featurebase.app/ to create a free account. You can upvote and comment on existing posts, make a new request, and subscribe to be notified when requests move into our roadmap.

**Comment by UdayHyma** [comment]
Added to Featurebase Roadmap : [🪙 ➕ Support multiple tokens per layer of the same type
](https://tokensstudio.featurebase.app/p/multiple-token-per-layer)
