### ISSUE TITLE
Variable Link Loss When Removing Token from The Inspect Tab

### ISSUE THREAD

**Issue by keeganedwin** [tokens-studio/figma-plugin#2337]
**Describe the bug**
User is facing an issue with the link between tokens and variables when applied on the same layer. Prior to our recent release, if a token and variable were applied on the same layer and the token was removed, the variable link would still be retained and displayed in the inspect tab with the variable icon. However, the current behavior is different, causing inconvenience for the user as they want to retain the variable link. 

**Used-case:**
1. User creates variables to accommodate their consumer base without plugin access, allowing them to switch brands and modes.
2. Tokens and variables are created separately by the user to achieve the desired functionality. However, they are manually kept in sync with the same set of items, sometimes with mismatched naming conventions.
3. User applies a token to an element and then applies a variable on the same layer.
4. When attempting to remove the applied token from the inspect tab, the token and the variable (not linked) are both being removed. 

**To Reproduce**
1. Create a token and apply it to an element.
2. Add a variable on the same layer.
3. Attempt to remove the token from the inspect tab.
4. Observe that not only the token but also the applied variable is removed.

**Expected behavior**
When removing a token from an element, the variable applied should remain intact on the same layer, as it did prior to the recent release. The variable should retain the link and be displayed with the variable icon in the inspect tab.

**Figma File:**
[Test file](https://www.figma.com/file/xeGS7DhURtkEOEbu0OkKIk/Github-Issue-%232337?type=design&node-id=2-4259&mode=design&t=jb1cect3Et3x8HTZ-4)

**Screenshots or Screencasts**
https://github.com/tokens-studio/figma-plugin/assets/93133012/962bf040-23fc-459f-81f9-42de05fdee03

**Comment by LukeFinch** [comment]
This request has been moved to our new feedback tool. Go check out https://tokensstudio.featurebase.app/ to create a free account. You can upvote and comment on existing posts, make a new request, and subscribe to be notified when requests move into our roadmap.

**Comment by UdayHyma** [comment]
Added to Featurebase Roadmap : [💡Removing a token removes the design property in figma](https://tokensstudio.featurebase.app/p/removing-a-token-removes-the-design-property-in-figma)
