### ISSUE TITLE
Gitlab issue connecting to repo

### ISSUE THREAD

**Issue by rbosker** [tokens-studio/figma-plugin#2339]
**Describe the bug**
When trying to connect to a repo, there is some strange behaviour which is causing some issues to push/pull.

**To Reproduce**

- Multi-file sync to the root folder: this seems to work fine for pushing and pulling.
- Multi-file sync to a folder: when the folder already exists, it seems that a connection is established, but nothing happens. You're not able to push or pull.
- Multifile sync, where the folder needs to be created by the plugin: immediatly throws a 404 error.
- single file sync: initial push works, but pull gives a 404 error.

**Expected behavior**
Be able to push and pull without issues.

**Screenshots or Screencasts**
![image](https://github.com/tokens-studio/figma-plugin/assets/109062656/2108d5bd-ae1e-4b9d-88f3-f39481e577f2)
![image](https://github.com/tokens-studio/figma-plugin/assets/109062656/24212284-aee7-4567-9a2e-c525b74f4b82)

Internal slack issue link including screenrec: https://hyma-team.slack.com/archives/C03BSF3TADU/p1698407134836899

**Comment by Meshock** [comment]
I think I have the same situation. I created a new connection to an existing repository on Gitlab. But instead of the pull operation, the plugin offers push to repo. Old connections don't work.

**Comment by thecodingfrog** [comment]
same here

**Comment by mtopping-agn** [comment]
+1 the endpoint for the pull returns "404 revision doesn't exist Not Found". 

Maybe something changed with the Gitlab API? The request seems well-formed and also doesn't work from postman but other API requests do.

**Comment by AKadochnikov** [comment]
+1 same here

**Comment by RYamashita3** [comment]
Same here. This is a critical outage that prevents us from using our design system.

**Comment by six7** [comment]
Sorry for the delay on this everyone, we're working on it.

**Comment by byjokese** [comment]
Awesome, thanks @six7, is getting to a problem for our designers, if you need any extra info, just ask.

![image](https://github.com/tokens-studio/figma-plugin/assets/5951126/d7ecb4ae-434d-4f35-a939-07a62afcf696)

**Comment by rbosker** [comment]
@RYamashita3 we're working on a solution and hope to have a new release with a fix, later on this week.

**Comment by six7** [comment]
Fix is out now, sorry about the delay everyone.

**Comment by SorsOps** [comment]
Hey @John-EonNext , could you provide your console logs or network logs to help debug?

**Comment by John-EonNext** [comment]
[console entry.docx](https://github.com/tokens-studio/figma-plugin/files/13376440/console.entry.docx)

Not sure if this is what you need.

**Comment by SorsOps** [comment]
Hey @John-EonNext , I need the console logs or network logs from inside figma. You should be able to open it by right clicking on the canvas inside figma. The main thing we are looking at is the reason for the failure which could be because of the use of a file or directory you're saving to, they have slightly different mechanisms

**Comment by John-EonNext** [comment]
[www.figma.com-1700132105405.log](https://github.com/tokens-studio/figma-plugin/files/13376677/www.figma.com-1700132105405.log)

Ah I see, thanks... okay try this.

**Comment by SorsOps** [comment]
@John-EonNext Your path is set to `ui/token-studio` on the `design-tokens_john` branch could you confirm that that path  and branch exists and has json files within it ?

**Comment by John-EonNext** [comment]
I can confirm that everything is correct, and the files are there... I have been working with the exact same credentials for a while now.
