### ISSUE TITLE
Set / get pluginData on variables for two-way sync

### ISSUE THREAD

**Issue by six7** [tokens-studio/figma-plugin#2343]
[Version 80](https://www.figma.com/plugin-docs/updates/2023/10/27/version-1-update-80/) of Figma's plugin API introduced support to set and get pluginData on variables / collections.

This means we can now set a variables "true token value" when we create/edit them via the plugin. This technically enables us to have a way so users can either update their variables using the plugin or via Figma itself, and we should be able to understand what's changed. Users could update a variable in Figma, change the source or the value, and we could then update the value for the user.

This needs some design thinking on:
- What happens when a variable was edited in Figma without the plugin? How will users know that a change has occurred?
- How will users be able to write those changes back to their tokens, should this be an automated action or a way for the user to confirm these changes?

**Comment by UdayHyma** [comment]
[Migrated to Featurebase](https://tokensstudio.featurebase.app/p/sync-external-storage-enhancements)
