### ISSUE TITLE
Prohibit Push if references are broken

### ISSUE THREAD

**Issue by netleader** [tokens-studio/figma-plugin#2344]
**Describe the solution you'd like**
To make it easier to identify problems it would be nice to prohibit the push to a remote repo. This would also avoid unnecessary builds.
This could be a toggle in the settings if unwanted.

**Comment by six7** [comment]
One problem there is that references can always be broken if a set is marked as inactive. We won't know where a reference comes from unless token sets are checked. Requiring users to have token sets active before pushing feels like a limitation 🤔

**Comment by LukeFinch** [comment]
This request has been moved to our new feedback tool. Go check out https://tokensstudio.featurebase.app/ to create a free account. You can upvote and comment on existing posts, make a new request, and subscribe to be notified when requests move into our roadmap.

**Comment by UdayHyma** [comment]
Added to Featurebase Roadmap : [↕️ Git sync enhancements - push, pull, merge, branching
](https://tokensstudio.featurebase.app/p/git-sync-enhancements)
