### ISSUE TITLE
add support for fill mode in Asset tokens

### ISSUE THREAD

**Issue by Yardco** [tokens-studio/figma-plugin#2347]
Currently when using asset tokens, the fill mode of the image is always fill, even if it was something else before. 

**Definition of done**
Respect the fill mode that is currently on the layer when applying an asset token:
- Fill
- Fit
- Tile

-------------
Original Issue
**Is your feature request related to a problem? Please describe.**
Currently when using asset tokens, the fill mode of the image is always fill, even if it was something else before. 

**Describe the solution you'd like**
Adding the option to add a fill mode to the asset token, or supporting a param (eq &fillmode=fit) would solve the issue images always defaulting to be filled when something else is desired.

**Comment by six7** [comment]
I think what we should do is respect the value on the node and keep it like that, not reset it to `Fill`. I wouldnt make that a setting on the token itself I think, at least for now

**Comment by Yardco** [comment]
Respecting the value already set would definitely already be an improvement. I can imagine though that having the token apply a fill mode (and thus overriding the current) would be desirable as well at some point. This would mimic more closely the way images coming from DAM’s can be controlled.

But if it we’re possible to at least respect the current value, it would make asset tokens for us useful enough to adopt.

**Comment by LukeFinch** [comment]
This request has been moved to our new feedback tool. Go check out https://tokensstudio.featurebase.app/ to create a free account. You can upvote and comment on existing posts, make a new request, and subscribe to be notified when requests move into our roadmap.

**Comment by UdayHyma** [comment]
Added to Featurebase Roadmap : [🪙 📸 Asset token enhancements
](https://tokensstudio.featurebase.app/p/asset-token-enhancements)
