### ISSUE TITLE
Unable To Un-apply Tokens On Multiple Layers At Once

### ISSUE THREAD

**Issue by keeganedwin** [tokens-studio/figma-plugin#2353]
**Describe the bug**
This feature worked in 1.37.9. Currently when multiple layers are selected and you apply a token, the plugin either applies it to a few layers or none at all. In addition to this, if you select multiple layers that already have the same token applied and try to bulk unapply tokens, it doesn't work. 

**Edit:**
This error seems to be inconsistent. It looks like when you first try to bulk apply tokens on layers it does not work, and the it does a couple of minutes later. 

**To Reproduce**
1. Select multiple layers
2. Apply a token

[Link to File for Testing](https://www.figma.com/file/1lxt6A2PsBvTJcqP5LjRPa/Github-Issue-%232353?type=design&node-id=2-63&mode=design&t=Sy4o3QujggVAdUAF-4)

**Expected behavior**
This should work as it did in 1.37.9, where one can bulk apply one token on multiple layers.

**Screenshots or Screencasts**
_Trying to bulk unapply tokens_
https://github.com/tokens-studio/figma-plugin/assets/93133012/867b42ac-b687-4167-a8ed-2922065c5baf

_Trying to bulk apply tokens_
https://github.com/tokens-studio/figma-plugin/assets/93133012/ae737508-bda4-44b1-a7ad-26576fcc4e04

**Comment by six7** [comment]
Is there anything consistent that causes this? I'm able to bulk-apply just fine. Can you try and see if there's a pattern to when it's not working?

Was able to reproduce the unapply one though!

**Comment by esthercheran** [comment]
On the first instance I am able to bulk apply and then I am unable to bulk unapply (only on one layer the token gets unapplied). Trying to apply the token again on the selected items does not work anymore after that.

**Comment by keeganedwin** [comment]
@esthercheran that's more or less the issue I've faced. It happens once then when I try to carry out the same steps again it does not work.

**Comment by keeganedwin** [comment]
@six7 I've created a test file and left it in the ticket
