### ISSUE TITLE
Add correct error message when trying to add folder to an empty GitLab repository from the Plugin

### ISSUE THREAD

**Issue by esthercheran** [tokens-studio/figma-plugin#2357]
**Describe the bug**
When connecting to an empty Gitlab repository and putting a folder name in the File Path input, we get a modal for pushing to the repository. On confirming, we get an error message "Error syncing with Gitlab, check credentials". This is misleading.

**To Reproduce**
1. Create a repository on GitLab without any folders or files
2. Connect to the repository from the plugin. Add a folder name in the file path input field
3. Modal to push to GitLab pops up
4. On confirming, error message "Error syncing with Gitlab, check credentials" is shown

**Expected behavior**
An error message showing the correct reason should be shown.

**Definition of done"
The below error message should be displayed: 
"Folder doesn't exist. Please create a folder in your repository. More information, please go to https://docs.tokens.studio/sync/gitlab"

**Screenshots or Screencasts**

https://github.com/tokens-studio/figma-plugin/assets/66366384/cd0e6836-1571-4677-a43c-fbc350c02da5

**Comment by esthercheran** [comment]
Add all the relevant error messages

**Comment by rbosker** [comment]
this issue is not reproducable anymore.
