### ISSUE TITLE
On-premise GitLab sync behind proxy

### ISSUE THREAD

**Issue by MiguelFranken** [tokens-studio/figma-plugin#2360]
**Is your feature request related to a problem?**
We are currently facing the problem that we are unable to sync our tokens stored on an On Premise GitLab instance that is accessible only via a proxy. Currently, the Figma Tokens Studio Plugin does not provide an option to specify a proxy in the provider sync settings in addition to the base GitLab URL.

**Describe the solution you'd like**
We would like to see an update in the Figma Tokens Studio Plugin where we have an option to specify a proxy in the provider sync settings. This will allow us to seamlessly sync our tokens stored on the On Premise GitLab instance via the specified proxy.

**Describe alternatives you've considered**
As an alternative, we tried manually syncing the tokens, but it is time-consuming and not efficient. A local proxy client agent is not feasible to use for our UI department.

**Comment by six7** [comment]
I assume the `baseUrl` you can set does not satisfy those needs, right? You'd rather have a dedicated input field that would replace any calls to `gitlab.com` with something else?

**Comment by MiguelFranken** [comment]
Yes.
To access certain internal tools like GitLab, we must set up a proxy, for instance, in Firefox. The connections will then be routed through the proxy, which we specify by its IP and port in the browser settings.

**Comment by LukeFinch** [comment]
This request has been moved to our new feedback tool. Go check out https://tokensstudio.featurebase.app/ to create a free account. You can upvote and comment on existing posts, make a new request, and subscribe to be notified when requests move into our roadmap.

**Comment by UdayHyma** [comment]
Added to Featurebase Roadmap : [🧑‍💻 Sync to external token storage enhancements](https://tokensstudio.featurebase.app/p/sync-external-storage-enhancements)
