### ISSUE TITLE
Ability To Display Opacity and Number Types As Suggestions

### ISSUE THREAD

**Issue by keeganedwin** [tokens-studio/figma-plugin#2363]
**Describe the bug**
Users would also like to use the `Number` and `Opacity` types to set up their modifier ramp to be referenced in the Color type. You can currently reference them in the color-modifier dropdown but only if manually typed out.

This is also related to issue: #2316 

**To Reproduce**
1. Create a number token with 0.5 as the value
2. Create an opacity token with 0.5 as the value
3. Try and reference either one of the tokens in  the color-modifier dropdown (modifier operations).

**Expected behavior**
Just as you can reference the `Other` type in the dropdown, also display tokens from the `Number` and `Opacity` types.

**Screenshots or Screencasts**
![CleanShot 2023-11-10 at 15 21 57@2x](https://github.com/tokens-studio/figma-plugin/assets/93133012/2db024ec-e41a-4b0a-b494-89d7b3ecfcaf)

**Figma file (optional)**
[Link to Test file](https://www.figma.com/file/N9CxdSQhqwsSRsBNNVcd7e/Untitled?type=design&node-id=2-9&mode=design&t=ik2X6GyOUzWFiJHs-4)

**Comment by UdayHyma** [comment]
[Migrated to Featurebase](https://tokensstudio.featurebase.app/p/expand-token-types)

**Comment by SamIam4Hyma** [comment]
Added to Featurebase Request-	[ Expand accepted reference token types](https://tokensstudio.featurebase.app/p/expand-accepted-reference-token-types)
