### ISSUE TITLE
Why is my button unusable?

### ISSUE THREAD

**Issue by Linhaolong** [tokens-studio/figma-plugin#2365]
![image](https://github.com/tokens-studio/figma-plugin/assets/105919496/3e913c0c-bb95-42ba-b38d-33daf0ce3b70)

**Comment by keeganedwin** [comment]
Hey @Linhaolong, you need to have themes defined in order to create variables. You can find more information on creating variables on our docs page: https://docs.tokens.studio/variables/creating-variables
