### ISSUE TITLE
Create the ability to select all sets in a theme at once

### ISSUE THREAD

**Issue by UdayHyma** [tokens-studio/figma-plugin#2369]
**Is your feature request related to a problem? Please describe.**
When a user has a lot of theme groups the ability to check/uncheck all sets in a particular group would be useful to save time for users that have to turn only one set on/off.

**Describe the solution you'd like**
Create the ability to select all sets in a theme at once. We also need to keep in mind that the toggle has options for: enabled, disabled and source. Preferably you can toggle all sets within a theme between the enabled, disabled and source.We need to determine how this will work.

**Additional context**
<img width="428" alt="Screenshot 2023-11-09 at 8 34 31 PM" src="https://github.com/tokens-studio/figma-plugin/assets/138768433/2ce5c919-1f53-4ec4-a06a-a31f7189006e">
![Screenshot 2023-11-09 at 2 19 26 PM](https://github.com/tokens-studio/figma-plugin/assets/138768433/d30d2de8-d656-4c88-9156-74022e590868)

**Comment by LukeFinch** [comment]
This request has been moved to our new feedback tool. Go check out https://tokensstudio.featurebase.app/ to create a free account. You can upvote and comment on existing posts, make a new request, and subscribe to be notified when requests move into our roadmap.

**Comment by UdayHyma** [comment]
Added to Featurebase Roadmap : [🌜Theme management (pro) enhancements
](https://tokensstudio.featurebase.app/p/theme-management-enhancements)
