### ISSUE TITLE
Visual distinction between empty and populated groups while collapsed.

### ISSUE THREAD

**Issue by UdayHyma** [tokens-studio/figma-plugin#2382]
**Is your feature request related to a problem? Please describe.**
It is difficult for the user to distinguish between empty groups and populated groups when they are collapsed because all groups look the same when collapsed and there is no way of telling which groups are empty and which groups have tokens so there is no usability coming out of the colour distinction.

**Describe the solution you'd like**
Use black label and caret icon to indicate populated groups .
Use grey label and no caret icon to indicate empty groups 

**Describe alternatives you've considered**
The caret next to the token type can also be removed on all empty groups because there is nothing to be further expanded.

**Additional context**
<img width="263" alt="image" src="https://github.com/tokens-studio/figma-plugin/assets/138768433/9a850189-3224-464b-a46b-283fc958cb04">
<img width="262" alt="image" src="https://github.com/tokens-studio/figma-plugin/assets/138768433/9343f11c-336c-4d60-890b-7f235e2bdb7b">
<img width="263" alt="Screenshot 2023-11-21 at 2 51 55 PM" src="https://github.com/tokens-studio/figma-plugin/assets/138768433/a97bd09f-47df-4640-80b2-2e318ce57b12">

**Comment by UdayHyma** [comment]
[Migrated to Featurebase](https://tokensstudio.featurebase.app/p/greenheart-v2-quality-of-life-enhancements)

**Comment by SamIam4Hyma** [comment]
Added to Featurebase Request-	[🪙 Token organization enhancements](https://tokensstudio.featurebase.app/p/token-organization-enhancements)
