### ISSUE TITLE
Display Error Message When Users Input Forbidden Characters

### ISSUE THREAD

**Issue by keeganedwin** [tokens-studio/figma-plugin#2385]
**Is your feature request related to a problem? Please describe.**
The plugin should display an error message for when users use characters or names in their tokens that do not allow to be used due to consequences. For instance, a user recently used **Value** as a part of their token name `progress-bar.value.typography` (the json uses this to define the value of a token) and this resulted in the plugin creating this token in the `Other` type after pushing and pulling from their repo. 

This can refer to the following ticket which describes not to use certain characters: #1747 

**Describe the solution you'd like**
Besides error messages, we could also consider disabling the save button preventing the user from saving such nomenclature.

**Comment by UdayHyma** [comment]
[Migrated to Featurebase](https://tokensstudio.featurebase.app/p/greenheart-v2-quality-of-life-enhancements)
