### ISSUE TITLE
Ability To Edit Tokens To Add Nested Levels

### ISSUE THREAD

**Issue by keeganedwin** [tokens-studio/figma-plugin#2386]
**Describe the bug**
Currently when you create a token like: `button.primary.container` and then want to edit it to add an additional level `button.primary.container.default`. The plugin throws the following error message "**Tokens can't share name with a group**".

**To Reproduce**
1. Create a token named `button.primary.container`
2. After creating, edit the token
3. Add a '**.**' to change it to `button.primary.container.default`

**Expected behavior**
Users should just be able to add additional levels if required. The current work around is to create the token from scratch.

**Screenshots or Screencasts**
<img width="666" alt="CleanShot 2023-11-22 at 16 46 25@2x" src="https://github.com/tokens-studio/figma-plugin/assets/93133012/97d867b0-7857-487d-b580-f67af5d08de4">

<img width="667" alt="CleanShot 2023-11-22 at 16 46 51@2x" src="https://github.com/tokens-studio/figma-plugin/assets/93133012/bce0a626-4115-4c78-b8f4-6f777a361f90">

**Comment by NuthanHyma** [comment]
**Figma File**

**Comment by NuthanHyma** [comment]
**Figma File**
[Test File](https://www.figma.com/file/uKsBeAjASewY7hNt6L9w5l/Issue-%232386?type=design&node-id=0%3A1&mode=design&t=ncDDUzL54f8y83go-1)

**Comment by SamIam4Hyma** [comment]
Added to featurebase roadmap item [💚 Naming conflict error enhancements - QOL](https://tokensstudio.featurebase.app/p/naming-conflict-error-enhancements)
