### ISSUE TITLE
Support For A Search/Filter Function For The Theme Dropdown

### ISSUE THREAD

**Issue by NuthanHyma** [tokens-studio/figma-plugin#2388]
**Is your feature request related to a problem? Please describe.**
A search/filter function for the theme dropdown to manage multiple brands & themes.

**Describe the solution you'd like**
We need to determine how this could work.

**Used Case:**
The user’s team supports over 50 brands and has different token sets for mobile and desktop (and soon to add native apps). Looking for the appropriate theme is a challenge for them.

**Additional context**
<img width="489" alt="Screenshot 2023-11-23 at 1 31 51 PM" src="https://github.com/tokens-studio/figma-plugin/assets/140593995/29ec4a03-c471-4ffe-9994-a4d8510daec0">

**Comment by LukeFinch** [comment]
This request has been moved to our new feedback tool. Go check out https://tokensstudio.featurebase.app/ to create a free account. You can upvote and comment on existing posts, make a new request, and subscribe to be notified when requests move into our roadmap.

**Comment by UdayHyma** [comment]
Added to Featurebase Roadmap : [🌜Theme management (pro) enhancements](https://tokensstudio.featurebase.app/p/theme-management-enhancements)
