### ISSUE TITLE
Font Size Type Should Not Support String Text

### ISSUE THREAD

**Issue by keeganedwin** [tokens-studio/figma-plugin#2389]
**Describe the bug**
The plugin currently allows you to use string text as a value for in the `Font Size` token. The plugin should not allows users to input such a value. 

**Used-case:**
Users can also reference this in the `Font Size` field of the typography token which they can save. Applying this does not give them the expected behaviour because the token does not have any numeric value defined nor does using any string text as a value work. 
 
**To Reproduce**
1. Create a `Font Size` token
2. Use string text as a value
3. Save and apply the token on text

**Expected behavior**
The plugin could display an error when users are inputting anything other than numbers as a value. Even for reference suggestions, it only displays tokens that have numbers as values. 

**Screenshots or Screencasts**
https://github.com/tokens-studio/figma-plugin/assets/93133012/54a3a7c1-f735-4274-954a-1eecf3d0fe29

**Comment by six7** [comment]
What do you mean with string text? Can you give a concrete example value?

**Comment by abdelhakimrafik** [comment]
@keeganedwin @six7 If I'm correct, the `Font Size` token should accept only a numeric value or an alias.
#### Current Behavior:
You can set the `Font Size` to any text (e.g., `smallText`), even if `smallText` is not an alias.

**Comment by NuthanHyma** [comment]
**Figma File**
[Test File](https://www.figma.com/file/UiYoHmFjIcnSVZjJ59rVtB/Issue-%232389?type=design&node-id=0%3A1&mode=design&t=jsNH62rUAbD5CHZX-1)

**Comment by keeganedwin** [comment]
This bug is no longer producible on **Prod 1.38.9** or **Beta V2-rc5**
