### ISSUE TITLE
Support For TS Plugin in Figma Dev Mode's Codegen Plugins

### ISSUE THREAD

**Issue by keeganedwin** [tokens-studio/figma-plugin#2391]
**Is your feature request related to a problem? Please describe.**
There are some users who would like to use the plugin in the `Codegen` section of Figma's Dev-mode, but this is currently not possible as you can't get custom plugins in VSCode yet

**Describe the solution you'd like**
Currently blocked but may also need more information on this. 

**Additional context**
<img width="393" alt="CleanShot 2023-11-27 at 18 44 34@2x" src="https://github.com/tokens-studio/figma-plugin/assets/93133012/a6feb467-aa3b-4848-8edd-06b5f258acc9">

**Comment by SamIam4Hyma** [comment]
proposing to archive as this is blocked by Figma
