### ISSUE TITLE
Border-Width Token With Value 0px Shows As 0.001px in Figma DEV Mode

### ISSUE THREAD

**Issue by NuthanHyma** [tokens-studio/figma-plugin#2393]
**Describe the bug**
when a border-width token is applied with a value of 0px it shows up as 0.001px in DEV mode. This accounts for border-width as a separate token and when using border-width in a Border token.
The applied border-width in the token is 0px (which is correct > see screenshot).

**Expected behaviour**
Show 0px border width in DEV mode, when 0px border width is applied.

**Screenshots or Screencasts**
<img width="313" alt="Screenshot 2023-11-29 at 4 36 44 PM" src="https://github.com/tokens-studio/figma-plugin/assets/140593995/a5ddcf38-7fa3-4e5c-b3c9-dd6fe55d7ed4">
<img width="240" alt="Screenshot 2023-11-29 at 4 36 10 PM" src="https://github.com/tokens-studio/figma-plugin/assets/140593995/8974f555-dd49-4068-86be-7de8fe6d6d7a">

**Comment by six7** [comment]
Will be released in 2.0

**Comment by SamIam4Hyma** [comment]
Added to Featurebase Roadmap-	[🐛 V2 Bug Fixes](https://tokensstudio.featurebase.app/p/v2-bug-fixes)

**Comment by SamIam4Hyma** [comment]
Added to Featurebase Roadmap-	[🐛 V2 Bug Fixes](https://tokensstudio.featurebase.app/p/v2-bug-fixes)

**Comment by matgalla** [comment]
Still experiencing this issue for sizing variables in v2.10.5
