### ISSUE TITLE
Color references are lost after "sync/create variables"

### ISSUE THREAD

**Issue by jolantis** [tokens-studio/figma-plugin#2399]
**Describe the bug**

Semantic (alias) color references are lost both in plugin and variables.

(see recording below)

**To Reproduce**

1. Update plugin to latest version 1.38.5
2. Trigger the "sync variables" or "create variables" actions from the plugin
3. Color variables are plain hex values instead of referencing global/core colors
4. And the worst is that now also all semantic/alias color tokens in the plugin have lost their reference to the global colors and are suddenly plain hex values too!

**Expected behavior**

Color references are not lost/gone, but respected as was the case before v1.38.5.

**Screenshots or Screencasts**

![Tokens-Studio-Color-Reference-Bug-231201](https://github.com/tokens-studio/figma-plugin/assets/68627/d7aed442-1a5f-4896-9f64-5384ee57fc19)

**Figma reference file**
https://www.figma.com/file/U80LRxwNLD6Kn82PcrmxMi/Github-Issue-2399?type=design&node-id=0%3A1&mode=design&t=rnbjYlOZKdfRPAHN-1

**Comment by jolantis** [comment]
Hey @henrilouis, good to know I'm not the only one! I hope this issue will be fixed as soon as possible. It is unacceptable to lose (color) references, as they are the core of what tokens are about.

**Comment by esthercheran** [comment]
Hey everyone, sorry for the issue. We are looking into it right away

**Comment by esthercheran** [comment]
@jolantis @henrilouis we are in the process of fixing the bug, in the meanwhile we have done a version rollback on the plugin. Big apologies from the team.

**Comment by henrilouis** [comment]
Thanks for the quick effort @esthercheran and team!

**Comment by jolantis** [comment]
@SorsOps thanks for the quick response on Friday, but it's not fully fixed for me!

When I trigger "create variables", the plugin doesn't create all variabel types anymore:`"type": "spacing"` and `"type": "borderRadius"` are not showing up as variables!

I've also tested it in an empty/new file, but the same issue. :(

**Comment by keeganedwin** [comment]
Hey @jolantis, the fix hasn't been merged and released yet which is probably why you're still facing some issues.
