### ISSUE TITLE
Cache-buster Querystring For Image Asset Caching and New Requests

### ISSUE THREAD

**Issue by keeganedwin** [tokens-studio/figma-plugin#2401]
**Is your feature request related to a problem? Please describe.**
Plugin does not refresh images after server update in multi-themes setup.

**Used-case:**
> Is there a way for the plugin to "re-pull" images? We're currently using assets tokens with a multi-themes setup. Updating/replacing the images on our server (without updating the url) doesn't seem to work and the plugin (caches?) keeps fetching the old image. Is there a way to force the plugin to re-pull the image?

**Solution from** @SorsOps:
We will have to check to see how the image asset gets attached. I'm assuming with how images are normally handled in a browser they are requested once from the browser then cached, we could potentially add a cachebuster by appending a querystring to the image url so that the browser makes a new request each time?

We likely will want to have some option you can turn on or off to automatically have it change the query perhaps

**Comment by esthercheran** [comment]
Let's make it automatic and not dependent on a checkbox

**Comment by UdayHyma** [comment]
Added to Featurebase Roadmap : [🪙 📸 Asset token enhancements
](https://tokensstudio.featurebase.app/p/asset-token-enhancements)

**Comment by UdayHyma** [comment]
[MIgrated to Featurebase](https://tokensstudio.featurebase.app/p/naming-conflict-error-enhancements)
