### ISSUE TITLE
Allow users to select whether to create Styles or Variables or both while exporting to Figma

### ISSUE THREAD

**Issue by esthercheran** [tokens-studio/figma-plugin#2411]
In #2406 we introduced a new option `Export to Figma` under the `Styles & Variables` 

![Image](https://github.com/tokens-studio/figma-plugin/assets/66366384/5fd5dae3-8f48-4ccc-aac2-e6ed604cc397)

We want to allow users to choose whether they want to create variables or styles or both from the `Options` button

![Image](https://github.com/tokens-studio/figma-plugin/assets/66366384/81a13502-2419-45b9-ab54-073c38e26cfa)

- On a new Figma file the `Options` screen should open up first. 
- On subsequent launch, clicking on the `Options` button will open up the below screen

![Image](https://github.com/tokens-studio/figma-plugin/assets/66366384/e82ca0b8-0374-416a-b720-37cbfcb68408)

- The options under `What variables should be created and updated?`
  - Select all : Creates color, number/dimension, text/string, booelan tokens as variables 
  - Color : only creates color tokens as variables
  - Number/Dimension: only creates dimension, number, spacing, sizing, border radius, border width as dimension variables
  - Text/String: only creates text tokens as text/string variables
  - Boolean : only creates boolean tokens as boolean variables
- The options under `What styles should be created and updated?`
  - Select all : Creates color, typography and  shadow tokens as color, typography and effects styles
  - Color: creates only color tokens as styles
  - Typography: creates only typography tokens as styles
  - Effects : creates only shadow tokens as styles

- On clicking confirm the screen below will be shown and the settings will be remembered for the FIgma file

![Image](https://github.com/tokens-studio/figma-plugin/assets/66366384/9b8d4f88-4a14-40f1-a47d-67c386c2054b)

- On clicking `Export to Figma`, variables or styles or both will be created depending on the selected checkboxes in the `Options` screen

**Comment by SamIam4Hyma** [comment]
@esthercheran @LukeFinch you'll want to look into #2475 to see if its still a bug that might influence the QA on this ticket.

**Comment by six7** [comment]
Will be fixed in 2.0

**Comment by SamIam4Hyma** [comment]
Added to Featurebase Roadmap-	[❖ ❇️ New styles and variables options menu](https://tokensstudio.featurebase.app/p/new-styles-and-variables-options-menu)
