### ISSUE TITLE
Add support for stroke weight and opacity variables

### ISSUE THREAD

**Issue by keeganedwin** [tokens-studio/figma-plugin#2414]
Figma recently released new properties to which we can apply variables:
- Stroke weight
- Opacity

We should make sure that when users apply a token that has a connected variable, we apply that variable for users.

**Comment by six7** [comment]
Will be part of 2.0

**Comment by chriskerr-performio** [comment]
@six7 @keeganedwin will 2.0 also cover layout grid and effects elements per the Dec 6 2023 Figma release??

**Comment by six7** [comment]
> @six7 @keeganedwin will 2.0 also cover layout grid and effects elements per the Dec 6 2023 Figma release??

We aim to support effects and effect styles as well, that one is tracked here: https://github.com/tokens-studio/figma-plugin/issues/2443

Layout grids will likely not make it, given we dont support those yet at all (and imo there are more important new token types to tackle)

**Comment by SamIam4Hyma** [comment]
Added to Featurebase Roadmap-	[❖ 🚧 ❇️ Variables in stroke weight and opacity](https://tokensstudio.featurebase.app/p/variables-in-stroke-weight-and-opacity)
