### ISSUE TITLE
Ad an ability to expand/collapse all sibling token nodes within a branch.

### ISSUE THREAD

**Issue by sweetdrumster** [tokens-studio/figma-plugin#2415]
**Is your feature request related to a problem? Please describe.**
I have a large hierarchy tokens tree structure within a token group and need to either scroll it all the way until I find the required node or manually collapse each node until I reach the required one. This is tiresome.

**Describe the solution you'd like**
Cmd + click on the expanded node collapses it and all the siblings. Cmd + click on the collapsed node expands it and all the siblings. 

**Describe alternatives you've considered**
Manually clicking node by node to collapse them

**Additional context**
With an extensive tokens tree it takes a lot of time to reach the required node without an ability to collaplse all siblings at once:
<img width="538" alt="image" src="https://github.com/tokens-studio/figma-plugin/assets/1147460/6161c3d3-ee81-4e77-88d8-ad9792e87cbd">

**Comment by LukeFinch** [comment]
This request has been moved to our new feedback tool. Go check out https://tokensstudio.featurebase.app/ to create a free account. You can upvote and comment on existing posts, make a new request, and subscribe to be notified when requests move into our roadmap.

**Comment by UdayHyma** [comment]
Added to Featurebase Roadmap : [🪙 Token organization enhancements
](https://tokensstudio.featurebase.app/p/token-organization-enhancements)
