### ISSUE TITLE
Changing a Modified Color Token's Reference Changes In Both Variable Modes

### ISSUE THREAD

**Issue by keeganedwin** [tokens-studio/figma-plugin#2416]
**Describe the bug**
This issue is similar to #2278, but this bug emerged only after the latest `1.38.6 release`. Changing modified color-tokens and creating/syncing variables now changes the value in both modes. 

1. The first issue in video presented is when changing the value of token updates the same value across both modes
2. The second issue presented is that the mode's values are only corrected upon clicking sync variables. 

**To Reproduce**
1. Create Variables
2. Change value of token - `jf.container.color.regular.bg.surface-main.enabled` - can be found in set `Patterns/Backgrounds`
3. See error

**Expected behavior**
It should work as it did previously:
1. Variables should be created respecting each mode's values
2. Changing a token's value should only update in one mode and not both

**Screenshots or Screencasts**
https://github.com/tokens-studio/figma-plugin/assets/93133012/1e6958d9-87e8-488d-9c6f-6f49044a856b

**Figma file (optional)**
[Test section](https://www.figma.com/file/7xl8D5zxOjBc8jeu58Nm4K/Untitled?type=design&node-id=3-534&mode=design&t=JJvhfISIozTijnM4-4)

**Comment by six7** [comment]
Will be fixed in 2.0
