### ISSUE TITLE
Improve Token Application Process 

### ISSUE THREAD

**Issue by keeganedwin** [tokens-studio/figma-plugin#2417]
**Is your feature request related to a problem? Please describe.**
When users want to apply tokens who `first` have styles/variables applied on frames, have to click a token twice before being able to apply it. 

**Used case:**
The process of designing a component typically involves applying styles and variables to it initially. Once that is done, we usually proceed to the plugin to map everything. However, switching multiple definitions from being style/variable-only to a token can be time-consuming. The plugin recognises the style/variable application, so we have to first `remove` and `apply` it again to set it as a token.

**Describe the solution you'd like**
We need to determine how this should work

**Additional context**
https://github.com/tokens-studio/figma-plugin/assets/93133012/ec1e3ff9-8961-44d7-aa89-cdd6b93792b4

**Comment by UdayHyma** [comment]
[Migrated to Featurebase](https://tokensstudio.featurebase.app/p/greenheart-v2-quality-of-life-enhancements)

**Comment by UdayHyma** [comment]
[Migrated to Featurebase](https://tokensstudio.featurebase.app/p/greenheart-v2-quality-of-life-enhancements)

**Comment by SamIam4Hyma** [comment]
Added to Featurebase Request-	[Tokens applied via styles and variables in the Figma UI are fragile](https://tokensstudio.featurebase.app/p/json-enhancements-for-color-tokens)
