### ISSUE TITLE
Color tokens appear in JSON, but not showing in plugin UI or switching with Theme

### ISSUE THREAD

**Issue by andrew-deem** [tokens-studio/figma-plugin#2419]
**Describe the bug**
I have multiple sets containing color tokens that after defining, uploading to GitLab, and using the plugin seem to disappear from Listing View.

It's the same tokens in the same sets that keep having this behavior. They appear to still be in the JSON view, but I can't manage them in the Listing View, and changing the theme no longer updates the corresponding styles. When I re-add the now-missing tokens, they work normally before then disappearing again. 

**To Reproduce**
1. Go to set called "components-inputs"
2. Click on Import Styles
3. Input tokens from the color styles I had created earlier for my Button component (created with "Create Styles")
4. Edit those tokens to reference existing color tokens instead of the absolute values they imported with
5. Use the plugin to manage another set of tokens
6. Return to set called "components-inputs"
7. Button color tokens no longer appear in List view. Changing theme no longer affects button color tokens.

**Expected behavior**
When tokens are added to the Listing view, they should remain there until manually deleted or renamed. Tokens visible in JSON view should show up in Listing view. 

**Screenshots or Screencasts**
Listing view, no color tokens for a group called "button"
<img width="821" alt="Screenshot 2023-12-11 at 12 44 38 PM" src="https://github.com/tokens-studio/figma-plugin/assets/153557665/7d8d67d9-c024-4763-8df6-0ab274ca49f6">

JSON view, showing several color tokens defined for a group called "button"
<img width="835" alt="Screenshot 2023-12-11 at 12 45 33 PM" src="https://github.com/tokens-studio/figma-plugin/assets/153557665/0df7e94f-0cc0-4a04-8597-ee891b211008">

**JSON (optional)**
[components-inputs.json](https://github.com/tokens-studio/figma-plugin/files/13640828/components-inputs.json)

**Comment by six7** [comment]
The reason is that one of your tokens ('button') shares the name with a token group. Rename it to button.default or so for it to work. The plugin UI informs you if you try to name a button like a group, but the JSON view doesnt

**Comment by andrew-deem** [comment]
ahhh ok, great catch. I will try that! Thank you!!

So not a bug then, but maybe there's UX opportunity. That message was VERY easy to ignore and dismiss in the moment. The impact wasn't clear and there weren't any hints or errors after the initial warning. An indicator like you get for a broken link in a token would be extremely helpful.

**Comment by rbosker** [comment]
will be fixed when https://github.com/tokens-studio/figma-plugin/issues/1205 is done
