### ISSUE TITLE
Ability To Display Token Usage Information

### ISSUE THREAD

**Issue by keeganedwin** [tokens-studio/figma-plugin#2421]
**Is your feature request related to a problem? Please describe.**
> As a user working with a brand agnostic system, I want to streamline the token mapping process to enhance efficiency. Currently, our token sets for Primitive, Semantic, and Colour theming contain numerous tokens that may not be necessary. To optimize our workflow and ensure the relevance of each token, we need a way to determine token usage across documents. To make things easier, we need a way to find out if these tokens are being used or not across our documents. Specifically, we want to know how many times `Token.X` and `Token.Y` have been applied. This will help us figure out which tokens are actually being used and which ones we can get rid of or simplify.

**Describe the solution you'd like**
We need to determine how this will work

**Possible solutions**
- When editing a token, show how many times it is applied on the document
- Also possibly show which tokens are not applied on the document (may affect performance)
- Information to be shown (used as token, variable or style)
- List view of tokens with usage information (filterable)
- Referenced tokens
- Tooltip

**Comment by LukeFinch** [comment]
This request has been moved to our new feedback tool. Go check out https://tokensstudio.featurebase.app/ to create a free account. You can upvote and comment on existing posts, make a new request, and subscribe to be notified when requests move into our roadmap.

**Comment by UdayHyma** [comment]
Added to Featurebase Roadmap : [🪙 Add support for Token usage metadata
](https://tokensstudio.featurebase.app/p/token-usage-metadata)
