### ISSUE TITLE
Option to update (selection, page, document, styles & variables) when you save while editing in JSON mode.

### ISSUE THREAD

**Issue by UdayHyma** [tokens-studio/figma-plugin#2435]
**Is your feature request related to a problem? Please describe.**
Currently when you rename tokens in the JSON view, it is not possible to remap this change when saving the JSON.

**Describe the solution you'd like**
A modal( second screenshot) that gives users the option to remap tokens after renaming and saving the JSON.

**Additional context**
We probably also need to think of how this feature is going to look, since we can’t copy this from how it looks in the listing view (the save JSON button is on the same place)
We could look at the before and after state of the json, and detect if there's any changes to tokens - if there's renames or if there's value changes / additions. That way we could offer the right options

![Json editor](https://github.com/tokens-studio/figma-plugin/assets/138768433/9c97842a-7a03-4a53-9198-52cfe2fa0046)
![Tokens add to selection](https://github.com/tokens-studio/figma-plugin/assets/138768433/ecc1c3ad-71de-4a96-b36a-1191a8541b33)

**Comment by LukeFinch** [comment]
This request has been moved to our new feedback tool. Go check out https://tokensstudio.featurebase.app/ to create a free account. You can upvote and comment on existing posts, make a new request, and subscribe to be notified when requests move into our roadmap.

**Comment by UdayHyma** [comment]
Added to Featurebase Roadmap : [🧑‍💻 JSON view/edit enhancements](https://tokensstudio.featurebase.app/p/json-viewedit-enhancements)
