### ISSUE TITLE
Renaming Theme-group & Theme Names Don't Update Variable Collection name or Mode name

### ISSUE THREAD

**Issue by keeganedwin** [tokens-studio/figma-plugin#2436]
**Describe the bug**
When changing the name of a `theme-group` as well as a `theme` and then syncing variables (rename variables option) the collections are not updated. Users are currently required to create fresh collections to have updated names. 

**To Reproduce**
1. Create variables
2. Change theme-group and theme name, save. 
3. Sync variables, rename variables option

**Expected behavior**
The `collection` (theme-group) name as well as the `mode` (theme) name should update after users select the rename variable option. 

**Screenshots or Screencasts**
[Video](https://github.com/tokens-studio/figma-plugin/assets/93133012/1a5e976e-8dee-425b-a252-4373931369c2)

**Comment by NuthanHyma** [comment]
**Figma File**
[Test File](https://www.figma.com/file/O66ziUhLcdt123PseBdQWM/Issue-%232436?type=design&node-id=0%3A1&mode=design&t=ygyU7NsD3kCYtZb1-1)

**Comment by SamIam4Hyma** [comment]
Added to Featurebase Roadmap as a known issue to test and track with V2 beta testers - [❖ 🪄 Sync variables and styles is now Export to Figma](https://tokensstudio.featurebase.app/p/sync-styles-and-variables-is-now-export-to-figma)

**Comment by SamIam4Hyma** [comment]
Added to Featurebase Roadmap-	[💚 Theme management enhancements - QOL](https://tokensstudio.featurebase.app/p/theme-management-enhancements-v2)

Added to Featurebase Roadmap-	[❖ 🪄 Sync variables and styles is now Export to Figma](https://tokensstudio.featurebase.app/p/sync-styles-and-variables-is-now-export-to-figma)

**Comment by keeganedwin** [comment]
This is still reproducible in **Prod 1.38.9** and **Beta V2-rc5**

**Comment by six7** [comment]
Completed in RC6
