### ISSUE TITLE
Unable To Create Folders Out Of Existing Sets

### ISSUE THREAD

**Issue by keeganedwin** [tokens-studio/figma-plugin#2437]
**Describe the bug**
Previously if a user had sets and wanted to group them under a folder, they could just prefix it with a forward slash **`/`** and the preferred set name. I.e. If I have sets `button` and `checkbox` and want to create them under the set `component` as a folder, I can prefix it with `component/button` to create the folder. The plugin currently responds to this instruction by not creating a functional folder. However, if I delete the `component` set, it then turns into a folder grouping the button and checkbox sets. 

**To Reproduce**
1. Create 3 sets - component, button, checkbox
2. Prefix button and checkbox with `component/`
3. See error
4. Delete component set
5. See second error

**Expected behavior**
Users should just be able to group existing sets into folders.

**Screenshots or Screencasts**
https://github.com/tokens-studio/figma-plugin/assets/93133012/0e686fc1-3e08-4af3-b8c0-4abf00d65e29

**Figma file (optional)**
[Test board](https://www.figma.com/file/ATUhIWdzQ57UpeQpIjy1em/Untitled?type=design&node-id=1-5&mode=design&t=EBtlGriRbhcHfZBv-4)

**Comment by NuthanHyma** [comment]
This issue still occurs in RC-9/10

**Comment by rbosker** [comment]
works in 2.2.0
