### ISSUE TITLE
Add support for binding variables to effects

### ISSUE THREAD

**Issue by six7** [tokens-studio/figma-plugin#2443]
Figma recently released support for binding variables to effects (shadows, blur), we should add those as well which would be huge for themable gradients.

https://www.figma.com/plugin-docs/updates/

- When applying a shadow that's referencing a color token and that color token has a variable connected, create the reference inside the shadow effect
- Do the same for background blur

https://www.figma.com/plugin-docs/api/VariableBindableEffectField/

**Comment by SamIam4Hyma** [comment]
Added to Featurebase Roadmap-	[❖💡Create a style powered by a variable ](https://tokensstudio.featurebase.app/p/create-a-style-powered-by-a-variable)
