### ISSUE TITLE
can't delete a set of tokens unless i close and reopen figma-tokens

### ISSUE THREAD

**Issue by hchiam** [tokens-studio/figma-plugin#2444]
**Describe the bug**
While working on updating my demo repo https://github.com/hchiam/figma-tokens-sync-example I noticed I can't delete a set of tokens unless I close and reopen figma-tokens.

**To Reproduce**
1. add a json of tokens: Settings > Sync providers > Add new > URL > Name and [URL](https://raw.githubusercontent.com/hchiam/figma-tokens-sync-example/main/open-props.figma-tokens.sync.json) > Save > Tokens
2. delete that sync provider (in Settings)
3. try to delete the token set (in Tokens)

**Expected behavior**
I should be able to Delete right away:
<img width="189" alt="image" src="https://github.com/tokens-studio/figma-plugin/assets/18131787/5b2e53a0-6e4e-4d87-8fc3-a26806e42bef">

**Actual behavior**
I can't Delete right away: (I have to close and reopen Tokens Studio for Figma to be able to see the Delete button) 
<img width="190" alt="image" src="https://github.com/tokens-studio/figma-plugin/assets/18131787/9e9168c7-e4a0-453a-af69-3a04ef8c9996">

**JSON (optional)**
https://raw.githubusercontent.com/hchiam/figma-tokens-sync-example/main/open-props.figma-tokens.sync.json

**Comment by six7** [comment]
URL sync is read-only, you can't delete there.

But the fact that the delete option even shows up seems like a bug, you should not be able to delete with a URL provider, ever.

Thanks for reporting!

**Comment by six7** [comment]
We'll have this fixed in our upcoming major 2.0 release, which might take a while, but I'm marking it as closed until for now 🙏
