### ISSUE TITLE
OKCLH color modifier

### ISSUE THREAD

**Issue by XavierVilars** [tokens-studio/figma-plugin#2459]
**Is your feature request related to a problem? Please describe.**
CLH is a great way to assure a true color perception in the design. But there are some issues on some colors. For example blue color tends to become purple with a high luminance. And of course should stay blue !

**Describe the solution you'd like**
One solution would be to use another color system : [OKCLH](https://oklch.com/#60.76,0.279,272.27,100). 
So why not creating a new color modifier possibilities : OKCLH ;).

**Comment by esthercheran** [comment]
@XavierVilars  Would you see this as another option in the dropdown for the color modifier? Or would you want to have the format for the color be written in OKLCH including in the json

**Comment by XavierVilars** [comment]
> @XavierVilars Would you see this as another option in the dropdown for the color modifier? Or would you want to have the format for the color be written in OKLCH including in the json

Hello, my demand was about having a new option in the color modifier. But thinking about having OKLCH format in JSON make also a lot of sense in term of transparency. Today my base colours are in hex and having them in OKLCH would make them easier to read and understand.

**Comment by rmnturov** [comment]
hi! please add support of OKLCH format for colro token value

**Comment by LukeFinch** [comment]
This request has been moved to our new feedback tool. Go check out https://tokensstudio.featurebase.app/ to create a free account. You can upvote and comment on existing posts, make a new request, and subscribe to be notified when requests move into our roadmap.

**Comment by UdayHyma** [comment]
Added to FeatureBase Roadmap : [🎨 Expanded support for color spaces](https://tokensstudio.featurebase.app/p/expanded-support-for-color-spaces)
