### ISSUE TITLE
AWS CodeCommit Support

### ISSUE THREAD

**Issue by iantrudell** [tokens-studio/figma-plugin#2468]
It looks like the plugin supports the following for syncing to Git source control:

Local storage (default)
URL
JSONBin.io
GitHub
GitLab
Azure DevOps
Supernova
Generic Versioned Storage
BitBucket (Planned)

Would it be possible to add AWS CodeCommit to the list of planned support? Thanks!

**Comment by LukeFinch** [comment]
This request has been moved to our new feedback tool. Go check out https://tokensstudio.featurebase.app/ to create a free account. You can upvote and comment on existing posts, make a new request, and subscribe to be notified when requests move into our roadmap.

**Comment by UdayHyma** [comment]
Added to Featurebase Roadmap : [↕️ AWS CodeCommit - Sync support request
](https://tokensstudio.featurebase.app/p/aws-codecommit)
