### ISSUE TITLE
Rename Styles (Via Sync Syles) Option Does Not Rename Styles

### ISSUE THREAD

**Issue by NuthanHyma** [tokens-studio/figma-plugin#2472]
**Describe the bug**
When renaming styles via the Sync Styles option, the plugin does not rename the styles.

**To Reproduce**

1. Open the plugin create the tokens and define themes
2. Go to styles & variables and create styles
3. Go to any token > right-click on the token and select `edit token`.
4. Rename the token and save it to `page`.
5. Now navigate to `styles & variables` > sync styles, select `rename styles` and save.
6. See the error in the local styles where the name is not updated.

**Expected behavior**
when renaming Styles Via Sync syles option should rename the styles.

**Screenshots or Screencasts**

https://github.com/tokens-studio/figma-plugin/assets/140593995/42fe6308-1260-4c85-8c09-5042e6d8e521

**Figma file (optional)**
[Test File
](https://www.figma.com/file/WJTmYSYqrZt5WQRu0h68FE/Untitled?type=design&node-id=0%3A1&mode=design&t=laOmXshe46EyKU0k-1)

**Comment by SamIam4Hyma** [comment]
Added to Featurebase Roadmap as a known issue to test and track with V2 beta testers - [❖ 🪄 Sync variables and styles is now Export to Figma](https://tokensstudio.featurebase.app/p/sync-styles-and-variables-is-now-export-to-figma)

**Comment by keeganedwin** [comment]
Closing this ticket as it is no longer reproducible after testing it on **Prod 1.38.9** and **Beta V2-rc5**.
