### ISSUE TITLE
Renaming Parent Group Doesn't Rename Token Values

### ISSUE THREAD

**Issue by keeganedwin** [tokens-studio/figma-plugin#2474]
**Describe the bug**
When I rename the parent level of a token like `color.blue.10` to `core.color.blue.10`, it doesn't prefix the values of tokens previously using `color.blue.10` to `core.color.blue.10`. In this example, the token is also a modifier, and upon renaming the group to `core.color.blue.10`, it prefixes core 2x in the modified token value - see second screenshot.

**To Reproduce**
1. Go to global set
2. Check json structure and token values
3. Rename `color.blue.10` group to `core.color.blue.10`
4. Check json structure and token values
5. See error

**Expected behavior**
In this example, after renaming the group, token `color.blue.10` which is referencing the token `color.blue.100`, should also have its value changed to `core.color.blue.100` when the group is renamed to `core.color.blue.10`

**Screenshots or Screencasts**
**Before renaming parent group (color.blue.10):**
![ag-default](https://github.com/tokens-studio/figma-plugin/assets/93133012/7370eab7-3396-4e10-9bae-d6ab56aac154)

**After renaming to (core.color.blue.10):**
![ag-bug](https://github.com/tokens-studio/figma-plugin/assets/93133012/df5c1417-6b5f-4ad0-bbd6-3342f163d2f1)

**Figma file (optional)**
[Test File](https://www.figma.com/file/gX7XRBbAFVukmTDRLx5gv5/Untitled?type=design&node-id=1-8&mode=design&t=ICF4ObjQWFdJzICU-4)

**Comment by keeganedwin** [comment]
I'm not sure this is a bug. More a ticket about functionality that needs to be considered. This is however still present in **Prod 1.38.9** and **Beta V2-rc5**.  This is also very related to #2435.

**Comment by six7** [comment]
Yeah I'd consider this a bug. We likely should rename that group and then update the references that make use of this group.

**Comment by NuthanHyma** [comment]
@six7 @SamIam4Hyma 
This is no longer reproducible in RC-10
