### ISSUE TITLE
Ignore First Part Of The Token Name For Styles Doesn’t Ignore The First Part.

### ISSUE THREAD

**Issue by NuthanHyma** [tokens-studio/figma-plugin#2475]
**Describe the bug**
when we select the `ignore first part of the token name for styles` option in settings, it does not ignore the first part of the token name when creating styles from the plugin.
So before syncing, all the texts grouped only under the theme name, `Saga`. After syncing styles, it prefixes all the text styles under `Saga/Font`. This shouldn't happen because I had the Ignore first part option checked.

**To Reproduce**

1. Navigate to the settings tab and make sure "` ignore the first part of the token name for styles`" is selected.
2. Go to styles & variables and create styles.
3. Now go to the typography token then right-click on the token, rename the token and save it to the page.
4. Go to` styles & variables` > `sync styles`
5. see the error in the local styles

**Expected behavior**
when `ignore first part of the token name for styles` option is selected in settings, it should ignore the first part of the token name when creating styles from the plugin.

**Screenshots or Screencasts**

https://github.com/tokens-studio/figma-plugin/assets/140593995/943c3da3-86ff-41ef-8948-a9659d26f204

**Figma file (optional)**
[Test File
](https://www.figma.com/file/S5TeT4hAvnVoJZnR7hzkev/Untitled?type=design&node-id=0%3A1&mode=design&t=Ex7etFaAHYf2SOQj-1)

**Comment by SamIam4Hyma** [comment]
Added to Featurebase Roadmap as a known issue potentially impacting beta testing results -	[❖ ❇️ New styles and variables options menu](https://tokensstudio.featurebase.app/p/new-styles-and-variables-options-menu)

**Comment by six7** [comment]
Marking as no longer reproducable in 2.0-rc6
