### ISSUE TITLE
Having different overrides in a the same token set group lead to wrong Figma Variable values

### ISSUE THREAD

**Issue by jbltx** [tokens-studio/figma-plugin#2477]
**Describe the bug**

When generating Figma Variables, if token sets from the same collection do have different keys, the token set that does not have these keys will not try to resolve them based on previously loaded token sets.

Example 
```jsonc
// common.json
{
  "color": {
     "darkGray": {
       "100": {
        "value": "#0a0a0a",
        "type": "color"
      }
     }
   }
}
// color/dark.json
{
  "primary": {
    "100": {
      "value": "{color.darkGray.100}",
      "type": "color"
    }
  }
}
// color/new-dark.json
{
  "color": {
    "darkGray": {
      "100": {
        "value": "#161616",
        "type": "color"
      }
    }
  },
  "primary": {
    "100": {
      "value": "{color.darkGray.100}",
      "type": "color"
    }
  }
}
```

This will give this Color collection

<img width="810" alt="image" src="https://github.com/tokens-studio/figma-plugin/assets/1284323/8850a25a-4999-4813-b68a-3e231caaedfb">

Note that this can be fixed manually by choosing the right reference in the Variables panel, but I would expect for the plugin to choose it correctly. 

<img width="482" alt="image" src="https://github.com/tokens-studio/figma-plugin/assets/1284323/e055de27-b2bd-4342-927f-03bd35389556">

**To Reproduce**
1. Create token sets from the example above
2. Create Themes based on theses sets 
  - Common/Common
  - Color/Dark
  - Color/New Dark

**Expected behavior**
I would expect that the created `color/primary/100` variable will have `color/darkGray/100` from `Common/Common`mode  as value, instead of the uknown `color/darkGray/100` from the `Color/Dark` mode

**Screenshots or Screencasts**
See above

**JSON (optional)**
See above

**Comment by UdayHyma** [comment]
[Migrated to Featurebase](https://tokensstudio.featurebase.app/p/sync-styles-and-variables-is-now-export-to-figma)
