### ISSUE TITLE
De-linter That Displays Broken Aliases

### ISSUE THREAD

**Issue by keeganedwin** [tokens-studio/figma-plugin#2478]
**Is your feature request related to a problem? Please describe.**
> A simple report that goes through all the sets and surfaces any broken aliases, and allows you to edit the broken values. 

**Additional context**
[Slack Thread](https://tokens-studio.slack.com/archives/C02JAL48UDN/p1706149832018009)

**Comment by UdayHyma** [comment]
[Migrated to Featurebase](https://tokensstudio.featurebase.app/p/greenheart-v2-quality-of-life-enhancements)

**Comment by SamIam4Hyma** [comment]
Added to Featurebase Request-	[↕️ Git sync enhancements - push, pull, merge, branching](https://tokensstudio.featurebase.app/p/git-sync-enhancements)
