### ISSUE TITLE
[Bug]: Trying to create variables from Opacity tokens does not create any variables

### ISSUE THREAD

**Issue by six7** [tokens-studio/figma-plugin#2481]
**Describe the bug**
If you have an opacity token and you try to create a variable out of it, it won't work. If you change type to `number` it will work.

**To Reproduce**
1. Create an opacity token with value 0.5
2. Create a theme group that would lead to a valid collection
3. Click Create variables

**Expected behavior**
Variable is created / type can be `number` (which only accepts numbers such as 0.1, 0.2, 1.0) so a conversion needs to happen

<img width="1172" alt="CleanShot 2024-01-29 at 09 50 34@2x" src="https://github.com/tokens-studio/figma-plugin/assets/4548309/c66b7190-c441-4371-939c-519ce8c0da76">

```
{
  "large": {
    "value": "0.5",
    "type": "opacity"
  },
  "largex": {
    "value": "0.5",
    "type": "number"
  },
  "large2": {
    "value": "{largex} / 2",
    "type": "number"
  }
}
```

**Comment by SamIam4Hyma** [comment]
Added to Featurebase Roadmap as a known issue potentially impacting beta testing performance-	[❖ 🚧 ❇️ Variables in stroke weight and opacity](https://tokensstudio.featurebase.app/p/variables-in-stroke-weight-and-opacity)
