### ISSUE TITLE
Create Variables For Specific/Selected Themes

### ISSUE THREAD

**Issue by NuthanHyma** [tokens-studio/figma-plugin#2483]
**Is your feature request related to a problem? Please describe.**
Ability to create variables of specific themes only.

**Used-case:**
Users do not want to create all the themes they have set up in all the files they are working in.

**Extra information:**
[Slack Threads](https://tokens-studio.slack.com/archives/C05LMAZPZ46/p1706516421690409)

**Comment by SamIam4Hyma** [comment]
@LukeFinch suggesting to close as this is covered in the PR 1974 https://github.com/tokens-studio/figma-plugin/pull/2522
