### ISSUE TITLE
Add the possibility to create a pull request for a different branch, once a push to a branch fails

### ISSUE THREAD

**Issue by rbosker** [tokens-studio/figma-plugin#2486]
**Is your feature request related to a problem? Please describe.**
Add the possibility to create a pull request for a different branch, once a push to a branch fails due to a lack of permissions.

**Describe the solution you'd like**
Once a push fails, show an error (described in linked issue) and give the possibility to create a pull request for a different branch (or on a new branch).

**Slack**
https://tokens-studio.slack.com/archives/C02DLQXNY6Q/p1706555083560259

**Comment by six7** [comment]
Closing this, pushing to a new branch won't help if permissions fail

Feel free to reopen if i got it wrong
