### ISSUE TITLE
Ability to duplicate credentials of the Sync provider/repo

### ISSUE THREAD

**Issue by NuthanHyma** [tokens-studio/figma-plugin#2490]
**Is your feature request related to a problem? Please describe.**
Duplicate the credentials of a sync provider so users don’t have to add credentials manually, instead only need to pate the PAT/Secrete key.

**Comment by LukeFinch** [comment]
This request has been moved to our new feedback tool. Go check out https://tokensstudio.featurebase.app/ to create a free account. You can upvote and comment on existing posts, make a new request, and subscribe to be notified when requests move into our roadmap.

**Comment by UdayHyma** [comment]
Added to Featurebase Roadmap : [🧑‍💻 Sync to external token storage enhancements
](https://tokensstudio.featurebase.app/p/sync-external-storage-enhancements)
