### ISSUE TITLE
Documentation uses `lineHeight` instead of `lineHeights` for token type

### ISSUE THREAD

**Issue by MrChrisRodriguez** [tokens-studio/figma-plugin#2494]
**Describe the bug**
The correct token type for line height is `lineHeights` but the documentation [Available Tokens Overview](https://docs.tokens.studio/available-tokens/available-tokens) page incorrectly lists `lineHeight`. 

In general, I think y'all should standardize to singular instead of the currently-confusing mix of singular and plural, but that's not relevant to this issue.

**To Reproduce**
1. Go to https://docs.tokens.studio/available-tokens/available-tokens
2. Look at the token listed for Line Height

**Expected behavior**
It should show `lineHeights`, not `lineHeight`

**Screenshots or Screencasts**
N/A

**Figma file (optional)**
N/A

**JSON (optional)**
N/A

**Comment by esthercheran** [comment]
Thank you for pointing it out! We'll have it changed soon. Will keep you updated.

**Comment by esthercheran** [comment]
@MrChrisRodriguez we have made the changes in the documentation for `lineheights`. While it will be great to consolidate the types to singular from the mix of singular and plural, this would be a breaking change and we have to consider how we can do that with minimum disruption. Thank you for the feedback 🙏  
Closing the issue, as the docs have been updated.
