### ISSUE TITLE
Create Broken Tokens From The Inspect Tab

### ISSUE THREAD

**Issue by keeganedwin** [tokens-studio/figma-plugin#2499]
**Is your feature request related to a problem? Please describe.**
Allow users to create tokens that are broken from within the inspect tab.

**Used-case**
A user is pushing tokens but the plugin crashes during the process of pushing. So the plugin is unable to pull unsaved changes upon reopening the plugin. The inspect tab however has the the last applied token/s displayed (broken) before the crash.

**User solution**
![image (24)](https://github.com/tokens-studio/figma-plugin/assets/93133012/f2901e91-0f35-4e22-a30f-4221309df58a)

**Comment by LukeFinch** [comment]
This request has been moved to our new feedback tool. Go check out https://tokensstudio.featurebase.app/ to create a free account. You can upvote and comment on existing posts, make a new request, and subscribe to be notified when requests move into our roadmap.

**Comment by UdayHyma** [comment]
Here's the URL to the featurebase post that is linked to this ticket: https://tokensstudio.featurebase.app/p/enhance-inspect-page-in-the-plugin
