### ISSUE TITLE
Focus Should Be On New Set After Creation

### ISSUE THREAD

**Issue by NuthanHyma** [tokens-studio/figma-plugin#2500]
**Is your feature request related to a problem? Please describe.**
After creating a new set, the focus should be on that new set as the user will create tokens. 

**Additional context**

https://github.com/tokens-studio/figma-plugin/assets/140593995/216783c6-8ee2-4d49-b7c7-b4862ba2c94f

**Comment by six7** [comment]
Will be part of 2.0
