### ISSUE TITLE
Allow the editing of an individual token's JSON

### ISSUE THREAD

**Issue by mikejyoung** [tokens-studio/figma-plugin#2501]
**Is your feature request related to a problem? Please describe.**
We are looking to make use of $extensions to pass through specific conditions for our custom transformers to handle on a per token basis. In addition, we envision cases where we want to assign metadata to tokens such as tags to aid for searching within documentation. As Tokens Studio is where we create and manage our tokens, entering the data here would make the most sense and avoid storing the data separately which could quickly get out of sync.

The challenge is that the only way to edit $extensions data in Tokens Studio is cumbersome as you need to switch to JSON mode and then find the token. This way also opens the door for accidentally changing the wrong data.

**Describe the solution you'd like**
Introduce the ability for to edit the JSON of a token while editing it.

**Additional context**
A possible implementation could be like this:
<img width="928" alt="#2501 Edit the JSON of an individual tokens" src="https://github.com/tokens-studio/figma-plugin/assets/75724470/2e79c601-3070-4399-afee-4e88f363181c">

**Comment by esthercheran** [comment]
@mikejyoung would you prefer to edit the json for each token or would it work if the $extensions data is exposed in the UI, if the purpose is to add data to $extensions

**Comment by mikejyoung** [comment]
@esthercheran 
I think I good starting point is JSON as its a flexible approach. 

An "Extensions" could also be added. I did a quick design of a possible approach:
<img width="876" alt="Screenshot 2024-02-12 at 9 23 48 AM" src="https://github.com/tokens-studio/figma-plugin/assets/75724470/043d8a77-c8d6-4b29-8e90-8a3039d1eb35">

The design is based on:

- The user sets their custom namespace in the settings
- Other namespaces are visible (such as tokens.studio), but not editable and collapsed by default
- The "key" dropdown will support autocomplete with previously used keys, for easier to set repeated extensions across tokens
- Similar to tokens, keys can support using a "." to put strings inside of objects within the JSON (i.e. transformed.resolve puts a "resolve" string inside of a "transformed" object)  
- The "value" input supports references (i.e. {fontSizes.sm})

**Comment by mikejyoung** [comment]
To provide a use case where we want to use Extensions...

In our `space` token group, we have a "1.5" token which equals "6px". Because tokens cannot have "." in their names, we create it in Tokens Studio as "1_5".

Our developer has written a custom transformer to turn convert these keys during transformation (i.e. "1_5" -> "1.5").

By using extensions, I (the designer) can pass the preferred key name to the transformer, which will change it if it finds a value for that extension key. This limits our developers needing to write code for bespoke cases.

```
{
    "space": {
        "1_5": {
            "value": "6px",
            "type": "dimension",
            "$extensions": {
                "elevate.design": {
                    "transformed": {
                        "key": "1.5"
                    }
                }
            }
        }
    }
}
```

**Comment by LukeFinch** [comment]
This request has been moved to our new feedback tool. Go check out https://tokensstudio.featurebase.app/ to create a free account. You can upvote and comment on existing posts, make a new request, and subscribe to be notified when requests move into our roadmap.

**Comment by UdayHyma** [comment]
Added to Featurebase Roadmap : [🪙 Token metadata enhancements](https://tokensstudio.featurebase.app/p/token-metadata-enhancements)
