### ISSUE TITLE
Unexpected behavior on creating variables modes from tokens which have modifiers

### ISSUE THREAD

**Issue by esthercheran** [tokens-studio/figma-plugin#2502]
When creating variables from tokens that have modifiers, the result is not as expected. 

![Image](https://github.com/tokens-studio/figma-plugin/assets/66366384/ed1f406c-ef48-4089-902b-55f875ff9632)

![Image](https://github.com/tokens-studio/figma-plugin/assets/66366384/ef40525d-2b0c-4f76-86c6-550008ce709c)

Steps to recreate:
1. Create a set (core) with two tokens: orange and blue
2. Create another set (mode/brand-a-light). Create a token (primary.500), use blue as reference.
3. Create a token primary.100 use primary.500 as reference and modify using lighten. Create primary.600 and use primary.500 as reference and modify using darken.
4. Create a new set (mode/brand-b-light). Create a token (primary.500), use orange as reference.
5. Create a token primary.100 use primary.500 as reference and modify using lighten. Create primary.600 and use primary.500 as reference and modify using darken.
6. Create themes:
     - Core/default : core set
     - Theme/brand-a-light: brand-a-light set
     - Theme/brand-b-light: brand-b-light set
7. Create variables. The result is in brand-a-light only primary.500 has the correct value, primary.100 and primary.600 has values from brand-b-light.

Expected outcome:
The variables should have the correct values in both the modes.

Figma file with tokens:
https://www.figma.com/file/wVwtA4yOvmbg9KVskyWOZw/Issue-%232502?type=design&node-id=0%3A1&mode=design&t=ydBlyZTk7gdoNqti-1

**Comment by ozgurgunes** [comment]
I'm also having this. On "create variables", color modifier is using "active" or "default" mode of given color reference. It gets fixed on "sync variables". So I have to run "sync variables" every time after "create variables".

**Comment by SamIam4Hyma** [comment]
@esthercheran I'm getting good results with V2 beta build, can you check as well and if it's solved please close? (:

**Comment by keeganedwin** [comment]
@SamIam4Hyma is correct. Closing this ticket as it the bug is no longer reproducible after testing it on Prod 1.38.9 and Beta V2-rc5. 
![CleanShot 2024-05-14 at 19 05 36@2x](https://github.com/tokens-studio/figma-plugin/assets/93133012/e872521b-d1f6-480b-8066-17c9b59037ff)
