### ISSUE TITLE
Math - Round Values Up or Down

### ISSUE THREAD

**Issue by netleader** [tokens-studio/figma-plugin#2503]
We use a lot of match to calculate dimension tokens but what bothers us is that there is no way to round values up or down.

e.g. {grid.helper.col-12.width}*(9/16)

This results in: 205.875 and we would like to have the possibility to round this up to 206.
We tried JS Math.round but it doesn't work.

**Comment by six7** [comment]
You can use round(n) or roundTo(n, 0) where the second argument is the number of decimals.

For a list of supported operations see https://www.npmjs.com/package/expr-eval
