### ISSUE TITLE
Composition Token Static Values aren't working

### ISSUE THREAD

**Issue by netleader** [tokens-studio/figma-plugin#2504]
**Describe the bug**
We are using composition tokens to create presets of images in certain formats e.g. 16:9 for a certain width.
When creating the composition token with a static value the value isn't used only the referenced values are working.

**To Reproduce**
Create a rectangle  600 x 300
Create a number token with a value of 400 name it {num.width.test}
Create a composition token name it: {comp.test}
Add height: 200
Add width: {num.width.test}
Apply the composition token to the rectangle.
Inspect the rectangle... only the width is applied 

**Expected behavior**
All props are created no matter if static or referenced.

**Screenshots or Screencasts**
![image](https://github.com/tokens-studio/figma-plugin/assets/3867846/f0f90174-a07d-4ced-9359-8c0ea77f8892)

**Comment by SamIam4Hyma** [comment]
@esthercheran can you look into this one to see if this is a bug or request for enhanced functionality please and label as such?

**Comment by six7** [comment]
Unable to reproduce, seems to work fine for me.

Feel free to reopen with more info and reproduction steps.



![Image](https://github.com/tokens-studio/figma-plugin/assets/4548309/adccc489-66dc-48a0-acb4-a9f9afe7ea6d)
