### ISSUE TITLE
functions aren't working with referenced tokens

### ISSUE THREAD

**Issue by netleader** [tokens-studio/figma-plugin#2505]
We use a lot of match to calculate dimension tokens. We tried to use the round functions but they aren't working with referenced tokens.

e.g. round({grid.helper.col-12.width}*(9/16))

**Comment by six7** [comment]
Hmm, unable to reproduce. this works for me:


![Image](https://github.com/tokens-studio/figma-plugin/assets/4548309/e1357047-0afe-4f15-8db8-3bae8591b7d2)

Feel free to reopen with more info

**Comment by SamIam4Hyma** [comment]
@netleader This is because the dimension token type has units in it, and its causing the math function to break. If you were using unitless number tokens, it will work.

**Comment by SamIam4Hyma** [comment]
Added to Featurebase Request-	[Math in value enhancements ](https://tokensstudio.featurebase.app/p/math-in-value-enhancements)
