### ISSUE TITLE
Have Newly Created Variables Auto Sync (import) To Tokens.

### ISSUE THREAD

**Issue by NuthanHyma** [tokens-studio/figma-plugin#2506]
**Is your feature request related to a problem? Please describe.**
When values are changed in the plugin, variables (values) are automatically updated. If variable values are changed, auto-update existing tokens.

**Comment by six7** [comment]
What if you're changing the variable values but don't have the plugin open?

**Comment by rmnturov** [comment]
hi! i want to edit variables in figma and have and ability to import them to existing Token Studio project. Without duplicates, only new or edited variables. May be in existing linked collections and modes

**Comment by UdayHyma** [comment]
[Migrated to Featurebase](https://tokensstudio.featurebase.app/p/sync-styles-and-variables-is-now-export-to-figma)
