### ISSUE TITLE
Plugin 2.2

### ISSUE THREAD

**Issue by esthercheran** [tokens-studio/figma-plugin#2507]
In this epic we aim to improve the editing experience of tokens as well as introduce new token types
```[tasklist]
### Introduce new token types
- [ ] #858
- [ ] https://github.com/tokens-studio/figma-plugin/issues/152
- [ ] https://github.com/tokens-studio/figma-plugin/issues/299
- [ ] #1748
- [ ] https://github.com/tokens-studio/figma-plugin/issues/1295
- [ ] https://github.com/tokens-studio/figma-plugin/issues/613
```

**Comment by six7** [comment]
@esthercheran can you fill out the contents of this issue? Let's not have empty issues.

**Comment by six7** [comment]
Closing in favor of https://github.com/tokens-studio/figma-plugin/issues/2679
