### ISSUE TITLE
Tokens Disappear When Renaming A Token Group Without Giving A New Name

### ISSUE THREAD

**Issue by NuthanHyma** [tokens-studio/figma-plugin#2508]
**Describe the bug**
On renaming a `token group`, if left blank (no valid rename), the entire tokens group disappears, but is still present in JSON; tokens exist.

**To Reproduce**
1. Navigate to the plugin
2. Go to any token group
3. Rename the` token group` with an empty text. (' ')
4. Save the change
5. tokens disappear when the tokens group is `collapsed`
6. The entire tokens group disappear in the visual view of the tokens

**Expected behavior**
On renaming a token group if left blank (no valid rename), the tokens group should be present in the sets > only with the name ' '

**Screenshots or Screencasts**

https://github.com/tokens-studio/figma-plugin/assets/140593995/9cbef460-059e-43a7-8848-c9a99c28bba3

**Figma file (optional)**
[Text File
](https://www.figma.com/file/kAt1susbKFVoACZxm6Y8nJ/Untitled?type=design&node-id=0%3A1&mode=design&t=YG4wMQo3HC2aCyzt-1)

**Comment by rahulthakur1007** [comment]
@keeganedwin,this bug is reproducible in prod 1.38.9 and beta v2-rc5

**Comment by keeganedwin** [comment]
> @keeganedwin,this bug is reproducible in prod 1.38.9 and beta v2-rc5

Closing

**Comment by rahulthakur1007** [comment]
@keeganedwin this bug is not reproducible in prod 1.38.9 and beta v2-rc5
