### ISSUE TITLE
Case sensitive tokens to work with lowercase letters

### ISSUE THREAD

**Issue by NuthanHyma** [tokens-studio/figma-plugin#2513]
**Is your feature request related to a problem? Please describe.**
When users use these case-sensitive tokens (text case, text decoration, font family, font weight), want them to work with lowercase letters too.
**Example:**
`text case`
Current behavior - None
Expected - none 

`Text Decoration`
Current behavior - None
Expected - none 

`Font Family`
Current behavior - Inter
Expected - inter 

`Font Weight`
Current behavior - Bold
Expected - bold

**Comment by six7** [comment]
Not sure I understand fully. Is this about being able to use `bold` for `Bold`? And `inter` for `Inter`?

**Comment by keeganedwin** [comment]
@six7 correct.

**Comment by UdayHyma** [comment]
[Migrated to Featurebase](https://tokensstudio.featurebase.app/p/typography-styles-with-variables)

**Comment by UdayHyma** [comment]
[Migrated to Featurebase](https://tokensstudio.featurebase.app/p/typography-styles-with-variables)

**Comment by SamIam4Hyma** [comment]
Added to featurebase request - 
[📏 Expand accepted reference token types and units](https://tokensstudio.featurebase.app/p/expand-accepted-reference-token-types)
