### ISSUE TITLE
Free Users Can Edit Tokens With Command Key

### ISSUE THREAD

**Issue by NuthanHyma** [tokens-studio/figma-plugin#2514]
**Describe the bug**
Free users can’t edit, duplicate, copy, or delete tokens when working in a multi-file repo, but there is a bug bypassing this when the command key is used; the users are able to edit a token.

**To Reproduce**
1. Use a multi-file repo
2. remove the license key
3. go to any token.
4. Hold the command key and click on the token to edit
5. This method works and the user can edit the token.

**Expected behavior**
Using the command key to edit the token should not work.

**Screenshots or Screencasts**

https://github.com/tokens-studio/figma-plugin/assets/140593995/7b4a2841-896f-43a8-bbac-1c2cc605617f

**Figma file (optional)**
[Test File
](https://www.figma.com/file/isZocKpKb0tDtyod9d3uD7/Issue-%232514?type=design&node-id=0%3A1&mode=design&t=tqOIcMlIFmj7sv2W-1)

**Comment by SamIam4Hyma** [comment]
Added to Featurebase Roadmap-	[🐛 V2 Bug Fixes](https://tokensstudio.featurebase.app/p/v2-bug-fixes)

**Comment by SamIam4Hyma** [comment]
Added to Featurebase Roadmap-	[🐛 V2 Bug Fixes](https://tokensstudio.featurebase.app/p/v2-bug-fixes)
