### ISSUE TITLE
Add Eye-dropper To Pick Colors From The Canvas

### ISSUE THREAD

**Issue by NuthanHyma** [tokens-studio/figma-plugin#2523]
**Is your feature request related to a problem? Please describe.**
Have an `eye-dropper` feature in the color picker modal to allow users to pick a color off Figma’s canvas (like Figma’s design panel color-picker)

**Additional context**
![image](https://github.com/tokens-studio/figma-plugin/assets/140593995/6f9dde99-d89e-48bb-945f-078b34adc934)

**Comment by SamIam4Hyma** [comment]
Added to featurebase if you want to upvote for this request

[](https://tokensstudio.featurebase.app/p/enhance-color-swatch-functionality)

**Comment by UdayHyma** [comment]
Here's the URL to the featurebase post that is linked to this ticket: https://tokensstudio.featurebase.app/p/bulbart-enhance-color-functionality-across-all-token-types
