### ISSUE TITLE
License key expired

### ISSUE THREAD

**Issue by rehaabtarek** [tokens-studio/figma-plugin#2525]
**Describe the bug**
License key is expired, unable to login

**Expected behavior**
A new working license key

**Screenshots or Screencasts**
<img width="407" alt="121" src="https://github.com/tokens-studio/figma-plugin/assets/156310552/d275d947-8b6b-46e0-90c9-a05049a207f6">

**Comment by esthercheran** [comment]
@rehaabtarek you can reach out to support@tokens.studio for license key related issues

**Comment by SamIam4Hyma** [comment]
@esthercheran can this one be closed?
