### ISSUE TITLE
Unable to do git sync for enterprise github using VPN

### ISSUE THREAD

**Issue by somsharan** [tokens-studio/figma-plugin#2526]
**Describe the bug**
Unbale to do git sync for enterprise github getting authentication's issues tried to pass different base url but still unable to do.

Note: we connect to enterprise github using VPN  

**Expected behavior**
Able to do git sync and do pull, push for enterprise github

**Screenshots or Screencasts**
this is the error even with valid credentials : Error syncing with GitHub, check credentials

**Comment by six7** [comment]
Can you describe some more how's the process with the VPN? Enterprise sync works, i could imagine von being the culprit.

**Comment by somsharan** [comment]
ok we access the enterprise github through VPN(global protect) as we work remotely. now how do we use this enterprise github to sync with token studio

**Comment by six7** [comment]
Probably best to share your settings (excl. the access key!) so we can be sure there's no misconfiguration.

**Comment by somsharan** [comment]
<img width="278" alt="image" src="https://github.com/tokens-studio/figma-plugin/assets/7229461/4d5c364d-3c08-4140-bce8-ccc85d6a6ed8">

**Comment by somsharan** [comment]
above is the settings defined

**Comment by six7** [comment]
> above is the settings defined

Sorry for the alt reply, we'll need more than that part of the screen - especially the part at the bottom with the baseUrl.

As something I can point out: Your `Repository` is lacking the owner. It should be e.g. `shopify/polaris` - for you it just shows `components`
