### ISSUE TITLE
size/numeric Alias suggestions stopped working in Typography tokens

### ISSUE THREAD

**Issue by leemlller** [tokens-studio/figma-plugin#2528]
**Describe the bug**

**To Reproduce**
1. Create any numeric token in Sizing or Dimension ex. **sizing/100** with value **16**
2. not fully input this alias in Typography fontSize, LineHeight, ParagraphSpacing etc... **{sizing.1...**
3. See error in suggestion dropdown **"Not found"**

**Expected behavior**
If you input full path **{sizing.100}** you'll see correctly calculated preview of **16** and after save it will work as indented

**Screenshots or Screencasts**
(https://tokens-studio.slack.com/archives/C02DLQXNY6Q/p1709571132215559)](https://tokens-studio.slack.com/archives/C02DLQXNY6Q/p1709571132215559)

**Figma file (optional)**
Send us the link to a Figma file containing a reproducible example

**JSON (optional)**
```
{
  "global": {
    "s": {
      "100": {
        "value": "16",
        "type": "sizing"
      }
    },
    "t": {
      "s100": {
        "value": {
          "fontSize": "{s.100}"
        },
        "type": "typography"
      },
      "d100": {
        "value": {
          "fontSize": "{d.100}"
        },
        "type": "typography"
      }
    },
    "d": {
      "100": {
        "value": "16px",
        "type": "dimension"
      }
    }
  }
}
```

**Comment by six7** [comment]
Will be fixed in 2.0
