### ISSUE TITLE
Create Variables Only From Tokens That Have Not Been Created

### ISSUE THREAD

**Issue by NuthanHyma** [tokens-studio/figma-plugin#2534]
**Is your feature request related to a problem? Please describe.**
Instead of recreating all variables each time, create only those that have not been previously created.

**Used Case**
When the user wants to create new variables through the plugin, it recreates all the existing tokens in the file.

**Comment by six7** [comment]
Hey @NuthanHyma I'm unable to reproduce. Creating new tokens properly only treats that one added variable as a changed variable in Figma. What am I missing?

https://github.com/tokens-studio/figma-plugin/assets/4548309/489604aa-96a4-44c6-8592-b0da65f4d224

**Comment by SamIam4Hyma** [comment]
Added to Featurebase Roadmap as a known issue to test and track with V2 beta testers -	[❖ 🪄 Sync variables and styles is now Export to Figma](https://tokensstudio.featurebase.app/p/sync-styles-and-variables-is-now-export-to-figma)

**Comment by six7** [comment]
Unable to reproduce in 2.0 rc6
