### ISSUE TITLE
Crashing while reordering sets

### ISSUE THREAD

**Issue by isaquepereira** [tokens-studio/figma-plugin#2537]
**Describe the bug**
When I try to reorder my sets the plugin is crash w/o explicit errors.
Figma Desktop App version 116.16.13
f
**To Reproduce**
1. Open tokens studio
2. Having multiple sets and sub-sets try to reorder

**Expected behavior**
Reorder successfully. Not crashing.

**Screenshots or Screencasts**

![CleanShot 2024-03-14 at 15 29 39@2x](https://github.com/tokens-studio/figma-plugin/assets/26747447/6c5cd1f6-02de-4fa6-938e-639698d94c0b)
![CleanShot 2024-03-14 at 15 28 07@2x](https://github.com/tokens-studio/figma-plugin/assets/26747447/03e35f18-5891-433f-8991-10de38de410c)

**Figma file (optional)**
Send us the link to a Figma file containing a reproducible example

**JSON (optional)**
If possible, attach the JSON that leads to this bug.

**Comment by isaquepereira** [comment]
I figured out.
I had this set group called Semantic (A) and I created a new set (for testing purposes) called Semantic (B) too.
When the new set (B) pass above the set group (A) the plugin crashes.
I had to rename the set and I was able to reorder.

**Comment by SamIam4Hyma** [comment]
@isaquepereira thanks for the update! Closing this ticket but tagging @cuserox for visibiliy as the team has been working on token set issues and might want to keep this in mind.
