### ISSUE TITLE
Make the Listing/JSON "Tab" a switcher.

### ISSUE THREAD

**Issue by isaquepereira** [tokens-studio/figma-plugin#2538]
**Is your feature request related to a problem? Please describe.**
Currently we need to do two precise clicks to switch between Listing and JSON mode.

**Describe the solution you'd like**
Having this as a switcher with a good hit area would improve this experience achieving a faster and fluid workflow.

**Describe alternatives you've considered**
Staying all the time in JSON. But dealing with colors w/o visual reference is quite awful.

**Additional context**
![CleanShot 2024-03-14 at 15 41 44@2x](https://github.com/tokens-studio/figma-plugin/assets/26747447/33d10b33-25a4-4684-95d1-022a192a14dd)

**Comment by six7** [comment]
Closing as complete and will be part of 2.0

**Comment by SamIam4Hyma** [comment]
Added to Featurebase Roadmap-	[🪄 👩‍💻 JSON Enhancements ](https://tokensstudio.featurebase.app/p/json-v2)
