### ISSUE TITLE
Second screen: Showing wrong resolved values

### ISSUE THREAD

**Issue by isaquepereira** [tokens-studio/figma-plugin#2539]
**Describe the bug**
Both the HEX and the color "badge" is wrong on second screen. I this case I'm referencing another token.
Also, I'm using modifiers to get my color scales.

**To Reproduce**
1. Set diferent color tokens w/ aliases (color scale)
2. Go to second screen
3. See the same color for every token.

**Expected behavior**
See as seemed on Figma Plugin.

**Screenshots or Screenc
![CleanShot 2024-03-14 at 16 26 34@2x](https://github.com/tokens-studio/figma-plugin/assets/26747447/de2059c3-73a1-4f92-a7ba-1097d1a2e87d)

**Comment by LukeFinch** [comment]
This request has been moved to our new feedback tool. Go check out https://tokensstudio.featurebase.app/ to create a free account. You can upvote and comment on existing posts, make a new request, and subscribe to be notified when requests move into our roadmap.

**Comment by UdayHyma** [comment]
Added to Featuerbase Roadmap : [👩‍🎨 🎨 Second screen enhancements
](https://tokensstudio.featurebase.app/p/second-screen-enhancements)
