### ISSUE TITLE
Introduce `font-variant-numeric` token type

### ISSUE THREAD

**Issue by kulset** [tokens-studio/figma-plugin#2540]
**Is your feature request related to a problem? Please describe.**
When I'm designing tables, I want to use tabular numerals in all columns with numbers and dates. 
Using tabular numerals makes the numbers in a column align vertically because each numeral has the same width. 
Many fonts support this, and Figma also has a setting for this under Type setting > Details > Numbers > Style.

**Describe the solution you'd like**
As a solution, I would like a token type for the CSS property `font-variant-numeric`.
This CSS property provides different ways of displaying numbers, fractions, and ordinal markers.

**Describe alternatives you've considered**
Currently, the only way to achieve this today is to define separate typography tokens for table text with a monospaced font. 
This is not ideal, as it deviates from the visual style.

**Comment by LukeFinch** [comment]
This request has been moved to our new feedback tool. Go check out https://tokensstudio.featurebase.app/ to create a free account. You can upvote and comment on existing posts, make a new request, and subscribe to be notified when requests move into our roadmap.

**Comment by UdayHyma** [comment]
Added to Featurebase Roadmap : [🪙 Expand token types](https://tokensstudio.featurebase.app/p/expand-token-types)
