### ISSUE TITLE
No connection to self-hosted Gitlab

### ISSUE THREAD

**Issue by brosua** [tokens-studio/figma-plugin#2544]
**Describe the bug**
A connection to the self-hosted Gitlab (htts://git.[company].com) is not possible. The error message is "invalid credentials". The instance is publicly accessible. The user has many projects.
However, a sync was possible with the same setup steps and Gitlab.com.

**Expected behavior**
I would like to connect with my selfhosted gitlab instance.

**Comment by six7** [comment]
Hey, this should be possible. Please reopen with details about the connection details you entered, so we can help. Make sure the PAT is obfuscated.
