### ISSUE TITLE
Displaying value in different format for documentation colour tokens

### ISSUE THREAD

**Issue by yapjonathan** [tokens-studio/figma-plugin#255]
**Is your feature request related to a problem? Please describe.**
![Screenshot 2021-09-17 at 11 05 54 AM](https://user-images.githubusercontent.com/1426739/133717938-ea52caf8-4ee3-448c-82aa-eb2e645fd6fe.png)
Currently, the documentation tokens only allow you to show the value of the token. e.g. using hex `#000000` will just display it as it. Being able to show them in other formats like RGB or HSL on top of the original value will be extremely helpful for managing documentation tokens. 

**Describe the solution you'd like**
A 'display value' field in edit token and allow for manipulating the value e.g.`rgb($neutral.50)` and being able to select it in the contextual menu.

- Does this needs to be prefilled?
- Add screenshot pointing out where the field needs to be @rbosker 
- In the list for documentation, also place a field: 'Display Value'

**Comment by six7** [comment]
Update on this: We initially wanted to tackle it in the next iteration, but I'm removing it again as I couldn't come up with a good enough solution. If someone has one that doesn't clutter the UI I'd appreciate it.

**Comment by SamIam4Hyma** [comment]
Suggest to close as its stale and can be reimagined when we focus on documentation in a future epic
