### ISSUE TITLE
Import Options Should Be Unselected by Default

### ISSUE THREAD

**Issue by keeganedwin** [tokens-studio/figma-plugin#2553]
**Is your feature request related to a problem? Please describe.**
Most people using the import functions will be importing in pixels, and results can be quite unpredictable if the REM feature is selected by default. 

**Describe the solution you'd like**
Have the options unselected by default allowing the user to check if and when the want to import the options.

**Additional context**
Current:
![CleanShot 2024-01-30 at 19 11 44@2x](https://github.com/tokens-studio/figma-plugin/assets/93133012/7af92518-f7a0-47c2-a45b-48e3e5398877)

Expected:
![CleanShot 2024-03-26 at 18 01 55@2x](https://github.com/tokens-studio/figma-plugin/assets/93133012/70238c7b-fac4-4741-834a-2f8102958676)

**Comment by six7** [comment]
Will be fixed in 2.0

**Comment by SamIam4Hyma** [comment]
Added to Featurebase Roadmap-	[💚 V2 Quality of Life Enhancements](https://tokensstudio.featurebase.app/p/greenheart-v2-quality-of-life-enhancements)
