### ISSUE TITLE
Drag-and-drop issue with color token

### ISSUE THREAD

**Issue by NuthanHyma** [tokens-studio/figma-plugin#2555]
**Describe the bug**
There seems to be an issue with the drag-and-drop feature, when it concerns more than a certain number of tokens in a group. I have 5 tokens in the gradient group and I’m unable to drag and drop their position. As soon as I break them down into a smaller number per sub-group, I’m able to drag and drop them.

**To Reproduce**
1. Go to color tokens
2. create more than 6 color tokens and then try to drag and drop
3. Then break them down into sub-groups and try to drag and drop
4. see the error

**Expected behavior**
The drag-and-drop feature should work even when there are more than 5 color tokens.

**Screenshots or Screencasts**

https://github.com/tokens-studio/figma-plugin/assets/140593995/27fb728f-a55e-41a4-a0be-0c3c14115ccc

**Figma file (optional)**
[Test File](https://www.figma.com/file/P8kz0w8SR6B0HLAEyujzWO/Issue-%232555?type=design&node-id=0%3A1&mode=design&t=1DAOJsCiQrvn5vOC-1)

**Comment by six7** [comment]
This has to do with color tokens being named numerically `300` etc. - you cannot rearrange them. Closing as unplanned
