### ISSUE TITLE
Manage theme controls should always have one active option

### ISSUE THREAD

**Issue by esthercheran** [tokens-studio/figma-plugin#2566]
Issue:
In the `Manage theme` modal the segemented controls can be toggled to not have any option in the active state (Disabled, Reference Only, Enabled). This control should always have one option in the active state.
This controls is also present in the Export Variables and Styles modal under `Change Sets`. The functionality should remain the same here as well.
 
Reproduction:

![Image](https://github.com/tokens-studio/figma-plugin/assets/66366384/09cc40f2-ede0-476e-a3ed-e6b000b74ba2)

![Image](https://github.com/tokens-studio/figma-plugin/assets/66366384/daa9fe9d-28a7-42ba-98fc-550b5f0b181b)

Definition of done:
The toggle of `Manage Themes` and `Change Sets` should always have one option in active state.

**Comment by LukeFinch** [comment]
Fixing this along with others as part of https://github.com/tokens-studio/figma-plugin/pull/2570

**Comment by SamIam4Hyma** [comment]
Added to Featurebase Roadmap-	[💚 Theme management enhancements - QOL](https://tokensstudio.featurebase.app/p/theme-management-enhancements-v2)
