### ISSUE TITLE
Resolved value of token is not showing when reference is used

### ISSUE THREAD

**Issue by six7** [tokens-studio/figma-plugin#2573]
Issue:
When a reference is used in a token, the resolved value is showing `null` or `[object object]`. This is occurring for all token types.

Reproduction:

![Image](https://github.com/tokens-studio/figma-plugin/assets/66366384/c82a6264-4bb0-4c38-bf20-f3f05e5d9d7f)

![Image](https://github.com/tokens-studio/figma-plugin/assets/66366384/1f287656-aea5-4ef8-a877-7834668384dc)

Definition of done:
When using a reference as the token value, the resolved value should be shown. Attached image of current plugin

![Image](https://github.com/tokens-studio/figma-plugin/assets/66366384/7aab610c-f7bb-4559-a223-c17591911bc6)

**Comment by LukeFinch** [comment]
This issue is caused by something in the DTCG format.
These forms work as expected when using legacy.

I assume the same is for the missing colours

**Comment by UdayHyma** [comment]
Added to FeatureBase Roadmap : [❇️ W3C - DTCG Specification Alignment
](https://tokensstudio.featurebase.app/p/w3c-dtcg-specification-alignment)
