### ISSUE TITLE
Create/Edit color token modal does not show color swatch

### ISSUE THREAD

**Issue by six7** [tokens-studio/figma-plugin#2574]
Issue:
When creating or editing a color token the color swatch is not shown on entering values as raw values or using references 

Reproduction:

![Image](https://github.com/tokens-studio/figma-plugin/assets/66366384/9b01d930-2702-4c8e-ac9e-ab81986be922)

![Image](https://github.com/tokens-studio/figma-plugin/assets/66366384/b81ac984-b6b2-4284-80c1-2b6719e421f3)

Definition of done:

When creating or editing color tokens the color swatch should show the corresponding color. This is true for both raw values and reference values if the value is valid. This is not true if the raw value is not a correct raw value or the reference value is broken.

**Comment by LukeFinch** [comment]
Do we think this is related to: https://github.com/orgs/tokens-studio/projects/34/views/3?pane=issue&itemId=58094445 ?
