### ISSUE TITLE
[2.0]: Styles / Variables Modal / Sets missing save button

### ISSUE THREAD

**Issue by six7** [tokens-studio/figma-plugin#2575]
There's no confimation / 'save' button on this screen when managing selected sets to export.

Ideal scenario:
- The changed state is not saved automatically but only after pressing a `Save` button here.
- There's a Cancel button that would close the dialog and *not* save the changes made.

![Image](https://github.com/tokens-studio/figma-plugin/assets/4548309/918e2652-b1d7-4ba5-ac01-90746ece4b4b)

**Comment by SamIam4Hyma** [comment]
Added to Featurebase Roadmap as a known issue in progress of being fixed -	[🚧 ❖❇️ Export styles and variables using sets (free plan) ](https://tokensstudio.featurebase.app/p/export-to-figma-using-token-sets)

**Comment by cuserox** [comment]
# ⚠️ WIP 
* Branch: `fix/2575-add-save-button-to-export-sets-modal`
* `TODO`s: reset selected sets to previous state when user: clicks **Cancel** OR presses the **<---** back arrow

<img width="200" alt="Screenshot 2024-05-24 at 17 34 07" src="https://github.com/tokens-studio/figma-plugin/assets/114073780/9ea2cd39-f0e8-4d75-a92b-c989eddcd629">
