### ISSUE TITLE
[2.0]: Styles Variables options should persist between sessions

### ISSUE THREAD

**Issue by six7** [tokens-studio/figma-plugin#2576]
these options do not persist between launches i constantly have to re-set them when i relaunch the plugin

![Image](https://github.com/tokens-studio/figma-plugin/assets/4548309/479d366d-d6c7-4126-ab18-dbfa6baf3fb9)

**Comment by SamIam4Hyma** [comment]
Added to Featurebase Roadmap as a point of feedback to collect as now the settings persist across all files which is less than desirable as these setting impact what styles and variables are updated -	[❖ ❇️ New styles and variables options menu](https://tokensstudio.featurebase.app/p/new-styles-and-variables-options-menu)
