### ISSUE TITLE
[2.0]: Manage themes modal: Numbers shown next to themes incorrect + inverted singular / plural

### ISSUE THREAD

**Issue by six7** [tokens-studio/figma-plugin#2577]
- singular / plural inverted on the hints here for `n styles`
- i also noticed those counts are not reflecting the actual state. try creating a bunch of variables / styles - the number does not seem to make sense

![Image](https://github.com/tokens-studio/figma-plugin/assets/4548309/453de642-b704-4f0d-b32e-b9f23e6b1f8c)

**Comment by SamIam4Hyma** [comment]
Added to Featurebase Roadmap-	[💚 Theme management enhancements - QOL](https://tokensstudio.featurebase.app/p/theme-management-enhancements-v2)
