### ISSUE TITLE
[2.0]: Spacing missing on Manage themes modal buttons

### ISSUE THREAD

**Issue by six7** [tokens-studio/figma-plugin#2578]
![Image](https://github.com/tokens-studio/figma-plugin/assets/4548309/4e267d61-37dd-4250-90a9-59abaf258bf7)

**Comment by SamIam4Hyma** [comment]
Added to Featurebase Roadmap-	[💚 Theme management enhancements - QOL](https://tokensstudio.featurebase.app/p/theme-management-enhancements-v2)
