### ISSUE TITLE
[2.0]: Weird focus state shown when pressing `Esc` on Styles & Variables options modal

### ISSUE THREAD

**Issue by six7** [tokens-studio/figma-plugin#2581]
When pressing `Esc` on the styles & variables options modal we put focus on the whole modal it seems. That modal has a default focus style, let's change it to the 2px accent colored outline.

https://github.com/tokens-studio/figma-plugin/assets/4548309/88f28ab0-0666-4f5c-b824-31a950d50b94

**Comment by SamIam4Hyma** [comment]
Added to Featurebase Roadmap as a known issue to avoid duplicate reporting in beta testing results -	[❖ ❇️ New styles and variables options menu](https://tokensstudio.featurebase.app/p/new-styles-and-variables-options-menu)
