### ISSUE TITLE
[2.0]: `Tools` and Styles and variables menu zIndex clashes with token sets

### ISSUE THREAD

**Issue by six7** [tokens-studio/figma-plugin#2585]
Likely an issue of a missing `Portal`: The tools menu seems to be "behind" the token sets entries - important: only appears on **token set folders / groups**

The Tools menu should likely be rendered in a Portal

![Image](https://github.com/tokens-studio/figma-plugin/assets/4548309/ac2df6cd-3641-46e4-84f4-fe1b08758e51)

![Image](https://github.com/tokens-studio/figma-plugin/assets/4548309/5274f2f4-9ce8-4bba-a513-433f5d2a30d3)

![Image](https://github.com/tokens-studio/figma-plugin/assets/4548309/c7c31a94-927f-4e11-9706-955bcf8f3b58)

**Comment by SamIam4Hyma** [comment]
Added to Featurebase Roadmap as a known issue potentially impacting beta testing results -	[❖ ❇️ New styles and variables options menu](https://tokensstudio.featurebase.app/p/new-styles-and-variables-options-menu)
