### ISSUE TITLE
[2.0]: Prefix styles with active theme name not working as expected

### ISSUE THREAD

**Issue by six7** [tokens-studio/figma-plugin#2606]
From @SamIam4Hyma 

RE: Prefix styles with active theme name setting
This doesn't seem to be working for me when I have styles already created, select the option, then try to export to Figma for a second time.
In a fresh file with no styles created yet, it does create styles with themes prefixed, however
I'm not sure in the figma design panel where it says "theme" where that name came from, looking at the "confirm themes" menu you can see none of the themes are called "theme"

![Image](https://github.com/tokens-studio/figma-plugin/assets/4548309/2f684e91-7265-4ff9-a9a4-222cab21e911)

**Comment by SamIam4Hyma** [comment]
Added to Featurebase Roadmap as a known issue potentially impacting beta testing results -	[❖ ❇️ New styles and variables options menu](https://tokensstudio.featurebase.app/p/new-styles-and-variables-options-menu)

**Comment by six7** [comment]
I can't reproduce this. Prefix styles with active theme name works fine on my end 🤔 

cc @SamIam4Hyma maybe you created `theme` by accident?

**Comment by six7** [comment]
Closing, please reopen if you can provide reproduction steps 🙏
