### ISSUE TITLE
Provide dedicated image for converting back from W3C to legacy format

### ISSUE THREAD

**Issue by six7** [tokens-studio/figma-plugin#2608]
> Also wondering if the images are supposed to be identical? It feels like the code preview should be flipped? We want to be sure visually there is some difference so users don't make "skimming" errors

From @SamIam4Hyma

**Comment by SamIam4Hyma** [comment]
Added to Featurebase Roadmap-	[❇️ W3C - DTCG Specification Alignment](https://tokensstudio.featurebase.app/p/w3c-dtcg-specification-alignment)
