### ISSUE TITLE
[2.0]: Creating styles with variables requires two runs

### ISSUE THREAD

**Issue by six7** [tokens-studio/figma-plugin#2614]
From https://hyma-team.slack.com/archives/C06RHB9RT2B/p1712773355229209

```
however its not obvious they need to have variables created first, I can have that setting selected in a new file and it creates both styles and variables, then I have to run it again to get it feed into each other properly
Bad news is, now I can't use the plugin at all for any theming. Neither token sets being applied or theme switching menus works.
```

**Comment by SamIam4Hyma** [comment]
Added to Featurebase Roadmap as a known issue to document and track that might influence beta testing -	[❖💡Create a style powered by a variable ](https://tokensstudio.featurebase.app/p/create-a-style-powered-by-a-variable)

**Comment by UdayHyma** [comment]
Added to Featurebase Roadmap - [❖💡Create a style powered by a variable](https://tokensstudio.featurebase.app/p/create-a-style-powered-by-a-variable)
