### ISSUE TITLE
[2.0]: Styles created with variables, styles seem to be empty in some cases

### ISSUE THREAD

**Issue by six7** [tokens-studio/figma-plugin#2615]
From https://hyma-team.slack.com/archives/C06RHB9RT2B/p1712788294096359

> When writing many styles that should be created with variables referenced setting on, the styles were created, all with empty values.
> selected themes to create styles from, variables not selected to sync at the same time
> Video 1
> In the same file, when I select all themes and variables to be synced at the same time, styles are created and populated with the correct values, but the original "empty value" styles still exist, so I now have duplicate styles
> The styles created do not have variables in their referenced value
> Video 2 and screensho
> If I try to run the plugin for a 3rd time with the same settings (thinking maybe now it will feed the variables into the styles now that both are created) the plugin does nothing and gets hung up in the "creating variables" message at the top of the plugin.
> Figma file attached if you want to investigate/replicate

**Comment by SamIam4Hyma** [comment]
Added to Featurebase Roadmap as a known issue to track that might influence beta testing -	[❖💡Create a style powered by a variable ](https://tokensstudio.featurebase.app/p/create-a-style-powered-by-a-variable)

**Comment by six7** [comment]
Unable to replicate anymore
