### ISSUE TITLE
[2.0]: Export to Figma with sets creates duplicate styles if multiple sets contain same token name

### ISSUE THREAD

**Issue by six7** [tokens-studio/figma-plugin#2616]
When using the Export to Figma option with Token sets to create variables or styles from, we create duplicate styles if multiple sets contain the same name.

To replicate:
- Load the `Preset`
- Click on Styles / Variables Export to Figma
- Check that color styles should be created
- Go to Token Sets, and check all sets (core, light, dark, theme)
- Click Export

Notice that there's multiple `fg.default` styles created, because they exist in both token sets.

Expected: Just one is created

---

From https://hyma-team.slack.com/archives/C06RHB9RT2B/p1712789929844199

> In a similar issue to whats happening with themes, when I export from sets in a new file (load sample set from plugin) and have the "export styles with variables references option selected:
> all styles are duplicated but they have the same values
> sets with themes (tokens with the same name) I assume create duplicates but they should have unique values
> Video 1
> The variables collection has one of the them sets empty

**Comment by SamIam4Hyma** [comment]
Added to Featurebase Roadmap as a known issue in progress of being fixed -	[🚧 ❖❇️ Export styles and variables using sets (free plan) ](https://tokensstudio.featurebase.app/p/export-to-figma-using-token-sets)
