### ISSUE TITLE
[2.0]: Add new sync provider / change to modal

### ISSUE THREAD

**Issue by six7** [tokens-studio/figma-plugin#2623]
```
Add new sync provider options do not show up properly when scrolled to the top, and shows options correctly when scrolled down to the bottom of the settings modal
```

Let's change the `Add new sync provider` dropdown to a modal instead

**Comment by SamIam4Hyma** [comment]
Added to Featurebase Roadmap-	[🪄⚙️ Settings page enhancements](https://tokensstudio.featurebase.app/p/settings-page-enhancements-v2)

**Comment by six7** [comment]
@LukeFinch can you take this on? Is a design-only task and I'd consider it part of polish
