### ISSUE TITLE
font-family fallback does not work

### ISSUE THREAD

**Issue by yanneckb** [tokens-studio/figma-plugin#2632]
Hello,
Im trying to add fallback fonts to my font-family token but it doesn't work. When I add the token value like this:
`"value": "'My Font', 'My Second Font', sans-serif",`
The browser renders it with quotes which wont work: `font-family: "'My Font', 'My Second Font', sans-serif";`

**Comment by six7** [comment]
Have you tried without the single quotes ?

**Comment by yanneckb** [comment]
@six7 wow so simple :D thanks it works now

**Comment by yanneckb** [comment]
@six7 then the value is `font-family: "My Font ,My Font 2, sans-serif";` which also doesn't work

**Comment by LukeFinch** [comment]
@yanneckb You'll need to ensure that you've also properly defined the font-family with an `@font-face`

https://developer.mozilla.org/en-US/docs/Web/CSS/@font-face

**Comment by six7** [comment]
Also you'll want a dedicated transformer that strips away all quotes in style dictionary, even the ones wrapping the full string

**Comment by six7** [comment]
Closing, feel free to reopen if the issue persists
