### ISSUE TITLE
2.0: DTCG icon does not update when switching, requires relaunch

### ISSUE THREAD

**Issue by six7** [tokens-studio/figma-plugin#2643]
RE - DTCG (new) - when switching branches, the icon indicators don't accurately show the format
the only way to get the icons to be correct is to relaunch the plugin
(format appears to be functioning as expected, its just the icons)

https://hyma-team.slack.com/archives/C06RHB9RT2B/p1713048168200149

**Comment by SamIam4Hyma** [comment]
Added to Featurebase Roadmap-	[❇️ W3C - DTCG Specification Alignment](https://tokensstudio.featurebase.app/p/w3c-dtcg-specification-alignment)
