### ISSUE TITLE
DTCG: When not pushing immediately after conversion, buttons are disabled

### ISSUE THREAD

**Issue by six7** [tokens-studio/figma-plugin#2644]
If i don't push from the modal flow right away, theres no way for me to push to github at all (button disabled everywhere). If "recover changes" on plugin load, the push changes button remains disabled.

https://hyma-team.slack.com/archives/C06RHB9RT2B/p1712613962733389

**Comment by SamIam4Hyma** [comment]
Added to Featurebase Roadmap-	[❇️ W3C - DTCG Specification Alignment](https://tokensstudio.featurebase.app/p/w3c-dtcg-specification-alignment)

**Comment by LukeFinch** [comment]
The Push to GitHub button in the footer still works. Not sure what the bug is here?
