### ISSUE TITLE
[2.0]: Rename variables non-functional

### ISSUE THREAD

**Issue by six7** [tokens-studio/figma-plugin#2645]
Trying to rename a token and checking the `Rename variable` option, does not lead to us renaming that variable

To reproduce:
- Create a token and create variables
- Rename that token in the plugin
- Notice how nothing happens

**Comment by SamIam4Hyma** [comment]
Added to Featurebase Roadmap-	[❖ 🪄 Sync variables and styles is now Export to Figma](https://tokensstudio.featurebase.app/p/sync-styles-and-variables-is-now-export-to-figma)
