### ISSUE TITLE
[2.0]: Duplicate variable collections when renaming theme groups and themes

### ISSUE THREAD

**Issue by six7** [tokens-studio/figma-plugin#2649]
Duplicate variable collections on renaming of theme groups and themes :ladybug:

- create variables
- change the name of theme group and or mode
- export to Figma
- Duplicate variables collections are created

Expected: It renames the variable collection (we save the theme id so we should be able to do so)

https://hyma-team.slack.com/archives/C06RHB9RT2B/p1713034153486329

https://github.com/tokens-studio/figma-plugin/assets/4548309/54b33133-f2a2-4183-8a24-190ec1de8751

**Comment by SamIam4Hyma** [comment]
Added to Featurebase Roadmap-	[💚 Theme management enhancements - QOL](https://tokensstudio.featurebase.app/p/theme-management-enhancements-v2)

Added to Featurebase Roadmap-	[❖ 🪄 Sync variables and styles is now Export to Figma](https://tokensstudio.featurebase.app/p/sync-styles-and-variables-is-now-export-to-figma)
