### ISSUE TITLE
[2.0]: Export to Figma based on Token Sets creates variables that have the wrong value

### ISSUE THREAD

**Issue by six7** [tokens-studio/figma-plugin#2651]
When exporting based on token sets we seem to create variables with wrong values

To replicate:
- Load preset
- Go to Export to Figma
- Change options to create color variables
- Choose `Token sets` to make it create variables based on sets
- Select all sets

Notice how it creates collections that all have the same variables with the same values, resulting in 4 collections that have all the same variables

Expected: It creates only the variables that are included in each set, e.g. core just contains colors/gray/100, etc, while light and dark contain the same (with different values) and theme contains variables just part of theme (button.primary.background etc)

https://github.com/tokens-studio/figma-plugin/assets/4548309/b0a93a8e-a463-4289-9bc3-218300086435

**Comment by SamIam4Hyma** [comment]
Added to Featurebase Roadmap-	[🚧 ❖❇️ Export styles and variables using sets (free plan) ](https://tokensstudio.featurebase.app/p/export-to-figma-using-token-sets)
