### ISSUE TITLE
[2.0]: Pulling from remote or restarting plugin causes blue dot to instantly appear

### ISSUE THREAD

**Issue by six7** [tokens-studio/figma-plugin#2652]
Usually when pulling from a remote such as github, after pull there's no unsaved changes. Also, when you performed a fresh pull from github and then restart the plugin. Meaning, the blue dot should not appear. However it seems that in 2.0 the blue dot instantly appears after pulling, causing users to believe that there's changes they can push.

To reproduce
- Have a basic set of tokens
- Push to github
- Restart plugin.

Note that there's unexpected behavior as in a blue dot appearing even though changes are pushed.

This might be related to https://github.com/tokens-studio/figma-plugin/issues/2653

**Comment by cuserox** [comment]
# Initial debugging findings 🔨 

* In `Footer.tsx`, check the value of **hasChanges** (blue badge shows when true) --->  🤖 [Location in code](https://github.com/tokens-studio/figma-plugin/blob/release-139/packages/tokens-studio-for-figma/src/app/components/Footer.tsx#L94) 🤖 
* `hasChanges` comes from **useChangedState.ts** ---> 🤖 [Location in code](https://github.com/tokens-studio/figma-plugin/blob/release-139/packages/tokens-studio-for-figma/src/hooks/useChangedState.ts#L33-L37) 🤖 
* `useChangedState.ts` uses **compareLastSyncedState.ts** ---> 🤖 [Location in code](https://github.com/tokens-studio/figma-plugin/blob/release-139/packages/tokens-studio-for-figma/src/utils/compareLastSyncedState.ts#L23-L26)🤖
*  `isEqual.ts` is responsible for comparing `lastSyncedState` with the local (parsed & formatted) `tokens` 

❓❓❓  Why **isEqual** returning `false` ❓❓❓

## Using `tokens-studio/ds` 
* Set up to sync & pull from `packages/tokens/src`
* Restart the plugin
* Untouched, it shows a blue badge

## Using `cuserox/tokens-studio-gh`

* Set up to sync & pull from `themes`
* Restart the plugin
* Untouched, it does not show a blue badge

**Comment by cuserox** [comment]
# Theory 1

🤔 Plugin is checking for local vs remote changes on _all_ branches, not currently selected one!

Video to test: https://hyma.rewatch.com/video/lnqkbht6niwd125y-2652bluedotpush

**Comment by cuserox** [comment]
🗯 📝 🔁 Added some more `console.log(...)`s - could not find a fix 😓 (CC @robinhoodie0823)

> Branch: [2652-20-pulling-from-remote-or-restarting-plugin-causes-blue-dot-to-instantly-appear](https://github.com/tokens-studio/figma-plugin/commits/2652-20-pulling-from-remote-or-restarting-plugin-causes-blue-dot-to-instantly-appear/packages/tokens-studio-for-figma)
