### ISSUE TITLE
[2.0]: Difference in token ordering in JSON

### ISSUE THREAD

**Issue by six7** [tokens-studio/figma-plugin#2653]
With the work on W3C we introduced a change which seems to cause a different order in tokens of our users. Existing .json files seem to have changed the order of individual keys. Technically not a big issue as this is just relevant to the individual keys (`value, type, description` and so on), but we don't want to be changing user's files without much reason.

Let's look into if we can work around this.

To reproduce:
- On production version of the plugin, push to github
- Open the 2.0 version
- Notice that it immediately shows a blue dot. When you push, it shows changes to token keys

Expected: No change in json, no blue dot, same order of keys as the user had set before.

**Comment by SamIam4Hyma** [comment]
Added to featurebase roadmap - 
[❇️ W3C - DTCG Specification Alignment](https://tokensstudio.featurebase.app/p/w3c-dtcg-specification-alignment)
[🪄 👩‍💻 JSON Enhancements ](https://tokensstudio.featurebase.app/p/json-v2)
