### ISSUE TITLE
[2.0] Delete unused styles & variables

### ISSUE THREAD

**Issue by LukeFinch** [tokens-studio/figma-plugin#2662]
We need an option in the 2.0 build to delete unused variables and styles in the document.

This functionality already exists as part of `Sync Variables/Styles` in pre-2.0 builds.
As 'Remove variables/Styles without connection' 

<img width="387" alt="image" src="https://github.com/tokens-studio/figma-plugin/assets/23120116/bab94f32-f6e0-4b7f-8060-fb2e07617d1e">

We can reuse the code, it just needs to be moved into the Export Styles and Variables modal

**Comment by six7** [comment]
Will be part of 2.0
