### ISSUE TITLE
Support horizontal and vertical gap when autolayout wraps

### ISSUE THREAD

**Issue by LukeFinch** [tokens-studio/figma-plugin#2669]
**Is your feature request related to a problem? Please describe.**

When using auto layout with wrap behaviour. It's possible to have different values for horizontal and vertical gap.
However we do not support this today

**Describe the solution you'd like**

Support both axes

**Describe alternatives you've considered**

**Additional context**

We may want to consider this as part of more layout options.
If we had a layout behaviour token, to control the direction, we could then conditionally handle the gap behaviour.

Setting a generic gap works when users toggle between vertical or horizontal layouts.
When they change to a wrapping layout, we need two gaps, which are direction specific.

Might be worth us interviewing users on how they'd expect this to be handled

**Comment by SamIam4Hyma** [comment]
@LukeFinch this is in a featurebase request already so I've migrated this over https://tokensstudio.featurebase.app/p/expand-token-types
