### ISSUE TITLE
2.2: Token Editing experience

### ISSUE THREAD

**Issue by six7** [tokens-studio/figma-plugin#2679]
With this release we're focused on

- New token types
  - Gradient tokens
  - Multiple fills
  - Motion token types
  - Auto Layout support
- Improved component token creation

Related issues:
- https://github.com/tokens-studio/figma-plugin/issues/858
- https://github.com/tokens-studio/figma-plugin/issues/152
- https://github.com/tokens-studio/figma-plugin/issues/613

**Comment by SamIam4Hyma** [comment]
@six7 here are the current posts in Featurebase for consideration with the epic planning. 

- [💡 Expand token types](https://tokensstudio.featurebase.app/p/expand-token-types)
- [🪙 ➕ Support multiple tokens per layer of the same type](https://tokensstudio.featurebase.app/p/multiple-token-per-layer)
- [🎨 Expand gradient color support](https://tokensstudio.featurebase.app/p/add-gradient-token-type-and-expand-functionality-past-linear)
- [🌈 🎨 Gradient styles from variables ](https://tokensstudio.featurebase.app/p/gradient-style-with-variables)

**Comment by SamIam4Hyma** [comment]
@six7 V2.2 has passed and all these issues are in featurebase so you can close this if you'd like
