### ISSUE TITLE
2.3: Designing with tokens

### ISSUE THREAD

**Issue by six7** [tokens-studio/figma-plugin#2680]
This release will be all about

- Improving the way users can apply tokens and design with them
- Parameter based UI to apply tokens
- Read-only way of using the plugin
- Copy and paste applied tokens
- Improved annotations

**Comment by SamIam4Hyma** [comment]
@six7 Here are a list of current featurebase posts related to this epic for your consideration 

- [ 🌜🌞 Theme Switcher for non-DS designers](https://tokensstudio.featurebase.app/p/theme-switcher-for-non-ds-designers) 
- [🤓 Document and annotate design token enhancements](https://tokensstudio.featurebase.app/p/documentation-and-annotate)
- [🪙 ➕ Apply token workflow enhancements](https://tokensstudio.featurebase.app/p/apply-token-workflow-enhancements)
- [💔 Tokens applied as variables or styles are Fragile](https://tokensstudio.featurebase.app/p/tokens-applied-as-variables-or-styles-are-fragile)
