### ISSUE TITLE
[2.0]: launch darkly flags are inactive unless I go to Settings tab

### ISSUE THREAD

**Issue by six7** [tokens-studio/figma-plugin#2681]
We had this problem before and seems to have come back.

If I open the plugin with a PRO subscription it shows as Not PRO until I click on the Settings tab.

https://github.com/tokens-studio/figma-plugin/assets/4548309/5b68b122-450e-4952-8367-a84a59e79745

**Comment by SamIam4Hyma** [comment]
@six7 FYI when I remove my licence key from the plugin, close the plugin, then add my licence key, it resets to expected behaviour.
