### ISSUE TITLE
Token tranform does not work with deeply nested folder structures

### ISSUE THREAD

**Issue by joonass-visma** [tokens-studio/figma-plugin#2684]
**Describe the bug**
Token tranform does not work with deeply nested folder structures.

**To Reproduce**
1. Create following folder structure `tokens/primitive/color/default.json`. json-file can have any valid content.
2. Run `npx token-transformer tokens out.json primitive/color/default`
3. `out.json` is created but contains just empty object `{}`

**Expected behavior**
Tranform should produce json-file containing the tokens from given sets, no matter how deep the folder structure is.

**Comment by six7** [comment]
I'd recommend to not use token-transformer anymore but switch over to Style dictionary's version 4. We're announcing deprecation notices on token-transformer once v4 is released (the prerelease is already very usable!)

https://v4.styledictionary.com/version-4/migration/
