### ISSUE TITLE
Token value field should grow in height

### ISSUE THREAD

**Issue by six7** [tokens-studio/figma-plugin#2721]
If users try to enter something like a long linear-gradient value and the value goes quite wide, the text input currently is not big enough to make sense of anything. Let's find a way where the input grows in height when users enter more.

We need to watch out for the prepending and appending button to the left so that those are still displayed correctly (likely vertical alignment top)

https://github.com/tokens-studio/figma-plugin/assets/4548309/886d07c0-e4be-467c-8c34-570cb37429e8

**Comment by keeganedwin** [comment]
- Also related to #2006 
- This issue is also present with referencing certain tokens in the Composition type: sizing, height, wdith.
