### ISSUE TITLE
Create Variable Collections With The Plugin's Order

### ISSUE THREAD

**Issue by keeganedwin** [tokens-studio/figma-plugin#2736]
**Is your feature request related to a problem? Please describe.**
If you currently have the theme-groups Core, Colors and Brand setup in this order in the
plugin, when you create variables the theme-groups which are translated to collections
are instead create in alphabetical order: Brand, Colors and Core.

**Describe the solution you'd like**
Collections should be created according to the order setup in the plugin as this change in
order confuses users when using going through variable collections.

**Additional context**
![CleanShot 2024-05-07 at 16 24 51@2x](https://github.com/tokens-studio/figma-plugin/assets/93133012/a9f2943b-71c2-4374-8d1c-eadd5fb9697a)

**Comment by keeganedwin** [comment]
Migrated to [Featurebase](https://tokensstudio.featurebase.app/p/tokens-applied-as-variables-or-styles-are-fragile)

**Comment by six7** [comment]
Closing this due to this being Figma behavior. Even if collections are created manually, Figma automatically orders the collections so that they're sorted alphabetically.
