### ISSUE TITLE
Duplicating Token Group Has The Loading Bar Stuck Indefinitely

### ISSUE THREAD

**Issue by keeganedwin** [tokens-studio/figma-plugin#2751]
**Describe the bug**
Duplicating a token group keeps the loading bar on the UI stuck indefinitely. 

**To Reproduce**
1. Create a Token Group
2. Duplicate the Token Group
3. See error

**Expected behavior**
This behaviour only seems to be present in Beta V2-rc5 and not Prod 1.38.9. The loading bar shouldn't get stuck indefinitely.

**Figma file:**
[File](https://www.figma.com/design/ewjwfKm0zgGrqEzeLe3vbQ/Untitled-(Copy)?node-id=2002-3&t=58fI7kBtilAiwAPj-4)

**Screenshots or Screencasts**
https://github.com/tokens-studio/figma-plugin/assets/93133012/b73554ea-f6e1-4ff9-bd92-31fcf0448ca0

**Comment by six7** [comment]
Fixed in https://github.com/tokens-studio/figma-plugin/pull/2767
