### ISSUE TITLE
[2.0] Document the logic behind 'Export to Figma' screen

### ISSUE THREAD

**Issue by cuserox** [tokens-studio/figma-plugin#2752]
# Context 📚 

The '**Export to Figma**' screen has a bunch of options, not always clear to users how they should be used or what they do.

<img width=300 src='https://github.com/tokens-studio/figma-plugin/assets/114073780/800870be-f2f1-4387-9b44-c4764edd1833' />

# Acceptance Criteria 🛠 
* For every toggle / tickbox, explain what the options do by listing
   * Relevant services, components, etc in the code to refer to
   * Overview of how these manipulate the data it outputs

**Comment by cuserox** [comment]
Created a board with screenshots and high level flows of what the "Export to Figma" modal does.

@SamIam4Hyma hope it helps and it can serve as a base for guides to document 📖 

Editable by anyone 📝 [**here**](https://www.figma.com/board/ujQoQbbFPyqmpTRDRs753t/Export-To-Figma-Options-Logic?node-id=0%3A1&t=qdi4cHNXP60eFH2u-1) 📝  

`TODO`s
*  🔴 Red stickies 🔴 are things missing that I could not figure out by myself
* Information might be misleading or inaccurate, to be verified by others

**Comment by six7** [comment]
I think this is great! Added some comments.

@SamIam4Hyma do you want to be the one approving this / declaring this as good enough so that we can close this issue / add comments on what might still be missing?

**Comment by cuserox** [comment]
Thanks for the comments on the shared [FigJam](https://www.figma.com/board/ujQoQbbFPyqmpTRDRs753t/Export-To-Figma-Options-Logic?node-id=0%3A1&t=Bk7z4ovKScKyorIM-1)! 📝 

Marking this as done and [linking it with its documentation task counterpart](https://github.com/tokens-studio/plugin-docs/issues/136#issue-2253187647), to carry on expanding this as a workflow document in its own file.
