### ISSUE TITLE
Debug mode not working / Session recording

### ISSUE THREAD

**Issue by six7** [tokens-studio/figma-plugin#2772]
It seems like right now Session recording doesnt work:

Might be related to React 18, websockets?

(this should show the id of the session being recorded)

![Image](https://github.com/tokens-studio/figma-plugin/assets/4548309/0fbbd3ad-9074-4cc7-92b6-190ad8d02d40)

**Comment by cuserox** [comment]
🧐 #### Initial investigation
* Seems that [setupReplay()](https://github.com/tokens-studio/figma-plugin/blob/release-139/packages/tokens-studio-for-figma/src/app/sentry.ts#L18-L27) is no longer supported
* Looking into migrating from 7.x to 8.x: https://docs.sentry.io/platforms/javascript/migration/v7-to-v8/v7-deprecations/#deprecate-class-based-integrations

**Comment by cuserox** [comment]
☝️ Ignore above, migration will happen in the FX epic. For Replay to work we are [covering the minimum requirements of the SDK to be >7.27.0](https://figma-tokens.sentry.io/replays/?project=5220409&statsPeriod=14d) (we are on "@sentry/react": "^7.53.1")
