### ISSUE TITLE
Expand / collapse of token sets causes weird UI issues

### ISSUE THREAD

**Issue by six7** [tokens-studio/figma-plugin#2780]
When your token sets share the name with token folders, and you expand/collapse token folders, the UI will act weird.

To reproduce:
- Create a set called `core/foo`
- Another one called `light/foo`
- Another one called `core`
- Another one called `light`

https://github.com/tokens-studio/figma-plugin/assets/4548309/535971bd-0c41-4887-8f24-f703f26cfc8b

**Comment by SamIam4Hyma** [comment]
Closing as this was fixed in another issue
