### ISSUE TITLE
Theme reference falsely take theme reference of prior themes into account

### ISSUE THREAD

**Issue by six7** [tokens-studio/figma-plugin#2798]
When a user has multiple themes that contain the same token name (e.g. to avoid Figma's 4 mode limit), and they try to create only one of those, we are using the wrong reference.

To reproduce:

- Create 4 token sets like this:

```
CoreA
CoreB
SemanticA
SemanticB
```

- create 2 themes:

```
A with active token sets CoreA + SemanticA
B with active token sets CoreB + SemanticB
```

Then go ahead and create variables one theme after another (with *just* the theme selected)

The result is that B has a reference to A, even though it has a local variable for that theme that should be used)

https://github.com/tokens-studio/figma-plugin/assets/4548309/36f7f4ac-24e5-44a9-8f73-93e66925550c

**Comment by SamIam4Hyma** [comment]
Looks like this issue should be closed based on items linked by Jan but its still open. @cuserox can you take a look and close/merge?
