### ISSUE TITLE
[Question] Github Sync provider: local or shared ?

### ISSUE THREAD

**Issue by gueetch** [tokens-studio/figma-plugin#2801]
Hey 👋 

I'm currently investigating this plugin as requested internally, more specifically the Github Sync feature.

Based on the documentation: https://docs.tokens.studio/sync/github
It's not clear to me if the token is shared (synced through Figma to other users of the plugin in my workspace/project) or if it stays local. May I ask you to confirm how it works ?

I'm asking to know if I need to setup a Github token from a service account (token shared), or request users to generate it from their accounts.

Also, might worth adding a note on the documentation about it.

Truely appreciated.
Thanks 🙏

**Comment by SamIam4Hyma** [comment]
Hi @gueetch 👋 Are you able to join our community slack where we can better support you with answering all sorts of questions and connecting you with the right people? I assume as you dig into your assessment you'll have more questions. (: 

https://tokens.studio/slack

**Comment by gueetch** [comment]
The answer I got
> You would want users to generate it from their accounts (personal access token) as this is a way to verify the user that is gaining access to the repository.

Thanks !
