### ISSUE TITLE
2.0: Empty modify being saved to JSON

### ISSUE THREAD

**Issue by six7** [tokens-studio/figma-plugin#2805]
Some users reported seeing empty `modify` values in their JSON. This seems to happen randomly during duplication, or other scenarios. My guess is this is related to the [duplicate group issue](https://github.com/tokens-studio/figma-plugin/issues/2779) that we had.

In any way, we should clear the `modify` just like we clear it if the `studio.tokens` or `$extensions` field is empty.

To reproduce

- Go to JSON view
- Paste this JSON
```
{
 "blue": {
    "value": "#ff0000",
    "type": "color",
    "$extensions": {
      "studio.tokens": {}
    }
  },
  "red": {
    "value": "#ff0000",
    "type": "color",
    "$extensions": {
      "studio.tokens": {
        "modify": {}
      }
    }
  },
 "valid": {
    "value": "#ff0000",
    "type": "color",
    "$extensions": {
      "studio.tokens": {
        "modify": {
          "type": "darken",
          "space": "srgb",
          "value": "0.5"
        }
      }
    }
  }
}
```
- Notice that the "red" one keeps the empty modify.
- Notice that the "blue" one correctly removes the empty extensions / studio.extensions field

Expected:
In this example only the "valid" token which has a non-empty modify piece is being kept, the rest should be removed, so the expected output would be

```
{
 "blue": {
    "value": "#ff0000",
    "type": "color"
  },
  "red": {
    "value": "#ff0000",
    "type": "color"
  },
 "valid": {
    "value": "#ff0000",
    "type": "color",
    "$extensions": {
      "studio.tokens": {
        "modify": {
          "type": "darken",
          "space": "srgb",
          "value": "0.5"
        }
      }
    }
  }
}
```

**Comment by chriskerr-performio** [comment]
Just for some extra info on the experience with this bug

This is occurring across all token types. It occurs when I edit the name of a token and then rename variables as I save it. Attached are a few videos of the same issue across a view different token types

The result is the Figma cannot understand the value being passed and so it does not update the value.

To resolve it, i have to go into the JSON and remove any instances of this extension.

Reasonably frustrating one to my workflow, any idea when this will be resolved?

Thanks! 🙏 

https://github.com/tokens-studio/figma-plugin/assets/100885654/12460aa8-0942-4212-bcae-0d8e0778d54e

https://github.com/tokens-studio/figma-plugin/assets/100885654/f0532332-0de2-43c3-a4cf-76f2281f23e3

https://github.com/tokens-studio/figma-plugin/assets/100885654/676e487e-fd0b-4998-8343-e47e49794914

https://github.com/tokens-studio/figma-plugin/assets/100885654/36ce5067-a5a1-49ae-84ec-305dad223b03
