### ISSUE TITLE
2.0: Add explainer text to Apply to menu

### ISSUE THREAD

**Issue by six7** [tokens-studio/figma-plugin#2814]
Let's bring back the explainer text to the apply to menu.

Let's also add one for the new apply as variables or raw values options.

```
Apply as 
Variables & styles:
If a token is connected to a variable or style will try to apply that

Raw values
Always apply as raw values
```

Prior:

![Image](https://github.com/tokens-studio/figma-plugin/assets/4548309/1333cca8-67d9-42a6-9ec5-06af4f9069c4)

New:

![Image](https://github.com/tokens-studio/figma-plugin/assets/4548309/f86cb9a7-c4fa-488c-982c-fe6c428c8324)

**Comment by SamIam4Hyma** [comment]
@six7 pretty sure the label should say "apply resolved value" as the "raw value" is whatever is entered and would show the references, math, etc. This might get confusing if we introduce this with the wrong label.
