### ISSUE TITLE
React DnD not working in BoxShadow Input

### ISSUE THREAD

**Issue by LukeFinch** [tokens-studio/figma-plugin#2832]
**Describe the bug**

When trying to rearrange the shadow order in a box-shadow token, the Drag-n-Drop handles not behaving as expected.
This was likely introduced when upgrading to React18 - there's a TODO item to check the logic.

**To Reproduce**
1. Create a box shadow token
2. Add another shadow
3. Use the drag handle 'click to drag'
4. Rearranging does not happen

**Expected behavior**
When dragging shadows around - they should rearrange

**Screenshots or Screencasts**

**Figma file (optional)**
Send us the link to a Figma file containing a reproducible example

**JSON (optional)**
If possible, attach the JSON that leads to this bug.

**Comment by akshay-gupta7** [comment]
Unable to reproduce this. Working as expected
CC: @keeganedwin
