### ISSUE TITLE
Dropdown menu dot selection shows as misaligned

### ISSUE THREAD

**Issue by cuserox** [tokens-studio/figma-plugin#2851]
**Describe the bug**
Dropdown menu shows the dots / ticks / icon misaligned for a user. Original thread 👉 [here](https://tokens-studio.slack.com/archives/C073SSG7DC7/p1717503797330239).

DropdownMenu uses Radix, this doesn't have [any open issues](https://github.com/radix-ui/primitives/issues?q=is%3Aissue+is%3Aopen+dropdown) related to it. Unable to reproduce locally _but_ found that `display: flow` is causing this on the **RadioItem** component ([explanation here](https://tokens-studio.slack.com/archives/C073SSG7DC7/p1718115078974019?thread_ts=1717503797.330239&cid=C073SSG7DC7)).

Potential solution, add a global CSS fix for the specific browser?

**To Reproduce**
1. Open the plugin
2. Open any dropdown with icons (i.e. 'Apply to...')
3. See misalignment

**Expected behavior**
Icons should be aligned. 

**Screenshots or Screencasts**
![Image](https://github.com/tokens-studio/figma-plugin/assets/114073780/933622ce-001a-4c67-803a-31d381f2cf78)

**Comment by six7** [comment]
This likely comes from the DS where the DropdownMenu Item doesnt have position relative but the icon slots are using position absolute?

github.com/tokens-studio/ds

**Comment by six7** [comment]
Note that I am unable to reproduce this one
