### ISSUE TITLE
Tokens referencing the same are showing a different value

### ISSUE THREAD

**Issue by cuserox** [tokens-studio/figma-plugin#2852]
**Describe the bug**
[Original thread](https://hyma-team.slack.com/archives/C06RHB9RT2B/p1718225540993229) 📝 Any changes made to tokens are persisting with the original value.

**To Reproduce**
1. Create 2 tokens with the same name and different values across sets
2. Try to use one of the tokens
3. See how the value applied does not match

**Expected behavior**
Token values should not override others across sets

**Screenshots or Screencasts**

#### Initial report
https://github.com/tokens-studio/figma-plugin/assets/114073780/12719d19-4335-4817-86ed-ee4bd170a300

#### 2nd try
Duplicating to a new token set does not fix it
https://github.com/tokens-studio/figma-plugin/assets/114073780/e2b413ee-c887-4345-a69f-d02317824706

#### 3rd try (+ explanation)
https://hyma-team.slack.com/archives/C06RHB9RT2B/p1718228603075099?thread_ts=1718225540.993229&cid=C06RHB9RT2B

**Comment by SamIam4Hyma** [comment]
not able to reproduce in v2.2
