### ISSUE TITLE
When on local document storage and then trying to push to git, modal says `Push to local`

### ISSUE THREAD

**Issue by six7** [tokens-studio/figma-plugin#2858]
In `packages/tokens-studio-for-figma/src/app/components/PushDialog.tsx` we seem to be using the wrong storagetype - it seems to use the currently *active* one, not the one youre about to push to.

The dialog says `Push to local` even though i'm pushing to git.

likely on line 116
```
          title={t('pushTo', { provider: transformProviderName(storageType.provider) })}
```
storageType is the wrong provider to use and we'd rather need to use localApiState.provider

![Image](https://github.com/user-attachments/assets/b18ae268-0361-4e1f-ad2b-f68505a93464)

**Comment by NuthanHyma** [comment]
@six7  @SamIam4Hyma 
this is not reproducible in` V 2.2.2`
	•	Added tokens to a local file and connected it to Git (tested with GitLab and GitHub).
	•	Pushed the changes.
	•	Noticed it shows “push changes” instead of “push to local”.
	•	Seems like the issue is resolved now.
