### ISSUE TITLE
Typography > Stylistic Sets

### ISSUE THREAD

**Issue by robinscholz** [tokens-studio/figma-plugin#2867]
**Is your feature request related to a problem? Please describe.**
As far as I am aware, there is currently no real way to tokenise font feature settings. We are looking into a simple workaround for stylistic sets using a `text` token, but ideally this should be possibly within `typography`

**Describe the solution you'd like**
I think what would work is a simple comma seperated list under the key `Stylistic Sets` within the `typography` object. This would cover at least quite a few use cases and would be easily transformed into custom css with Style Dictionary!

**Comment by SamIam4Hyma** [comment]
Hi @robinscholz we have a new request and upvoting tool! Do you want to add your request there so you can track its progress? Otherwise I can do it for you (: 

https://feedback.tokens.studio/
