### ISSUE TITLE
Creating Variables Color-Modifiers Creates Blank Variables

### ISSUE THREAD

**Issue by keeganedwin** [tokens-studio/figma-plugin#2873]
**Describe the bug**
This seems like an old bug again where creating variables with color-modifiers results in blank variables; this was tested in rc7. The bug is also quite inconsistent as it sometimes works and sometimes doesn't. The user however has checked the test file shared below and confirms that it is the issue they are facing.

Older Related Issues:
1. #2407 
2. #2139
3. #2059 
4. #2012 

**To Reproduce**
Steps to reproduce the behavior - available in test file.

**Expected behavior**
No matter what reference is being used and no matter the color space, variables should created with as expected with the calculated values. 

**Screenshots or Screencasts**
https://github.com/tokens-studio/figma-plugin/assets/93133012/c0ea1d5d-173b-42aa-844f-35319b394fb1

**Figma file (optional)**
[Test File](https://www.figma.com/design/u3Lyr9uTHVx8yiU77AdlR3/Simon-issue?node-id=15-2&t=7hf6Ycge3HLfkXzE-4)

**Comment by robinhoodie0823** [comment]
The issue was the mis-configuration of themes and not from code. Confirmed by the user.
