### ISSUE TITLE
Errors when applying typography related tokens to nodes

### ISSUE THREAD

**Issue by cuserox** [tokens-studio/figma-plugin#2901]
**Describe the bug**
Given a set of tokens, and applying these to a component, there are errors at times with typography tokens.

**To Reproduce**
1. Have a token set using asynchronous loaded typography
2. Apply to a few components
3. See error in the console

**Expected behavior**
Ability to load the font and apply typography styles as expected

**Screenshots or Screencasts**
After applying tokens on a node:
![Image](https://github.com/tokens-studio/figma-plugin/assets/114073780/8f521b08-c5ae-4f3a-9c86-080270eaf41f)

**Comment by robinhoodie0823** [comment]
This issue is not able to be reproduced. Seems it has been fixed in the latest figma updates. So close the issue right now.
