### ISSUE TITLE
Unable to Login to Second-Screen

### ISSUE THREAD

**Issue by keeganedwin** [tokens-studio/figma-plugin#2903]
**Describe the bug**
Trying to login to the second-screen in `rc8` does not work.

**To Reproduce**
Steps to reproduce the behavior - just try to login with your credentials. 

**Expected behaviour:**
Not sure if we do have error messages thrown in `rc8`, but it would be great to have some error messages indicated the exact issue with login credentials. The only error currently displayed in `38.9` seems to be "_Invalid login credentials_"

**Screenshots or Screencasts**
https://github.com/tokens-studio/figma-plugin/assets/93133012/06dfbee3-6b28-4376-80db-a52cbc60392c

**Comment by six7** [comment]
Confirming this is a .env related issue as well

**Comment by six7** [comment]
Closing, this has been a .env related issue - confirming it works for internal RC9
