### ISSUE TITLE
Surface the number of variables linked

### ISSUE THREAD

**Issue by cuserox** [tokens-studio/figma-plugin#2925]
**Is your feature request related to a problem? Please describe.**
When someone exports themes to Figma, we currently display the number of created variables and collections. It would be helpful to show the number that have been linked / attached instead of 'No Variables Created', which is what shows as the variables were already there, but were somehow unlinked.

<img src='https://github.com/tokens-studio/figma-plugin/assets/114073780/b13bdf46-b9c1-4c6a-9bd3-ff02324fdb45' width=300 />

Another community request: https://tokens-studio.slack.com/archives/C073SSG7DC7/p1719923126230879?thread_ts=1719921281.457329&cid=C073SSG7DC7

**Describe the solution you'd like**
Given I have variables in Figma
If these become unlinked
And I re-export them again
I expect a toast to tell me that they're been re-linked, with the correct count 

**Describe alternatives you've considered**
N/A

**Additional context**
Work can be carried on from fixing the variables & collections counter: https://github.com/tokens-studio/figma-plugin/issues/2838. Suggested by the community [here](https://tokens-studio.slack.com/archives/C073SSG7DC7/p1719344890571949).

**Comment by SamIam4Hyma** [comment]
This issue is in [Featurebase for future prioritization](https://feedback.tokens.studio/p/theme-management-enhancements)
