### ISSUE TITLE
Opacity type tokens do not create variables

### ISSUE THREAD

**Issue by regoremor** [tokens-studio/figma-plugin#2928]
**Describe the bug**
I am trying to create Figma variables from the Tokens Studio and the "opacity" type tokens do not create variables.

**Screenshots or Screencasts**
<img width="403" alt="Screenshot 2024-06-27 at 8 00 39 PM" src="https://github.com/tokens-studio/figma-plugin/assets/9708927/e10fb3c6-bff4-4db3-ab01-9cd14c2aa30a">

**JSON (optional)**
`{
  "opacity": {
    "0": {
      "value": "0",
      "type": "opacity",
      "description": "Opacity 0"
    },
    "10": {
      "value": "0.1",
      "type": "opacity",
      "description": "Opacity 10%"
    },
    "20": {
      "value": "0.2",
      "type": "opacity",
      "description": "Opacity 20%"
    },
    "30": {
      "value": "0.3",
      "type": "opacity",
      "description": "Opacity 30%"
    },
    "40": {
      "value": "0.4",
      "type": "opacity",
      "description": "Opacity 40%"
    },
    "50": {
      "value": "0.5",
      "type": "opacity",
      "description": "Opacity 50%"
    },
    "60": {
      "value": "0.6",
      "type": "opacity",
      "description": "Opacity 60%"
    },
    "70": {
      "value": "0.7",
      "type": "opacity",
      "description": "Opacity 70%"
    },
    "80": {
      "value": "0.8",
      "type": "opacity",
      "description": "Opacity 80%"
    },
    "90": {
      "value": "0.9",
      "type": "opacity",
      "description": "Opacity 90%"
    },
    "100": {
      "value": "1",
      "type": "opacity",
      "description": "Opacity 100%"
    }
  }
}`

**Comment by six7** [comment]
This is already fixed in the 2.0 beta which is open for the public to test - join us in Slack on `#_beta-v2-open`

**Comment by regoremor** [comment]
Hi @six7 thanks for your answer. How do I test the 2.0 version?
