### ISSUE TITLE
Strange behaviour Math in Composition tokens.

### ISSUE THREAD

**Issue by rbosker** [tokens-studio/figma-plugin#2960]
**Describe the bug**
Some math operations doesn't work properly in Composition tokens in Beta rc8 release. In the current 1.38.9 version, everything does work properly.

**To Reproduce**
Please check the screen recording (with audio) for the explanation. 
Math examples that does work:
- {reference1}*{reference2}
- {reference1}*2

Math examples that don't work:
- 10+10
- ({reference1}*{reference2))*2
- ({reference1}+10)*2

**Note**
The same behaviour does seem to work in Typography tokens.

**Screenshots or Screencasts**

https://github.com/tokens-studio/figma-plugin/assets/109062656/6ea070ba-5be2-44d9-8122-200ec858268a

**Comment by six7** [comment]
Closing as fixed in RC10
