### ISSUE TITLE
Rem value not calculating properly

### ISSUE THREAD

**Issue by robinhoodie0823** [tokens-studio/figma-plugin#2961]
**Describe the bug**
RE Rem value not calculating properly.

The preview is showing differently, it seems it does not rely on rem setting.

**Expected behavior**
The preview value must be correct based on rem setting.

**Screenshots or Screencasts**
[screenshot](https://hyma-team.slack.com/archives/C06RHB9RT2B/p1720053806553829)

**Comment by SamIam4Hyma** [comment]
closing this ticket as I can't reproduce this in RC9 or 10
