### ISSUE TITLE
Using Opacity in Tokens Creates Blank Variable [2]

### ISSUE THREAD

**Issue by keeganedwin** [tokens-studio/figma-plugin#2977]
**Describe the bug**
This is a recurring bug that has been reported previously in:
1. #2549 
2. #2015 

When you create a variable of a token that's using the alpha operation as a color modifier, it creates a blank #ffffff variable.

**To Reproduce**
1. Create a color token also using an opacity token as reference
2. Create variables
3. See error
4. Go back to the the token
5. Edit token
6. Click on Save
7. Error is resolved - variable is updated

**Expected behavior**
The user should not have to edit the token and then save it for it to update the variable to its correct value

**Screenshots or Screencasts**
[Recording](https://github.com/tokens-studio/figma-plugin/assets/93133012/77ab5c7c-440a-4f28-b6de-46266031225a)

**JSON (optional)**
Reach out to me for token-set

**Comment by tokendan** [comment]
@keeganedwin Any update on this bug? it's giving me some grief, and I'm blocked on a major multi-brand (Pizza Hut, KFC and TacoBell) theming project

**Comment by keeganedwin** [comment]
@tokendan will look into it and get back to you!

**Comment by SamIam4Hyma** [comment]
@six7 thinking this could be related to my comment in https://github.com/tokens-studio/figma-plugin/issues/1822. If we don't mix the opacity tokens with color tokens, we seem to have more consistent results.

**Comment by SamIam4Hyma** [comment]
@tokendan I have a feeling this is because our Opacity tokens are connected to Figma's layer opacity/transparency and not intended to be a part of a color variable which needs to be resolved. 

A workaround could be to convert the tokens you are using in color tokens to a `number token` and see if that resolves the problem.

**Comment by tokendan** [comment]
Thanks both, at least for now the bug has been broadly addressed with the rc9 release. My opacities aren't showing as white anymore.

**Comment by keeganedwin** [comment]
Closing this ticket as it's fixed.
