### ISSUE TITLE
Pull from Github indicator remains ON when pull was successful

### ISSUE THREAD

**Issue by robinhoodie0823** [tokens-studio/figma-plugin#2984]
**Describe the bug**
After pulled from Github, did not get any confirmation that the pull was successful. The indicator persisted.
Even the pull was successful and themes and tokens were visible in the themes config (so the pull was successful).
Pulled several more times to see if the indicator would clear, it did not.
Restarting the plugin cleared the indicator. Originally from [here](https://hyma-team.slack.com/archives/C06RHB9RT2B/p1720554231904009).

**Expected**
The pull indicator should be off after pull was successful.

**Comment by cuserox** [comment]
@SamIam4Hyma this is now merged into the V2 brach!
