### ISSUE TITLE
Introduce `duration` token type

### ISSUE THREAD

**Issue by derekluciani** [tokens-studio/figma-plugin#299]
### Description
Add support for duration tokens.
Properties+example: https://second-editors-draft.tr.designtokens.org/format/#duration

### Background
```
type: 'duration',
label: 'Duration',
appliedToken: 'duration',
value: The value MUST be a string containing a number (either integer or floating-point) followed by an "ms" unit
```

### Applying
Applying this token would influence the `node.reactions[].action.transition.duration` property of all reactions. If there is no reaction on a layer, don't do anything.
Links to Figma API:
https://www.figma.com/plugin-docs/api/Reaction
https://www.figma.com/plugin-docs/api/FrameNode#reaction-prototyping-related-properties
https://www.figma.com/plugin-docs/api/Transition

**Comment by six7** [comment]
We don't have the duration type yet, but we should definitely add it! I think we can customize the easings of prototype interactions with the plugin now, so this is a perfect case for tokens!

**Comment by jamesrdavis** [comment]
Do you plan to add both duration and timing/easing tokens?

**Comment by six7** [comment]
Yes, we do! We plan on adding new token types in the coming months, motion being one of them!

**Comment by LukeFinch** [comment]
This request has been moved to our new feedback tool. Go check out https://tokensstudio.featurebase.app/ to create a free account. You can upvote and comment on existing posts, make a new request, and subscribe to be notified when requests move into our roadmap.

**Comment by UdayHyma** [comment]
Added to Featurebase Roadmap : [🪙 Expand token types](https://tokensstudio.featurebase.app/p/expand-token-types)
