### ISSUE TITLE
Styling is removed from nodes when there are broken references and using a non local provider

### ISSUE THREAD

**Issue by cuserox** [tokens-studio/figma-plugin#2991]
# Context 📝 

👀 [Original thread](https://hyma-team.slack.com/archives/C06RHB9RT2B/p1720556205762459)

🎨 Figma files to aid testing: https://www.figma.com/files/team/1048274382449167570/project/250987771/theme-testing?fuid=1268569349009769980

Do the same steps in:
- [File 1 - control with local variables](https://www.figma.com/design/zW7VuydWO0XqoQjQ7864s7/Template-Radix-components-themes-safety-copy?node-id=4093-12643&t=izK5soib7jRi5Sqj-1)
- [File 5 - test with non local variables](https://www.figma.com/design/0os11bKtfVvjBtB511svH4/TEST-5COMPONENT-LIB-NLV-RADIX-safety-copy?node-id=4093-12643&t=Su2fdjzHu5OjK7Tk-1)

1. Open the plugin
2. Make sure it's set to "Apply to page" 
3. Turn on the themes: components (all), primitives (all), mode (dark), brand (tokens), density (default), surface (default), text-styling (default)

#### File 1 - control
* Provider: local 
* Apply styles, theme switch between dark & light, all styles get applied to the relevant nodes

#### File 5 - test
* Provider: remote (GH owned by @SamIam4Hyma https://github.com/tokens-studio/non-local-test)
* Apply styles, some node missbehave, specifically **typography** where a lot of the values are set to **0**
<img width="150" alt="Screenshot 2024-07-12 at 15 34 51" src="https://github.com/user-attachments/assets/6b102ed2-f637-49d7-b2e4-08d8fd75308d">

See text 'disappeared'
<img width="250" alt="Screenshot 2024-07-12 at 15 19 09" src="https://github.com/user-attachments/assets/58361165-3c16-4017-b1f8-5f65edbd1682">

# Acceptance Criteria 🔧 
* Styling should not be break node styling

**Comment by cuserox** [comment]
### Initial investigations 🐣

⚠️ WIP branch: `fix/2991-persist-styles-on-nodes`

#### Testing setup
* [Figma file here](https://www.figma.com/design/G32KrwCvLU1Mq77FDXrIoq/Testing-NLV?node-id=2002-19842&t=HmgzLdEzry100coM-1) 🎨 
* Switch between **local** & **remote** (GH owned by @SamIam4Hyma https://github.com/tokens-studio/non-local-test), ensure to apply styles
* See lots of `Calling setBoundVariable with a variable id is deprecated. Please pass the variable node instead.` errors
   * Fix to remove warnings in above branch

#### Continued ⏳ 
Investigating how the styles are applied on local vs remote, for example `actions.button.default.typography` on the **label** for [button/success-tier2](https://www.figma.com/design/G32KrwCvLU1Mq77FDXrIoq/Testing-NLV?node-id=2002-19842&t=HmgzLdEzry100coM-1)
<img width="67" alt="Screenshot 2024-07-12 at 16 53 52" src="https://github.com/user-attachments/assets/5387cf60-f9ce-4ad5-8e1f-0ef9a6597717">

The token: `actions.button.default.typography` uses `{theme.text-style.actions.label.default}`
<img width="226" alt="Screenshot 2024-07-12 at 17 00 25" src="https://github.com/user-attachments/assets/2ae2d175-7020-4c3a-b3f5-c5939d15f6f0">
Which then uses `{brand-typography.p2.default}`
<img width="179" alt="Screenshot 2024-07-12 at 17 01 35" src="https://github.com/user-attachments/assets/75b4ded1-3fed-4d02-a5c7-66f974878cee">
This token then uses references to `{brand.*}` values
<img width="250" alt="Screenshot 2024-07-12 at 17 02 46" src="https://github.com/user-attachments/assets/12fe3329-4d09-45c1-91e2-4c268b0625b3">

These all seem to be resolving correctly 🧐 🤷‍♀️

**Comment by SamIam4Hyma** [comment]
@cuserox lets set up some time to get this figured out. Happy to help with what I can.

**Comment by cuserox** [comment]
@SamIam4Hyma 👋 Have a whirl at the RC when you're back 🌴
