### ISSUE TITLE
Pulling from BitBucket overwrites $metadate/$themes with empty data

### ISSUE THREAD

**Issue by rbosker** [tokens-studio/figma-plugin#2997]
**Describe the bug**
In the sync provider BitBucket you can push everything fine, but when you pull changes with themes, these themes are overwritten on pull with empty data and no themes are present anymore.

**To Reproduce**
1. Create a tokenset with themes and sync those to BitBucket
2. Check BitBucket to see that the themes data is available on the remote.
3. Pull the tokens again > you will get a message that configuration has changed.
4. Check themes and see that there are no themes.

**Screenshots or Screencasts**
![image](https://github.com/user-attachments/assets/61f71b3f-8db1-48a7-9304-1afa24383ab5)

**Note**
Beta RC9 > this happens with tokens created in the Beta as well as v1.38.9

**Comment by rbosker** [comment]
hey @cuserox , could you take a look at this issue? Let me know if you have questions about it

**Comment by akshay-gupta7** [comment]
The issue was only occurring when tokens were being pulled from single tokens file sync.
Is addressed in the following Pull Request:
