### ISSUE TITLE
Documentation Tokens: Support for CSS/SCSS/JS...

### ISSUE THREAD

**Issue by derekluciani** [tokens-studio/figma-plugin#300]
**Is your feature request related to a problem? Please describe.**
The current documentation tokens only support:
- Name
- Raw Value
- Value
- Description

**Describe the solution you'd like**
I'd be nice if documentation could generate names specific to a codebase:
- CSS variable
- SCSS variable
- JS variable

**Additional context**
Our design team uses SCSS variables and it'd be nice to document our tokens in Figma in this format.

**Comment by six7** [comment]
So for a token named `colors.bg.default` we'd expose `var(--colors-bg-default)`, right? I like that! Makes me wonder if we'd be able to do that dynamically so it could be a primitive that you'd be able to format/transform on your own

**Comment by dmackerman** [comment]
Isn't this what tools like `style-dictionary` are for? I guess you need to run the Figma Tokens output through the transformer first, but adding these types of things as first class features of the plugin feels nice, too.

**Comment by six7** [comment]
Update on this: We initially wanted to tackle it in the next iteration, but I'm removing it again as I couldn't come up with a good enough solution. If someone has one that doesn't clutter the UI I'd appreciate it.

**Comment by SamIam4Hyma** [comment]
@six7 suggest to close b/c it's stale and we can reimagine when we focus on documentation in a future epic.
