### ISSUE TITLE
Exporting Variables/Styles: check/uncheck all token sets

### ISSUE THREAD

**Issue by rbosker** [tokens-studio/figma-plugin#3003]
**Describe the bug**
When you have a lot of tokensets, you now need to manually enable/disable those sets. It would be nice if we can add a check/uncheck all option at the top of this view.

**To Reproduce**
1. Export styles and variables
2. confirm   what you want to export
3. Select Token sets
4. Click 'Change sets'

**Expected behavior**

**Screenshots or Screencasts**
<img width="491" alt="image" src="https://github.com/user-attachments/assets/26d27490-f527-4f40-936f-d50bbe0199d4">

**Slack**
https://tokens-studio.slack.com/archives/C02JAL48UDN/p1721155404395529

**Comment by SamIam4Hyma** [comment]
Migrated to [Featurebase as a request for upvoting.](https://feedback.tokens.studio/p/export-to-figma-from-token-sets-enhancements)
