### ISSUE TITLE
Enhancement: Make it possible to collapse theme groups in 'Manage themes'

### ISSUE THREAD

**Issue by rbosker** [tokens-studio/figma-plugin#3004]
**Is your feature request related to a problem? Please describe.**
Add the ability (like in the tree view of the token sets) to collapse theme groups. in this way it's easier to manage the themes when working with larger token sets.

**Additional context**
<img width="531" alt="image" src="https://github.com/user-attachments/assets/4be833d4-c2a5-4e6d-a9d0-c8089806aac9">

**Comment by SamIam4Hyma** [comment]
Migrated to[ featurebase as a request ](https://feedback.tokens.studio/p/manage-themes-like-tokens-set)
