### ISSUE TITLE
Converting to W3C format causes two values in new and old format on push

### ISSUE THREAD

**Issue by rbosker** [tokens-studio/figma-plugin#3017]
**Describe the bug**
When you convert your tokens to W3C and push those tokens to a syncing provider, the json shows the tokens in the old and new format.

**To Reproduce**
1. Open tokenset
2. Convert tokens to W3C format
3. Push to syncing provider (tested with GitHub, GitLab & BitBucket).
4. See the tokens on the remote that have double values in the new and old format.
5. The JSON in the plugin shows the JSON correctly, but on the remote it's wrong.

**Note**
Reproducable in rc9 & rc10

https://github.com/user-attachments/assets/f93869cb-dd8e-483b-a458-8431dad0122f

**Comment by rbosker** [comment]
@cuserox could you take a look at this issue? Seems to be an important issue, since it messes up the formating of tokens.

**Comment by cuserox** [comment]
🤖 PR is being reviewed: https://github.com/tokens-studio/figma-plugin/pull/3022

🔨 Build of the fix: [3017-fix-double-format-keys.zip](https://github.com/user-attachments/files/16378735/3017-fix-double-format-keys.zip)

👀 @rbosker @keeganedwin @akshay-gupta7 Could one of you please test this works as expected with other providers? I only tested with GitHub.

**Comment by rbosker** [comment]
tested this for BitBucket, GitLab and ADO > all is working as expected 🥳

**Comment by cuserox** [comment]
🤔 Question: if the user was experiencing duplicate keys (legacy & DTCG) on the remote, this should sanitize and fix it, correct?

If so, it will be worth adding it to troubleshooting docs and making it visible to those encountering it.

**Comment by six7** [comment]
Closing as PR is merged
