### ISSUE TITLE
Typography/Composition tokens don't give a good preview in the plugin, when using the W3C format

### ISSUE THREAD

**Issue by rbosker** [tokens-studio/figma-plugin#3019]
**Describe the bug**
The preview in the plugin shows a list of values, but not the same (good) view when using the old format.
The screenshots below show the W3C and legacy preview, where the legacy preview looks a lot better (with the resolved values).

**Screenshots or Screencasts**
W3C format
![image](https://github.com/user-attachments/assets/9f47f0f0-8c1f-4606-a816-8da53492f869)

Legacy format
![image](https://github.com/user-attachments/assets/215dac0b-5ec0-4687-a768-6d3c951dd3f4)

**Comment by six7** [comment]
Fixed in RC10
