### ISSUE TITLE
Plugin crash with non-string token values in resolve duplicate modal

### ISSUE THREAD

**Issue by macintoshhelper** [tokens-studio/figma-plugin#3025]
**Describe the bug**

Plugin crashes when opening the duplicate resolve modal and there are duplicate tokens with typography/composition values.

**Expected behavior**

- Shared logic with `TokenTooltipContentValue`
- Later on this UI should be decoupled from being tooltip specific.

**Screenshots or Screencasts**

<img width="376" alt="image" src="https://github.com/user-attachments/assets/cabfa8bc-bd96-4bae-977b-542cd2012953">

**Figma file (optional)**
Send us the link to a Figma file containing a reproducible example

**JSON (optional)**
If possible, attach the JSON that leads to this bug.

**Comment by six7** [comment]
Closed in RC10
