### ISSUE TITLE
Strange behaviour on pushing changes: Diff+actual pushed changes

### ISSUE THREAD

**Issue by rbosker** [tokens-studio/figma-plugin#3028]
**Describe the bug**
There are 2 issues that seems to be somewhat related:

1. Diff view on push shows tokens that are already pushed (this doesn't work in beta releases, but does work in 1.38.9)
2. Pushing tokens making strange commits (changing not only the token that you added/edited)

Please check the screenrecording where I explain what the issue is:

https://github.com/user-attachments/assets/3de97e65-6721-4f14-b629-b5ed36bce1fb

**Comment by cuserox** [comment]
I believe we have a fix 🔨 ✨ The last up to date build can be found here: https://github.com/tokens-studio/figma-plugin/pull/3035#issuecomment-2255876816

@rbosker could you please give it a test, and note down if:
* Is the original issue fixed?
* Any other unexpected behaviours?

Thanks! 😄

**Comment by rbosker** [comment]
@cuserox 

1. Diff view is fixed and didn't see any strange behaviour over there 🎈 
2. The pushes still seems inconsistent as we noticed last week. If you make 2 commits to the same branch in a short amount of time, could it be that GitHub merges those 2 commits into one? That seems to be happening.

**Comment by rbosker** [comment]
One thing I noticed besides this: this build (and the previous one you shared) doesn't accept my license key. I think this is due to the build, since in all RC's this does work properly.

**Comment by cuserox** [comment]
> 2\. The pushes still seems inconsistent as we noticed last week. If you make 2 commits to the same branch in a short amount of time, could it be that GitHub merges those 2 commits into one? That seems to be happening.

Ah yes, I had a similar issue regarding license key. Could be that we need to tweak something in the artifact build, or we can only use one key across environments? Not sure about this one CC @six7

**Comment by cuserox** [comment]
> 2\. The pushes still seems inconsistent as we noticed last week. If you make 2 commits to the same branch in a short amount of time, could it be that GitHub merges those 2 commits into one? That seems to be happening.

Let's pair on this.

**Comment by rbosker** [comment]
on point 2: 

https://github.com/user-attachments/assets/52d74813-87a9-45c4-ad88-0e3b7ddcbe35
