### ISSUE TITLE
JSONBin for Multi-person collaboration workflow does not work properly (diff are not shown properly)

### ISSUE THREAD

**Issue by UdayHyma** [tokens-studio/figma-plugin#3031]
**Describe the bug**
When using JSONBin for Multi-collaboration, when the user pulls new changes in, the token differentiator does not show the changes properly. 

**To Reproduce**
1. Use JSONBin with the same API key and ID.
2. Person A update his design token (Update on remote clicked)
3. Person B pulls once changes are made.
4. The token diff modal will pop up with incorrect data and sometimes even appears blank.

**Expected behavior**
When Person A updates their tokens, and then person B pulls it should show accurately what changes have been made.

Related Tickets: https://github.com/tokens-studio/figma-plugin/issues/3028#issue-2429627426

**Comment by cuserox** [comment]
Potentially fixed with this issue: https://github.com/tokens-studio/figma-plugin/issues/3028

Diffs in local vs remote are a shared utility

**Comment by cuserox** [comment]
I believe we have a fix 🔨 ✨ The last up to date build can be found here: https://github.com/tokens-studio/figma-plugin/pull/3035#issuecomment-2255876816

@UdayHyma could you please give it a test, and note down if:
* Is the original issue fixed?
* Any other unexpected behaviours?

Thanks! 😄

**Comment by UdayHyma** [comment]
@cuserox Tested it out!

- Yes the original issue is fixed, where the token diff shows the correct changes.

-  The state of the tokens is *removed* when a token has just been added and the user pulls.

![image (1)](https://github.com/user-attachments/assets/78f3c574-f1c9-4341-8f64-11c3cfe9317b)
![image (2)](https://github.com/user-attachments/assets/1a39182c-e8cd-4acb-9a63-383e871e90ae)

**Comment by cuserox** [comment]
> [@cuserox](https://github.com/cuserox) Tested it out!
> 
> * Yes the original issue is fixed, where the token diff shows the correct changes.
> * The state of the tokens is removed when a token has just been added and the user pulls. > 'the state is therefore incorrect and needs to be the value of the token in green.
> 
> ![image (1)](https://private-user-images.githubusercontent.com/138768433/353465042-78f3c574-f1c9-4341-8f64-11c3cfe9317b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI0NDA2MTUsIm5iZiI6MTcyMjQ0MDMxNSwicGF0aCI6Ii8xMzg3Njg0MzMvMzUzNDY1MDQyLTc4ZjNjNTc0LWYxYzktNDM0MS04ZjY0LTExYzNjZmU5MzE3Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDczMVQxNTM4MzVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xNzVkNzY4YTBmOTg0NGI5OTRkOTE0YjkwMWE4ZjZjNjdlYTQxODRjOTJiMzViMzdhMzkxMzczNmQwN2E1NGIwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.A6ypVESoB1HiqdKmuxSWpRaP0-qGxtiBvh17bOHyIUc) ![image (2)](https://private-user-images.githubusercontent.com/138768433/353465080-1a39182c-e8cd-4acb-9a63-383e871e90ae.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI0NDA2MTUsIm5iZiI6MTcyMjQ0MDMxNSwicGF0aCI6Ii8xMzg3Njg0MzMvMzUzNDY1MDgwLTFhMzkxODJjLWU4Y2QtNGFjYi05YTYzLTM4M2U4NzFlOTBhZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDczMVQxNTM4MzVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03MjRkZDYwZjU0NGZjNTFkOGYxYjYxMmVkNzU3MDZjNWIxOWZjYTQ0YjA3MWMxYWExZTI0ODJiZjdjOGQ3ODRkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.hH5MLSHzH54VRzihI2aPMCtytfK32SsIsU943A60bJY)

Awesome 😸 I'll mark it as ✅ Done ✅ alongside https://github.com/tokens-studio/figma-plugin/issues/3028 ✨
