### ISSUE TITLE
On-premise GitLab

### ISSUE THREAD

**Issue by MartinKristof** [tokens-studio/figma-plugin#3055]
**Describe the bug**
Hello, I want to use GitlabSync with our on-prem GitLab instance.
It fails on auth, probably caused by our firewall.
Can I get list of IP range to allow on our side until you resolve https://github.com/tokens-studio/figma-plugin/issues/2360?

**To Reproduce**
1. Go to Settings - To providers
2. Click on 'Add new' Gitlab
3. Fill the form

**Expected behavior**
GitlabSync works

**Screenshots or Screencasts**
![Snímek obrazovky 2024-08-08 v 8 43 25](https://github.com/user-attachments/assets/07b70d96-2b4a-4e97-ae95-c69d8f144d8a)

**Comment by six7** [comment]
There is nothing between Figma and your Gitlab instance. The plugin connects directly to it, so we can't share an IP list because there is nothing to share.

Let me know if i misunderstood

**Comment by MartinKristof** [comment]
There is a firewall on our side. Our GL instance is accessible only via VPN. Your service must have any IP address :)

**Comment by MartinKristof** [comment]
Can you help me, please?

**Comment by MartinKristof** [comment]
Solved, wrong path of owner. Sorry.
