### ISSUE TITLE
Unable to push to other branches when using ADO as a provider

### ISSUE THREAD

**Issue by cuserox** [tokens-studio/figma-plugin#3067]
# Context 📝 
Initial thread: https://hyma-team.slack.com/archives/C06RHB9RT2B/p1723558086329689

Useful ADO docs: https://learn.microsoft.com/en-us/rest/api/azure/devops/git/pushes/create?view=azure-devops-rest-6.0&tabs=HTTP#uri-parameters

# Bugs 🐛 

- [x] 1. When pushing changes to ADO, trying to create a PR leads to a 404 / error page

   * Temporary workaround: ensure that users add a project name to their ADO setup (Debugged with @rbosker) 
   
- [x] 2. Pushing to ADO in on different branches that are not **main** gives a 409 response

<img src="https://github.com/user-attachments/assets/7f0707a4-baa0-48e7-bcf5-9c54c1d92156" width=250 />

- [x] 3. When creating a new branch from sync settings, one expects the branch on remote to contain all the files once created

- [x] 4. When switching between single / file to multi file, there's errors when pushing

# Acceptance Criteria 🛠 
* Test all providers that support branches can: 
   * Push to any other branches that **are not main**
      - [x] GitHub
      - [x] GitLab
      - [x] Azure DevOps
      - [x] BitBucket
   * Lead to the correct URL when "Create pull request" is clicked
       - [x] GitHub (`${baseUrl}/${repo}/compare/${branch}?expand=1`)
      - [x] GitLab (`${baseUrl}/${id}/-/merge_requests/new`)
      - [x] Azure DevOps (`${orgUrl}${projectId && `/${projectId}`}/_git/${repositoryId}/pullrequestcreate?sourceRef=${branch}&targetRef=main`)
      - [x] BitBucket (`${baseUrl}/${repo}/pull-requests/new?source=${branch}`)

**Comment by rbosker** [comment]
Users who are facing this issue currently can use the 1.38.9 build as a work around, until this issue is fixed. Attached the build and below the information on how to install this version:
- download the zip file
- unzip the zip file
- install the plugin from manifest
- Steps are in this video → https://share.cleanshot.com/ftbDH41n

[tsfigma-1_38_9.zip](https://github.com/user-attachments/files/16610179/tsfigma-1_38_9.zip)

**Comment by UdayHyma** [comment]
Bitbucket pushes the changes to a different branch that is not main, but when clicking the pull request button the link takes us to the correct url but nothing shows up on the page
<img width="780" alt="Screenshot 2024-08-14 at 15 08 44" src="https://github.com/user-attachments/assets/df1394db-4152-4850-b36d-a9f10002fb1e">
<img width="557" alt="Screenshot 2024-08-14 at 15 09 01" src="https://github.com/user-attachments/assets/8803e841-34ac-4083-bd5f-2dee62e5d182">
<img width="1512" alt="image" src="https://github.com/user-attachments/assets/c1638438-92a3-4a99-a2ba-c5c7fb9db18d">

**Comment by cuserox** [comment]
@rbosker @UdayHyma - the fixes are being reviewed. Artifact to test locally can be found [here](https://github.com/tokens-studio/figma-plugin/pull/3071#issuecomment-2288577258) 🙏
