### ISSUE TITLE
Gitlab: creating a new folder structure from the plugin doesn't work.

### ISSUE THREAD

**Issue by rbosker** [tokens-studio/figma-plugin#3076]
**Describe the bug**

- :x:Gitlab: creating a new folder structure from the plugin doesn't work.
- :white_check_mark: connecting to an existing folder works
- :white_check_mark: creating and syncing to a single file works

**To Reproduce**
1. Setup Gitlab
2. Use as path a folder that doesn't exist
3. You will get a 404 and the folder isn't created.
![image](https://github.com/user-attachments/assets/08cc7a33-b170-4ded-a324-f57d20d28087)

**Acceptance criteria**
- [x] Users should be able to push to a new branch when editing the sync provider details (i.e. from `main` to `new-branch`)
- [x] New branch created should be based on the current one that's selected in the plugin
- [x] New branch created should be selected and visible in the branch switcher
- [x] Users should be able to push to a single new file or a new folder when editing the sync provider details (i.e. change from `tokens.json` to `theme`)
- [x] If the user does not complete the "Push to remote" flow, the sync provider details should revert to the original ones

**Comment by cuserox** [comment]
👋 @rbosker the fix is ready to be reviewed (🔨 while I fix tests) - https://github.com/tokens-studio/figma-plugin/pull/3089 🙏

**Comment by cuserox** [comment]
This has now been merged to the `main` branch 🎉
