### ISSUE TITLE
Styles not syncing in figma since V 2.0

### ISSUE THREAD

**Issue by moerthgeorg** [tokens-studio/figma-plugin#3080]
Hello, I haven't touched my figma file since the update. Now today when I click on Apply to document the colors are not syncing, even though the process seems to be doing its job and it has always worked before. I switched from light to dark mode here and now nothing happens when I apply the changes to the document. In the plugin the right variables show up but the styles in figma stay the same.

![Screenshot 2024-08-16 at 14 31 06](https://github.com/user-attachments/assets/a60dfd34-89fd-4776-a1f1-ad8695f0a64c)
=

[$metadata.json](https://github.com/user-attachments/files/16637082/metadata.json)
[$themes.json](https://github.com/user-attachments/files/16637083/themes.json)
[lara-dark.json](https://github.com/user-attachments/files/16637084/lara-dark.json)
[lara-light.json](https://github.com/user-attachments/files/16637085/lara-light.json)

**Comment by rbosker** [comment]
hi @moerthgeorg , thanks for reporting! We're looking into styles related issues after the release and I added your ticket in there: https://github.com/tokens-studio/figma-plugin/issues/3083

**Comment by six7** [comment]
2.0 requires you to manually click `Export styles` - we no longer just update styles if you activate a token set, its now a deliberate action
