### ISSUE TITLE
Incorrect Hue Value Exported When Converting HSL to Figma

### ISSUE THREAD

**Issue by NuthanHyma** [tokens-studio/figma-plugin#3082]
**Describe the bug**
When converting colors stored in HSL format to HEX in Figma, the hue values are exported incorrectly. The hue value shifts, resulting in discrepancies between the original HSL value and the value displayed in Figma.

**To Reproduce**
1. Navigate to plugin > color token
2. create a color token with the value of hsl(220, 2%, 90%) and save 
3. now export variables 
4. got to figma variables and check the hsl value
5. it shows 240, 2%, 90%

**Expected behavior**

**User(Rich Fonteneau) explains why this happens**
The hue is shifting from 220 to 240.
The discrepancy you’re noticing,between the HSL values is due to the way colors are approximated and represented in different color spaces.

Here’s what’s happening:
When Tokens Studio, for example, converts ‘hsl(220, 2%, 90%)’ to HEX, the HSL value is first converted to an RGB value. HSL is a cylindrical coordinate system, while RGB and HEX are cartesian. The slight difference in the calculation methods can result in a minor shift in color. The RGB values derived from ‘hsl(220, 2%, 90%)’ are approximated to RGB(229, 229, 230), which translates to ‘#E5E5E6’ in HEX.
When you see Figma converting ‘#E5E5E6’ back to HSL, the process again involves converting from HEX to RGB and then to HSL. The RGB values ‘229, 229, 230’ are quite close to a neutral gray, leading to a  hue that can vary slightly due to rounding and the precision the algorithms used. In this case, it results in ‘hsl(240, 2%, 90%)’.
For colors with low saturation, the RGB or HEX output can be nearly identical across a broad range of hues. In your case, hues between approximately 210 and 270 degrees would all produce a very similar color in RGB/HEX. Since these hues all produce the same or a very similar HEX color, converting back from that HEX color to HSL can land on any hue within that range, depending on the algorithm used. In this case, it happened to land on 240, but it could just as easily been any hue from 210 to 270 without changing the perceived color.

**Screenshots or Screencasts**
<img width="1250" alt="Screenshot 2024-08-16 at 7 58 19 PM" src="https://github.com/user-attachments/assets/e1bf5415-075d-433f-9c1a-bd63d031c2c7">

**Figma file (optional)**
Send us the link to a Figma file containing a reproducible example

**Comment by six7** [comment]
I'm afraid there's nothing we can do.

Figma expects colors in `RGB`, so we have to convert the HSL to RGB. https://www.figma.com/plugin-docs/api/Paint/#color

If we were able to apply colors in different modes in Figma we'd be able to solve this, but with this constraint we can't do much, closing.
