### ISSUE TITLE
Styles Issues after 2.0 release

### ISSUE THREAD

**Issue by rbosker** [tokens-studio/figma-plugin#3083]
**Describe the bug**
1. Issue where styles worked in 1.38.9, but after release they didn't. (screenrecording Robbert > can't share the recording over here) > @keeganedwin can you link related thread?
2. Issue where multiple themes are enabled and the styles don't show in Figma. (screenrecording Keegan > can't share here) > https://tokens-studio.slack.com/archives/C02HN88QARL/p1723732865563299
Internal screenrecording: https://hyma-team.slack.com/archives/C04V8U8UH0F/p1723817105349809?thread_ts=1723813528.996869&cid=C04V8U8UH0F
3. #3088 
4. https://github.com/tokens-studio/figma-plugin/issues/3095

Also linking this user submitted related issue: https://github.com/tokens-studio/figma-plugin/issues/3080
https://github.com/tokens-studio/figma-plugin/issues/3088#issue-2475404043

**Comment by akshay-gupta7** [comment]
Isuse no.1 is resolved by #3103

**Comment by rtkramer** [comment]
I am having this problem again, document wide styles break on text layers in my custom overrides, they all revert to raw values, styles get broken. But when I look at the Lara set for same token they still work style is connected.
