### ISSUE TITLE
Export to Figma feature doesn't export all the variables associated to the Theme

### ISSUE THREAD

**Issue by marach-t-mtl** [tokens-studio/figma-plugin#3086]
**Describe the bug**
Export to Figma feature doesn't export all the variables associated to the Theme.

The theme:
![image](https://github.com/user-attachments/assets/d78e7df8-2feb-4ffc-a43b-c36d175e326e)

The exported variables:
![image](https://github.com/user-attachments/assets/e041005c-4e0b-4e4e-82cc-e5d311092d8b)

Since the `prim/mtl/color/value` doesn't get exported into variables, all the variables in `sem/color/mtl-light` are all referenced to empty variable, thus, cannot be used.

**To Reproduce**
1. Create a token set that refer the color of another token set
2. Create a theme with those 2 sets, make sure to `Enabled` ( NOT `Reference Only`)
3. Export Variables to Figma using `Style & Variables > Export styles & Variables`

**Expected behavior**
- It should export both token sets as variables, when I pick `Enabled` Theme configuration
- It should NOT export the token, if I pick `Reference Only` in Theme configuration

**Screenshots or Screencasts**
(See above)

**Comment by keeganedwin** [comment]
hey @marach-t-mtl, it looks like you've only created a collection for the `sem/color`, but you're variables are missing hte core/primitives collection. 
![CleanShot 2024-08-22 at 20 04 12@2x](https://github.com/user-attachments/assets/3a1a68e3-cb59-4a67-8e59-e305a9ca2afa)
It is advised to always create a separate variable collection of your `core/primitive` tokens. These core/primitive sets need to always be enabled and then subsequent sets that are referencing these tokens need to be enabled BUT have the core set to `reference only`.

**Comment by six7** [comment]
Closing, this should work with the above steps
