### ISSUE TITLE
Prefix with theme name working vs not working

### ISSUE THREAD

**Issue by UdayHyma** [tokens-studio/figma-plugin#3088]
**Describe the bug**
If I have the dark theme selected but want to export styles for the light theme with the export option `Prefix styles with active theme name` enabled, the plugin instead exports styles with `Ignore first part of token name`. It seems to be the case that a user has to select the the `set` and `theme` 2x before being able to export it correctly with the `Prefix styles with active theme name` option enabled. 

**To Reproduce**
1. Have two sets also setup as themes - same theme-group
2. Select `Set B` in the plugin's main view
3. Enable the `Prefix styles with active theme name` option
4. Select the appropriate style options
5. In the themes screen, instead select `Set A` for export
6. Export styles
7. See error

**Expected behavior**
I don't think the user should have to select the set first then proceed to select the same set again but in the themes screen to export as styles with the `Prefix styles with active theme name` option enabled. Regardless of which set is selected, the user should be able to export the any theme that is selected in the final export screen.

**Screenshots or Screencasts**
https://github.com/user-attachments/assets/f63d7980-368f-4e9e-bb41-3ab014dae8ef

**Figma file (optional)**
[Test file](https://www.figma.com/design/eNM2QtrFQspfM9uruvKunl/Nils-Prefix-Theme-Issue?node-id=2-67&t=BX5TAx6Ewne8Ega4-4)

**Comment by akshay-gupta7** [comment]
@UdayHyma @rbosker @keeganedwin , isn't this consistent with the expected behaviour that only those styles shall be exported when the corresponding set is active:
https://docs.tokens.studio/styles/create-styles

<img width="1520" alt="Screenshot 2024-08-21 at 00 26 46" src="https://github.com/user-attachments/assets/f167c899-43eb-4b6a-86ff-04bd1e7fbbb1">

**Comment by rbosker** [comment]
@akshay-gupta7 > that is correct, the difference is that we now have 2 places where we can enable sets: the plugin and the export modal. I expect that if I enable a set in the export view, that just works like the set is active in the plugin view.
