### ISSUE TITLE
'Remove styles and variables without connection to a token' Option Enabled Does not Create Variables

### ISSUE THREAD

**Issue by keeganedwin** [tokens-studio/figma-plugin#3090]
**Describe the bug**
Since the release of 2.0, we've seen a lot of users have the export option `Remove styles and variables without connection to a token` enabled at all times which results in creation of no variables. 

**To Reproduce**
1. Create tokens in two different `sets`
2. Group both these `sets` as themes under one `theme-group`
3. Export as Variables without any export options enabled 
4. Add a new token to one of the sets
5. Enable `Remove styles and variables without connection to a token` and export
6. See error
7. Disable the option and export again
8. Variables are exported

**Expected behavior**
Not sure about this as the result of having this option enabled may also be expected behaviour

**Screenshots or Screencasts**
https://github.com/user-attachments/assets/ff611f63-c5fe-4d9c-a029-4321219c38da

**Figma file (optional)**
[Test file](https://www.figma.com/design/JLz9NjZeLRCSDIDpz2reK2/Untitled?node-id=103-7&t=PrhmwplFZWgTFDAT-4)

**Comment by six7** [comment]
I think 2.1.0 fixes this, feel free to reopen if not
