### ISSUE TITLE
Exporting variables creates Collections per each token set, ignores theme groups

### ISSUE THREAD

**Issue by andrew-deem** [tokens-studio/figma-plugin#3099]
**Describe the bug**
When exporting variables using "Export styles & variables" in V2.0.1 of the plugin, a variable collections is created for each token set I am exporting from. Each collection has only 1 mode, named after the token set. The variable collection named after my theme groups is not updated.

**To Reproduce**
1. Click on "Styles and Variables" from the Tokens tab of the plugin
2. Click on "Export styles and variables"
3. Check boxes to 'Create and Update' variables, leaving all 'Styles' boxes unchecked 
4. In 'Tokens exported to Figma should:' switch ON 'Update existing style and variable names'
5. Click "Confirm"
6. In 'Themes' tab, check 'Select All' themes to export
7. In 'Token Sets' tab, set my global tokens to be 'Reference Only'. Set component token sets to 'Enabled'. 
8. Click "Confirm"
9. Click "Export to Figma"

**Expected behavior**
Expected behavior is well described by video on Tokens Studio Youtube channel of the older version of the plugin, around 7:45. https://youtu.be/AtMVxP0UMII?si=IsksqLgFOIFiEpZw&t=465

I would expect a single Variable Collection in Figma (which already exists and contains tokens) thats named based on my theme groups to be added to/updated. I would expect each variable to correlate to a design token, with a mode correlating to each theme. To my recollection, this is how it functioned prior to 2.0. 

**Screenshots or Screencasts**

Existing variable collection, named after my Theme Groups in Tokens Studio. 
<img width="871" alt="Screenshot 2024-08-23 at 13 23 38" src="https://github.com/user-attachments/assets/3d86aaff-1530-4e1a-a97f-9943d9a23486">

<img width="905" alt="Screenshot 2024-08-23 at 13 24 19" src="https://github.com/user-attachments/assets/6fa1f817-7b93-4a7b-a604-7b50dfd7793e">

Resulting collections when exporting:
<img width="175" alt="Screenshot 2024-08-23 at 13 24 39" src="https://github.com/user-attachments/assets/ec895083-724b-4e93-be40-3fd81a7d1c93">

<img width="551" alt="Screenshot 2024-08-23 at 13 25 18" src="https://github.com/user-attachments/assets/5095c256-704b-4b99-aa16-82750bee14a8">

**Comment by six7** [comment]
> In 'Token Sets' tab, set my global tokens to be 'Reference Only'. Set component token sets to 'Enabled'.

Make sure to not use the Token Sets tab, use the `Themes` tab if you want to use Themes. This should work if you export from there.
