### ISSUE TITLE
Styles are not working properly

### ISSUE THREAD

**Issue by gargantu4** [tokens-studio/figma-plugin#3102]
**Describe the bug**
Theme should switch automatically the colours in style. It still doesn't work on 2.0.2

**To Reproduce**
1. Create a file
2. export styles
3. Create a copy of the token set
4. change one colour
5. Activate the token set
6. Figma styles should be updated

**Expected behavior**
Figma styles should be updated based on the theme / token set activation

**Screenshots or Screencasts**
https://drive.google.com/file/d/1CF4xgd3-1VHo7uF32YBVKIfS9Vc3a6CV/view?usp=drive_link

**Figma file (optional)**
even in new ones.

**JSON (optional)**
If possible, attach the JSON that leads to this bug.

**Comment by six7** [comment]
Sorry for the late reply here.

2.0 changed things so you'll need to re-export your styles for them to be updated, we dont update just by activating a token set anymore.
