### ISSUE TITLE
Typography Composite Token not being Overridden 

### ISSUE THREAD

**Issue by keeganedwin** [tokens-studio/figma-plugin#3118]
**Describe the bug**
In `38.9` users were able to override a single property of a typography composite token with the appropriate token type. For example, if a typography token is applied, a user can override just the `fontFamily` property with a `font-family` token. This is however no longer possible in `2.0` and proceeding versions.

**To Reproduce**
1. Create a typography token with references
2. Apply the token to a text
3. Apply a any token overriding one of the typography properties

**Expected behavior**

**Screenshots or Screencasts**

**Figma file (optional)**
Send us the link to a Figma file containing a reproducible example

**JSON (optional)**
If possible, attach the JSON that leads to this bug.

**Comment by six7** [comment]
I think this is solved in 2.1.0 - can you confirm @keeganedwin ?

**Comment by keeganedwin** [comment]
> I think this is solved in 2.1.0 - can you confirm @keeganedwin ?

Bug is still present
