### ISSUE TITLE
Lack of sync provider authentication error handling

### ISSUE THREAD

**Issue by Arcrammer** [tokens-studio/figma-plugin#3120]
![image](https://github.com/user-attachments/assets/a8acd089-814a-4065-8e67-1d9625164a3d)

There is a lack of error communication to the user when configuring a sync provider. In the attached screenie an example of this can be found when attempting to configure GitHub as a sync provider.

The authentication process is allowed to fail without raising an exception which leads to subsequent API calls returning a 404. The user is then left with no means of reverse engineering their way out of the problem and is forced to escalate by contacting support. (Which has happened more than once according to my correspondence with a gentleman named Keegan)

My recommendation would be to emphasize in the documentation to the user that they must use the _Classic_ token type when creating a token with GitHub. It was also unclear whether that token was meant to be created under the repository or the users own account, which would lead (and has) to greater unnecessary escalation within that employees own organization.

I would further recommend the use of the authentication APIs to provide the user an appropriate error response they can use to work backwards from. If it doesn't help the user it would most definitely help the team greater understand what led the cause.

If resources are constrained I would be happy to offer assistance in exchange for a spot on the team

**Comment by keeganedwin** [comment]
Heyy @Arcrammer! Are you still facing issues with connecting to Github?
In the meantime I will also migrate this ticket to [FeatureBase](https://feedback.tokens.studio/p/sync-external-storage-enhancements) as the `"improve credentials error"` point is more a feature request than a bug.

**Comment by Arcrammer** [comment]
🌞 Hey there Keegan, wasn’t expecting to see that name here! I am thankfully no longer facing issues! All I had to do was change the token type on GitHub from “fine-grained” to “classic”

I agree this can be considered a feature request. I only opened the ticket to bring attention to the issue in hopes it might save y’all some support tickets. As always I’m happy to provide help if desired, you know how to reach me.

Have a pleasant Monday!

**Comment by keeganedwin** [comment]
> 🌞 Hey there Keegan, wasn’t expecting to see that name here! I am thankfully no longer facing issues! All I had to do was change the token type on GitHub from “fine-grained” to “classic”
> 
> I agree this can be considered a feature request. I only opened the ticket to bring attention to the issue in hopes it might save y’all some support tickets. As always I’m happy to provide help if desired, you know how to reach me.
> 
> Have a pleasant Monday!

Feedback is always welcome and appreciated!
