### ISSUE TITLE
setTokensFromVariables does not correctly compare descriptions

### ISSUE THREAD

**Issue by mrtnvh** [tokens-studio/figma-plugin#3135]
**Describe the bug**
On import variables, when determining if a token is existing or updated, the comparison of the old token and new token description leads to false positives or negatives as it could compare different types of values.

This because of the fact that:
1. Figma provides empty descriptions as empty string.
2. Tokens Studio saves empty descriptions as a value of `undefined`

**To Reproduce**
Steps to reproduce the behaviour:
- Create token without description in Tokens Studio
- Export to Figma.
- Import to variables to Tokens Studio.
- See that the existing token is falsely determined as a new token.

**Expected behaviour**
See that no tokens have changed.

**Proposal**
1. Normalize description before check if they are equal.

From: 
https://github.com/tokens-studio/figma-plugin/blob/45697ef5023dc171587eadf2b1128b607ef5e0d0/packages/tokens-studio-for-figma/src/app/store/models/tokenState.tsx#L392

To:
```ts
const normalizedOldValueDescription = oldValue.description ?? '';
const normalizedTokenDescription = token.description ?? '';
if (isEqual(oldValue.value, token.value) && isEqual(normalizedOldValueDescription, normalizedTokenDescription)) {
```

2. Reuse logic from `setTokensFromStyles` in `setTokensFromVariables`
https://github.com/tokens-studio/figma-plugin/blob/45697ef5023dc171587eadf2b1128b607ef5e0d0/packages/tokens-studio-for-figma/src/app/store/models/tokenState.tsx#L349-L350

3. Abstract token determination to separate function for both `setTokensFromStyles` and `setTokensFromVariables`

---

If you agree that this would be a bug, I'm happy to provide a PR with one of the options above, depending on what the preference of the maintainers is.

**Comment by six7** [comment]
Hey @mrtnvh sorry for the slow response here.

I agree - that proposal does make sense to me. If you want to contribute, I'd be happy to review and get those changes into one of our coming releases 💖 

Thank you!!
