### ISSUE TITLE
Can't update variables using multiple modes

### ISSUE THREAD

**Issue by bzupancic** [tokens-studio/figma-plugin#3136]
**Describe the bug**
After importing variables from Figma, I'm unable to update them using the same collection.

**To Reproduce**
1. Create a variable in Figma with 2 modes—light and dark.
![image](https://github.com/user-attachments/assets/be1e56a4-8806-4fc8-a3b6-83e6c825f70e)

2. Click on "Styles and Variables" and select "Import variables"
![image](https://github.com/user-attachments/assets/48a97864-1327-426b-91ac-85f4ed022c8d)

Both "Light" and "Dark" modes are created (as expected).
![image](https://github.com/user-attachments/assets/38b83582-ec6e-4946-8d6b-eb07ad1fa56d)
![image](https://github.com/user-attachments/assets/fc8555ab-a9b9-49c9-815b-dcae4e32f729)

3. Update light mode gray-100 value
![image](https://github.com/user-attachments/assets/edf4f256-95c5-4ff5-a5f8-548af6556bbb)

4. Using the "Export styles & variables" action, with "Create and update - Variables - Color" selected, confirming, and "Exporting to Figma"
![image](https://github.com/user-attachments/assets/10e42445-4c6a-4e75-9cbf-57fffa75dc79)
![image](https://github.com/user-attachments/assets/6ebcdcba-19c9-4d44-bdd0-023c551fc9c9)
![image](https://github.com/user-attachments/assets/cbe7585e-e15a-44e9-bfd7-a9bf0914912b)

Another collection is created.

**Expected behavior**
My expectation is the value for gray 100 would be updated for the light mode column.

**Comment by keeganedwin** [comment]
heyy @bzupancic, it looks like you're trying to import and export variables to keep them in sync but this is currently not possible. These are two separate functions. Here's my [response](https://github.com/tokens-studio/figma-plugin/issues/3131#issuecomment-2348815631) to ticket from another user reporting the same issue. Here's also the [ticket](https://feedback.tokens.studio/p/sparkle-import-variables-should-include-themes-pro) for a feature on our feedback platform FeatureBase, that if implemented can possibly resolve the flow of using both functions to keep variables in sync.

**Comment by keeganedwin** [comment]
heyy @bzupancic, it looks like you're trying to import and export variables to keep them in sync but this is currently not possible. These are two separate functions. Here's my [response](https://github.com/tokens-studio/figma-plugin/issues/3131#issuecomment-2348815631) to ticket from another user reporting the same issue. Here's also the [ticket](https://feedback.tokens.studio/p/sparkle-import-variables-should-include-themes-pro) for a feature on our feedback platform FeatureBase, that if implemented can possibly resolve the flow of using both functions to keep variables in sync.
