### ISSUE TITLE
Switching Tokens Structure from File Path to Folder Path Loads Incorrect Design System

### ISSUE THREAD

**Issue by NuthanHyma** [tokens-studio/figma-plugin#3161]
**Describe the bug**
The development team decided to change the token structure from a file path to a folder path. After updating the settings, switching from a folder path to a file path results in loading an incorrect design system. Instead of loading the intended design system, it loads another design system we support, even though the two are completely separate and stored in different repositories on GitHub. Both systems previously used tokens.json, but we want to change one of them to use a folder named tokens.

**To Reproduce**
1. Setup 2 repos
2. repo 1 setup with multi-file > file path tokens
3. repo 2 setup with file path tokens.json
4. Setup a connection to the separate repo's in your plugin (so 2 connections, to both repos)
5. try to update the single file to multi-file

**Expected behavior**
Switching the path should load the intended design system without referencing or pulling in any unrelated design systems.

**Screenshots or Screencasts**

https://github.com/user-attachments/assets/64d44fd9-61a3-4b3b-977f-74e450f7fc91

**Figma file (optional)**
[Test File
](https://www.figma.com/design/nO4G4787DcAtP8cViri5xI/Untitled?node-id=0-1&t=wpVZRKMpoiBiE998-1)

**Comment by rbosker** [comment]
can you give this another test @NuthanHyma ?

**Comment by NuthanHyma** [comment]
@jan @SamIam4Hyma 
Closing this ticket! since This is not reproducible in V 2.2.3

**Comment by NuthanHyma** [comment]
Closing this Ticket

**Comment by jan** [comment]
@NuthanHyma you tag me bruh?
