### ISSUE TITLE
Selecting No Export Option for Styles Leads to Unexpected Result

### ISSUE THREAD

**Issue by keeganedwin** [tokens-studio/figma-plugin#3163]
**Describe the bug**
When you have no option enabled on exporting styles, the plugin exports tokens with the token group's name, and when you enable the `Ignore first part of token name for styles` they export tokens stripping the token group's name. So at the moment it seems to be that the plugin has 3 export options:
1. Ignore first part of token name for styles
2. Prefix styles with active theme name
3. None of the above selected

**To Reproduce**
1. Load any set of tokens in the plugin
2. Export styles `without` any of the aforementioned options enabled
3. See error

**Expected behavior**
The plugin has only ever supported `two` methods of exporting styles. We should stick to it as this will probably cause unexpected results for users. 

**Screenshots or Screencasts**
https://github.com/user-attachments/assets/ebe4866d-1cd3-424e-a85b-102bbbf69053

**Comment by keeganedwin** [comment]
Reproducible in `2.2.2`. I don't know if this was intentional but I don't think the plugin has had 3 exporting options, but now there seem to be 3.

In the recording you will see that the first time I export the styles I don't have any export options selected. These are how styles are exported with the 3 different methods:
1. Without export options - `color.button.primary.default.border`
2. Ignore first part of token name for styles - `button.primary.default.border`
3. Prefix styles with active theme name - `default.color.button.primary.default.border`


[Recording](https://github.com/user-attachments/assets/1ca9de6b-0ec6-468e-94c8-52baa77b2d3c)

**Comment by six7** [comment]
@keeganedwin i dont get what the issue is - seems to be working as expected. Let's close if youre also not sure

**Comment by keeganedwin** [comment]
> @keeganedwin i dont get what the issue is - seems to be working as expected. Let's close if youre also not sure
Okay. Then I guess I was just confused!
