### ISSUE TITLE
Supernova Sync Error Message

### ISSUE THREAD

**Issue by UdayHyma** [tokens-studio/figma-plugin#3166]
**Describe the bug**
When setting supernova sync up the user is facing an error message (Beta Error Message)

**Steps to reproduce**
I am unable to reproduce but these are the steps the user is going through
1. Add a new sync provider
2. Enter credentials and mapping
3. Save
4. The beta error message shows up

**Screenshots or Screencasts**
<img width="324" alt="image" src="https://github.com/user-attachments/assets/99c5e6a5-f540-4f24-a17e-faf94b5d1815">

**Figma file (optional)**
Send us the link to a Figma file containing a reproducible example

**JSON (optional)**
If possible, attach the JSON that leads to this bug.

**Comment by rbosker** [comment]
Not reproducable anymore, error messages seem to be good for all tested cases.
