### ISSUE TITLE
BitBucket Data Center and Server sync

### ISSUE THREAD

**Issue by kokovtsev** [tokens-studio/figma-plugin#3168]
I have a project with source code kept in an on-premise BitBucket installation, and I would like to keep the design tokens there as well.

For example, in GitLab integration it is possible to provide a "Base URL" which solves the problem for self-hosted GitLab instances. I expect that a similar setting for BitBucket would be useful as well.

<img src="https://github.com/user-attachments/assets/2e72bb5d-d005-4c17-919a-8e8df9fa86ad" width="500" />

Can this feature be implemented at some point? I understand there might be compatbility issues between different versions of BitBucket but it would be great if this can be done in a generic, widely compatible way. Happy to contribute btw if you support the idea.

Thanks!

**Comment by rbosker** [comment]
hi @kokovtsev , I migrated this request to our [Feature Base](https://tokensstudio.featurebase.app/p/bitbucket-enhancements), from where we can check if this is possible.

**Comment by kokovtsev** [comment]
Thanks @rbosker!
Would you be ready to review and accept a PR for this feature if we create one?

**Comment by rbosker** [comment]
@kokovtsev if you can file a PR for this and that meets the plugin standards, we can get it reviewed/accepted. Also linking @akshay-gupta7 in this thread.
