### ISSUE TITLE
Published Changes in Figma Shows all Changes in the File Modified

### ISSUE THREAD

**Issue by keeganedwin** [tokens-studio/figma-plugin#3169]
**Describe the bug**
There seems to have been some change made in the plugin that's affecting the changes displayed when publishing Figma libraries. Previously, when users would make token changes and update anything in a file, Figma would only show the `modified changes` and not everything else. Currently, the plugin shows that everything in the file is `modified`. This Seems to affect styles, variables and components.

> Here's the [slack thread ](https://tokens-studio.slack.com/archives/C06MVD961K8/p1721153538418999) wherein this was issue was last discussed. As discussed in the thread, the the user of the thread continued to face this issue at the time but one (Simone) didn't. However Simone recently [reported](https://tokens-studio.slack.com/archives/C06MVD961K8/p1727098659276589?thread_ts=1721153538.418999&cid=C06MVD961K8) that they're facing it now as well.

**To Reproduce**
1. Export any - variables or styles - to Figma
2. Publish Figma file
3. Change one token and update it's variable/style
4. Publish the file
5. See error - Figma displays that more than 1 variable/style have been modified

**Expected behavior**
Only the modified changes should be displayed in Figma.

**Screenshots or Screencasts**
This recording is from a user who's facing this with styles
https://github.com/user-attachments/assets/7e5ec554-be8c-41d5-aa37-aaaf80be2cc5

**Comment by six7** [comment]
Bringing conversations from Slack here:

- Turns out we didn't have a check for if variable values were the same before we updated them
- Styles already had this check, so this should not happen for Styles - let's focus this issue on Variables
