### ISSUE TITLE
Tooltips Fly Out of Container When Scrolling Fast with Large Token Files

### ISSUE THREAD

**Issue by NuthanHyma** [tokens-studio/figma-plugin#3183]
**Describe the bug**
While creating/editing any token values and scrolling quickly through the existing tokens (specially a large token file), tooltips occasionally fly out of the container, resulting in layout issues. This behavior is especially noticeable with large token files.

**To Reproduce**
1. Get a large token file 
2. go to tokens
3. create/edit the token
4. Fast scroll through the tokens 
5. see the error.

**Screenshots or Screencasts**

https://github.com/user-attachments/assets/0a113fc8-188b-4ca6-98c9-a0d2e5d19296

**Comment by six7** [comment]
Closing this as a wontfix. too much effort for almost zero value add
