### ISSUE TITLE
Unable to apply a background fill to an instance/variant of a component

### ISSUE THREAD

**Issue by rbosker** [tokens-studio/figma-plugin#3194]
**Describe the bug**
Currently it's not possible to add a background fill to an instance/variant of a component. Other tokens like sizing, radii, opacity do seem to work. If you directly apply a color from Figma to an instance/variant, that does work.

**To Reproduce**
1. Create a component and variant
2. Try to apply a color token as background fill to the instance/variant

**Expected behavior**
It should be possible to add a background fill to an instance/variant.

**Note:**
It seems that the 'selection color' shown in the second recording has something to do with this.

**Screenshots or Screencasts**
https://github.com/user-attachments/assets/4bebc1d7-0342-47df-b593-8158bcc26b50
https://github.com/user-attachments/assets/db506e22-019b-4df2-a316-554249e622d7

**Comment by SamIam4Hyma** [comment]
@rbosker is there a color token already applied to the parent component?

**Comment by rbosker** [comment]
@SamIam4Hyma no, there was not a color token applied to the parent component.

**Comment by six7** [comment]
Closing this. User error (correct me if I'm wrong).

Your rectangle that fills the entire component had a fill of yellow, then you tried to apply to the parent another fill. That will never be visible because the child fill wins
