### ISSUE TITLE
Export Variables: once Variables are exported, you can't update a reference to raw value and vice versa

### ISSUE THREAD

**Issue by rbosker** [tokens-studio/figma-plugin#3208]
**Describe the bug**
once Variables are exported, you can't update a reference to raw value and vice versa

**To Reproduce**
1. Create 2 color tokens: Token 1 having a raw hex value and Token 2 referencing Token 1
2. Export these as Variables (Themes export)
3. Change Token 2 to a raw HEX value and in Token 1 you reference Token 2 now
4. Export your variables again.
5. See that the Variable that first referenced another value stays as a referenced token and the color is not updated. The variable that was initially a raw value, updates the value, but isn't changing to a referenced token/variable.

**Expected behavior**
Expect that Token 1 updates to a referenced Variable in step 4. Expect Token 2 to update to a Hex value with the correct value.

**Screenshots or Screencasts**
https://github.com/user-attachments/assets/7c27dda7-dd21-40de-93d4-0b4b3e20795b

**Note**
This probably also applies for other token types.

**Comment by liamco** [comment]
Not sure if this helps or muddies the waters but I just submitted a bug report where we're having a pretty similar issue; #3209

**Comment by DarioSoller** [comment]
We are also affected by that bug at the moment. FYI: For us at the moment it's with some inset spacing tokens/variables, as this issue does not seem to be limited to a certain token type.

**Comment by akshay-gupta7** [comment]
> We are also affected by that bug at the moment. FYI: For us at the moment it's with some inset spacing tokens/variables, as this issue does not seem to be limited to a certain token type.

@DarioSoller We have a fix for this in progress, which should be released soon.

**Comment by DarioSoller** [comment]
@akshay-gupta7 nice that sounds promising. Actually for us this decides, if we will ship another design token release before Xmas or not. Looking forward to it. Thx for the quick update!

**Comment by six7** [comment]
✅ This has been released with 2.2.3
