### ISSUE TITLE
Enable aliases in token descriptions

### ISSUE THREAD

**Issue by six7** [tokens-studio/figma-plugin#328]
From Slack:

> Question about the token 'Description' field: I'm wondering if you can use elements from the token you're defining? In creating a typography token, it has a name, a font family, weight, size, etc. I'd like to have the description describe the token: "Poppins Bold / 40px / 50px line-height" - but the numbers are themselves tokens.
> 
> I'm envisioning something like "$font $fontWeight / $fontSize / $lineHeight"

**Comment by SamIam4Hyma** [comment]
@six7 Suggest to close b/c it's stale and we can reimagine when we focus on documentation in a future epic.
