### ISSUE TITLE
[GitHub Sync]: Plugin will not push to an empty repo

### ISSUE THREAD

**Issue by benjaminleonard** [tokens-studio/figma-plugin#387]
**Describe the bug**
A new repo without any files in it cannot be pushed to. Resolvable by creating an empty file.

**To Reproduce**
1. Create new repo using the GitHub dashboard
2. Create your PAT and set up the sync in Figma Tokens
3. Push changes

**Screenshots or Screencasts**
<img width="296" alt="Screenshot 2021-12-23 at 15 04 20" src="https://user-images.githubusercontent.com/4020798/147258902-96ad6c39-5da1-4386-961c-5b899737e512.png"><img width="315" alt="Screenshot 2021-12-23 at 15 03 01" src="https://user-images.githubusercontent.com/4020798/147258897-34e12253-9cce-4ab2-b6d7-c53e0afb57ec.png">

**Comment by natashaTpT** [comment]
I'm having the same issue

**Comment by SamIam4Hyma** [comment]
@six7 do we want to close/archive this one as this is a known issue we have already documented which is solved by ensuring there is a read-me file when you create the repo?
