### ISSUE TITLE
Add support to remove tokens from instance that is present on the main component without overwriting

### ISSUE THREAD

**Issue by ZachShea** [tokens-studio/figma-plugin#392]
**Describe the bug**
On some component instances, changing or removing tokens seems to work at first, but the tokens magically change back or reappear. This is consistently happening with some components, and doesn't happen at all with others.

**To Reproduce**
I haven't figured out how to reproduce consistently, but with a problematic component, do the following:
1. Create an instance of a component that has one or more tokens applied
2. Change or remove one of the tokens on the instance
3. Click off the instance, then back on, and see the token restore itself

You'll also see the token restore itself once you apply/delete another token on the instance, this is shown in the video, where I try to remove multiple tokens, but they keep popping back in.

**Expected behavior**
Changing/deleting tokens should persist

**Screenshots or Screencasts**

https://user-images.githubusercontent.com/7295062/148596187-30b00482-0466-4bdb-a646-77fadacedc66.mov

**Comment by six7** [comment]
This was introduced in version 129 in the form of `none` tokens that you can apply on the `Inspect` tab. It will ensure that no value from the parent will inherit for that token.
