### ISSUE TITLE
Access to Figma Tokens for users with "View only" permissions

### ISSUE THREAD

**Issue by derekluciani** [tokens-studio/figma-plugin#395]
**Is your feature request related to a problem? Please describe.**
We have a large development team that needs to reference Figma Tokens, but we can't afford to give them all "Edit access".

**Describe the solution you'd like**
Figma Tokens plugin would be available from Figma Inspect mode.

![Figma-Tokens-Plugin_for_view_only_users](https://user-images.githubusercontent.com/16504121/148965001-c1fe9bd2-028e-401c-808d-c497081308e7.jpg)

**Comment by six7** [comment]
I so wish this was possible, but Figma doesn't expose any pluginData in the Inspect panel or allow a plugin to live there :(

@jhajduk-pgs wrote a plugin for this use case though! It's basically Figma Tokens in Read Only mode: https://www.figma.com/community/plugin/1027918127238203371

**Comment by jhajduk-sage** [comment]
That's right - you need write access for the file to run plugins in it.
However there is one workaround, although I am not sure if this solution addresses your issue.

If you have your components (with design tokens applied) stored in a Figma Library, you can create your own file with write access, then import library via Assets pane, and Figma Tokens Inspector should work fine for those components.

Let me know if this helped!

**Comment by ugo3** [comment]
It could be a possibility but doing so dev won't get updates on the Main Library.
Or an I missing something ?

**Comment by jhajduk-sage** [comment]
Yes, that's right. This way developers will miss info on updating library.

You can still send them notifications on Slack or other communicator though ;).

**Comment by clairedenning** [comment]
I'm a designer and have been continually frustrated that I've had to give edit access to developers so that they can inspect tokens. The figma files are too precious to give access to anyone and eveyone! I hope this extension works :) I believe it will be super useful for designers too.

**Comment by LukeFinch** [comment]
This request has been moved to our new feedback tool. Go check out https://tokensstudio.featurebase.app/ to create a free account. You can upvote and comment on existing posts, make a new request, and subscribe to be notified when requests move into our roadmap.

**Comment by SamIam4Hyma** [comment]
[Light version / view only mode of plugin](https://tokensstudio.featurebase.app/p/theme-switcher-for-non-ds-designers)
