### ISSUE TITLE
Custom rem configuration support

### ISSUE THREAD

**Issue by jorenbroekema** [tokens-studio/figma-plugin#401]
## Descriptiom
I was looking at the design tokens w3c draft spec https://design-tokens.github.io/community-group/format/#dimension for dimensions specifically, I think `rem` would be very cool to add support for in this plugin, as I use it basically everywhere and it's a shame my design tokens using rem cannot be used in Figma Tokens.

## Suggested solution
The most flexible way would a combination of a token and a setting:

- The user can create any token that holds the REM value, eg {base.font.size} or anything more generic {scale._base}
- In settings, the user can link a token to a unit (currently just REM, but we might have more use cases for connecting unit to a token in the future). Se we'd have an input: REM = {base.font.size}. But this could also be a hard value (eg. 10px), which has a default of 16 if nothing is entered.

This would keep things configurable and easy to manage IMO, without breaking the current functionality. This also allows theme based overrides since the setting references a token, which could hold a different value per theme (eg desktop/mobile). @mikekamminga 

![Image](https://user-images.githubusercontent.com/4548309/189476064-5e541fd8-9c50-4059-bd0d-cba6fc9954f1.png)

**Described user solution**
Since rem in web is the base font-size, I think it would make sense to do an interpretation step that just multiple the rem value with the base font size like this:
```json
{ "foo": { "value": "4rem" } }
```
becomes
```
foo = 4 * {base.font.size}
```

So the question is then, what is this `{base.font.size}` reference? I guess it would be a token that the user can add, or in absence the plugin could add a default one with value `16px`? I'm not entirely sure what the most user-friendly way is to deal with this as perhaps the user wants to change the key of this token as well, perhaps when user imports or creates tokens that contain "rem" as the unit it could create a popup where the user can create the base.font.size token with a key and value of their choosing. We'd perhaps need to update the `{base.font.size}` reference values if the key of this "special" token is changed? It's a bit hard to reason about how exactly this would be implemented given the lack of context I have on this plugin ;) so just throwing out a suggestion

**Described user solution alternative**
Doing `* 16` for rem by default but I don't like that idea as 16px is not everyone's base font-size.

**Additional context**
With some direction, happy to try a PR to contribute this.

**Comment by six7** [comment]
This is in the plugin already, although not configurable! The plugin will currently convert rem by * 16, so 1rem = 16px.

I'm wondering where/how we'd want to make this configurable to the user. It feels like it should be a token, not a setting in the UI. Then you could override it by switching from desktop to mobile theme?

**Comment by jimmygutron** [comment]
I think this feature should be necessary for users who using `rem` unit.

Because they usually set the body's `font-size` to `62.5%` to calculate rem value easily. (It makes 1rem = 10px)

**Comment by mikekamminga** [comment]
I think the most flexible way would a combination of a token and a setting:
- The user can create any token that holds the REM value, eg `{base.font.size}` or anything more generic `{scale._base}`
- In settings, the user can link a token to a unit (currently just REM, but we might have more use cases for connecting unit to a token in the future). Se we'd have an input: REM = `{base.font.size}`. But this could also be a hard value (eg. `10px`), which has a default of 16 if nothing is entered.

This would keep things configurable and easy to manage IMO, without breaking the current functionality.

**Comment by jimmygutron** [comment]
Thanks for answer, @mikekamminga . So where is the setting about linking a token to a unit? In setting there are just about Token Storage
<img width="626" alt="스크린샷 2022-07-13 오후 1 32 04" src="https://user-images.githubusercontent.com/59547099/178651182-f3e6512a-a00e-4c94-9f09-ac9c8ae986a3.png">
.
