### ISSUE TITLE
Get Partial values of Color Tokens

### ISSUE THREAD

**Issue by lizzzzard** [tokens-studio/figma-plugin#418]
**Problem**
I use the HSL color space to create Variations of colors (e.g. lighter, darker) or even matching colors. 
The way I do this: start with a given color, then:
- Change Hue value only to get a different color that is harmonious with our start color (because saturation and lightness are stable)
- Change Saturation only to get a muted color (e.g. for disabled states)
- Change Lightness only to lighten or darken a color.
See [this elaborate article for more information on using the HSL colorspace effectively in CSS](https://tsh.io/blog/why-should-you-use-hsl-color-representation-in-css/)

**Possible Solution**
I wish for figma tokens to give me the ability to reference HSL values of a color token.
For example: {color.primary.hue} or {color.primary.saturation} or {color.primary.lightness}, {color.primary.alpha}
or just {color.primary.H},  {color.primary.S},  {color.primary.L} and {color.primary.A}

This way, I could create a 10% lighter variation of a color token like this:
Color: hsla({color.primaryH}, {color.primary.S}, {color.primary.L}*1,1, {color.primary.A})

Or, I could create a analogous (or monochromatic, triadic, tetradic) color scheme by doing calculations with the hue value.

**Describe alternatives you've considered**
I could create a lighter variation by using the rgba space and just set fixed alpha values to lighten/darken, BUT:
- Doesn't give me the ability to create color schemes
- Only works on white backgrounds 
- I want my color switches to have 100% opacity by default

**Comment by nathan-valiant** [comment]
+1 to the above. I usually work by using HSL and manipulating values as opposed to just RGBA'ing, makes for more accessible colours. Would be great if this could be bumped!

**Comment by SamIam4Hyma** [comment]
@six7 Suggest to close b/c we've accomplished this with color modifiers and opacity tokens in the plugin today.
