### ISSUE TITLE
Support Grid Styles

### ISSUE THREAD

**Issue by lizzzzard** [tokens-studio/figma-plugin#419]
**Is your feature request related to a problem? Please describe.**
I love and use [grid styles](https://help.figma.com/hc/en-us/articles/360040450513-Create-layout-grids-with-grids-columns-and-rows#h_01F1ZKBDKC6KA06QJF6EA24EGQ). But Figma Tokens doesn't have the ability to interact with grid styles.

**Describe the solution you'd like**
Please support grid styles.

**Describe alternatives you've considered**
Not having the ability to provide grid styles within my design system. It makes me sad :( ;)

**Comment by lukasoppermann** [comment]
Hey @six7 is there any chance this will make it into the plugin soon?

**Comment by six7** [comment]
I'd love to understand how you'd imagine this would look like as a token, given the W3C hasn't included that in their current draft.

My guess is something like 

```
{
  "type": "grid",
  "value": {
    "type": "stretch", | left | right | center
    "count": 8,
    "gutter": 16,
    "margin / offset": 0,
    "width": 0, (depending on if its stretch, left, right, center this is disabled)
    "color": "rgba(255, 0, 0, 0.2)"
  }
}
```

**Comment by rickbenetti** [comment]
Based in your suggestion I created this idea:

`{
  "grid": {
    "desktop": {
      "12columns": {
        "value": {
          "type": "stretch",
          "count": 12,
          "gutter": 20,
          "margin / offset": "5%",
          "width": "auto",
          "color": "{color.primary.100}",
          "description" : "(depending on if its stretch, left, right, center this is disabled)"
        },
        "type": "other"
      }
    },

    "tablet": {
      "8columns": {
        "value": {
          "type": "stretch",
          "count": 8,
          "gutter": 20,
          "margin / offset": "5%",
          "width": "auto",
          "color": "{color.primary.100}",
          "description" : "(depending on if its stretch, left, right, center this is disabled)"
        },
        "type": "other"
      }
    },

    "mobile": {
      "6columns": {
        "value": {
          "type": "stretch",
          "count": 6,
          "gutter": 20,
          "margin / offset": "5%",
          "width": "auto",
          "color": "{color.primary.100}",
          "description" : "(depending on if its stretch, left, right, center this is disabled)"
        },
        "type": "other"
      }
    }
  } 
}`

**Comment by SamIam4Hyma** [comment]
@six7 @six7 Suggest to close b/c it's stale and we can introduce when DTCG has a type for this

**Comment by keeganedwin** [comment]
Migrated to [featurebase](https://tokensstudio.featurebase.app/p/expand-token-types)
