### ISSUE TITLE
Inform users when token value won't be recognized

### ISSUE THREAD

**Issue by six7** [tokens-studio/figma-plugin#421]
Users currently have no way of knowing when a value is being recognized and will work in Figma.

#286 had an issue where it seemed like repeating-linear-gradient worked in the UI (as it's being parsed by css) but we weren't able to transform it to Figma.

We should let the user know when their value is incorrect. (e.g. alias not found, value not being parsed by adding an unknown unit, etc)

**Comment by iamnbutler** [comment]
This would be really helpful! I spent a while trying to debug why one of my box shadow styles wasn't working, and had to resort to visual testing as I was unsure if the token was valid or not.

**Comment by LukeFinch** [comment]
This request has been moved to our new feedback tool. Go check out https://tokensstudio.featurebase.app/ to create a free account. You can upvote and comment on existing posts, make a new request, and subscribe to be notified when requests move into our roadmap.

**Comment by SamIam4Hyma** [comment]
Added to Featurebase Request-	[Undo and emergency exit](https://tokensstudio.featurebase.app/p/undo-enhancements)
