### ISSUE TITLE
Export modal: Add option to "resolve values"

### ISSUE THREAD

**Issue by A143447** [tokens-studio/figma-plugin#423]
**Is your feature request related to a problem? Please describe.**
We have several categories of tokens that build on each other: core, bridging and components. (Components referring to bridging and bridging referring to core).
In the Figma Tokens plugin, JSON tab, when all the categories are selected, 'All token sets' is selected and export is clicked, the tokens are exported with the referring token name rather than the actual resolved value being calculated. It would be helpful to have the option of resolving tokens to their actual value as the next step for the exported JSON is to generate iOS/Android etc specific tokens using Style Dictionary. (Style Dictionary requires that the actual value be given). Can you please assist?

This image is the exported Component (referring to bridging - that refers to Core). The expected value of the token is 8 - as per the subsequent image:
![image](https://user-images.githubusercontent.com/39042077/150704642-e57f0853-d717-4813-8a18-843dc6d54ad0.png)
![image](https://user-images.githubusercontent.com/39042077/150712891-1ac9d85a-d092-4c5f-bb6f-efae5cdf07c7.png)

**Describe the solution you'd like**
As part of the export process, a new option to resolve tokens to their actual value could be given. This functionality (not option) was available in version 52 of the plugin.

**Describe alternatives you've considered**
The only alternative that we have considered is to have a local version of the figma plugin version 52 available for the developers to use when exporting the tokens. This version allows the developers to select multiple categories of tokens and the export has the values resolved to the lowest level. 

**Additional context**
This request is related to https://github.com/six7/figma-tokens/issues/189

**Comment by six7** [comment]
This shouldn't be too difficult to add, thanks for opening this!

We'd want another option in export `resolve values` - something similar to what we'd want to do for the token-transformer package.

**Comment by A143447** [comment]
yes, `resolve values` sounds perfect. Thank you so much for being open to this feedback

**Comment by six7** [comment]
FYI: Version 18 of token transformer now features a way to `--preserveRawValue=true` giving you a dedicated rawValue field on each token. This doesn't solve this issue yet, but should provide another way of accessing those unresolved values.

**Comment by SamIam4Hyma** [comment]
@six7 Suggest to close b/c it's stale unless I'm misunderstanding
