### ISSUE TITLE
Gradients not picked up for gradientStops <0% or >100%

### ISSUE THREAD

**Issue by neatlittlemacapps** [tokens-studio/figma-plugin#424]
**Describe the bug**
I created a gradient token but it isn't being picked up in Figma

**To Reproduce**
Create these gradients:

1. linear-gradient(0deg, $color.primary.key 0%, #02B2C7 100%)
2. linear-gradient(0deg, $color.primary.key 0%, #02B2C7 150%)
3. linear-gradient(0deg, $color.primary.key -80%, #02B2C7 100%)

Apply these gradients.

Gradient 1 works
Gradient 2 and 3 don't

**Expected behavior**
Applying any of these 3 gradients shows up in Figma

**Screenshots or Screencasts**
<img width="1342" alt="Screenshot 2022-01-26 at 15 44 07" src="https://user-images.githubusercontent.com/60575307/151186906-a1ac78e4-45ab-4ab8-9a59-67346be3d049.png">

**Figma file (optional)**
[Send us the link to a Figma file containing a reproducible example
](https://www.figma.com/file/DFuiQxqXRKkAB4gsSe10gY/gradient-issues)

**JSON (optional)**
{
  "test 1": {
    "value": "linear-gradient(0deg, #d5a5d7 0%, #02B2C7 100%)",
    "type": "color"
  },
  "test 2": {
    "value": "linear-gradient(0deg, #a5a5d7 0%, #02B2C7 150%)",
    "type": "color"
  }
}

**Comment by Blyawon** [comment]
Same here as well. Gradient rotation doesn't work currently.

**Comment by six7** [comment]
Found the cause: Gradient stops below 0% or above 100% seem to have stopped working when we fixed gradient orientation. Will look into this, thanks for reporting!

**Comment by uipetals** [comment]
Yes, Same for me

**Comment by qimmiq** [comment]
@six7 @neatlittlemacapps @Blyawon 
https://github.com/tokens-studio/figma-plugin/issues/2331 i think this describes more of the gradient bug. right?

**Comment by LukeFinch** [comment]
This request has been moved to our new feedback tool. Go check out https://tokensstudio.featurebase.app/ to create a free account. You can upvote and comment on existing posts, make a new request, and subscribe to be notified when requests move into our roadmap.

**Comment by UdayHyma** [comment]
Added to Featurebase Roadmap : [🎨 Expand gradient color support
](https://tokensstudio.featurebase.app/p/add-gradient-token-type-and-expand-functionality-past-linear)
