### ISSUE TITLE
Memory out of bounds in Safari

### ISSUE THREAD

**Issue by ShaneHudson** [tokens-studio/figma-plugin#429]
I'm getting a RuntimeError when I try to open the plug-in, after using it for a while.

```
Error: RuntimeError: Out of bounds memory access (evaluating 'Module["asm"]["jsvm_evalCode"].apply(null,arguments)')
```

This feels related to #269.

**To Reproduce**
1. Open the plugin
2. If that alone isn't enough to show the error, click around the page, close the plugin
3. Open plugin again
4. It will show the error in console and in a popup at the bottom of the screen.

This appears to be only related to Safari

**Comment by six7** [comment]
I'll close this one in favor of https://github.com/tokens-studio/figma-plugin/issues/1751 to track similar errors. We've not yet been able to eliminate all causes that lead to this, but we're still on it. Affects Figma when in idle for a while, and affects multiple plugins.
