### ISSUE TITLE
Introduce new variant token type

### ISSUE THREAD

**Issue by six7** [tokens-studio/figma-plugin#434]
An interesting approach to variants and components could be to introduce a `variant` token type. Users could specify `size: 300` and the plugin would switch a layer where that token is applied to the variant of `size: 300`. In Figma that would mean that we look at other currently applied variants and then only change the one affected. This does require that there's a variant like this existing in the main component, though.

From Slack:

```
Hey, I’d love to have the component property or variant token type to be able
to control properties of the component and use compositions effectively.
For example I use Container component to specify different sizes of the graphic
elements (eg icons). Then If I use the Container in other UI components I need
to specify the token for it. But now I can do that only in the pixel values,
eg size: 24 instead of the convenient size: 300 which is a variant of the Container
```

![image](https://user-images.githubusercontent.com/4548309/152497269-3a01028a-a768-4573-9134-2487591a4af0.png)

**Comment by yeroar** [comment]
+1 from me 👍🏼

**Comment by SamIam4Hyma** [comment]
@six7 proposing we archive this one until it comes up again its a couple years old.
