### ISSUE TITLE
[Gradient tokens]: Support for radial gradients

### ISSUE THREAD

**Issue by juwain** [tokens-studio/figma-plugin#441]
I'm creating tokens set for new project. And there are not only linear, but also radial gradients applied to components. Unfortunately, when I tried to use some radial gradient syntax it didn't work:
```
radial-gradient(178.91% 178.91% at 50% 50%, {someColor} 0%, {anotherColor} 100%)
```

It'll be very handy being able to save such types of tokens.

[radial-gradient() - CSS: Cascading Style Sh…](https://developer.mozilla.org/en-US/docs/Web/CSS/gradient/radial-gradient())

**Comment by LukeFinch** [comment]
This request has been moved to our new feedback tool. Go check out https://tokensstudio.featurebase.app/ to create a free account. You can upvote and comment on existing posts, make a new request, and subscribe to be notified when requests move into our roadmap.

**Comment by UdayHyma** [comment]
Added to Featurebase Roadmap : [🎨 Expand gradient color support](https://tokensstudio.featurebase.app/p/add-gradient-token-type-and-expand-functionality-past-linear)
