### ISSUE TITLE
Support HSLA color swatches without using % for S and L

### ISSUE THREAD

**Issue by evansanto** [tokens-studio/figma-plugin#450]
**Describe the bug**
If using HSL or HSLA for colour, the swatch does not display the colour - it just displays as white. It does however work perfectly in relation to Figma: the colour is shown in the Figma colour styles fine.

**To Reproduce**
1. Create a color token using HSL

**Expected behavior**
The colour should be shown in the swatch.

**Screenshots or Screencasts**
<img width="353" alt="Screen Shot 2022-02-09 at 12 01 57 pm" src="https://user-images.githubusercontent.com/37431196/153101987-d7a2e73a-36c7-4d2b-9b4d-f3c13f958cf3.png">
<img width="672" alt="Screen Shot 2022-02-09 at 12 02 16 pm" src="https://user-images.githubusercontent.com/37431196/153101996-8da1b6a9-513d-45a3-afef-7fb9fb47ca2c.png">

**JSON (optional)**
{
  "color": {
    "hslColor": {
      "value": "hsla(230, 84, 55, 1)",
      "type": "color"
    }
  }
}

Amazing plugin by the way - thanks so much!

**Comment by six7** [comment]
The reason for this is that the token in the UI is giving it's raw value and letting the browser decide if it can display that. That means, CSS. In CSS, the `S` and `L` values need a `%` sign at the end for them to work.

If you write your hsla values like this: `hsla(230, 84%, 55%, 1)`, however we should do something to streamline these and what Figma accepts.

**Comment by evansanto** [comment]
Ah - thanks so much - user error sorry...! All is working great now - thanks again for such an amazing plugin!

**Comment by mck** [comment]
While fixing this maybe it's also possible to put the hsla value in if the color picker is set to hsla

**Comment by SamIam4Hyma** [comment]
Suggesting we archive this one as its stale and covered elsewhere @six7
