### ISSUE TITLE
Add token details as comments in figma's inspect mode.

### ISSUE THREAD

**Issue by AlexeyNovik** [tokens-studio/figma-plugin#452]
**Is your feature request related to a problem? Please describe.**
Right now it's a bit complex to understand where the exact token is applied when inspecting the component. You have to compare the token value (or calculations) with values in figma's inspect to understand what should be used and where...

![image](https://user-images.githubusercontent.com/1397327/153450945-e4b23dae-314e-4d6f-ba16-107e5788dd97.png)

**Describe the solution you'd like**
It would be great to see tokens next to the code as a comments. i.e.:
padding: 4px 8px; /* button.padding.m button.padding.l */

**Describe alternatives you've considered**
Reviewing the Inspect tab in the plugin was not 100% helpful.

**Comment by dmackerman** [comment]
This would be really nice. `style-dictionary` has a similar feature which you configure called `outputReferences` which adds comments like you mentioned:

<img width="1117" alt="image" src="https://user-images.githubusercontent.com/289938/153952226-9fc1870e-da88-48ea-abaf-25ed1e957ed5.png">

**Comment by six7** [comment]
Unfortunately this is not possible as of now. Figma gives us no way of exposing something in the inspect tab.

**Comment by AlexeyNovik** [comment]
@six7 I shared this issue with the Figma team. Maybe they could propose some ideas.

**Comment by pernsteinerc** [comment]
@AlexeyNovik wouldn't your use case bing solved via https://github.com/six7/figma-tokens/pull/415#issue-1109713704?

**Comment by Perni1984** [comment]
@AlexeyNovik wouldn't your initial use case being solved via https://github.com/six7/figma-tokens/pull/415#issue-1109713704 ?

**Comment by AlexeyNovik** [comment]
Working with annotations can be helpful, but just a little (as a checklist). 
When you select a specific item in component you can copy the code, so why the devs should spend extra time to extract values by comparing them with annotations, then copying the annotation parts to set up initial stylesheets?

**Comment by dmackerman** [comment]
Following up on my style-dictionary `outputReferences` -- this won't work for anyone trying, because if you're using the `token-transformer`, those aliases are stripped away before processing.

**Comment by thaoula** [comment]
Hi, has there been any movement by Figma on this issue?

**Comment by SamIam4Hyma** [comment]
@six7 proposing we close this one as inspect mode in Figma has changed and this need will be addressed in other areas of the plugin experience, dev mode etc.

**Comment by six7** [comment]
Closing this as stale and Figma shipped dev mode. Please reopen if you feel this was done in error.
