### ISSUE TITLE
Rename `description` to `comment` in token-transformer

### ISSUE THREAD

**Issue by MoritzStefaner** [tokens-studio/figma-plugin#499]
**Is your feature request related to a problem? Please describe.**
Currently, comments are stored in `description` properties. Style-dictionary expects comments to be stored in `comment` properties.

**Describe the solution you'd like**
token-transformer could convert `description` properties to `comment` properties.

**Describe alternatives you've considered**
—

**Additional context**
—

Thanks for your consideration or any pointers on how to achieve this!

**Comment by MoritzStefaner** [comment]
Just checking in if this has been given consideration yet? Thanks!

**Comment by SamIam4Hyma** [comment]
proposing to archive for now as description aligned with the DTCG standards
