### ISSUE TITLE
Import settings: ignore styles starting with "_" and "."

### ISSUE THREAD

**Issue by alexhris** [tokens-studio/figma-plugin#532]
Figma libraries have the native behaviour that if you add "_" or "." in the token/style name, it doesn't get exported together with the other styles and components from the Library. 

It would be great if I can just check "Ignore styles that are not in Library / that start with "_" or "." " while I'm importing the native Figma styles/tokens instead of having to delete them afterwards.

Thanks!

**Comment by six7** [comment]
Having that as a setting would probabl solve your need, right? I can imagine some users would want to import those, and some don't.

**Comment by alexhris** [comment]
Yes, sure :) one checkbox setting would be great! Thanks!

**Comment by SamIam4Hyma** [comment]
@six7 proposing to close as this feature was introduced I believe.
