### ISSUE TITLE
Respect aspect ratio when applying size tokens to width or height only

### ISSUE THREAD

**Issue by mzilverberg** [tokens-studio/figma-plugin#544]
**Description**
I have a set of illustration with a fixed aspect ratio (6:5). When I apply a size token to these illustrations, it either treats them as square (1:1 ratio) or distorts the illustration, depending on whether I have toggled 'constrain proportions' on or not in Figma.

**Expected behavior**
If I have 'constrain proportions' turned on and apply the size token to either the width or height only (thus: not the default 'all'), I want the layer to respect that behavior. For example:

1. I have an illustration that's 300x250
1. I apply a size token of 60 to its width

I expect the dimensions to be 60x50 and not 60x60. When 'constrain proportions' is turned off, however, it may be distorted (to 60x250) as the current behavior does.

Please tell me if I am overlooking something. If not, I sincerely hope you can help me with this!
Thanks in advance.

**Comment by six7** [comment]
The plugin currently doesn't consider the constrain proportions settings, but it's definitely something that's doable, we'd just have to introduce a check before applying width or height to see if that setting is on.

**Comment by mzilverberg** [comment]
I thought it wouldn't be too hard. Hope you can find the time to implement this check!

**Comment by SamIam4Hyma** [comment]
Proposing to archive as min/max dimension tokens likely solve the need.
