### ISSUE TITLE
Applying and updating tokens works for one user, but another user in the same file doesn't see the changes.

### ISSUE THREAD

**Issue by clairedenning** [tokens-studio/figma-plugin#546]
A user changes what tokens are applied, and clicks the UPDATE button to refresh the figma elements. Everything looks fine. Another user doesn't see the token changes. So for example, say I have a red colour token and apply it to some figma elements that were previously coloured with a green colour token. I think click the UPDATE button to make sure all elements are refreshed.  Visually everything looks red, and I can see the red colour token in the Inspect panel. Another user may see everything red, but the inspect panel shows the green token still applied.
Screengrabs show the same element selected but for one user the colour is green, for the other it is black. Visually it is black.
<img width="345" alt="image" src="https://user-images.githubusercontent.com/49988488/159909744-49ad1469-41c5-4716-b8ff-413c8f2027c6.png">
<img width="282" alt="image" src="https://user-images.githubusercontent.com/49988488/159909780-f152cca4-6fdf-475b-8093-f7ed484623e7.png">

**Comment by six7** [comment]
The state that is supposed to sync is just tokens, token sets right? Or also which token sets are active? I'd imagine some users work on different parts of a page with different sets active.

**Comment by clairedenning** [comment]
Both users were in a call, looking at the same figma page, and using the same token sets. The screengrabs provided are from 2 different users looking at the same element at the same time.
