### ISSUE TITLE
[Git Sync] publish tokens in another package root

### ISSUE THREAD

**Issue by felipetodev** [tokens-studio/figma-plugin#561]
Hello!

I was wondering if it is possible to publish my token.json from Figma to a custom folder inside my UI package in a monorepo repository.

Example: I'm using this output path: packages/ui/src/figma/token.json

The error was that GitHub use that path as a folder in my base root of my repository instead of creating the token.json in that path

Is there any way to publish in a custom root inside my repository my tokens?

**Comment by six7** [comment]
I'll have to find out if this is possible, so the root of the repo is higher up than where you'd like to save it?

**Comment by felipetodev** [comment]
Thats right!
If there is any way I can help please let me know ✌️

**Comment by six7** [comment]
Picking this up again. Is there a way where we can tell octokit what the "real root" is?

**Comment by SamIam4Hyma** [comment]
@six7 curious if this is still something to look at or archive as its quite old.

**Comment by six7** [comment]
Closing this as stale. Please reopen if you feel this was done in error
