### ISSUE TITLE
Token name collision between text style and color style leads to an override in JSON

### ISSUE THREAD

**Issue by Norskes** [tokens-studio/figma-plugin#578]
**Description**
When a text style name matches a color style name, one of these tokens will be overriden in JSON format on import and lost for export. (Probably they use the same key in JSON structure and their values override each other).  

**To Reproduce**
1. Create color style named "secondary".
2. Create text style named "secondary".
3. Import styles into Figma Tokens
4. Switch to JSON and view "secondary" key value in its structure

**Expected behavior**
a) Both tokens should be included into JSON structure with their respective values.
b) Some warning should be thrown to inform about name collisions.

This case also affects nested branches. So that if you declared "secondary/foo" and "secondary/bar" color styles ("secondary" is a palette name here) and then added a font syle "secondary", the latter would override both color styles in JSON. This means that the whole palette would be lost on export and import to another file, which is not obvious.

**Comment by six7** [comment]
Thanks for raising this issue. I believe we should let the user know in the import dialog that they can't import a token twice, and that names should be unique. That way they'd understand why only once of the two can and will be imported.

**Comment by LukeFinch** [comment]
This request has been moved to our new feedback tool. Go check out https://tokensstudio.featurebase.app/ to create a free account. You can upvote and comment on existing posts, make a new request, and subscribe to be notified when requests move into our roadmap.
