### ISSUE TITLE
Bad performane and laggy files, tokens not getting applied

### ISSUE THREAD

**Issue by Blyawon** [tokens-studio/figma-plugin#586]
**Describe the bug**
Since the last bigger update, it feels like the plugin is super slow and crashes a lot.
When I open a larger file it is performant until I open the tokens plugin. Then the whole file starts lagging.
Sometimes when I try to apply tokens nothing happens and I have to restart the plugin.

**To Reproduce**
Happening on larger files

**Expected behavior**
No crashes and lags 

Thanks!!

**Comment by six7** [comment]
👋 Could you share the file with me on Slack? Also, when did the regression start? With the performance update or the last one we did (token sets)?

**Comment by six7** [comment]
I'll close this one in favor of https://github.com/tokens-studio/figma-plugin/issues/1751 as an issue that consolidates a bunch of other crash-related issues
