### ISSUE TITLE
Alternative way to apply tokens

### ISSUE THREAD

**Issue by ervasive** [tokens-studio/figma-plugin#589]
Sometimes it can be a challenge (at least for me) to manage applied tokens exclusively through the Tokens interface, especially when the tokens set grows in size or if the tokens structuring is unconventional. For example I prefer to group tokens by component e.g. `$ui.button.primary.disabled.opacity` instead of by property type `opacity.sublte` etc. so to find and apply all the required tokens I have to scroll a lot.

Currently the Inspect tab can be used to replace applied tokens with different ones but there is no way to apply additional tokens.

**Describe the solution you'd like**
I think it can be useful to add the ability to apply additional tokens within the "Inspect" interface or in some other more "manual" form as an alternative to current UI.

**Describe alternatives you've considered**
One of the solutions could be an autocomplete text field where the user enters some part of an existing token name to apply.
![tokens-autocomplete](https://user-images.githubusercontent.com/85254/162461190-05acabb2-8ba0-4db9-9e61-9cfb2308a259.jpg)

**Comment by six7** [comment]
Thanks for creating this issue! We'll be working on something similar soon. In addition, we'll allow you to group not by property, but by your naming schema.

**Comment by ervasive** [comment]
Sounds great, looking forward to it.

Should I close the issue?

**Comment by six7** [comment]
Let's leave it open for now, as it provides a lot of value for shaping those other issues 🙏

**Comment by SamIam4Hyma** [comment]
@LukeFinch I think this is related to the grouping/name items you are working on.

**Comment by LukeFinch** [comment]
This request has been moved to our new feedback tool. Go check out https://tokensstudio.featurebase.app/ to create a free account. You can upvote and comment on existing posts, make a new request, and subscribe to be notified when requests move into our roadmap.

**Comment by UdayHyma** [comment]
Added to Featurebase Roadmap :[🪙 ➕ Apply token workflow enhancements
](https://tokensstudio.featurebase.app/p/apply-token-workflow-enhancements)
