### ISSUE TITLE
Add support to auto-layout properties

### ISSUE THREAD

**Issue by darioaschero** [tokens-studio/figma-plugin#613]
***Is your feature request related to a problem? Please describe.***
At the moment isn't possible to define a token value for the size properties which, when applied, will be interpreted as “Fill container”.
Since also the others auto layout settings are not supported, they can be considered as part of this feature request.

***Describe the solution you'd like***
Auto layout related properties can be categorised in two groups:

**Size:**
Size tokens could support two additional values `100%` ( fill container)  and `auto` (hug content)

**Layout:**
Figma supports a subset of the flexbox api which can be summarised as follows
```
flex-direction: vertical | horizontal 
 
align-items: center | flex-strart | flex-end

justify-content: center | flex-start | flex-end | space-between 
```
Considering that these properties are all ```enum```, the first approach which came to my mind is to treat them as a small token composition and use radio buttons to assign values. If this approach worth to be explored, I can produce a mock up of the ui.

**Comment by C3PablO** [comment]
Looking forward to seeing progress on this ;)

**Comment by SamIam4Hyma** [comment]
@six7 can we close this ticket here as its in featurebase as a request?

**Comment by SamIam4Hyma** [comment]
Closing as it's been migrated to featurebase - [Expand Token Types](https://feedback.tokens.studio/p/expand-token-types)

Please upvote and create a free account to get notified when work starts on this request

**Comment by SamIam4Hyma** [comment]
Closing as it's been migrated to featurebase - [Expand Token Types](https://feedback.tokens.studio/p/expand-token-types)

Please upvote and create a free account to get notified when work starts on this request
