### ISSUE TITLE
[Additional Settings] Ability to add PaintStyle id's from the library color styles to use in other pages

### ISSUE THREAD

**Issue by snak10** [tokens-studio/figma-plugin#626]
I'm using Figma Tokens literally as an extension of Figma's UI, always open, and not being able to use Color Tokens as library styles outside the library in plugins is a downside that Figma limits in their plugin API.

But would it be possible to have a field on a settings page in the plugin to add the paintstyles id's from the library using the console to show us?

I know this is a heavy-user feature, but I guess people who are trying to innovate the design-ops on their companies would be heavy users of Figma and could be taught to use this feature...

**Comment by six7** [comment]
We'll be introducing something like this with a revamped Themes feature.

Right now setting a styleId to a token might not always be the best thing (it might be for some users though) as it could depend on other sets that influence this token.

Ideally the style is bound to a specific theme-combination, so we'll be introducing that once we tackle that.

**Comment by six7** [comment]
We introduced this a while ago, sorry for never closing this issue. You can attach color styles to tokens when using `Themes`. See https://docs.tokens.studio/themes/themes-pro
