### ISSUE TITLE
Allow multi user edit flow with Github integration

### ISSUE THREAD

**Issue by edwart-dataprovider** [tokens-studio/figma-plugin#640]
**Describe the bug**
Currently it is possible to work with Github to store your JSON file. But when working with multiple users, there is no check if you try to push a file to Github that lacks changes made by another user. It just overwrites the other users code.

**To Reproduce**
1. create token file on Github
2. allow two users to work in this repository
3. adjust token, push it
4. when the other user changes things to the tokens and tries to push the changes, it just overwrites the changes made by the other user. 

**Expected behavior**
It should warn you about new changes and offer the option to pull these change without destroying your own changes.

**Screenshots or Screencasts**

**Figma file (optional)**
Send us the link to a Figma file containing a reproducible example

**JSON (optional)**
If possible, attach the JSON that leads to this bug.

**Comment by esthercheran** [comment]
While it would be nice to have merging directly happen inside the plugin, I think it will be difficult, for one because of the limited space available inside the plugin to actually resolve conflicts. I think a better workflow is to work using branches for changes, and merge the PRs into the main branch. We could think of giving the option to move the changes to a new branch in case the remote branch is has changes.

**Comment by edwart-dataprovider** [comment]
@six7 The most ideal solution is to tell there is a newer version on the remote and offer the solution to pull and merge. If there are conflicts it would be nice to have the option to resolve these inside the plugin, but as @esthercheran already mentions, this could become to cluttered. 

A workaround I use right now is to have a main branch and every change I do is on a branch which is merged to the main branch. It would be nice to see this structure inside the plugin, with the option to switch branches.

**Comment by dalindev** [comment]
Is there a solution to this? When push from Figma Studio UI to GitHub, if two users edit even different lines of the JSON, it still doesn't merge it correctly

**Comment by LukeFinch** [comment]
This request has been moved to our new feedback tool. Go check out https://tokensstudio.featurebase.app/ to create a free account. You can upvote and comment on existing posts, make a new request, and subscribe to be notified when requests move into our roadmap.

**Comment by UdayHyma** [comment]
Added to Featurebase Roadmap : [↕️ Git sync enhancements - push, pull, merge, branching](https://tokensstudio.featurebase.app/p/git-sync-enhancements)
