### ISSUE TITLE
Change Search to also find the keyword in token descriptions

### ISSUE THREAD

**Issue by mswbol** [tokens-studio/figma-plugin#670]
Support the content keywords in the search description.

**Comment by LukeFinch** [comment]
This request has been moved to our new feedback tool. Go check out https://tokensstudio.featurebase.app/ to create a free account. You can upvote and comment on existing posts, make a new request, and subscribe to be notified when requests move into our roadmap.

**Comment by UdayHyma** [comment]
Added to Featurebase Roadmap : [🔎 Search enhancements](https://tokensstudio.featurebase.app/p/search-enhancements)
