### ISSUE TITLE
Box Shadow token alias mode should support multiple stacked shadows.

### ISSUE THREAD

**Issue by mihkeleidast** [tokens-studio/figma-plugin#706]
**Is your feature request related to a problem? Please describe.**

Currently, when changing a box shadow token to alias mode, only a single input is rendered. In that input, I can enter an alias for only a single shadow. The "add another shadow" button is enabled, but does not do anything in "alias mode". As shadows can be stacked in input mode, it would make sense that they can also be stacked in alias mode.

**Describe the solution you'd like**

When a box shadow token is in alias mode, the "add another shadow" button should work and add new inputs, when clicked. Each of those inputs should allow a single alias token to be specified.

**Describe alternatives you've considered**

1. Not using alias mode, but that defeats the purpose of the feature altogether.
2. Alias mode could be toggled on a single shadow value, e.g. it might be benefitial to create a stacked shadow, where one is aliased and the other is not. Not necessary for my usecase, but could be considered.

**Additional context**

Alias mode, allows for a single input:
![image](https://user-images.githubusercontent.com/1892091/168304766-23c87e6e-3649-4875-91ad-5de2bd0c311d.png)

Input mode, allows for multiple inputs:
![image](https://user-images.githubusercontent.com/1892091/168304876-a4d38473-a8c4-4adc-8aae-531b871023c6.png)

## Designs

Let's add a button in front of the Type selector that lets users toggle between alias mode and value mode for each of the shadow items. Clicking the button converts this part of the shadow into an alias selector, letting users pick from available shadows.

![image](https://user-images.githubusercontent.com/4548309/190503609-4ecd6471-b0ba-433b-9731-366c86d742dd.png)

![image](https://user-images.githubusercontent.com/4548309/190503908-d7788fc4-3bba-41b4-b70c-efd19206ece2.png)

This might not be the best/most discoverable solution, but it's something that allows us to iterate on.

**Comment by leovogel** [comment]
+1

This is a feature thought existed; I was about to build my shadows in this componentized way.

**Comment by danfigmatokens** [comment]
Same here. I had just asked about this in the Slack thinking it was a bug, would very much love to get this added. This is exactly how we are building our shadow tokens in dev.

**Comment by danfigmatokens** [comment]
Just posted in the FT Slack asking about this thinking it was probably a bug. Would definitely love to get this in as it's how our dev team is building the shadow tokens right now and I'd like to be able to get the FT structure to match (we're not syncing with dev yet but hoping to at some point!)

**Comment by six7** [comment]
> Just posted in the FT Slack asking about this thinking it was probably a bug. Would definitely love to get this in as it's how our dev team is building the shadow tokens right now and I'd like to be able to get the FT structure to match (we're not syncing with dev yet but hoping to at some point!)

Q on this: you'd only want to reference multiple single shadow tokens that way? Or would you expect if you reference a shadow token that has 3 layers of shadows that the plugin expands that?

**Comment by mihkeleidast** [comment]
> Q on this: you'd only want to reference multiple single shadow tokens that way? Or would you expect if you reference a shadow token that has 3 layers of shadows that the plugin expands that?

Can you clarify the question, do you mean if FT should allow stacked shadows in either alias mode, or non-alias mode, or could these be mixed?

Just to provide some examples, our source of truth is our style-dictionary token collection in JSON, in there both "no alias", "all alias", and "mixed" would be valid, so it would be nice if FT could support the same:

```json
{
  "shadow": {
    "elevation": {
      "alias": {
        "value": ["{shadow.core.12}", "{shadow.core.4}", "{shadow.core.2}"]
      },
      "mixed": {
        "value": [
          "{shadow.core.12}",
          "{shadow.core.4}",
          {
            "x": "0",
            "y": "1",
            "blur": "2",
            "spread": "0",
            "color": "{color.core.black.8}",
            "type": "dropShadow"
          }
        ]
      }
    }
  }
}

```

**Comment by danfigmatokens** [comment]
@six7 I would expect both to work, whether the reference tokens contain single or multiple shadows per token.

**Comment by six7** [comment]
So, to clarify, both should work, correct?

```
{
  "shadow": {
    "core": {
      "value": {
        "x": "0",
        "y": "1",
        "blur": "2",
        "spread": "0",
        "color": "{color.core.black.8}",
        "type": "dropShadow"
      }
    },
    "alias": {
      "value": ["{shadow.core}", "{shadow.mixed}"]
    }
    "mixed": {
      "value": [
        "{shadow.core}",
        {
          "x": "0",
          "y": "1",
          "blur": "2",
          "spread": "0",
          "color": "{color.core.black.8}",
          "type": "dropShadow"
        }
      ]
    }
  }
}
```

with the result of `shadow.alias` being

```
[
  "{shadow.core}",
  "{shadow.core}",
  {
    "x": "0",
    "y": "1",
    "blur": "2",
    "spread": "0",
    "color": "{color.core.black.8}",
    "type": "dropShadow"
  }
]
```

**Comment by danfigmatokens** [comment]
Exactly what I would expect, yep. Keeping them in the order they are applied across all and repeating any that are repeated by mixing multiple layers of reference tokens.

**Comment by six7** [comment]
Would you want to mix aliases with regular shadows? I'm mainly thinking about keeping the UI clean here, technically it should be possible.

As in

```
shadow:
  [
    '{shadow.small}',
    {
      offsetX: 0,
      offsetY: 4,
      blur: 4,
      spread: 0,
      color: '#000080'
    }
  ]
```

**Comment by six7** [comment]
Would you want to mix aliases with regular shadows? I'm mainly thinking about keeping the UI clean here, technically it should be possible.

As in

```
shadow:
  [
    '{shadow.small}',
    {
      offsetX: 0,
      offsetY: 4,
      blur: 4,
      spread: 0,
      color: '#000080'
    }
  ]
```

**Comment by danfigmatokens** [comment]
I don't think we would ever do that. I would probably expect it to be possible theoretically, but personally for our system, no.

**Comment by LukeFinch** [comment]
This request has been moved to our new feedback tool. Go check out https://tokensstudio.featurebase.app/ to create a free account. You can upvote and comment on existing posts, make a new request, and subscribe to be notified when requests move into our roadmap.

**Comment by UdayHyma** [comment]
Here's the URL to the featurebase post that is linked to this ticket:https://tokensstudio.featurebase.app/p/enhanced-functionality-for-boxshadow-tokens-greater-effects-in-figma
