### ISSUE TITLE
Export Inspected tokens on a given element

### ISSUE THREAD

**Issue by Andrewangeta** [tokens-studio/figma-plugin#708]
**Is your feature request related to a problem? Please describe.**
The inspect tool is great to view the tokens associated with a given UI element/component. 
While having visibility in Figma is great, I think there's room for some more powerful use cases.

**Describe the solution you'd like**
it would be nice to be able to export an element and it's applied tokens in a JSON format.
So for example the following inspected element with the current tokens applied : 

<img width="657" alt="Screen Shot 2022-05-13 at 11 00 24 AM" src="https://user-images.githubusercontent.com/12012815/168311607-f571c203-7132-4682-9f1f-588ee5a2c0d6.png">

And the view via the inspect tool: 

<img width="770" alt="Screen Shot 2022-05-13 at 10 59 30 AM" src="https://user-images.githubusercontent.com/12012815/168311481-1197b3d2-0d06-4cf2-a979-15bfca919b11.png">

Ideally it would be nice to export the JSON for this and give the top level key a name for this particular arrangement of tokens like `buttonSecondary`

```json
{
   "buttonSecondary": {
        "fill": "secondary",  
        "borderRadius": "small",
        "height": "{customSet.Height}" // <- Referencing a different set if possible
    }
}
```
Also possibly seeing multiple elements selected all at once to have a large export of all the current variants/arrangements of tokens.

**Describe alternatives you've considered**
Hand writing the json.

**Additional context**
The main goal of this feature is to make Figma the absolute source of truth for tokens as well as styling for UI elements using tokens. 
With that goal in mind consider an iOS os Android app where I would want to generate SwiftUI or jetpack Compose code for all the tokens and then all the various styling for elements using the tokens.

A workflow would be 
1. Create design tokens in Figma
2. Create styled elements using those design tokens
3. Export the tokens (currently supported) 
4. Export the styled elements in JSON
5. Parse that JSON and auto generate tokens as well as structured styles for elements in Swift and Kotlin (done via a developer not this plugin)
6. Easily make a storybook app from the generated styles and tokens for various platforms.

**Comment by six7** [comment]
I really like this idea! Few questions:
- I'd guess the resolved tokens would not be part of this export, rather just the way you wrote it above (`height: {sizing.height}`)?
- This would only be possible in the Single inspect mode (not the Multi-inspector where you can select whole pages and see all applied tokens) - as you've outlined in your screenshot.

A flow I could see, like you described:
- Select an element that has tokens on it
- Go to single inspect mode
- Near the annotations area we could have a button allowing you to generate JSON
- ConfirmModal pops up asking you for a name of this (could default to layer name?)
- Once name is entered, present the user a JSON - OR - download a .json file

A slightly simpler flow without the need for a confirm modal:
- Select an element that has tokens on it
- Go to single inspect mode
- Near the annotations area we could have a button `Copy to clipboard` - allowing you to copy the JSON to clipboard
- That's it. The generated JSON contains a parent key named after the layer

I'm fine with both approaches, I feel the second one would be cleaner, requires less steps but I'm open to both solutions!

If you'd like to work on this, please work on the `next` branch (there might be some errors regarding our recently added feature flag solution, let me know if you run into these I can help you out there). We're also currently restructuring the plugin in a way that we're adding full type safety and better test coverage throughout the plugin, so I'd currently expect some merge conflicts if you're working on this, although it shouldn't be too bad.

**Comment by Andrewangeta** [comment]
@six7   Thanks for the feedback/looking at this. And I'd have no problem working on this, although to be fair/honest I have next to 0 experience with JS/web development, I'm mainly an iOS/swift and Kotlin developer and server-side swift 😅 I was looking into how the plugins actually are developed in Figma this weekend and it looks to mainly be html and typescript, so I'm fairly new to it all. Any pointers (even rough ones) would be super appreciated like what folder/file should I start playing with. I can learn but it's definitely a curve for me.

**Comment by Andrewangeta** [comment]
@six7  Also I wouldn't mind giving a nice donation to the project either to get this implemented 👀. And maybe multi select wouldn't be a bad option that defaults to the layers name as the parent key for all selected layers potentially just let me know what you think.

**Comment by six7** [comment]
Out of interest: is the way this would be transformed to kotlin or swift something that's fairly standardized? Or is that dependant on parameters that you configure? Would be neat if you could choose between json or any other output you need

**Comment by six7** [comment]
> @six7  Also I wouldn't mind giving a nice donation to the project either to get this implemented 👀. And maybe multi select wouldn't be a bad option that defaults to the layers name as the parent key for all selected layers potentially just let me know what you think. 

So for now we're kind of tied with other items but we're open to the idea of paid issue bounties! I dont think it's extremely hard. All the tokens are already in the Inspector, just a matter of transforming to that output json.

**Comment by Andrewangeta** [comment]
> Out of interest: is the way this would be transformed to kotlin or swift something that's fairly standardized? Or is that dependant on parameters that you configure? Would be neat if you could choose between json or any other output you need

So for my use case it's more about style and not necessarily standardized per se. It _could_ be standard but it depends on the needs of who might want it. But I'm definitely interested in the bounty aspect. How would we get that rolling?

**Comment by SamIam4Hyma** [comment]
Added to Featurebase Request-	[🤓 Document and annotate design token enhancements](https://tokensstudio.featurebase.app/p/documentation-and-annotate)
