### ISSUE TITLE
Token definition in Figma Description

### ISSUE THREAD

**Issue by leovogel** [tokens-studio/figma-plugin#729]
**Is your feature request related to a problem? Please describe.**
The frustration is that there is no way to generate token name automatically that appear in Zeroheight documentation via the Figma description field of color and text styles.

**Describe the solution you'd like**
I would like the ability to put a Figma Tokens token Name value as an alias into the token's own description field; I'll call this a meta Name alias. This could then be displayed in Zeroheight as there is the option to show the Figma description field value in Zeroheight for each token.

I also need to be able to use the Figma Tokens token Type value as an alias in the token's own description field. I'll call this a meta Value alias.

I would create a custom Other token called "prefix" and set the value to "--nds".

And I would create a custom Other token called "token" and set the value to "{prefix}-{meta.Type}-{meta.Name}". I would need the ability to have a control on this to convert the text to all lower case and the option to replace a character with another character as our final tokens use "-" separators where Figma Tokens sometimes uses "." separators.

This would allow me to generate the full design system token name in the description field with the following:
{token}

Final output example:
Given a color token with Name value of "core.Blue.400".
The Description value of this token would be "--nds-color-core-blue-400".

**Describe alternatives you've considered**
The only other alternative I see without a feature like this is to manually write out all of the tokens as plain text in Zeroheight which is a very time-consuming process and difficult to ensure is up to date.

**Additional context**
I want a reliable and automatic way to document in Zeroheight, our design system documentation tool, all of our final design tokens alongside a corresponding example of each.

**Comment by SamIam4Hyma** [comment]
@LukeFinch @six7 this is stale, is it still an issue we need to work on? Please advise or close

**Comment by LukeFinch** [comment]
This request has been moved to our new feedback tool. Go check out https://tokensstudio.featurebase.app/ to create a free account. You can upvote and comment on existing posts, make a new request, and subscribe to be notified when requests move into our roadmap.
