### ISSUE TITLE
Allow aliases to link to an object

### ISSUE THREAD

**Issue by six7** [tokens-studio/figma-plugin#73]
Example: `{ "primitives": { "gap": { "xs": "4px", "s": "8px", "m": "16px", "l": "32px", "xl": "64px" } }, "spacing": "$primitives.gap" }`

Reported in #70

**Comment by six7** [comment]
We've kind of put this on hold as it's not very clear from a UI point of view how to differentiate tokens that are coming from an object from tokens that are actual tokens.

**Comment by SamIam4Hyma** [comment]
@six7 suggest to close this one as its stale and can be reimagined later

**Comment by six7** [comment]
Yeah unfortunately i dont see this move forward within the spec anytime soon, closing.
