### ISSUE TITLE
Keyboard shortcut for "Undo" feature

### ISSUE THREAD

**Issue by ssashqo** [tokens-studio/figma-plugin#740]
When plugin window is active, the Cmd+Z or Cntrl+Z does not do anything in document, so why not use this shortcut to undo an action within the plugin?

**Comment by LukeFinch** [comment]
This request has been moved to our new feedback tool. Go check out https://tokensstudio.featurebase.app/ to create a free account. You can upvote and comment on existing posts, make a new request, and subscribe to be notified when requests move into our roadmap.
