### ISSUE TITLE
Allow applying raw value without attaching token. 

### ISSUE THREAD

**Issue by philippahlfeld-netflow** [tokens-studio/figma-plugin#770]
**Is your feature request related to a problem? Please describe.**
When working in a Team of varying proficiency, it happens a lot to us, that designers change e.g. spacings or border radius values for elements, that have tokens applied to them. They don't change the token or apply a new token, but change the raw value in the figma UI. 

When applying a theme / updating a token those individual changes get overwritten (as expected). This has led to quite some inconsistencies and discussions in the team, wether figma tokens should be used in the way we do: managing most properties in tokens. 

The current consensus is, that tokens that can be generated as a style are perfectly fine to use. Tokens that don't have styles attached (e.g. spacings or border radius) should only be used as a means of documentation, while not being directly applied to elements. 

**Describe the solution you'd like**
I'm not entirely sure, how to circumvent this. 

One possible option may be: Allow users to toggle on a per token type basis, if a token should only apply the raw value, without attaching the token the element. That would at least deal with the accidental overwrites when updating/applying a theme.

Another option: Display a warning, when a property is changed, that has a token attached to it. That would of course require the plugin to be open and may not be possible at all. 

Both solutions seem suboptimal though.

**Describe alternatives you've considered**
Currently we only use tokens to manage/generate styles as well as document properties, that cannot be generated as styles. 

I've also considered, that the team may just be to bad to deserve working with tokens, but I'd prefer not to 🤷

**Comment by SamIam4Hyma** [comment]
proposing we archive and consider in a different way on how to solve the underlying need for designers to use tokens, in this case, designers using number variables would get the job done and if they are connected to tokens, the OP's job is also done. @six7
