### ISSUE TITLE
Annotation / allow user to select which tokens to annotate

### ISSUE THREAD

**Issue by esthercheran** [tokens-studio/figma-plugin#800]
[From Slack](https://figmatokens.slack.com/archives/C02JAL48UDN/p1654109080365799):

Could we add simple select boxes to allow user control over which documentation tokens get output using the annotation tool. It would make editing and updating specific tokens faster and easier I think.

Right now if I need to update just the color of a label you need to generate the whole set and delete what you don’t need just for 1-2 tokens

My documentation closely follows Esthers example in her Youtube video, separating out common and sizing tokens, etc. So having more control over the output seemed handy, if that makes sense.

![image](https://user-images.githubusercontent.com/66366384/171567928-1ab8edcf-f671-4cd8-84f7-cf18718a0e18.png)

**Comment by SamIam4Hyma** [comment]
proposing to archive, when we do a focus on documentation we can think about solutions using what has changed in since this was created. @esthercheran
