### ISSUE TITLE
Identify which token is modified, checkout state

### ISSUE THREAD

**Issue by XavierVilars** [tokens-studio/figma-plugin#821]
**Is your feature request related to a problem? Please describe.**
Pushing the "push to github button" wihtout having a good view of what I'm pushing make me feel unconfortable. 

**Describe the solution you'd like**
It could be nice to have some kind of list of checkout's tokens to check that I'm not pushing something I don't want. And why not to decide what I want to push or not. Just like I'm doing on Studio Code.

**Describe alternatives you've considered**
More than an alternative, a visual elements in my lists could be nice to identify quickly my modification. 

Tks !

**Comment by six7** [comment]
Love the idea. Something like a diff between old/new, what files were changed and what exactly changed.

I'm guessing we should add that to the PushDialog that appears when you press the Push button. That way you'd understand what changes you are committing.

**Comment by color2life** [comment]
@six7 Can I take this to design. please assign to me.

**Comment by phantasmagoriadigital** [comment]
The diff feature was released in the last release.
