### ISSUE TITLE
Make token sets not editable when unchecked

### ISSUE THREAD

**Issue by mikekamminga** [tokens-studio/figma-plugin#830]
**Is your feature request related to a problem? Please describe.**
I would love if an unchecked tokenset was uneditable. I have multiple tiers and jump between files to work on separate libraries, but sometimes I have selected the wrong tokenset and change or add what I need before I realize that I'm in the wrong tokenset.. Can anyone relate?

**Describe the solution you'd like**
Add a setting to disable editing for unchecked token sets

From Slack conversation: https://figmatokens.slack.com/archives/C02JAL48UDN/p1654681040084709

**Comment by SamIam4Hyma** [comment]
@mikekamminga is this still an active request of yours or can we archive? I think the need you had here is being addressed differently.
