### ISSUE TITLE
Figma Tokens crashing

### ISSUE THREAD

**Issue by ianturk** [tokens-studio/figma-plugin#848]
**Describe the bug**
Figma Tokens crashes often.

**To Reproduce**
1. Using Figma Tokens for a little while

**Expected behavior**
No or less crashing

**Screenshots or Screencasts**
<img width="1408" alt="image" src="https://user-images.githubusercontent.com/3350351/172757451-da181299-1fb9-43c2-a32a-7c1c9cac98c1.png">

**Comment by six7** [comment]
Are you using the web-based version or the Figma desktop client? I get that error from time to time using other plugins as well. I've read that clearing Figma's cache or [simply restarting Figma](https://forum.figma.com/t/memory-access-out-of-bounds/6300) helps in that case.

**Comment by rbosker** [comment]
adding thread with more crash reports including error logs: https://figmatokens.slack.com/archives/C02DLQXNY6Q/p1663258132510049

**Comment by six7** [comment]
I'll close this one in favor of https://github.com/tokens-studio/figma-plugin/issues/1751 - we're still tweaking the plugin but haven't eliminated all causes of this. We're also in touch with Figma regarding this given this is something that seems to affect more plugins when Figma is idle for a while.
