### ISSUE TITLE
[Gradient tokens]: Support for radial angular/conic gradients

### ISSUE THREAD

**Issue by ianturk** [tokens-studio/figma-plugin#858]
**Describe the bug**
Angular/conic gradient tokens don't apply

**To Reproduce**
1. Create a token with a conic gradient: conic-gradient(from 180deg at 50% 50%, #ffffff 0deg, #ffffff00 45deg, #ffffff 360deg)
2. Apply token to  shape on canvas

**Expected behavior**
Token applies gradient token

**Comment by six7** [comment]
We currently only support linear-gradient, conic and angular would be possible, but we'd need to create a transformer to Figma's matrix first. We currently only have that for linear.

**Comment by vkogmail** [comment]
Would really love to have this working, running into the issue in my current problem

**Comment by litemeup-cyprus** [comment]
Yes this would be great, waiting for it too! Any updates on this?

**Comment by C3PablO** [comment]
Any update on this? We would love to be able to apply conic gradients. The lack of support for this type of gradient is causing us some trouble with the themes.

**Comment by SamIam4Hyma** [comment]
Added to Featurebase Request-	[ 💡 🎨 Expand gradient color support](https://tokensstudio.featurebase.app/p/add-gradient-token-type-and-expand-functionality-past-linear)

**Comment by SamIam4Hyma** [comment]
@six7 can we close as this is in featurebase and no longer planned?

**Comment by SamIam4Hyma** [comment]
Closing this issue as not planned as its been migrated to featurebase - [💡 🎨 Expand gradient color support](https://tokensstudio.featurebase.app/p/add-gradient-token-type-and-expand-functionality-past-linear) 

Please click the link to create a free account and upvote the request so we can notify you when we start working on it. 🚀
