### ISSUE TITLE
Documentation Indicator Ring

### ISSUE THREAD

**Issue by six7** [tokens-studio/figma-plugin#873]
From Slack:
> It would be great if Figma Tokens would show a different color for the indicator if the Token is used as a “Documentation Token”. Instead of blue, documentation could be purple.
> Benefit: More clarity through color coding meta info and actual appliance

Let's use a purple color `#8A38F5` for the outline when a Documentation token is applied.

![Image](https://user-images.githubusercontent.com/4548309/173253647-9a818ba9-89b8-4732-b991-b9205c383435.png)

**Comment by rbosker** [comment]
if both tokens are there, only show blue border.

**Comment by UdayHyma** [comment]
Added to Featurebase Roadmap : [🤓 Document and annotate design token enhancements
](https://tokensstudio.featurebase.app/p/documentation-and-annotate)

**Comment by SamIam4Hyma** [comment]
closing - migrated to FB

**Comment by SamIam4Hyma** [comment]
closing - added to featurebase

**Comment by SamIam4Hyma** [comment]
Closing as added to featurebase
