### ISSUE TITLE
Introduce "unit" to all measure tokens

### ISSUE THREAD

**Issue by mikekamminga** [tokens-studio/figma-plugin#893]
Introduce "unit" to all measure tokens, as dropdown (px, pt, em, %, plain or possibly other), and limit what unit is valid in what type of token. Right now, measures are simple textual values so everything from "1" to "1px" to "1%"  to "one" is acceptable. This however is really impractical if other things depend on it, for example, if you use it as reference in shadow - and I believe it can also present challenges of actually applying those tokens as well, as parsing of this must fail and will mostly be 0 - which will also be very enigmatic error for the user. I understand this is little bit bigger scope of work, but in sophisticated, production-ready design systems, you want to set boundaries for the users and guide them to correctly identify their intent

**Comment by SamIam4Hyma** [comment]
@six7 proposing we close this as we are aligning units with DTCG spec and other requirements that are more current.
