### ISSUE TITLE
Add option to see fully generated JSON (diff)

### ISSUE THREAD

**Issue by mikekamminga** [tokens-studio/figma-plugin#894]
Add option to see fully generated JSON (as it would come to the repository) inside the interface as well. Right now, if you are developing integration that requires the entire JSON structure (including say sets / brands), that JSON is only available upon commit to the repository

**Comment by six7** [comment]
I feel these two would solve the same use case? Seeing changes on push. Or what would the benefit be in seeing the whole json, if not for push?

https://github.com/six7/figma-tokens/issues/821

**Comment by six7** [comment]
Closing this in favor of https://github.com/tokens-studio/figma-plugin/issues/1609
