### ISSUE TITLE
Additional meta data on tokens (based on a setting)

### ISSUE THREAD

**Issue by mikekamminga** [tokens-studio/figma-plugin#907]
Adding (by turning on or off in a settings panel I guess) more metadata to each token (creation date, last update date, created by, last updated by, and the possibility to add extra open ended fields like how the description field works today).

For example the Material tokens look like this:
```
{
      "class": "token",
      "type": "color",
      "id": "md.ref.palette.error40",
      "name": "md.ref.palette.error40",
      "value": "#b3261eff",
      "category_id": "ref.color.palette",
      "last_updated": "2022-03-30T17:34:16.000Z",
      "last_updated_by": "Material",
      "description": "Error 40",
      "tags": [
        "ref",
        "color",
        "palette"
      ]
    }
```

**Comment by six7** [comment]
Can we find a way to make this compliant with the W3C draft? Perhaps in the extensions field?

**Comment by LukeFinch** [comment]
This request has been moved to our new feedback tool. Go check out https://tokensstudio.featurebase.app/ to create a free account. You can upvote and comment on existing posts, make a new request, and subscribe to be notified when requests move into our roadmap.

**Comment by UdayHyma** [comment]
Added to Featurebase Roadmap : [🪙 Token metadata enhancements
](https://tokensstudio.featurebase.app/p/token-metadata-enhancements)
