### ISSUE TITLE
New token type: Boolean

### ISSUE THREAD

**Issue by mikekamminga** [tokens-studio/figma-plugin#909]
An interesting feature is the visibility boolean used for hiding and showing elements inside a component. 

Well, we have styled elements who are quite complex. Brands choose compositions based on the options they have. Without the visibility boolean every branded header, as seen in the images, needs to disable the bullet manually when brand A is activated. And I can't use the 0.001px hack in Figma tokens because it doesn't work 

![image](https://user-images.githubusercontent.com/988169/174265199-8a275f7b-abf4-4053-b207-e5396bd7d53a.png)
![image](https://user-images.githubusercontent.com/988169/174265214-de89cd13-72e5-408f-b585-2e0ec733bca9.png)

Let's introduce a new token type: `boolean`.

Options:
`either true | false` (display as a toggle).
or `Reference mod` where the input becomes our tokenpicker (like other tokens).

Applications:
- Layer visibility

**Comment by six7** [comment]
I'd suggest we change this to `Boolean` which will allow us to set this not just for visibility but for many other applications as well.
