### ISSUE TITLE
Support fuzzy search

### ISSUE THREAD

**Issue by mswbol** [tokens-studio/figma-plugin#931]
<img width="532" alt="image" src="https://user-images.githubusercontent.com/46061868/175557431-8e0e2cae-4e25-42f5-9380-69f881c11b3c.png">

The search bar supports vague search, and the search keywords are regardless of the front and back.This is more convenient for users to screen token.

e.g:When the token name is "A.B.C.D", when the user enters the keyword "A.C.B", the design of the token "a.b.c.d" can also be searched.

**Comment by six7** [comment]
I think you're describing fuzzy search here, correct?

**Comment by LukeFinch** [comment]
This request has been moved to our new feedback tool. Go check out https://tokensstudio.featurebase.app/ to create a free account. You can upvote and comment on existing posts, make a new request, and subscribe to be notified when requests move into our roadmap.

**Comment by UdayHyma** [comment]
Added to Featurebase Roadmap : [🔎 Search enhancements](https://tokensstudio.featurebase.app/p/search-enhancements)
