### ISSUE TITLE
Style text segments

### ISSUE THREAD

**Issue by reccanti** [tokens-studio/figma-plugin#944]
**Is your feature request related to a problem? Please describe.**

![Screen Recording 2022-06-29 at 1 27 43 PM](https://user-images.githubusercontent.com/10334948/176499334-40e1db95-a318-44bd-b042-4426ed47c95f.gif)

For our design system, I find it limiting that we can't use Figma Tokens to style a section of text.

**Describe the solution you'd like**

When I select a text range and apply a style to it, it should apply the token to the range of text

**Describe alternatives you've considered**

Another way of solving this problem would be to have multiple text ranges that flow into each other, but we haven't found a good way of doing this. Other ideas on that would be helpful!

**Additional context**

I realize text segments don't have pluginData the way other nodes do, so applying token data isn't as straightforward. Would love to know the problems/considerations you've made about this, and if you have any workarounds!

**Comment by six7** [comment]
Out if curiosity: why is it important to you that a token is applied there? Isn't the style itself enough?

If the plugin offered a way to swap themes not only for tokens but also for any styles it finds, would that solve your problem?

**Comment by reccanti** [comment]
I think something like that would work for most scenarios, and would be a big improvement!

**Comment by six7** [comment]
Closing this, we'll have Swap style functionality soon!
