### ISSUE TITLE
Utilize documentation tokens in the annotations

### ISSUE THREAD

**Issue by stramel** [tokens-studio/figma-plugin#947]
**Is your feature request related to a problem? Please describe.**
When using the annotations for the tokens they work great except when you update the token name. Once the token name has been updated, the annotation is out-of-date.

**Describe the solution you'd like**
I would like the annotation to utilize the documentation tokens - name token so that the annotation stays up-to-date.

**Describe alternatives you've considered**
I don't know of any alternatives other than manually updating each of them.

**Comment by six7** [comment]
By annotation do you mean the Annotation feature? Or Documentation tokens?

**Comment by stramel** [comment]
> By annotation do you mean the Annotation feature? Or Documentation tokens?

Yes, by annotation I mean the Annotation feature. When I use the Annotation feature to document the tokens and later update the token's name, it doesn't update the annotation.

**Comment by SamIam4Hyma** [comment]
proposing to close/archive and revisit a solution for documenting tokens in the future @six7

**Comment by six7** [comment]
Closing this as stale. Please reopen if you feel this was done in error, we'll revisit once we tackle improved annotations or documentation tokens.
