### ISSUE TITLE
Handover - deep inspect feature

### ISSUE THREAD

**Issue by Marcin-Spiewak** [tokens-studio/figma-plugin#968]
Hi,

So I think you can use the same logic for handover annotation for the deep inspect cases. It works great with normal inspect mode but if my frame has some other tokens inside it would be nice to also mention them. Like you can see them in inspect mode. Even if a blocker here is you cant refer in innovation to the elements that are inside as children because you cant read the Figma layer name at least you can mention that this object has some other tokens inside as children.

**Comment by six7** [comment]
Can you elaborate a bit more on that? I don't yet fully understand. Do you want to visualize that a layer has other layers that has tokens in them? Or is it about a different visualization for Deep inspect?

**Comment by Marcin-Spiewak** [comment]
Hmm, I thought to have a view that I can show all the tokens something like you have in the inspect mode. Thanks to this global handover annotation I can show to the devs all the tokens that are used in my component for example the card or button.

**Comment by SamIam4Hyma** [comment]
proposing we close as I believe this is addressed in the way deep inspect works today. @six7
