### ISSUE TITLE
Support new W3C syntax for `$value`, `$type` and `$description`

### ISSUE THREAD

**Issue by six7** [tokens-studio/figma-plugin#999]
The W3C format defines the use of `$` characters at the beginning of all properties such as `$value` and `$description` or `$type`. We currently do not support that. Given a lot of our users do not have this setup either, we need to be careful when we introduce this.

### Let users opt in to this format
In the credentials of each provider, let users define what format they want to use. 
- Legacy Tokens Studio format (`value`, `description`, `type`)
- DTCG Format

If a user has chosen the new format, we output the JSON in a different way. `type`, `description` and `value` properties will be prefixed by the `$` character. This should be a rather simple change, given we transform the JSON anyway when we display it to users.

- Display $ character in front of properties
- When exporting include this new format
- Use these new property names to pick up values instead of the old way

### Why store this on the provider level?
Users might opt-in to this approach on a storage level, as they convert their tokens or their build pipelines. 

### What is the default going forward?
For a migration period, we keep the current format as the default and use the new one as an opt-in format. After a while we'd treat the new format as the default (but any credentials not containing this `Token format` property will be treated like the old one.

**Comment by danvpeterson** [comment]
Was just coming to ask about this, I would absolutely love to see this added! The idea of being able to choose a version is definitely interesting. Hoping this is something that has a high priority but I'm sure you're juggling a lot.

**Comment by six7** [comment]
Closing, will be part of our 2.0 release

**Comment by SamIam4Hyma** [comment]
Added to Featurebase Roadmap-	[❇️ W3C - DTCG Specification Alignment](https://tokensstudio.featurebase.app/p/w3c-dtcg-specification-alignment)

**Comment by SamIam4Hyma** [comment]
Added to Featurebase Roadmap-	[❇️ W3C - DTCG Specification Alignment](https://tokensstudio.featurebase.app/p/w3c-dtcg-specification-alignment)
